### ISSUE TITLE
[feature request] English translation

### ISSUE THREAD

**Issue by DefectiveByDesign** [Blinue/Magpie#10]
Please make a translation, google translate would be good enough.

I could probably use Capture2text until there's a translation, but not having one will limit the userbase and hurt search results.

**Comment by Blinue** [comment]
Thank you so much for your suggestion. I'm glad to see this tool useful to you, I wrote it for my own needs.

I am not good at English, so although I am willing to translate it, I need some help.

The user interface does not have too much text, so you should not encounter too much trouble to use. I will translate it, but it may take a long time.

**Comment by FluffyDiscord** [comment]
+1

**Comment by kondors1995** [comment]
It would be really nice to have UI translated to english  how abou t ussing matchine traslatiing

**Comment by Blinue** [comment]
[Here](https://github.com/andrewcs0901/Magpie/releases/tag/v0.5.1) is an English translation. Many thanks to @andrewcs0901

**Comment by kondors1995** [comment]
big tnx

**Comment by Blinue** [comment]
Thanks to @neoKushan, Magpie supports English now.

**Comment by jukrb0x** [comment]
> Thanks to @neoKushan, Magpie supports English now.

The program is great. I would suggest translation for the complete document (description, intro, how to use, ...) so that the repository can be shared in a more fluid manner.

DeepL is better than Google translate, I think, may help with translating.

**Comment by mirh** [comment]
It wouldn't be bad if you could have an english readme (like [here](https://github.com/Pixeval/Pixeval) for example) too. 
https://github.com/7Brandyn7/Magpie

**Comment by r57zone** [comment]
The latest version has support for English 
![](https://user-images.githubusercontent.com/9499881/147781745-a2376ab7-b2b6-49d8-b190-55caa4642576.png)

**Comment by mirh** [comment]
Yes, I just asked for a translated readme on github. 
@7brandyn7 can make a PR with his perhaps
