### ISSUE TITLE
使用截图工具截图时会截取到鼠标

### ISSUE THREAD

**Issue by wang-ctrl** [Blinue/Magpie#1001]
### Expected behavior 预期的功能

magpie全屏后再配合picpick或是faststone等截图工具时，截图会把鼠标也截取到
尽管取消掉绘制光标的勾选后截图就不会截取到鼠标，但是这样就完全没有了光标很难进行操控
有可能的话希望能够优化一下，十分感谢!

**Comment by Blinue** [comment]
推荐用Win+PrintScreen截图，第三方工具适配不了
