### ISSUE TITLE
使用同样的内置算法从0.9.1换到0.11.1最新版后性能急剧下跌

### ISSUE THREAD

**Issue by xkjxziochu** [Blinue/Magpie#1005]
### Program(Game) 游戏名

视觉小说/Galgame

### Capture method 捕获模式

Graphics Capture

### Related screenshot (optional) 相关截图（可选）

使用旧版本的帧率可以轻松稳定60FPS或以上：
![20241002114039050](https://github.com/user-attachments/assets/88d406ab-a28f-48ef-aead-cdf82fe1ef1d)
![20241002114039051](https://github.com/user-attachments/assets/7f704595-75a1-4eeb-8618-ed061a1faf14)
![20241002114039052](https://github.com/user-attachments/assets/34a98b7c-b94f-49f0-b5db-2c329056a1b5)
换为新版本后只有不到30fps，而且帧率波动极大，已经尝试切换其他捕获模式，渲染算法，也是同样的情况，开启模拟独占全屏，内联效果参数、禁用DirectFlip等也是同样帧率极低
![20241002114239053](https://github.com/user-attachments/assets/9b66e140-7768-4829-a08e-c67a64c1f5f3)
![20241002114339054](https://github.com/user-attachments/assets/28cee3e6-58ff-43ed-84af-41a21b5b37f6)
![20241002114339055](https://github.com/user-attachments/assets/a1031085-282d-45c9-b145-63499444ad27)

### Log files 日志文件

旧版本日志文件：[Magpie.log](https://github.com/user-attachments/files/17219486/Magpie.log)
新版本日志文件：[magpie.log](https://github.com/user-attachments/files/17219483/magpie.log)

**Comment by BLACKCHARGE** [comment]
这是因为重复帧检测的原因，检测到重复帧就不缩放了，可以有效降低GPU负载，你没觉得卡顿就没影响

**Comment by xkjxziochu** [comment]
> 这是因为重复帧检测的原因，检测到重复帧就不缩放了，可以有效降低GPU负载，你没觉得卡顿就没影响

淦，原来新版本的重复帧检测优化会导致这种视觉小说游戏变成这样吗？但我的确是肉眼感受到游戏里的小动画会卡顿，其他倒是没太感受出来。我之所以感受最明显是因为我用着sunshine串流到手机就会感受到巨卡，是卡到文字都一帧一帧出来的

**Comment by xkjxziochu** [comment]
> 这是因为重复帧检测的原因，检测到重复帧就不缩放了，可以有效降低GPU负载，你没觉得卡顿就没影响

有手动关闭的方法吗？还是说我只能回滚到旧版本了XD

**Comment by BLACKCHARGE** [comment]
> > 这是因为重复帧检测的原因，检测到重复帧就不缩放了，可以有效降低GPU负载，你没觉得卡顿就没影响
> 
> 有手动关闭的方法吗？还是说我只能回滚到旧版本了XD

打开3D游戏模式或者去开发者选项里关掉

**Comment by Blinue** [comment]
小动画卡顿可能和 #899 有关。串流卡可以参考 https://github.com/Blinue/Magpie/issues/141#issuecomment-2105749081 配置

**Comment by xkjxziochu** [comment]
> > > 这是因为重复帧检测的原因，检测到重复帧就不缩放了，可以有效降低GPU负载，你没觉得卡顿就没影响
> > 
> > 
> > 有手动关闭的方法吗？还是说我只能回滚到旧版本了XD
> 
> 打开3D游戏模式或者去开发者选项里关掉

谢谢！开启3D模式后确实可以了，不过目前就是搞不清楚为什么串流会感觉到那么明显的卡顿而直接从屏幕看则不会，目前还在研究，如果可以解决的话就不损失体验的情况下降低功耗了
