### ISSUE TITLE
用LE转区之后无法放大

### ISSUE THREAD

**Issue by someggs** [Blinue/Magpie#1006]
### Expected behavior 预期的功能

希望用了转区工具后也能放大

**Comment by Blinue** [comment]
试试以管理员身份运行 Magpie

**Comment by someggs** [comment]
好的 试过已经解决了，谢谢你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xu ***@***.***&gt;
发送时间: 2024年10月4日 10:51
收件人: Blinue/Magpie ***@***.***&gt;
抄送: someggs ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Blinue/Magpie] 用LE转区之后无法放大 (Issue #1006)





 
试试以管理员身份运行 Magpie
