### ISSUE TITLE
not working on LEGO DC Super-Villains

### ISSUE THREAD

**Issue by duckaleuze** [Blinue/Magpie#1007]
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

win10 22h2 19045.5011

### Reproduction steps 复现步骤

open the game, launch Magpie and try to use it

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/17370331/magpie.log)

**Comment by Blinue** [comment]
To use Magpie, you should run the game in windowed mode.
