### ISSUE TITLE
你好，请问在一些网游，例如彩虹六号、黎明杀机这些游戏里面可以用吗？

### ISSUE THREAD

**Issue by Lemon4289** [Blinue/Magpie#101]
它们分别使用battleye和easy anti-cheat作为反作弊引擎，会有导致游戏被封号的可能吗？

**Comment by Blinue** [comment]
这个问题你应该问游戏/反作弊引擎开发者。

Magpie对游戏的更改：使用EasyHook将一个DLL注入游戏进程，并接管SetCursor函数。
