### ISSUE TITLE
Add keyboard shortcuts to change scaling mode

### ISSUE THREAD

**Issue by octopushugger** [Blinue/Magpie#1012]
### Expected behavior 预期的功能

I would like to be able to change scaling mode without leaving fullscreen, selecting from the dropdown, and fullscreening again. It can be hard to compare scaling algorithms with so much change blindness inbetween switching modes. It would also be much faster to just hit a key combo. 

Maybe add buttons like this to add/modify key combo to switch to the mode when scaling is active:
![Magpie_BMSbJMvPLH](https://github.com/user-attachments/assets/5b9f5c7f-c96c-4550-b87f-7b5516a97458)

Would also be nice if it allowed setting a single key instead of only a combo.

**Comment by hooke007** [comment]
dup https://github.com/Blinue/Magpie/issues/387
