### ISSUE TITLE
运行steam版的quake1无法缩放窗口

### ISSUE THREAD

**Issue by 0erek9** [Blinue/Magpie#1013]
### Magpie version 程序版本

v0.11.1

### Windows version 系统版本

win10 22H2

### Related screenshot (optional) 相关截图（可选）

![无标题](https://github.com/user-attachments/assets/4f96c797-a2f7-4aa4-b2b3-9082044617d8)
![image](https://github.com/user-attachments/assets/b40485c8-bab3-4831-8157-9a81c7846fee)
![image](https://github.com/user-attachments/assets/be95022e-bd86-4cf9-8e0a-a090d61a9627)

### Reproduction steps 复现步骤

电脑的DirectX版本为12
快捷键为alt+F11
所有的缩放模式和捕获方式都试过了，没有用，定时器激活也没有用,更换显示卡选项没有用
最多就是游戏里面的鼠标指针消失了，然后窗口会闪一下黄色方框
以管理员运行magpie没有用

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/17485569/magpie.log)

**Comment by Blinue** [comment]
和 #979 是同样的问题，你的显卡不支持 [ID3D11Device5::CreateFence](https://learn.microsoft.com/en-us/windows/win32/api/d3d11_4/nf-d3d11_4-id3d11device5-createfence)。你可以试试更新驱动，或者用 v0.10。
