### ISSUE TITLE
Not working with Ragnarok Landverse Thailand

### ISSUE THREAD

**Issue by bankthanapol** [Blinue/Magpie#1017]
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

Win11

### Reproduction steps 复现步骤

1. open Magpie
2. open Ragnarok Landverse Thailand
3. press hotkey to start win+shift+a
4. nothing happen

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/17567913/magpie.log)

**Comment by Blinue** [comment]
Have you tried running magpie as admin?

**Comment by bankthanapol** [comment]
Hi,

Thanks for advice, work like a charm
big thanks

Best Regard,
Thanapol (Bank).
