### ISSUE TITLE
Cursor not showing on second screen

### ISSUE THREAD

**Issue by kanjieater** [Blinue/Magpie#1020]
### Magpie version 程序版本

v0.11.1

### Windows version 系统版本

Win 11

### Related screenshot (optional) 相关截图（可选）

![image](https://github.com/user-attachments/assets/70edb99f-52fb-4970-acbb-305d9e174b26)

The game is on my 1 monitor on the right. The cursor shows over the upscaled game just fine. I move my mouse to another screen or disable magpie, and i cant see my cursor anywhere.

### Reproduction steps 复现步骤

1. Start game. (I'm trying to use on the visual novel called 大穢)
2. Press magpie hotkey
3. Cursor only is drawn over the game & hidden on all other screens, even if I disable magpie again

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/17601250/magpie.log)

**Comment by Blinue** [comment]
Have you tried changing the capture method?

**Comment by kanjieater** [comment]
Yes, i can post logs for those too

**Comment by Blinue** [comment]
I’m unable to reproduce the issue on my end. Does this error also occur when scaling other games?

**Comment by kanjieater** [comment]
[magpie.log](https://github.com/user-attachments/files/17666813/magpie.log)
I'm not sure what changed but it seemed to resolve itself, after i rotated through the other capture methods

**Comment by kanjieater** [comment]
The issue was another program called YomiNinja. When I close that, things go back to normal. Thank you for the help as always.

**Comment by kanjieater** [comment]
It seems magpie has this issue when anything tries to capture the display. I can reproduce this with another program called [GameSentenceMiner](https://github.com/bpwhelan/GameSentenceMiner) It happens every time for me, and the creator managed to reproduce but much less frequently.

If i use the OBS capture in this software my cursor disappears. If I close obs, my cursor shows with magpie just fine.

**Comment by Blinue** [comment]
Thanks for investigating! I can now reproduce the issue on my end.

WGC has long had compatibility issues with ShowSystemCursor, so I restart WGC whenever the cursor moves to another window/monitor to work around it. However, this approach appears to break down when other applications are also using WGC. I’ll look into alternative solutions.
