### ISSUE TITLE
兼容性模式下无法放大窗口

### ISSUE THREAD

**Issue by jyxjyx1234** [Blinue/Magpie#1023]
### Question 问题

在游玩一个老游戏时，游戏需要在兼容性模式（windows xp）下才能运行。我尝试了所有四种捕获方式，magpie均无法放大窗口。请问有什么解决方案吗？

**Comment by Blinue** [comment]
需要以管理员身份运行magpie

**Comment by jyxjyx1234** [comment]
了解了，非常感谢
