### ISSUE TITLE
在144hz/165hz刷新率下，Graphics Capture模式下帧数无法跟随原始帧数

### ISSUE THREAD

**Issue by RuckyLu123** [Blinue/Magpie#1024]
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

win11 24h2 26100.2161

### Related screenshot (optional) 相关截图（可选）

![8f3cc9589a400ff194850308550db9e](https://github.com/user-attachments/assets/94cbd931-901a-44e5-bf6b-b27183cce554)
系统配置为：12700kf D4 4090
其他模式并无异常

### Reproduction steps 复现步骤

1.调整 '主' 显示器刷新率为非60整数倍的刷新率，如144，165等
2.打开任何一个默认帧数为稳定60FPS的视觉小说游戏
3.选择Graphics Capture抓捕模式 
4.按下hotkey
5.观察自带的帧数检测器数值

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/17663645/magpie.log)
[magpie.1.log](https://github.com/user-attachments/files/17663647/magpie.1.log)

**Comment by RuckyLu123** [comment]
若是主显示器调为60的整数倍刷新率，如60，120，则不会出现此问题

**Comment by RuckyLu123** [comment]
我可能没有解释清楚，帧数不是浮动的而是锁定48fps，稳定的48fps，同时显卡能耗表现同时符合帧数限制为48fps的功耗，然后RTSS的帧数监视器也抓取magpie的窗口帧数为48

**Comment by RuckyLu123** [comment]
> 60 FPS 即每帧 16.6ms，显示器 144 Hz 每帧展示 6.9ms，这种不匹配使得经常某一帧落在下一秒里，那么前一秒就是 59 FPS，后一秒是 61 FPS。表面上帧率浮动，其实是稳定的。
我可能没有解释清楚，帧数不是浮动的而是锁定48fps，稳定的48fps，同时显卡能耗表现同时符合帧数限制为48fps的功耗，然后RTSS的帧数监视器也抓取magpie的窗口帧数为48

**Comment by RuckyLu123** [comment]
> 60 FPS 即每帧 16.6ms，显示器 144 Hz 每帧展示 6.9ms，这种不匹配使得经常某一帧落在下一秒里，那么前一秒就是 59 FPS，后一秒是 61 FPS。表面上帧率浮动，其实是稳定的。

我可能没有解释清楚，帧数不是浮动的而是锁定48fps，稳定的48fps，同时显卡能耗表现同时符合帧数限制为48fps的功耗，然后RTSS的帧数监视器也抓取magpie的窗口帧数为48

**Comment by Blinue** [comment]
magpie 的帧数没有参考价值，因为会自动删除了重复帧，而且也和捕获方式有关。打开 3D 游戏模式会关闭重复帧检测，这样你就能看到捕获的帧数。

**Comment by RuckyLu123** [comment]
> magpie 的帧数没有参考价值，因为会自动删除了重复帧，而且也和捕获方式有关。打开 3D 游戏模式会关闭重复帧检测，这样你就能看到捕获的帧数。

已测试，在3D模式下依旧锁48帧，但如果显示器刷新率改为60或120，则正常保持60

**Comment by RuckyLu123** [comment]
我换个平台测试下，可能是系统问题

**Comment by RuckyLu123** [comment]
> magpie 的帧数没有参考价值，因为会自动删除了重复帧，而且也和捕获方式有关。打开 3D 游戏模式会关闭重复帧检测，这样你就能看到捕获的帧数。

win10 下 加7800XT 无法复现，怀疑是驱动或者系统问题

**Comment by RuckyLu123** [comment]
问题关闭，属于偶发性bug，估计只存在于个人系统上

**Comment by RuckyLu123** [comment]
问题关闭，属于偶发性bug，估计只存在于个人系统上

**Comment by RuckyLu123** [comment]
重装23h2 问题解决 真的麻了
