### ISSUE TITLE
个例游戏无法缩放

### ISSUE THREAD

**Issue by tcg279** [Blinue/Magpie#1025]
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

windows11 家庭版 22631.4317

### Related screenshot (optional) 相关截图（可选）

![QQ20241108-200059](https://github.com/user-attachments/assets/79c57e27-8657-490e-ac0c-12ee6ba710d7)
![QQ20241108-195947](https://github.com/user-attachments/assets/b25d57d6-1da7-442f-85a8-d37f7288b2cc)

### Reproduction steps 复现步骤

游戏名为  ウルスラグナ ～征戦のデュエリスト～ （乌鲁斯拉格纳~征战的决斗者）
日版原版可以正常缩放，汉化版缩放无反应。（图一为汉化版，图二为已缩放的日版）
软件设置没有问题其他游戏都可正常缩放，目前只发现这个无法缩放。
日版于2024.11.08 9分左右进行测试 
汉化版于2024.11.08.10分左右进行测试
游戏原文件通过百度网盘分享的文件：ches.rar
链接：https://pan.baidu.com/s/1m2fMlKJi2iUx_u84RhbU0Q?pwd=oyv3 
提取码：oyv3 

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/17678327/magpie.log)

**Comment by RuckyLu123** [comment]
建议尝试使用管理员模式启动magpie再进行缩放试试

**Comment by tcg279** [comment]
> 建议尝试使用管理员模式启动magpie再进行缩放试试

成功了谢谢你的回复。
