### ISSUE TITLE
外接显示器时4:3游戏无法全屏

### ISSUE THREAD

**Issue by blongtimeago** [Blinue/Magpie#1027]
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

win11 23H2

### Related screenshot (optional) 相关截图（可选）

![屏幕截图 2024-12-01 142801](https://github.com/user-attachments/assets/6c70561f-857e-4bac-921f-d52c43cf3712)
![屏幕截图 2024-12-01 142845](https://github.com/user-attachments/assets/e4be87c9-4a2a-4953-b57b-d78ec477eb33)

### Reproduction steps 复现步骤

笔记本屏幕16：10，1080p，可正常全屏所有分辨率游戏。外接显示器16：9，2k，投影选“仅第二屏幕”（即仅在显示器上显示），可正常全屏16:9的720p或1080p游戏，无法全屏800*600的4:3游戏（上下左右都有黑边）。

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/17967904/magpie.log)

**Comment by Blinue** [comment]
你只用了一个 Anime4K_Upscale，把画面放大一倍，所以没法填满屏幕。

**Comment by blongtimeago** [comment]
> 你只用了一个 Anime4K_Upscale，把画面放大一倍，所以没法填满屏幕。

确实是缩放模式的问题。调了可以了，感谢！
