### ISSUE TITLE
Pixellate or Sharp Bilinear shader implementation

### ISSUE THREAD

**Issue by ribolovac510** [Blinue/Magpie#103]
Hello, I was wondering if it would be possible to implement Pixellate or Sharp Bilinear shader for upscaling pixel graphics. This would be useful for users who want to upscale games with pixel graphics with non-integer scaling and maintain the sharp pixel look without shimmering and non-square pixels.

Here's an explanation what these shaders do:
https://filthypants.blogspot.com/2017/01/shaders-for-sharpest-pixels.html
and also their implementation in libretro/RetroArch for example:
https://github.com/libretro/common-shaders/blob/master/interpolation/shaders/pixellate.cg
https://github.com/libretro/common-shaders/blob/master/interpolation/shaders/sharp-bilinear.cg

**Comment by Blinue** [comment]
There has been a feature request for pixel art #62. 

It's not hard to port these shaders and I will port them after the refactoring is done.

**Comment by ribolovac510** [comment]
Cool, xBRZ produces rounder shapes while these shaders produce more of a blocky retro looking image, all in all having lots of different upscaling options so users can pick and choose based on their preferences is great.
Thank you very much for you work, looking forward to future releases! :)
