### ISSUE TITLE
画面卡住

### ISSUE THREAD

**Issue by hhyacg** [Blinue/Magpie#104]
放大后在某些ADV游戏上经过几秒画面就会卡住，但声音没卡(测试另外一些ADV游戏就不会，奇怪)，需要输入动作例如移动鼠标之类的才不会卡住，不知道是游戏引擎的锅还是啥。抓取模式、注入方式和缩放模式都测了一遍，无解。

**Comment by Blinue** [comment]
Magpie不会检测光标移动，它只是在每帧都获取光标位置并渲染出来，因此这个错误应该与Magpie无关。你可以在选项->高级里打开帧率显示，看看究竟是Magpie卡住了还是游戏本身卡住了。

**Comment by hhyacg** [comment]
> Magpie不会检测光标移动，它只是在每帧都获取光标位置并渲染出来，因此这个错误应该与Magpie无关。你可以在选项->高级里打开帧率显示，看看究竟是Magpie卡住了还是游戏本身卡住了。

画面直接定格，帧率显示也不会动（显示什么数字就定在那里）

**Comment by Blinue** [comment]
应该是渲染失败了，可惜这部分没有日志，请等待下个版本

**Comment by Blinue** [comment]
请尝试最新版本，如果依然遇到此问题，可以提交新的 issue。
