### ISSUE TITLE
Can't use WinRT, GDI works fine (and yes I am on a version higher than v1903)

### ISSUE THREAD

**Issue by EricPlayZ** [Blinue/Magpie#105]
I'm on 20H2. Magpie just doesn't seem to work with WinRT, no matter the injection method and it doesn't work on any game I have tried so far either, like Minecraft, Rocket League, etc. GDI works fine but its really choppy for me (the window runs only at 40 FPS for whatever reason). Is a component missing from my Windows install? I don't get it lol. I'm using the v6.0 release btw. If there's any fixes from the latest commits, I could build it and try again I guess.

![2021-09-01_13-23-07](https://user-images.githubusercontent.com/24963708/131656990-55069665-1ec9-42f8-9f77-f24bcf4eeff3.png)
![image](https://user-images.githubusercontent.com/24963708/131657463-8b65e804-0f08-4b12-a6c2-e2cd8f147e84.png)

EDIT: Here's some logs if they have anything useful in them:
[CursorHook.log](https://github.com/Blinue/Magpie/files/7090402/CursorHook.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/7090403/Magpie.log)

EDIT 2: I've compiled the latest source, I get the same issue although now I get an error in the log:
[Magpie.log](https://github.com/Blinue/Magpie/files/7090488/Magpie.log)

**Comment by Blinue** [comment]
[Magpie.zip](https://github.com/Blinue/Magpie/files/7090873/Magpie.zip)

Try this build.

**Comment by EricPlayZ** [comment]
> [Magpie.zip](https://github.com/Blinue/Magpie/files/7090873/Magpie.zip)
> 
> Try this build.

Still doesn't work, although now I get a different error:

![image](https://user-images.githubusercontent.com/24963708/131682150-7e500dd5-f810-4b78-b4e2-b08790973977.png)

**Comment by EricPlayZ** [comment]
Nope, though my GPU is integrated, don't know if that has any impact. I also mess around with Windows a lot, so could've I possibly broken a service/component that is required in order for it to work?

**Comment by Blinue** [comment]
If the latest version still has this issue, feel free to reopen it
