### ISSUE TITLE
Feature Request ...

### ISSUE THREAD

**Issue by Nerboruto** [Blinue/Magpie#107]
could you add a function that skips any kind of transformation of the captured window? in practice, the captured window must appear in the center of the screen as acquired.
it could be useful to better diagnose lag problems.
Thank you.

**Comment by Blinue** [comment]
Just add this to ScaleModels.json:

``` json
{
    "name": "Origin",
    "model": []
}
```

I'm working on improving performance, big changes will be made in the next version :)

**Comment by Nerboruto** [comment]
Thank you I'll try it...
