### ISSUE TITLE
文明5在使用后会双光标

### ISSUE THREAD

**Issue by pkudeader** [Blinue/Magpie#108]
使用方法：
桌面分辨率为3840*2160，文明5设置1920*1080窗口模式，然后使用快捷键全屏。
可以正常全屏，效果也不错，但光标一直有两个。
无论是不注入、启动后注入、运行时注入都是这样。
用不同的放大方法都有。
Magpie版本是0.6

**Comment by Blinue** [comment]
请提供logs文件夹里的日志

**Comment by pkudeader** [comment]
[Magpie.log](https://github.com/Blinue/Magpie/files/7102584/Magpie.log)

**Comment by Blinue** [comment]
EasyHook的注入失败了，有可能是游戏限制进程注入

**Comment by hooke007** [comment]
link https://github.com/Blinue/Magpie/issues/121
