### ISSUE TITLE
tripling mouse cursor

### ISSUE THREAD

**Issue by Nuke142** [Blinue/Magpie#112]
Game "Ratropolis" have only 1080p resolution so i want to use Magpie for better looking at my 1440p monitor.
Problem is game doubling or even tripling mouse cursor when i press alt+f11.
other games i tested don't have this issue.
Please look, game for you: https://drive.google.com/file/d/15vBk5Gd0DKaniW5lzcl52N0HRr7vALVq/view?usp=sharing

**Comment by Blinue** [comment]
I didn't encounter this issue.
![屏幕截图(1925)](https://user-images.githubusercontent.com/34770031/132125034-c8ef2297-7868-48e8-891b-f74a19dc65e6.png)
Make the game windowed first, then select "Inject at Runtime" in Magpie.

**Comment by Nuke142** [comment]
Yeah. Now it's works properly.
What about "Inject at Runtime" ? Is it recommended setting as default? What it do and why it's good?

**Comment by 22earth** [comment]
> Yeah. Now it's works properly.
> What about "Inject at Runtime" ? Is it recommended setting as default? What it do and why it's good?

If the target window uses a custom cursor, two cursors may appear on the screen. To solve this problem, you can use "Injection Mode" of Magpie.

No Injection: default mode for the target window does not have a custom cursor
Injection at Runtime: inject DLL into target process at runtime, and remove the injection after exiting fullscreen
Injection at Startup: when "Injection at Runtime" does not work properly, you can choose this option. You need to manually select the program to be started and injected.

ps: some antivirus software may flag Magpie as malicious when it use DLL injection technique
