### ISSUE TITLE
FSR doesn't work on 0.6, was working on 0.5

### ISSUE THREAD

**Issue by notNSANE** [Blinue/Magpie#114]
Windows 10 x64 fully updated, GPU is AMD HD 6850, CPU is Ryzen 1600.

All other modes work. This is the error when I use the hotkeys:

![image](https://user-images.githubusercontent.com/7162375/132124581-1cd439bb-5d67-4873-b9cc-b1311a7cea12.png)

There's no info about this on logs.txt so no point in pasting, I triple checked.

Extra info just in case: Only RAVU gives good performance on my GPU, on WinRT mode. GDI has terrible performance in all modes.

**Comment by Blinue** [comment]
Did you mean v0.6? This is the latest version.

**Comment by notNSANE** [comment]
yep, fixed titl

**Comment by Blinue** [comment]
[Magpie.zip](https://github.com/Blinue/Magpie/files/7090873/Magpie.zip)

Try this build and screenshot the error message.

**Comment by MuhammadUsmanMithani** [comment]
[this](https://i.imgur.com/h38ukY8.png) is the error im getting (chinese logs in english mode tho)

**Comment by Blinue** [comment]
Delete ScaleModels.json in the root directory, then it should work properly.

**Comment by notNSANE** [comment]
perfect!
