### ISSUE TITLE
Stuter: GAME RUST

### ISSUE THREAD

**Issue by jokbon** [Blinue/Magpie#115]
https://user-images.githubusercontent.com/29400409/132127704-fd61887a-881e-420f-a1c6-6fc99c6d9781.mp4

Stutter on game rust. DX11

**Comment by jokbon** [comment]
on all modes it stuters or have poor performance

**Comment by Blinue** [comment]
There've been many reports about performance issues and I am working on it.

**Comment by Blinue** [comment]
I am closing this as it is outdated. If you encounter this problem in the latest version, please file a new issue.
