### ISSUE TITLE
稍修改大小和饱和度的新图标包

### ISSUE THREAD

**Issue by LightMu** [Blinue/Magpie#116]
<img src = 'https://s3.bmp.ovh/imgs/2021/09/69613448651f58ea.png' />

链接https://wwa.lanzoui.com/iJv2nto8k4f

**Comment by Blinue** [comment]
![image](https://user-images.githubusercontent.com/34770031/132204198-eafa1bc2-a012-48c8-853f-1bda07c56d14.png)
![image](https://user-images.githubusercontent.com/34770031/132204217-2b963838-ddf3-49eb-816c-44d84cdf61b7.png)
![image](https://user-images.githubusercontent.com/34770031/132204247-9f39f1d9-0076-48e1-b3e7-3fd24d5c4549.png)
![image](https://user-images.githubusercontent.com/34770031/132204383-c4c2480f-02b0-48ce-9f18-25add597c860.png)
![image](https://user-images.githubusercontent.com/34770031/132204409-eabbff11-7b8a-4f93-8ca2-b0e770a5305f.png)

大小合适，但浅色背景下对比度还是差一点，另外在深色背景下形状显得有点奇怪（个人感觉）

**Comment by Blinue** [comment]
你可以自己替换图标试试，只需替换Magpie文件夹里的logo.ico

**Comment by LightMu** [comment]
<img src = 'https://s3.bmp.ovh/imgs/2021/09/9a98f49e9d19bc74.png' />

周围加一点黑色阴影，浅色下图标的表现就会好很多，没办法同时兼顾两个，除非改用鲜艳的红色或者蓝色打底

**Comment by Blinue** [comment]
![image](https://user-images.githubusercontent.com/34770031/132217313-1664bb5c-d2b7-4b35-8cf1-11ea6401259e.png)
加了阴影效果更不好了

渐变色在图标很小时很难看得清，而且现在的颜色比较淡，放在白色背景下对比度不够。另外灰色的边框也太细节，在32x32下基本看不到，缩小时也影响观感。可以再简化一下，颜色加深一点，可以换成纯色或者几种不同颜色的组合（蓝白，蓝绿等），在各种颜色的背景上都有足够的对比度。我觉得越简单越好。

放几个或许可以参考的图标
![image](https://user-images.githubusercontent.com/34770031/132220589-7d79007d-c1f8-431d-abdf-8a6663db6b99.png)
![image](https://user-images.githubusercontent.com/34770031/132220740-72b42182-8377-47ad-9f48-8f3db63d8628.png)
![image](https://user-images.githubusercontent.com/34770031/132221124-60cd5990-74d5-4678-bf2f-354572237ccd.png)
![image](https://user-images.githubusercontent.com/34770031/132221172-f46ecb41-cd02-470b-8cbf-148fc928ad39.png)
![image](https://user-images.githubusercontent.com/34770031/132221410-f8f80b99-7b4e-4deb-b9e3-e4ca9ffe3f3a.png)

抱歉提了这么多要求，因为Logo是一个项目的门面

**Comment by LightMu** [comment]
<img src = 'https://s3.bmp.ovh/imgs/2021/09/af115b5118e1e65d.png' />

**Comment by LightMu** [comment]
<img src = 'https://s3.bmp.ovh/imgs/2021/09/200364218975b3d8.png' />

**Comment by Blinue** [comment]
![image](https://user-images.githubusercontent.com/34770031/132233348-4965541d-5998-48b0-9e31-96ee2b0120ed.png)
![image](https://user-images.githubusercontent.com/34770031/132233715-eb12cd36-0f46-41cd-a867-f61fe8028fa1.png)
![image](https://user-images.githubusercontent.com/34770031/132233722-297efdba-85a1-4a2b-83c3-c57d5e302888.png)
![image](https://user-images.githubusercontent.com/34770031/132233731-8d603813-28a2-4d1b-bf29-9af452e6177e.png)
两个都很棒。小图标的话第二个更好看，但是相比第一个配色有点单调

**Comment by LightMu** [comment]
<img src = 'https://s3.bmp.ovh/imgs/2021/09/24a63c62cb134cfe.png' />

**Comment by Blinue** [comment]
yysy，确实
![image](https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/45/aa/82/45aa82d1-9e7b-9525-3492-52d8b36cb88a/source/512x512bb.jpg)
配色和形状都和小猿搜题很像...

**Comment by Blinue** [comment]
有更多想法请提交新 issue
