### ISSUE TITLE
Target设置成x64，编译失败

### ISSUE THREAD

**Issue by JeffersonQin** [Blinue/Magpie#117]
如题：

![image](https://user-images.githubusercontent.com/30655701/132203226-d3763a1c-ae58-4e88-acac-230a26efbc5d.png)

x86下无上述情况，下面是自动生成的 x86 配置格式：

![image](https://user-images.githubusercontent.com/30655701/132203398-7c1c51db-2a50-4f6d-bc9e-ae6330403b7b.png)

由于默认情况下没有 x86 这个配置，所以一添加就会让所有 project 文件修改内容，所以对此感到困惑，谢谢解答。

**Comment by Blinue** [comment]
只有x64配置。想编译x86的话你需要配置一下CONAN_INSTALL，它默认只生成x64的依赖

**Comment by JeffersonQin** [comment]
谢谢。因为我不太熟悉C++，我前面研究了一下，貌似是因为没有安装依赖导致找不到头文件。建议把这部分内容加入编译的wiki里

**Comment by Blinue** [comment]
生成CONAN_INSTALL将自动添加依赖，但只会添加x64的，因此你在编译x64时没有错误。Magpie不支持x86，不熟悉C++的话就不要尝试编译了。

**Comment by JeffersonQin** [comment]
好的（大感谢
