### ISSUE TITLE
两个光标 Double Cursor

### ISSUE THREAD

**Issue by Blinue** [Blinue/Magpie#121]
如果你在使用Magpie时遇到了两个光标的问题，首先请尝试将“进程注入”选项设置为“运行时注入”，如果不起作用，再尝试“启动时注入”。如果它们都不起作用，请在这里汇报这个问题（记得提交日志）。

请注意：
1. **不要**在多人游戏中使用这个选项，可能会被反作弊引擎判定为作弊。
2. 这个选项无法保证成功，因为有些游戏限制进程注入。你可以在本 issue 查找有没有对这个游戏的汇报。

**Comment by Blinue** [comment]
[这里](https://github.com/Blinue/Magpie/wiki/%E5%8F%8C%E9%87%8D%E5%85%89%E6%A0%87-Double-Cursors)汇总了进程注入功能对游戏的支持，欢迎任何人贡献。

**Comment by Blinue** [comment]
feature/doubleCursor分支更换了隐藏光标的方式，现在没有双光标的问题了，希望你们测试一下 @palxex @hooke007

**Comment by hooke007** [comment]
我这里测试暂无问题
Total War 这种需要启动器的游戏也没问题了

**Comment by Blinue** [comment]
而且不需要进程注入，也能用在多人游戏里了

**Comment by PenguinDOOM** [comment]
Double cursor in genshin imapct has been resolved.

**Comment by palxex** [comment]
抱歉，刚找到时间测试。已确定原神/崩坏3/Cemu中双光标问题解决，暂未观察到其他问题。

**Comment by AVerteC** [comment]
Does Magpie still use process injection? I noticed the injection method selector has disappeared in Magpie v0.6.1

**Comment by Blinue** [comment]
No. You can now use Magpie on any game.

**Comment by sr1canskhsia** [comment]
![](https://p.sda1.dev/2/e53cf6339d29e1988ca3076e2890731e/Snipaste_2021-09-17_00-50-15.png)

出现问题了：凡是使用**BGI引擎**的游戏在**WinRT Capture**抓取模式下会出现双关标（GDI无此问题，v0.6.0无此问题），具体表现如图

已测试会出现双关标的游戏：
- あまいろショコラータ２
- サクラノ詩 —櫻の森の上を舞う—
- キラ☆キラ

其他游戏引擎尚未测试，系统版本为Windows 10 Version 1909

**Comment by Blinue** [comment]
看起来 WinRT Capture 把系统光标也捕获到了，这个问题只会在1903和1909的系统上出现，从2004开始这个API提供了不捕获系统光标的的功能。

Magpie 进入全屏时虽然全局隐藏了系统光标，但在某些窗口上系统光标仍有可能被 WinRT Capture 捕获到。暂时没有这个问题的解决办法，只能更换捕获方式或者升级系统。

我以后会增加不绘制光标的功能，这样就可以直接使用由 WinRT Capture 捕获到的光标了。

**Comment by sr1canskhsia** [comment]
感谢，看来我得考虑升级系统了，一直滞留在两年前的系统上也不是个办法

**Comment by Blinue** [comment]
现在已彻底解决双光标问题（除了在 RDP 中），所以我将关闭这个 issue。另外 wiki 中的双重光标页面我也计划删除 @hooke007
