### ISSUE TITLE
Planetside 2 FSRCNN is 6 times slower than FSR

### ISSUE THREAD

**Issue by jokbon** [Blinue/Magpie#122]
![image](https://user-images.githubusercontent.com/29400409/132343931-9f42da2e-ab62-488b-ab90-bc74b4c94597.png)
vs
![image](https://user-images.githubusercontent.com/29400409/132343993-10a82d4f-9839-4e73-9793-7b685ce2a813.png)

Asuming theres probaly some isusue.

**Comment by jokbon** [comment]
game runs dx11

**Comment by Blinue** [comment]
FSRCNNX takes more GPU resources than FSR, and it is not suitable for 3D games.
