### ISSUE TITLE
[feature request] add the option to manually tweak the size of cursor after upscaling

### ISSUE THREAD

**Issue by hooke007** [Blinue/Magpie#124]
增加选项：允许用户调节缩放后绘制光标的放大/缩小倍率。算是体验上的额外微小改进吧

源窗口的分辨率和缩放目标分辨率差距过大的话，当前情况下，放大后的光标会显得过小。

这个选项对应的应该是部分游戏存在的游戏内光标大小调节功能。

**Comment by Blinue** [comment]
在高分辨率下全屏后的绘制的光标和原始光标大小一样吗

**Comment by hooke007** [comment]
目前是完全一样

**Comment by Blinue** [comment]
非整数倍缩放会有模糊的问题，除非让光标也支持高级缩放算法

**Comment by hooke007** [comment]
光标模糊倒是不重要，，主要是光标大小对游戏的操作逻辑会有影响

**Comment by Blinue** [comment]
我会在v0.7添加这个功能
