### ISSUE TITLE
Magpie refreshing 3fps while game is full 144, unless screen recording software is on.

### ISSUE THREAD

**Issue by ssjbardock** [Blinue/Magpie#129]
Not sure what is triggering this issue, but the game (Days Gone) was working fine yesterday for hours, then today (no updates/changes) Magpie is refreshing at 3fps (counter on), but in game stats show full 144hz.

Additionally, while trying to record the issue, I found that if I am recording with either the Xbox recorder (win+g), or AMD recorder, the game works fine in Magpie!

If I end the amd recording with the hotkey while playing, Magpie immediately drops back to 3 fps.

Played fine using .6 yesterday, now today .6 and .6.1 both present same problem.

So far no other games presenting this.

Specs: 5800x / 6800xt / 64gb ram

**Comment by LightMu** [comment]
I remember that DayGone used the old version of UE4 and couldn't turn on TAAU, so I used Magpie to zoom and get a lower number of frames. It seems that LosslessScaling is normal.

**Comment by Blinue** [comment]
I believe this is because the game is optimized in some way so that it has a high priority on the GPU. The recording feature provided by the OS can ignore this optimization, but Magpie cannot.

**Comment by ssjbardock** [comment]
The weird part is it worked fine without the recording software for hours yesterday. Still not sure what could have changed as I haven't updated anything for the last week or so.

**Comment by ssjbardock** [comment]
Wrong button. Still strange that it worked for hours yesterday without any recording software going, but stopped today. Can't think of any changes I've made recently that could have caused this. Hopefully the 0.7 capture method helps!

**Comment by tigerw** [comment]
#166 may be relevant here, specifically https://github.com/Blinue/Magpie/issues/166#issuecomment-932931520. The author provided a patched build: https://github.com/Blinue/Magpie/issues/166#issuecomment-932912782

**Comment by Blinue** [comment]
You can turn on "Disable DirectFlip" to fix this issue now
