### ISSUE TITLE
希望增加子项目的设置界面

### ISSUE THREAD

**Issue by LightMu** [Blinue/Magpie#130]
希望在应用程序里增加缩放比例和锐化强度的设置界面，让操作设置更加简单。（非必须）

**Comment by hooke007** [comment]
_这个问题的本质其实就是ScaleModels.json的图形化_

**Comment by Blinue** [comment]
现在有个在游戏内更改缩放配置的计划，类似于Reshade。这个功能短时间内不会实现，我现在主要在做性能优化。

**Comment by Blinue** [comment]
v0.10 已实现

**Comment by LightMu** [comment]
感谢，新功能很好用。
Magpie距离上次更新有一段时间了。因为我使用Magpie的主要目的是游戏，我一直在寻找其它在游戏上表现更好的项目，不久前已经找到了Magpie和LosslessScaling的替代品。使用注入式的采样缩放器，可以实现更高版本FSR和DLSS。我想它可能来源于RTX Remix游戏里的应用，目前已经有多款游戏支持。它的缩放方法似乎是将采用实际分辨率的窗口超分得到更大的窗口，再将其设置为全屏幕无边框窗口。如果您对这个有兴趣，您可以作为参考拓展magpie的后续功能。
再次感谢您和所有开发成员的辛苦和付出。祝您生活愉快！

**Comment by Rigelstars** [comment]
> 感谢，新功能很好用。
> Magpie距离上次更新有一段时间了。因为我使用Magpie的主要目的是游戏，我一直在寻找其它在游戏上表现更好的项目，不久前已经找到了Magpie和LosslessScaling的替代品。使用注入式的采样缩放器，可以实现更高版本FSR和DLSS。我想它可能来源于RTX Remix游戏里的应用，目前已经有多款游戏支持。它的缩放方法似乎是将采用实际分辨率的窗口超分得到更大的窗口，再将其设置为全屏幕无边框窗口。如果您对这个有兴趣，您可以作为参考拓展magpie的后续功能。目前我对Magpie的使用场景主要在2D游戏，视频和办公上。
> 再次感谢您和所有开发成员的辛苦和付出。祝您生活愉快！

除了这两个工具还有什么?
