### ISSUE TITLE
建议给图标加1像素白色描边以避免黑色任务栏下一坨黑 ... 附修改好的图像素材和对比图

### ISSUE THREAD

**Issue by neavo** [Blinue/Magpie#131]
现在的图标在黑色任务栏的时候完全是一坨黑什么都看不到，建议调整一下，

![对比](https://user-images.githubusercontent.com/998676/132795487-567ff873-3ee5-4822-bb51-e19e86dc5914.jpg)

[newicon.zip](https://github.com/Blinue/Magpie/files/7141082/newicon.zip)

**Comment by Blinue** [comment]
我想换一个全新的图标 #116 目前还在讨论中

**Comment by neavo** [comment]
> 我想换一个全新的图标 #116 目前还在讨论中

哈哈哈哈 我觉得 [#116](https://github.com/Blinue/Magpie/issues/116) 里那几个图标都有点一言难尽 （手动捂脸）

可以先加上描边顶一下，新图标的事情再从长计议，现在的实在是难找

**Comment by Blinue** [comment]
v0.7发布还要很久，暂时不急。你可以先用自己的分支

**Comment by Blinue** [comment]
如果没有新图标，我会添加根据任务栏颜色自动切换图标的功能

可用的API：
[获取系统颜色](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.uisettings.getcolorvalue?view=winrt-20348)
[系统颜色更改时得到通知](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.uisettings.colorvalueschanged?view=winrt-20348)
