### ISSUE TITLE
Fate Stay Night不能启用

### ISSUE THREAD

**Issue by Lancet7** [Blinue/Magpie#134]
OS: Windows 10 21H1
Magpie Version: 0.6.1

Fate Stay Night使用WinRT会提示 WinRT捕获出错，切换到GDI则提示 "渲染出错: wicBmpClipper初始化失败 (HRESULT=0x80070057)

**Comment by Blinue** [comment]
请查看[使用提示](https://github.com/Blinue/Magpie#%E4%BD%BF%E7%94%A8%E6%8F%90%E7%A4%BA)的第一条
