### ISSUE TITLE
App crashes after pressing hotkey

### ISSUE THREAD

**Issue by Kimika247** [Blinue/Magpie#138]
For some reason, the app automatically closes itself each time I press the hotkey. Tried different scaling/capture modes, hotkeys, DPI settings, older versions, tried with both games and default windows apps, running as admin, disabling windows defender, nothing changed. Windows 10 20H2 19042.1165 build. No idea how to fix this, here is the log file if that's any help
[Magpie.log](https://github.com/Blinue/Magpie/files/7150252/Magpie.log)

**Comment by Blinue** [comment]
#31 may help.

**Comment by Kimika247** [comment]
> #31 may help.
What is meant by building it yourself and how to actually do it?

**Comment by Blinue** [comment]
Compiling Magpie can be a daunting task if you are not familiar with programming. 

[Here](https://github.com/Blinue/Magpie/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97) (Chinese) is a description of how to compile it.

**Comment by loopdee** [comment]
I have the same issue running on Windows 7. I try Magpie (fsr) with Terraria, and then it crashes, with the windows prompt "Magpie has unexpectedly closed" or whatever.

**Comment by loopdee** [comment]
I attempted to compile through Visual Studio, and it gave me an error, telling me that the DLL 'Runtime' was unable to be loaded, and that the specified module could not be found.

**Comment by Blinue** [comment]
#69
