### ISSUE TITLE
有些游戏的窗口全屏后还是能选中窗口外，导致失去焦点

### ISSUE THREAD

**Issue by palxex** [Blinue/Magpie#140]
举例：原神窗口分辨率1920x1080，经Magpie FSR等比缩放至4K后，战斗中偶尔会恢复为窗口（因为此时按键多且频次高，无法判断具体是什么操作触发了问题），此时可发现游戏窗口失去焦点，再次使其获得焦点后才能恢复。
稳定触发方法：游戏地图界面按Esc打开菜单，此时游戏内鼠标光标显现（此游戏大地图上鼠标操作被映射到摄像头转动），移动到四边之一，点击，游戏逸出全屏。或者将游戏窗口配置为与屏幕原生比例不同然后缩放，此时周围会出现黑边，鼠标移动到黑边上，游戏定制的鼠标光标会还原为系统光标，点击黑边位置同样会逸出全屏。
问题的可能成因推断：是否该游戏内未对鼠标位置作出限制导致？能否由magpie来实现限制？

**Comment by Blinue** [comment]
Magpie会尝试将光标限制在窗口内，但这个操作在3D游戏中会失败，因为游戏已经限制了光标来让玩家可以自动移动视角。在这种情况下，鼠标就不会被限制了，因此可以移除窗口。

可以解决这个问题，只需在每帧渲染之前都尝试限制光标，这会增加一点CPU开销。下个版本我会添加这个功能。

**Comment by Blinue** [comment]
会在0.7里实现。你的更改没有问题，不会有性能影响。我在实现时会使用一个计时器而不是在每一帧都调用。

**Comment by Blinue** [comment]
最新的提交修复了这个问题

**Comment by palxex** [comment]
非常感谢，经测试已解决。
