### ISSUE TITLE
settings config not saving

### ISSUE THREAD

**Issue by humanana** [Blinue/Magpie#142]
0.61 release  win10x64
settings config not saving

**Comment by Blinue** [comment]
Please provide more details. Which option cannot be saved? How can I operate to reproduce this error?

**Comment by WerrW01f** [comment]
После удаления VS из системы тоже перестали сохраняться настройки в файле Magpie.exe.config, хотя в программе галочки исправно сохраняются. Также перестала работать опция "minimize to system tray at startup" независимо от галочки в программе или настройки в Magpie.exe.config

**Comment by Blinue** [comment]
Does this problem still exist in v0.9?
