### ISSUE TITLE
Super ultrawide resolution failure

### ISSUE THREAD

**Issue by mussawarakram** [Blinue/Magpie#143]
It would appear there are issues when using this application with >21:9 aspect ratios, such as 32:9 resolutions (3840x1080 or 5120x1440).

Any attempt to scale any 32:9 resolution causes the following error message:
![image](https://user-images.githubusercontent.com/84466871/133453437-772b253f-2ee1-4236-ba36-0ae891d38da7.png)

I can happily scale 21:9 up with black bars on left and right. Any resize of the window to increase the width ratio from this results in this error message.

**Comment by Blinue** [comment]
This is currently a limitation of Magpie and will be fixed in the next release. For more information: #17 #94

**Comment by Blinue** [comment]
This issue has been fixed in v0.7
