### ISSUE TITLE
Issue with MS Flight Simulator

### ISSUE THREAD

**Issue by calebsdeq** [Blinue/Magpie#144]
Good afternoon,

I have used Magpie with several games and works great, however with MS Flight Simulator it expands the screen to fullscreen but does not upscale from what I can see.

I am running 6.0.1 using FSR and WinRT with GTX 1060 6GB.

Images below:

1080p:
![MSFS1080p](https://user-images.githubusercontent.com/20947857/133463326-937281f1-c351-4891-a7e2-6044074750c3.png)

720p with Magpie FSR:
![MSFS720p](https://user-images.githubusercontent.com/20947857/133463544-bb7dbdf0-42b6-4e1d-aec2-17a383f13e18.png)

Slider:
[https://www.instarestoration.com/slider/view/60c0d290-09a3-486a-bf50-726f4a3deeec](https://www.instarestoration.com/slider/view/60c0d290-09a3-486a-bf50-726f4a3deeec)

Thank you!

**Comment by Blinue** [comment]
The hint text is not drawn in the game scene, but is implemented as a separate window which cannot be captured by Magpie as Magpie can capture only one window at a time.

**Comment by calebsdeq** [comment]
> The hint text is not drawn in the game scene, but is implemented as a separate window which cannot be captured by Magpie as Magpie can capture only one window at a time.

Perfect! Thank you very much! Will close the issue.
