### ISSUE TITLE
Windows 11 magpie 0.6.1 not working

### ISSUE THREAD

**Issue by Niafans** [Blinue/Magpie#145]
magpie 0.6.1 .exe does not work on windows 11 earlier release versions work correctly.

**Comment by Blinue** [comment]
Where did it go wrong? Is there an error message?

**Comment by A1pine** [comment]
Same Problem here, the program just exit  without notice when I pressed Alt+F11 or click the button.

**Comment by opbush** [comment]
it was doing this before for me but now it seems to be saving.

**Comment by Niafans** [comment]
> Where did it go wrong? Is there an error message?

When I try to open it, no message appears and it does not open.
 
It is as if I did not open it
When I try to open it, no message appears and it does not open.

**Comment by Niafans** [comment]
> Where did it go wrong? Is there an error message?


When I try to open it, no message appears and it does not open.
 
It is as if I did not open it
When I try to open it, no message appears and it does not open.

**Comment by Niafans** [comment]
> Where did it go wrong? Is there an error message?
When I try to open it, no message appears and it does not open.
It is as if I did not open it
