### ISSUE TITLE
Windows 11 does not open the program

### ISSUE THREAD

**Issue by Niafans** [Blinue/Magpie#146]
When trying to open the exe no message appears and the service does not appear in the task manager.

**Comment by Niafans** [comment]
Other versions work correctly

**Comment by Blinue** [comment]
Please provide logs.

**Comment by luojunyuan** [comment]
win11 currently is in preview status

**Comment by fr4nk1sh** [comment]
Hello, It dosn't seem to be working on windows 11 for me either, is there are info i can give you to help out i'd be glad to help.
Looking forward to try this software!

**Comment by luojunyuan** [comment]
> Hello, It dosn't seem to be working on windows 11 for me either, is there are info i can give you to help out i'd be glad to help.
> Looking forward to try this software!

Are you trying to use the v0.7.0 version? If you can't get any message after staring the executable. Press win key type ` Event Viewer` select `windows log` - `Application`, post the error info made by the application may help the owner.  Btw there is no problem on my win11 pc.

**Comment by Blinue** [comment]
If you encounter this problem in v0.8, feel free to reopen this issue.
