### ISSUE TITLE
外接电视机会黑屏

### ISSUE THREAD

**Issue by staroffish** [Blinue/Magpie#154]
将游戏拖拽到外接的电视机上后，按快捷键ALT+F11
游戏窗口会全屏但是画面会黑屏，能显示帧数，能看见鼠标，但是游戏画面是黑屏。

**Comment by Blinue** [comment]
更换捕获方式有画面吗

**Comment by staroffish** [comment]
WinRT 会黑屏
GDI 只能显示画面的一部分，感觉像是把图片拉伸的太大了

**Comment by Blinue** [comment]
实际上是多显示器问题，Magpie现在不支持多显示器。电脑和电视的分辨率和DPI分别是多少

**Comment by staroffish** [comment]
显示器是 2K 100% 电视机是4K 200%  
我试了下 改回100% 貌似可以用了。。。 难道是DPI的问题？

**Comment by Blinue** [comment]
Magpie不能在DPI不同的多显示器上工作，我以后会考虑添加支持。

**Comment by Blinue** [comment]
Magpie 现已支持在 DPI 不同的多显示器上工作 #202
