### ISSUE TITLE
通过RDP连接使用Magpie时全屏后还是能选中窗口外，导致失去焦点

### ISSUE THREAD

**Issue by shenmintao** [Blinue/Magpie#157]
iPad通过RDP远程连接到PC后，触摸模式下使用Magpie启动全屏，虽然显示部分是全屏的，但只要点击一下就会选到窗口外，并失去焦点
如果使用鼠标模式，虽然鼠标会被限制在窗口内，但会出现两个鼠标且速度和大小都不同步

**Comment by Blinue** [comment]
这涉及到两个限制。一是不支持触屏，这是实现原理的限制，未来也没有支持的计划。二是在远程桌面上出现双光标问题（#121），这可能是因为Magpie使用的隐藏系统光标的API在远程桌面中不起作用。你可以尝试使用0.6.0版本，它使用不同的方式隐藏系统光标。

**Comment by Blinue** [comment]
[MagSetInputTransform](https://docs.microsoft.com/en-us/windows/win32/api/magnification/nf-magnification-magsetinputtransform)可以映射触屏输入。我不会去实现这个功能，有意向的人可以尝试一下。

**Comment by shenmintao** [comment]
好的，我会先尝试一下0.6.0版本，是否有用我会记录在这并且关闭issue
MagSetInputTransform我也会研究一下看看能不能用
谢谢解答

**Comment by shenmintao** [comment]
0.6.0版本只能在GDI抓屏时只会显示一个鼠标，但速度非常慢，WinRT Capture依旧会显示两个鼠标。
MagSetInputTransform对于远程桌面不起作用

**Comment by Blinue** [comment]
如果有进展欢迎贡献，这样可以帮助和你遇到了同样问题的人😀

**Comment by Blinue** [comment]
https://github.com/Blinue/Magpie/issues/218#issuecomment-980506414
