### ISSUE TITLE
建议为ACNet和Anime4K增加三倍放大的选项

### ISSUE THREAD

**Issue by chaos700** [Blinue/Magpie#158]
现在的ACNet和Anime4K都是默认将输入放大至两倍，
虽然可以透过修改ScaleModels.json应用两次放大算法，
不过会不可避免造成一些性能损失，尤其是对核显设备消耗过大，
一般老游戏最常见的分辨率720p，放大三倍正好完美对应4k显示器，
如果增加三倍放大的选项，再配合原来的两倍放大，
可以更灵活调整自定义缩放，减少性能的损失。

**Comment by Blinue** [comment]
这些基于机器学习的算法只训练了放大到两倍的变体，因此请向他们提功能请求。

**Comment by chaos700** [comment]
原来如此，谢谢大佬回复及告知，那这个issue就没用了，我先关闭吧。
