### ISSUE TITLE
CRT emulation shader

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Blinue/Magpie#160]
Thanks for the good app.
Many old games are scary on LCD. I would like to run any old games with CRT shader.
For example:
https://github.com/mamedev/mame/tree/master/hlsl (MAME HLSL CRT shader)
https://github.com/Matsilagi/RSRetroArch (CRT and etc shader collection, ported for ReShade and ShaderToy)

**Comment by Blinue** [comment]
I'll port them after v0.7 is released.

**Comment by 0x4E69676874466F78** [comment]
@Blinue 
> I'll port them after v0.7 is released.

Thank you very much!

**Comment by Blinue** [comment]
I've ported some CRT shaders, including CRT-Easymode, CRT-Geom, CRT-Hyllian, CRT-Lottes and GTU, I think this is enough for most people

crt-royale is a nice shader too, but it doesn't fit magpie

**Comment by 0x4E69676874466F78** [comment]
@Blinue thanks a lot!
Soon I will try a new shaders.

> crt-royale is a nice shader too, but it doesn't fit magpie

What's wrong there?

**Comment by Blinue** [comment]
crt-royale has high requirements on the size of the input image. It is more suitable to be integrated in a simulator than as a general-purpose post-processing stage.

**Comment by 0x4E69676874466F78** [comment]
Thanks for the answer.

**Comment by 0x4E69676874466F78** [comment]
Visually more correct settings:
```
  {
    "name": "CRT-Geom",
    "effects": [
      {
        "effect": "CRT_Geom",
        "scale": [ -1, -1 ],
        "curvature": 0,
        "CRTGamma": 1.5,
        "monitorGamma": 2.2,
        "cornerSize": 0.001,
      }
    ]
  },
 ```
I don't know why need to reduce CRTGamma.

Lanczos
![magpie-lanczos](https://user-images.githubusercontent.com/4449851/148201467-887da5a1-82ac-470a-9863-23099512feda.jpg)

CRT-Geom before: 
![magpie-crtgeom-before](https://user-images.githubusercontent.com/4449851/148201483-5eab0fcf-02c5-4ea3-b8de-15e24e7df31f.jpg)

CRT-Geom after: 
![magpie-crtgeom-after](https://user-images.githubusercontent.com/4449851/148201499-b383878d-3841-4705-a24f-70e5b2eb2379.jpg)

**Comment by 0x4E69676874466F78** [comment]
Also need to include in settings all CRT Shaders. 
CRT_Hyllian and CRT_Lottes are good.
For this game I liked more CRT_Lottes.
But I will try to make a hybrid with FXAA antialiasing.

**Comment by Blinue** [comment]
Thanks for the test, here is a sample config:
https://gist.github.com/hooke007/818ecc88f18e229bca743b7ae48947ad#file-scalemodels-json-L240

**Comment by 0x4E69676874466F78** [comment]
Very nice:
```JSON
  {"name":"CRT_Lottes","effects":[
    {"effect":"SMAA_High"},
    {"effect":"CRT_Lottes","scale":[-1,-1],
     "hardScan":-8,"hardPix":-3,"warpX":0.0,"warpY":0.0,
     "maskDark":0.5,"maskLight":1.5,"scaleInLinearGamma":1,"shadowMask":3,"brightBoost":1,
     "hardBloomPix":-1.5,"hardBloomScan":-2,"bloomAmount":0.15,"shape":2},
  ]},
```
![изображение](https://user-images.githubusercontent.com/4449851/148207122-06e859ff-4aa3-4bf6-8365-751e79b1d4e5.png)

Thanks again for porting these shaders to Magpie!
