### ISSUE TITLE
Native build for arm64.

### ISSUE THREAD

**Issue by sqwwqw5** [Blinue/Magpie#161]
As titled, a guide would be really helpful.

**Comment by Blinue** [comment]
Magpie is based on .NET framework 4.7, which does not run on ARM64.

**Comment by sqwwqw5** [comment]
> Magpie is based on .NET framework 4.7, which does not run on ARM64.

oops... Thanks for the detail.
Magpie does run on windows on arm, though took a severe performance penalty.

**Comment by Blinue** [comment]
Magpie won't support arm64 officially, most of its dependencies are x64 only
