### ISSUE TITLE
locking fps in mapgie

### ISSUE THREAD

**Issue by TengriciTURK** [Blinue/Magpie#162]
TÜRK:

Oyunda gösterilecek kare sayısını kilitlemeye yarayan Vsync benzeri bir seçenek Mapgie içine eklenirse güzel olur. Bu kilitlenecek kare sayısı kutucuğa biz yazalım. Örneğin Mapgie içinde kare sayısını 75fps'de kilitlediysek, 76 kareye çıkmasın. 

english(Google çeviri):

It would be nice if a Vsync-like option that locks the number of frames to be displayed in the game is added to Mapgie. Let's write the number of frames to be locked in the box. For example, if we locked the number of frames in Mapgie at 75fps, it should not increase to 76 frames.

**Comment by Blinue** [comment]
Currently Magpie's frame rate is fully controlled by DWM. The option to specify the frame rate is a nice feature, and I may implement it later.

**Comment by Blinue** [comment]
v0.7 provides an option to lock fps

**Comment by yourmom2002** [comment]
Is it no longer possible to lock fps at certain value? I can only see vsync option now in 0.9, which is not always viable.
