### ISSUE TITLE
hotkey not working 0.7

### ISSUE THREAD

**Issue by humanana** [Blinue/Magpie#165]
press default hotkey alt+f11 not working

 0.6 still work but some game is need to to click scale after then click that windows so it is going to work
 
 now 0.7 need to use scale after all the time or it will not work with hotkey

**Comment by Blinue** [comment]
No changes were made to the hotkey implementation. If the hotkey does not work, you should restart Magpie as administrator.

**Comment by Blinue** [comment]
I don't know how this issue arose, it seems to be a problem with your desktop environment. Magpie requires .NET framework 4.7, you may need to reinstall it.

Magpie's config file is located in C:\Users\{USER}\AppData\Local\Magpie, you should check it too.

**Comment by MorderczkazPolski12** [comment]
Hello. 

Encountered the same issue while playing Scarlet Nexus where the Magpie refused to scale up, ( using 7.0 Preview version ) 
tried in Order:
Running Magpie as admin / game as normal
Running Magpie as admin / game as admin
Magpie as normal / game as normal
Magpie as normal / game as admin
Changing Hotkey
Restarting PC

Completely forgotten that there is manual option to scale
What Fixed the issue:
Installing Reshade

and currently (on my side ) Scarlet Nexus was the only gam were Magpie refused to cooperate

**Comment by Blinue** [comment]
I am closing this issue because it is outdated. If you encounter it in the latest version, please submit a new issue.
