### ISSUE TITLE
往日不再无法使用

### ISSUE THREAD

**Issue by facc62** [Blinue/Magpie#166]
Magpie在我拥有的所有游戏上都运行的十分出色，除了往日不再
在GraphicsCapture模式下，加载页面能够达到完美的60帧，一旦进入主菜单，Magipie帧率就变成为了5帧左右，卡顿，画面正常
而DwmSharedSurface模式下，游戏整个白屏了，根据鼠标移动到选项的按键音判断，似乎帧数很低
两个GDI模式下，都是黑屏，根据鼠标移动到选项的按键音判断，似乎帧数同样很低

**Comment by Blinue** [comment]
对于一些游戏GraphicsCapture是唯一的捕获方式。

从你的描述看使用Magpie之后游戏的帧率非常低，你可以在选项，高级里打开帧率显示看Magpie本身的帧率如何

**Comment by facc62** [comment]
这些截图应该能显示出问题
![屏幕截图(3)](https://user-images.githubusercontent.com/91741908/135708325-e42d51f2-28d2-4dce-9bc6-de6ec83fdd1b.png)
![屏幕截图(5)](https://user-images.githubusercontent.com/91741908/135708332-8cefadb9-8979-4e50-81c1-2512cfeab007.png)
![QQ截图20211002154838](https://user-images.githubusercontent.com/91741908/135708339-a730f053-9a33-48f0-a665-9e16c78130cd.png)
并且我注意到，在使用GraphicsCapture模式下，一旦鼠标不动，画面只有3帧（通过Magpie自带的帧率显示），而运动到选项时，会达到30FPS左右浮动，整体的体验就是游戏响应十分慢，卡顿

**Comment by facc62** [comment]
只针对往日不再

**Comment by Blinue** [comment]
[这里](https://github.com/Blinue/Magpie/issues/94#issuecomment-907728719)有一些优化性能的提示

**Comment by facc62** [comment]
很可惜，我确实将Magpie的进程优先级设置为更高，关闭了游戏模式。虽然运动鼠标时，Magpie的帧数是在41-60波动，然而，体验并没有比幻灯片好
尝试过使用更低的材质质量，并没有帮助，显卡都是没爆过显存
同时，在对往日不再进行缩放时，Magpie自身的界面也有可能会黑屏

**Comment by Blinue** [comment]
谢谢反馈，我会调查一下

**Comment by facc62** [comment]
希望我是唯一遇到这个问题的倒霉蛋- -

**Comment by Blinue** [comment]
目前已经复现了你的问题。对于《往日不再》，GraphicsCapture 是唯一可行的捕获模式。

初步认定是 GraphicsCapture 捕获的 bug。在游戏中按下 Win+G 打开 Xbox Game Bar，可以瞬间使 Magpie 变得流畅。要想维持这种流畅状态，可以使用录制功能。

**Comment by Blinue** [comment]
另外《往日不再》不支持DPI缩放，你应该修改它的“高DPI缩放替代”。修改之后其他的捕获方式也可以捕获到画面，但始终只能捕获到主菜单

**Comment by Blinue** [comment]
[Magpie.zip](https://github.com/Blinue/Magpie/files/7273130/Magpie.zip)
试一下这个版本

**Comment by facc62** [comment]
这个版本运行的相当喜人！

**Comment by Blinue** [comment]
原因比较有技术性。Magpie 使用 DirectFlip 技术降低延迟，但出于某种原因这个游戏和 DirectFlip 不兼容。在这个版本中我关闭了 DirectFlip，因此虽然可以使用了，代价是一帧的延迟。

我会提供选项，让用户可以在必要的时候关闭 DirectFlip。
