### ISSUE TITLE
FSR Upscale Confusion

### ISSUE THREAD

**Issue by mrpeterd** [Blinue/Magpie#167]
Hi. So I am a little confused as to how the upscaling of this tool works. Yes I have seen the AMR FSR resolution/upscaling chart but I'm wondering how this tool specifically works.
If my display setting in WIndows 10/11 is set to 3840x2160p (4K) and the games resolution is set to 1920x1080p (HD), does it upscale the 1080p to 4K? Or does it upscale it between 4K and 1080p (1440p QHD) roughly?

**Comment by Blinue** [comment]
This tool can zoom any game to full screen. If your monitor is 4K, it will zoom all games to 4K, regardless of the original resolution of the game.

**Comment by mrpeterd** [comment]
I understand that part. So if the game is running 1080p in the games settings, the tool will upscale it to my monitors resolution (4K)?
So the game will actually be running at 4K without the game being set to 4K?

**Comment by Blinue** [comment]
The game runs in 1080p, but Magpie will present it in 4K.

**Comment by mrpeterd** [comment]
@Blinue thank you for answering. That makes more sense now. So I'm getting 4K visuals thanks to Magpie.
