### ISSUE TITLE
Capture mode: Injection Error when using GDI + nothing happens with WinRT Capture

### ISSUE THREAD

**Issue by gokunazz** [Blinue/Magpie#17]
Hi there, first and foremost thank you for the awesome program but I experienced these problems:

1). There is an error when trying to launch with the capture mode set to 'GDI' instead of WinRT Capture
![image](https://user-images.githubusercontent.com/87958401/126926266-827f16cd-9c34-4917-a55a-5adaec24e615.png)

2). Also, when using Capture mode 'WinRT Capture':-
When I activate the assigned hotkey to perform the injection, the window will auto-closes itself and the targeted application (.exe) does not go into full screen mode (i.e. nothing happens). If nothing happens, that means the injection did not go through or something is blocking the injection that causes the game/application to NOT go into full screen.

Settings I used:-
![image](https://user-images.githubusercontent.com/87958401/126926752-8d5bfd7b-a7bb-4822-9b87-69055f71375c.png)

I performed all of the actions on the main monitor, but nothing seemed to work.

I'm not sure if these helps but My setup:-
[x] Dual Monitor setup
[x] Nvidia GPU scaling settings:
- Hardware scaling instead of GPU scaling
- Override the scaling mode set by games & programs
[x] Disabled Antivirus/windows defender
[x] Disabled Nvidia GeForce Experience in-game overlay

**Comment by Blinue** [comment]
Error Code 0x88990027：D2DERR_INTERMEDIATE_TOO_LARGE

The graph could not be rendered with the context's current tiling settings.

It seems that the tile size (image size) is too large for your GPU. Anime4K doubles input size, maybe your GPU can't handle  such a large image.

1. You can try again on a smaller window
2. Does the lanczos algorithm work?

**Comment by gokunazz** [comment]
I'll try your suggestion and will update the result soon.
I'm using the latest RTX 3080, so I don't think it's a GPU issue hmmm

**Comment by Blinue** [comment]
This program has not been tested on a 2K/4K screen, because I don't have such a monitor.

[WinRT Capture](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture) is only available in v1803 and later. This mode is not very reliable, but much faster. I can't locate the problem because the program crashed. Magpie has very limited records of errors now, and I will add logging in the next version.

**Comment by gokunazz** [comment]
I see. It makes sense now since I'm running on v1909.
Thanks again for your feedback and helpful tips.

I hope you can mention in the instruction (under 'Use Suggestion') if the user has a 2K or 4K monitor, they should set their window resolution as: 1080p or in certain instances, 1440p if it works. Otherwise they will encounter the Error Code 0x88990027：D2DERR_INTERMEDIATE_TOO_LARGE

Have a nice day and all the best in your endeavors

**Comment by Blinue** [comment]
Many thanks. Have fun.
