### ISSUE TITLE
老卡用户的心声：可不可以不要上 dx feature 11_1?

### ISSUE THREAD

**Issue by tigerinus** [Blinue/Magpie#175]
还在用 GTX 560，Magpie 0.7 跑不起来，0.6 就跑的起来。应该是不支持 dx 11.1 的原因。

很喜欢这个工具，老卡的福音。。可不可以考虑一下维持在 dx 11.0 就好了？

谢谢

**Comment by Blinue** [comment]
https://github.com/Blinue/Magpie/discussions/164#discussioncomment-1418126
