### ISSUE TITLE
[feature request] Work with Reshade

### ISSUE THREAD

**Issue by Blinue** [Blinue/Magpie#18]
Would you mind adding a way to use Reshade with Magpie so, upscaled games can have Reshade shaders at upscaled resolutions? 

For Example:
Game resoltuion = 1920x1080
Magpie upscales to = 3840x2160
Reshade runs on Magpie and,
Reshade effects (like FXAA) = 3840x2160

This way a game can have 2 Reshades. One operates at the game's own resolution, the other one operates on Magpie at higher (upscaled) resolution. 

Thank you for this nice software, BTW.

_Originally posted by @canceralp in https://github.com/Blinue/Magpie/issues/12#issuecomment-887409795_

**Comment by Bonfire-GTK** [comment]
I second this, It would be amazing to have almost every single game FSR compatible

**Comment by Small-Ku** [comment]
This definitely a nice feature. I also would like to know how do we deal with the depth buffer

**Comment by bakwas247** [comment]
This is a good idea, if so we can apply anti aliasing to the upscaled output rather than just on the low res render.

**Comment by canceralp** [comment]
> This is a good idea, if so we can apply anti aliasing to the upscaled output rather than just on the low res render.

AMD recommends doing the AA "before" upscaling in it's FSR documents. However, for other effects, a Reshade integration would be superb. For example, effects like film grain, chromatic aberration, DOF  should be used at native resolution for the best efficiency.

**Comment by Nerboruto** [comment]
I wanted to report that reshade already works on magpie .. I have already done numerous tests on it.
[d2d1.zip](https://github.com/Blinue/Magpie/files/7079432/d2d1.zip)
unfortunately the overhead problem remains ... I await further developments...

**Comment by mirh** [comment]
Magpie upscales a bitmap. 
Reshade works on the 3D scene. 
What is this bug report even about?

You can't have shaders apply to a photo. 
You either keep everything inside reshade (and that seems sci-fi already, considering you'd have to somehow undersample the in-game scene, and then run the upscaling filter you want all unbeknown to it), or you forget about it.

**Comment by Nerboruto** [comment]
depends on what the shader does ... sure you don't have access to the depth buffer .. but if you have a 2d shader like filmgrain or deband or tonemapper etc .. these work correctly

**Comment by Blinue** [comment]
Support for reshade is no longer planned since Magpie has its own effect syntax now.
