### ISSUE TITLE
虛擬機上運行閃退

### ISSUE THREAD

**Issue by sky456757** [Blinue/Magpie#194]
### Magpie version 程序版本

0.6.1

### Windows version 系统版本

win10 21H1

### Reproduction steps 复现步骤

在Mac 上的parallel 虛擬機上執行時按下hot key 或 scale 之後馬上閃退，在vmware虛擬機上則不會這樣

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7446727/Magpie.log)

**Comment by Blinue** [comment]
0.6.1没有关键模块的日志，试试这个版本

[Magpie.zip](https://github.com/Blinue/Magpie/files/7446853/Magpie.zip)

**Comment by sky456757** [comment]
[Magpie.log](https://github.com/Blinue/Magpie/files/7446945/Magpie.log)
這一版一點開馬上閃退

**Comment by Blinue** [comment]
请提供Runtime.log

**Comment by sky456757** [comment]
沒有生成Runtime.lo
<img width="723" alt="截圖 2021-10-30 下午11 39 50" src="https://user-images.githubusercontent.com/22101536/139539833-4ad9396b-7763-4cc8-a55b-e19d4c138bd0.png">
g

**Comment by Blinue** [comment]
初始化失败了，parallel 虚拟机可能缺少某些关键功能

Magpie 的初始化过程：

1. 初始化 spdlog
2. 初始化 COM
3. 注册主窗口类
4. 初始化 Magnification API
5. 初始化 CNG

最有可能失败的步骤是 4 和 5，可能 parallel 没有对它们的支持

**Comment by sky456757** [comment]
![Uploading 截圖 2021-10-30 下午11.57.11.png…](
<img width="1520" alt="截圖 2021-10-30 下午11 57 23" src="https://user-images.githubusercontent.com/22101536/139540379-c5b4112c-4f6c-4ca2-9066-f9ec5857338d.png">
)
所以是.net的問題嗎

**Comment by sky456757** [comment]
所以是.net的問題嗎
<img width="1520" alt="截圖 2021-10-30 下午11 57 23" src="https://user-images.githubusercontent.com/22101536/139540426-771beba7-4f47-4d7a-9edc-f80034f0fbb6.png"
<img width="1528" alt="截圖 2021-10-30 下午11 57 11" src="https://user-images.githubusercontent.com/22101536/139540445-0957701a-f8c4-4e39-88d6-0b65dba95d30.png">
>

**Comment by Blinue** [comment]
这里只记录了系统缺少某个DLL文件。

几个解决方案
1. 安装（修复）.NET framework 4.7，看能否解决问题
2. 重装系统
3. 不使用parallel

**Comment by sky456757** [comment]
修復之後ok了
