### ISSUE TITLE
error happening with installed video driver

### ISSUE THREAD

**Issue by wefghjk** [Blinue/Magpie#195]
### Magpie version 程序版本

0.7.0_preview1

### Windows version 系统版本

win10 21h1

### Reproduction steps 复现步骤

I have just restored my computer and downloaded magpie for testing before installing my video driver (i3 3110m intel HD 4000) and before installing it worked normally, but soon after installing the drivers when active magpie shows an error and not works no matter which mode i use

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7450229/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7450230/Runtime.log)

**Comment by Blinue** [comment]
Try this build 
[Magpie.zip](https://github.com/Blinue/Magpie/files/7244125/Magpie.zip)

**Comment by wefghjk** [comment]
same problem
logs: 
[Magpie.log](https://github.com/Blinue/Magpie/files/7450437/Magpie.log)

**Comment by Blinue** [comment]
Your driver does not support DirectX feature level 10.0. I suggest you uninstall the driver if you have no reason to keep it.

**Comment by wefghjk** [comment]
Intel HD 4000 supports up to Directx level 11

**Comment by Blinue** [comment]
So it's an issue of your driver. The driver you installed may not be the latest.

**Comment by wefghjk** [comment]
i installed the latest driver today and the 0.7 preview didn't worked, but the build worked
