### ISSUE TITLE
Cannot compile - missing files like document.h

### ISSUE THREAD

**Issue by CoderStone** [Blinue/Magpie#196]
### Magpie version 程序版本

Latest commit

### Windows version 系统版本

win 11

### Related screenshot (optional) 相关截图（可选）

![image](https://user-images.githubusercontent.com/34324909/140049776-76c56144-815f-469b-8a29-90215bf4feaa.png)

### Reproduction steps 复现步骤

Get most recent commits, then try to compile.

### Log files 日志文件

N/A

**Comment by Blinue** [comment]
You need SDK 22000
https://github.com/Blinue/Magpie/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97

**Comment by CoderStone** [comment]
Installed SDK 22000 yet still exact same errors. Unsure as to what's going on.

**Comment by Blinue** [comment]
1. Retarget project to sdk 22000
2. Build CONAN_INSTALL to install dependencies
