### ISSUE TITLE
Double msi afterburner overlay

### ISSUE THREAD

**Issue by Taiyou06** [Blinue/Magpie#197]
### Magpie version 程序版本

v0.7.0 Preview1

### Windows version 系统版本

win 10 21H1

### Related screenshot (optional) 相关截图（可选）

![image](https://user-images.githubusercontent.com/77050201/141359454-af384aeb-c029-4420-bdf4-b40079cd3d1d.png)

### Reproduction steps 复现步骤

use msi afterburner's on screen display (osd) on any game with magpie

### Log files 日志文件

[Runtime.log](https://github.com/Blinue/Magpie/files/7522926/Runtime.log)

**Comment by Blinue** [comment]
https://github.com/Blinue/Magpie/discussions/164#discussioncomment-1567168

**Comment by Taiyou06** [comment]
oh thank you!
