### ISSUE TITLE
Can't see the window while streaming through Moonlight and Steam Link (possibly more)

### ISSUE THREAD

**Issue by motorolah** [Blinue/Magpie#198]
### Magpie version 程序版本

0.7.0

### Windows version 系统版本

Win10 21H1

### Reproduction steps 复现步骤

Start streaming using any streaming client and look at the client's side, the screen will appear frozen or possibly zoomed in (like while streaming the game directly on Discord).

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7531236/Magpie.log)
[Runtime.1.log](https://github.com/Blinue/Magpie/files/7531237/Runtime.1.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7531238/Runtime.log)

**Comment by Blinue** [comment]
This is a known issue #141 and is related to the way Magpie is implemented. You may need to file a request to the streaming software.

**Comment by Blinue** [comment]
Go to #141  for further discussion
