### ISSUE TITLE
Can't use DwmSharedSurface, GDI & GDI over DXGI

### ISSUE THREAD

**Issue by Zadder** [Blinue/Magpie#199]
### Magpie version 程序版本

0.7.0

### Windows version 系统版本

22000.318

### Related screenshot (optional) 相关截图（可选）

I always get a black screen when using DwmSharedSurface, GDI & GDI over DXGI. The only mode that works is WinRT Capture. I have an ASUS FX505DT laptop with 1650 mobile and a ryzen 5 3550h, also tried it on windows 10 on the same machine. same results, even when using another version of the software.

### Reproduction steps 复现步骤

I started the software and the game
I've put the game on 1366x768 windowed mode
Pressed the shortcut button on magpie while the game window was on focus, the game goes fullscreen and it's showing a black screen. Only mode that works is WinRT Capture. 

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7534354/Magpie.log)
[Runtime.1.log](https://github.com/Blinue/Magpie/files/7534355/Runtime.1.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7534356/Runtime.log)

**Comment by Blinue** [comment]
Thanks for the feedback.

There's no perfect capture method. For some games, Graphics Capture is the only viable way to capture, therefore it's not a bug. Magpie provides multiple capture methods so that when one method fails, you can switch to another.

**Comment by Zadder** [comment]
Ok, thanks, dude
