### ISSUE TITLE
奇怪的功耗

### ISSUE THREAD

**Issue by cheng1nuo** [Blinue/Magpie#200]
### Question 问题

使用这个[commit](https://github.com/Blinue/Magpie/commit/5784987b10da52b28af15480316f7ea4436c0ee2)编译的Magpie 发现缩放窗口后会导致 GPU 频率 会提升到最高 导致功耗和温度过高黑屏死机
系统版本为 Windows 11 Insider Preview 10.0.22499.1010 (rs_prerelease)
AMD Raden Software 版本为 [21.10.2](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-21-10-2)
屏幕分辨率为4k
显卡为 RX580 2304 8G

**Comment by Blinue** [comment]
怀疑是操作系统的bug。只有这个commit有问题吗？重启能解决吗？

**Comment by Blinue** [comment]
#180

**Comment by cheng1nuo** [comment]
重启无效 跟#180一样会导致导致黑屏死机

**Comment by cheng1nuo** [comment]
从发的0.7预发布版本到尝试自己构建的版本都有类似情况

**Comment by Blinue** [comment]
日志有没有记录错误？你也可以试试更新驱动。

**Comment by cheng1nuo** [comment]
日志没有 驱动更新也尝试过

**Comment by Blinue** [comment]
因为日志没有记录错误，所以我认为是桌面环境的问题。我只能提一些建议：
1. 修复 .NET framework 4.7
2. 修复 DirectX
3. 尝试在集显上运行 Magpie（如果有）
4. 在 Magpie 中限制帧率能不能解决功耗过高的问题
5. 如果是驱动bug可以尝试安装旧版驱动

**Comment by cheng1nuo** [comment]
12 好的我回去尝试重新安装net4.7和dx
3 amd 2600没有集成显卡
4 好的 我回去尝试降级到10月份和9月份amd驱动

**Comment by cheng1nuo** [comment]
12 重新安装以后 没什么变化
4 将帧率限制到最大的144而非无限制以后 功耗回归正常水平
5 驱动未降级或升级 维持发 issue 时候的 21.10.2

**Comment by Blinue** [comment]
看起来是帧率限制的原因。建议使用垂直同步或将帧率设为和屏幕刷新率相同
