### ISSUE TITLE
最小化跟关闭到托盘后图标消失

### ISSUE THREAD

**Issue by login404** [Blinue/Magpie#203]
### Magpie version 程序版本

v0.7.0

### Windows version 系统版本

Win10 1809 (LTSC 2019 17763.2183)

### Related screenshot (optional) 相关截图（可选）

![动画](https://user-images.githubusercontent.com/69505914/141904029-40c5a433-baed-424e-a501-dd94e553ddca.gif)

### Reproduction steps 复现步骤

步骤如图
100%复现

尝试过的解决方法:
关闭SmartSystemMenu
MacType排除Magpie进程
不经过PortableApps.com Launcher直接运行Magpie
均无效 想不到可能的冲突了…

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7543292/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7543293/Runtime.log)

**Comment by Blinue** [comment]
不开启“关闭时最小化到系统托盘”也会遇到这个问题是吗

**Comment by login404** [comment]
> 实际上是创建系统托盘图标时失败了。
> 
> 不开启“关闭时最小化到系统托盘”也会遇到这个问题是吗（这时最小化 Magpie 也会进入系统托盘）

对 该选项不论是否开启都会复现

**Comment by Blinue** [comment]
尝试一下安装/修复 .NET framework 4.7

**Comment by login404** [comment]
> 尝试一下安装/修复 .NET framework 4.7

4.7无法安装 显示已安装更高版本(4.8)
修复了4.8 仍然复现

**Comment by Blinue** [comment]
[Release.zip](https://github.com/Blinue/Magpie/files/7543686/Release.zip)
试试这个版本

**Comment by login404** [comment]
> [Release.zip](https://github.com/Blinue/Magpie/files/7543686/Release.zip) 试试这个版本

该版本可以正常工作

**Comment by Blinue** [comment]
这个错误只会在旧版本 windows 上出现

https://github.com/Blinue/Magpie/commit/d027527743229c0b34a6c07d6f432e1760bf80bb
