### ISSUE TITLE
ACnet doesn't work anymore in 0.7

### ISSUE THREAD

**Issue by bacbt9** [Blinue/Magpie#206]
### Magpie version 程序版本

0.7

### Windows version 系统版本

win10 21h1 19043.1288

### Reproduction steps 复现步骤

1. Start magpie
2. Switch to ACnet
3. Set any capture method, doesn't matter
4. Switch to other app window
5. Press magpie hotkey 

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7546060/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7546061/Runtime.log)

**Comment by Blinue** [comment]
Use this build [Magpie_v0.7.0.zip](https://github.com/Blinue/Magpie/files/7546110/Magpie_v0.7.0.zip)

I've also replaced the release assets.

**Comment by bacbt9** [comment]
Okay, works fine now. Thx!
