### ISSUE TITLE
conanbuildinfo.props

### ISSUE THREAD

**Issue by hooke007** [Blinue/Magpie#21]
我完全不熟悉这个Conan...但是现版本缺乏多个文件 conanbuildinfo.props 导致无法编译，我看了下上级目录被gitignore处理掉了...

**Comment by Blinue** [comment]
VS要装[Conan Extension for Visual Studio](https://marketplace.visualstudio.com/items?itemName=conan-io.conan-vs-extension)。props文件是Conan生成的，里面是本地库的路径。
我最近会写编译指引。

**Comment by hooke007** [comment]
感谢。目前暂时将相关模块改回canon前的状态进行编译，程序工作良好。
