### ISSUE TITLE
Extreme lag in 3-5 second intervals?

### ISSUE THREAD

**Issue by kimberly990** [Blinue/Magpie#211]
### Program(Game) 游戏名

Fallout 76

### Capture method 捕获模式

Any

### Related screenshot (optional) 相关截图（可选）

It's very frustrating. Setting a manual FPS cap fixes the issue, but at the same time introduces a lot of screen tearing.

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7559252/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7559253/Runtime.log)

**Comment by Blinue** [comment]
Does this happen in all games, or just Fallout 76?

**Comment by kimberly990** [comment]
It seems to be limited to Fallout 76. I'm not sure what's causing it. I have vsync disabled in that game, but it's capped at 120 FPS through Rivatuner. Disabling that cap doesn't seem to make a difference.

**Comment by Blinue** [comment]
I'm closing this as it is outdated. If you encounter this problem in the latest version, please file a new issue.
