### ISSUE TITLE
VSYNC option severely affects game performance

### ISSUE THREAD

**Issue by CoderStone** [Blinue/Magpie#215]
### Program(Game) 游戏名

Minecraft Dungeons

### Capture method 捕获模式

GDI

### Related screenshot (optional) 相关截图（可选）

Not vsync, 100hz display:
![image](https://user-images.githubusercontent.com/34324909/142741883-6bf01334-fbb4-438f-b76d-6db25c9d760c.png)

Magpie vsync with 100hz display:
less than 30fps.

### Log files 日志文件

[Runtime.log](https://github.com/Blinue/Magpie/files/7575409/Runtime.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/7575410/Magpie.log)

**Comment by Blinue** [comment]
Magpie uses low latency technology by default, which can cause a significant drop in frame rate in case of poor performance. Turning on the "Allow extra latency" option can also alleviate this problem.

**Comment by palxex** [comment]
@Blinue In recent builds I noticed that "Allow extra latency" option makes extra frame drop( for ex. genshin 60fps, magpie FSR with it drops to less than 30fps, without it still 60fps), and in my memory the situation was not same when the option was first added. Does the implemention of this option changes?

**Comment by Blinue** [comment]
这里的实现没更改过，v0.7.1 正式版有这个问题吗

**Comment by palxex** [comment]
> 这里的实现没更改过，v0.7.1 正式版有这个问题吗

0.7.1经过测试没有这个问题。非常奇怪，今天我用之前能测出这个问题的build，同样的机器同样的环境怎么也重现不出来了。实在找不到原因了，看来是误报，非常抱歉。
另外想问一下，“允许额外的延迟”和“禁用DirectFlip”这两个选项的关系是？

**Comment by Blinue** [comment]
“允许额外的延迟”用于在性能不足的情况提高帧率，“禁用DirectFlip”用于解决某些游戏的兼容性问题 #166。实现上没有关系。

它们各会引入一帧延迟，同时选中会有两帧延迟

**Comment by palxex** [comment]
@Blinue 突然又在Win11 Dev上重现出来了，之前是在Win10上。这个看来有点随机性——跟哪次开机有关的那种。
触发时的配置和截图
![1 0](https://user-images.githubusercontent.com/58222/144704256-8c18ada0-895e-42dd-a297-7da0e0383e51.png)
![1 1](https://user-images.githubusercontent.com/58222/144704257-eda560cf-bd6c-46fd-8dfc-96bfa7deeb5f.png)
未触发时的
![2 0](https://user-images.githubusercontent.com/58222/144704259-520a85e8-3d80-49f7-a370-ae22cfe42de9.png)
![2 1](https://user-images.githubusercontent.com/58222/144704271-5dc6d892-7756-417c-a9b0-4a3311e29891.png)
可见此时CPU/GPU都未占满，不大可能是资源的问题。另外游戏的原始帧数并未降低，降低的只是magpie的放大帧数。

**Comment by palxex** [comment]
又测了一下，在未知条件下勾选“允许额外的延迟”并导致magpie的放大帧数异常后（同一个build，我上午那次开机都没事），再勾选“禁用DirectFlip”可以解决此问题……虽然我机器上看log，Hardware Composition 支持和Multiplane Overlay 支持都是否，按理来说DirectFlip压根没有支持，这个选项勾不勾应该是无影响的才对？

**Comment by Blinue** [comment]
这个问题请新开issue
