### ISSUE TITLE
Spanning over multiple screens

### ISSUE THREAD

**Issue by xSvenHD** [Blinue/Magpie#219]
### Expected behavior 预期的功能

For racing and flying simulators we use 3 screens. 
Would it be possible to add custom size and position and projection on all monitors?
Now it only does the main monitor.

**Comment by Blinue** [comment]
It's a nice feature, I'll update if there's any progress

**Comment by Blinue** [comment]
We have some options on multi-monitor now

![image](https://user-images.githubusercontent.com/34770031/147172952-3957aa42-0907-48de-bd48-5938cc7d3b9b.png)

They'll be available in v0.8

**Comment by xSvenHD** [comment]
Awesome that will be perfect!
