### ISSUE TITLE
在surface pro 7运行Magpie显示初始化失败

### ISSUE THREAD

**Issue by yudancon** [Blinue/Magpie#220]
### Question 问题

Magpie是否支持surface pro 7？打开Magpie显示初始化失败，无法进入Magpie，使用管理员身份也不行。系统是win10，64位，21H1。MagpieV0.61-0.71都显示初始化失败。
![magpie初始化失败](https://user-images.githubusercontent.com/95042954/143475977-fd4fe9bb-caba-4f6f-bcb2-41d106fbd5b7.PNG)

**Comment by hooke007** [comment]
> 程序报错不要使用此模板，应该返回上级重新选择 Bug 错误 选项。

请补充log，硬件信息辅助判断

**Comment by yudancon** [comment]
已补充log，硬件信息
[Magpie.log](https://github.com/Blinue/Magpie/files/7605903/Magpie.log)
![硬件信息](https://user-images.githubusercontent.com/95042954/143517251-3d8c570d-8501-401e-973f-7811f218ac77.PNG)

**Comment by Blinue** [comment]
尝试一下修复 .NET framework 4.7

**Comment by Blinue** [comment]
不知为何有些计算机上找不到同文件夹下的 Runtime.dll，我也很费解

**Comment by Blinue** [comment]
[Release.zip](https://github.com/Blinue/Magpie/files/7606826/Release.zip)
这个版本能工作吗

**Comment by yudancon** [comment]
> [Release.zip](https://github.com/Blinue/Magpie/files/7606826/Release.zip) 这个版本能工作吗

也是不能工作，.NET framework 4.7也修复过，同样不行。

**Comment by Blinue** [comment]
尝试一下以管理员权限运行

**Comment by yudancon** [comment]
> 尝试一下以管理员权限运行

也试过，还是不行。

**Comment by hooke007** [comment]
能不能尝试打包Runtime.dll进exec成静态库

**Comment by hooke007** [comment]
...只是给开发者提供可能的策略

**Comment by Blinue** [comment]
[Release.zip](https://github.com/Blinue/Magpie/files/7608944/Release.zip)
试试这个版本，失败的话发下日志

**Comment by yudancon** [comment]
这个版本打开没显示初始化失败，直接闪退，用管理员权限也是闪退
[Magpie.log](https://github.com/Blinue/Magpie/files/7608973/Magpie.log)

**Comment by Blinue** [comment]
尝试一下安装 msvc 运行库 https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

另外你也可以提供 Windows 日志，在 事件查看器->Windows日志->应用程序

**Comment by Blinue** [comment]
> 能不能尝试打包Runtime.dll进exec成静态库

无法加载 dll 的问题大部分都不是路径原因。.net core 有一种打包 dll 的方法，但会拖累启动速度

**Comment by yudancon** [comment]
安装运行库后可以正常运行了，可能是之前的运行库版本太旧了，感谢！

**Comment by Blinue** [comment]
我会把这个要求加入 README
