### ISSUE TITLE
建议增加根据窗口分辨率等条件自动调用对应预设缩放配置的功能

### ISSUE THREAD

**Issue by neavo** [Blinue/Magpie#223]
### Expected behavior 预期的功能

比如目前我在实际使用应用时，设置了三个不同的配置文件，分别用于超低分辨率（640x480-）、低分辨率（480P-720P）、中等分辨率（720P-1080P），当我更换游戏时，总是需要手动打开应用切换对应的配置，略嫌麻烦

如果可以提供一定的程度的自动判断条件应该会方便很多，比如在配置文件中设置 A配置适合高度不大于480像素的应用、B配置适合高度介于480和720像素之间的应用，在缩放时就会自动调用对应的配置文件。

**Comment by Blinue** [comment]
这个主意不错。我以前的想法是加一个游戏内 UI，可以在游戏内改变针对它的配置，但这个功能比较复杂。如果可以在 ScaleModels.json 里支持条件判断就可以对某一类（或某一个）窗口应用单独的设置。

判断条件不止有源窗口大小，还可以有缩放比例，源窗口标题/类名/exe 名，DPI 缩放等。这个功能的缺点是准入门槛较高，现在的 ScaleModels.json 就已经很多用户不会使用。

关于这方面的操作逻辑我还在考虑

**Comment by neavo** [comment]
> 这个主意不错。我以前的想法是加一个游戏内 UI，可以在游戏内改变针对它的配置，但这个功能比较复杂。如果可以在 ScaleModels.json 里支持条件判断就可以对某一类（或某一个）窗口应用单独的设置。
> 
> 判断条件不止有源窗口大小，还可以有缩放比例，源窗口标题/类名/exe 名，DPI 缩放等。这个功能的缺点是准入门槛较高，现在的 ScaleModels.json 就已经很多用户不会使用。
> 
> 关于这方面的操作逻辑我还在考虑

是这样的，所以我个人建议这个匹配逻辑不用太复杂，就窗口分辨率，最多在加个文件名匹配就行，这些能覆盖绝大部分自动切换的需求了

**Comment by neavo** [comment]
> 这个主意不错。我以前的想法是加一个游戏内 UI，可以在游戏内改变针对它的配置，但这个功能比较复杂。如果可以在 ScaleModels.json 里支持条件判断就可以对某一类（或某一个）窗口应用单独的设置。
> 
> 判断条件不止有源窗口大小，还可以有缩放比例，源窗口标题/类名/exe 名，DPI 缩放等。这个功能的缺点是准入门槛较高，现在的 ScaleModels.json 就已经很多用户不会使用。
> 
> 关于这方面的操作逻辑我还在考虑

另外，有了这样的自动匹配以后，大家就把自己的配置文件做成傻瓜包共享出来，方便其他不会写或者懒得写 ScaleModels.json 的用户了

毕竟配置文件都懒得写的用户，你也不能指望他能搞懂什么情况该用什么配置 。。。。哈哈哈

**Comment by Blinue** [comment]
我计划实现这个功能，还会加入对硬件能力的判断，实现计算着色器以后如果硬件支持可以自动切换到效果的计算着色器版本。以后能不能做成 UI 随缘吧

**Comment by Blinue** [comment]
v0.10 实现了特定窗口的配置文件，和这个功能有很大重合。因此我决定不实现这个功能。
