### ISSUE TITLE
建议增加收藏夹功能

### ISSUE THREAD

**Issue by Kanadeforever** [Blinue/Magpie#224]
### Expected behavior 预期的功能

类似Borderless Gaming的收藏夹功能
软件在启动状态下，检测到目标程序运行，则自动以预设参数缩放该窗口

这样可以在设置开机自启动后，打开目标程序时自动缩放该程序

如果有人提过了请关闭，谢谢（应该没人提自动启动缩放这个）

### Alternative behavior (optional) 近似的功能（可选）

https://tanalin.com/en/projects/integer-scaler/

也可以类似integer scaler的自动缩放功能，手写路径来读取

**Comment by Blinue** [comment]
有人提出过类似的需求 https://github.com/Blinue/Magpie/issues/166#issuecomment-939413505

平心而论，按一次快捷键并不费什么功夫，你可以把快捷键改为更容易使用的组合。我想让 Magpie 更聚焦于缩放本身，尤其是现在项目只有我一个人维护的情况下
