### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by Blinue** [Blinue/Magpie#23]
### Discussed in https://github.com/Blinue/Magpie/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **Koteusz** August  2, 2021</sup>
The magpie uses a lot of resources. It is able to take 8% - 20% of the processor in the task manager. It also causes visible latency. In video upscaling it is not a problem, but in games (a lot of people are here for that) it’s useless.
It would be great, if you can do something about that problem. My processor is ryzen 7 4800u.
Also GDI seems to be working better with little to no latency.
![Zrzut ekranu 2021-08-02 142206](https://user-images.githubusercontent.com/82718856/127861195-ce4a2c53-975a-47bc-93a3-1b6d1e877481.png)

</div>

**Comment by Blinue** [comment]
Weird. Magpie generally does not take more than 5% of the CPU. My processor is R5 4600H.

**Comment by Blinue** [comment]
What about GPU?

**Comment by hooke007** [comment]
Lanczos (without adaptive sharpen)
winrt: no latency. =================== i7 10875h (18%) 2070sLP (5%)
GDI: visible latency and about half frame rates.  i7 10875h (8%) 2070sLP (16%)

**Comment by Blinue** [comment]
Made a diagnostic. Most of the current CPU usage is for D2D rendering and frame capture. 

No good optimization methods have been found yet, so I'll just leave this issue open.

**Comment by Blinue** [comment]
I'm still optimizing the GDI capture mode, its performance varies greatly depending on the rendering technology used by the source window.

**Comment by canceralp** [comment]
I believe after a while, we'll be asking you a game specific version that hooks into exe files and trick them into different canvas sizes, like making the game thinking it is running at exclusive Fullscreen 1080p but it's actually centered inside a 4K canvas.

**Comment by Koteusz** [comment]
There are results upscaling task manager. Gpu usage is 3D tab. Cpu usage is only from Magpie. Magpie compiled as RELEASE (02.08.2021). Hardware: Ryzen 7 4800u, iGPU, 16GB Ram.
![Zrzut ekranu 2021-08-02 220329](https://user-images.githubusercontent.com/82718856/127917564-7854d513-3e5d-421f-a2f9-265b97b54f33.png)

**Comment by Koteusz** [comment]
Maybe it will be useful to see how the obs studio is capturing the image: https://github.com/obsproject/obs-studio

**Comment by Nerboruto** [comment]
unfortunately performances are not good and there is a lot of latency ...
i tested skyrim on native 1080p and fsr 720p only +4-5fps of difference but native looks much better.
you have to understand where to optimize.

**Comment by Nerboruto** [comment]
I did other tests and I was able to improve the performance by changing the parameters on the vsync in the game window. there is probably some synchronization problem in the capture.
I put the refresh at 75 and half vsync.
how many cpu cores does magpie use? 
I also tried to remove the affinity on the cpu 0 but i didn't understand if it gets better with this mod.

**Comment by okaxihd** [comment]
Hello friends, **Magpie** can only be used with **vsync on** ie lock your framerate **(60hz=60fps)** and use **RTSS to remove latency** so the CPU usage is practically normal and the performance gain is very good I did several tests and all games were 100% error free. **I still recommend using the reshade with lumasharpen** to give the image a nice improvement. Sorry about my English.

**Comment by Nerboruto** [comment]
> Hello friends, **Magpie** can only be used with **vsync on** ie lock your framerate **(60hz=60fps)** and use **RTSS to remove latency** so the CPU usage is practically normal and the performance gain is very good I did several tests and all games were 100% error free. **I still recommend using the reshade with lumasharpen** to give the image a nice improvement. Sorry about my English.


on my old dual core pc @ 3.66ghz, on Skyrim SE performance is not great. I did several tests with vsync, fps limit, cpu affinity etc ... I also tried to remove rcas to lighten the effect. from the task manager i see magpie usage> 20/24% on WINRT . GDI performance is bad.
if there was a null bypass filter you could understand if the FSR filter is heavy or if it is an overhead problem related to capturing frames.

**Comment by Blinue** [comment]
OBS provides two methods of capturing windows
BitBlt -> GDI
Windows 10 -> WinRT

So we have the same capture methods, but OBS seems to be better in performance. Magpie may learn from it.

**Comment by PenguinDOOM** [comment]
> I found this online...
> https://atyuwen.github.io/posts/optimizing-fsr/
> as an option you could do a lighter version of fsr but with fp32 math...
Probably FP16, since it's based on FsrEasuH.

**Comment by Nerboruto** [comment]
> > I found this online...
> > https://atyuwen.github.io/posts/optimizing-fsr/
> > as an option you could do a lighter version of fsr but with fp32 math...
> 
> Probably FP16, since it's based on FsrEasuH.

has already been implemented on magpie's competitor ... performance increase is irrelevant and only worsens quality ...
does not make sense.

**Comment by soredake** [comment]
> > > I found this online...
> > > https://atyuwen.github.io/posts/optimizing-fsr/
> > > as an option you could do a lighter version of fsr but with fp32 math...
> > 
> > Probably FP16, since it's based on FsrEasuH.
> 
> has already been implemented on magpie's competitor ... performance increase is irrelevant and only worsens quality ...
> does not make sense.

What competitor?

**Comment by PenguinDOOM** [comment]
> > > > I found this online...
> > > > https://atyuwen.github.io/posts/optimizing-fsr/
> > > > as an option you could do a lighter version of fsr but with fp32 math...
> > > 
> > > 
> > > Probably FP16, since it's based on FsrEasuH.
> > 
> > 
> > has already been implemented on magpie's competitor ... performance increase is irrelevant and only worsens quality ...
> > does not make sense.
> 
> What competitor?

Maybe Lossless Scaling

**Comment by PenguinDOOM** [comment]
> > > I found this online...
> > > https://atyuwen.github.io/posts/optimizing-fsr/
> > > as an option you could do a lighter version of fsr but with fp32 math...
> > 
> > 
> > Probably FP16, since it's based on FsrEasuH.
> 
> has already been implemented on magpie's competitor ... performance increase is irrelevant and only worsens quality ...
> does not make sense.

Performance will only improve if the hardware is capable of handling FP16.

**Comment by Nerboruto** [comment]
> > > > I found this online...
> > > > https://atyuwen.github.io/posts/optimizing-fsr/
> > > > as an option you could do a lighter version of fsr but with fp32 math...
> > > 
> > > 
> > > Probably FP16, since it's based on FsrEasuH.
> > 
> > 
> > has already been implemented on magpie's competitor ... performance increase is irrelevant and only worsens quality ...
> > does not make sense.
> 
> Performance will only improve if the hardware is capable of handling FP16.

I think even with fp16 it does not make sense because the quality degrades too much. fsr is already lacking in quality especially when the resolution is low. 
I tried it and then deactivated it because I didn't like the result.

**Comment by PenguinDOOM** [comment]
> > > > > I found this online...
> > > > > https://atyuwen.github.io/posts/optimizing-fsr/
> > > > > as an option you could do a lighter version of fsr but with fp32 math...
> > > > 
> > > > 
> > > > Probably FP16, since it's based on FsrEasuH.
> > > 
> > > 
> > > has already been implemented on magpie's competitor ... performance increase is irrelevant and only worsens quality ...
> > > does not make sense.
> > 
> > 
> > Performance will only improve if the hardware is capable of handling FP16.
> 
> I think even with fp16 it does not make sense because the quality degrades too much. fsr is already lacking in quality especially when resolution is low.
> I didn't like the result.

I was curious, so I tried it.
FP32
![FP32](https://user-images.githubusercontent.com/50603637/132533129-269cb648-6331-4e51-8b52-5f48625d223e.png)
FP16 (Sharpness shader)
![FP16_sharpness](https://user-images.githubusercontent.com/50603637/132533328-a4fc0fde-7201-4dac-8926-f1926b1399da.png)
FP16 (Upscaling shader)
![FP16_upscaling](https://user-images.githubusercontent.com/50603637/132533491-9be93962-6bb0-4a59-8eb5-8cfe3d3b7513.png)
FP16 (All)
![FP16_all](https://user-images.githubusercontent.com/50603637/132533705-32250f1f-7e76-4b49-bfdd-6c9f5a3ec2f2.png)

Upscaling shader have the most impact on quality.
I don't see any difference in performance since it is not high fps.

**Comment by PenguinDOOM** [comment]
> > > > > > I found this online...
> > > > > > https://atyuwen.github.io/posts/optimizing-fsr/
> > > > > > as an option you could do a lighter version of fsr but with fp32 math...
> > > > > 
> > > > > 
> > > > > Probably FP16, since it's based on FsrEasuH.
> > > > 
> > > > 
> > > > has already been implemented on magpie's competitor ... performance increase is irrelevant and only worsens quality ...
> > > > does not make sense.
> > > 
> > > 
> > > Performance will only improve if the hardware is capable of handling FP16.
> > 
> > 
> > I think even with fp16 it does not make sense because the quality degrades too much. fsr is already lacking in quality especially when resolution is low.
> > I didn't like the result.
> 
> I was curious, so I tried it.
> FP32
> ![FP32](https://user-images.githubusercontent.com/50603637/132533129-269cb648-6331-4e51-8b52-5f48625d223e.png)
> FP16 (Sharpness shader)
> ![FP16_sharpness](https://user-images.githubusercontent.com/50603637/132533328-a4fc0fde-7201-4dac-8926-f1926b1399da.png)
> FP16 (Upscaling shader)
> ![FP16_upscaling](https://user-images.githubusercontent.com/50603637/132533491-9be93962-6bb0-4a59-8eb5-8cfe3d3b7513.png)
> FP16 (All)
> ![FP16_all](https://user-images.githubusercontent.com/50603637/132533705-32250f1f-7e76-4b49-bfdd-6c9f5a3ec2f2.png)
> 
> Upscaling shader have the most impact on quality.
> I don't see any difference in performance since it is not high fps.

This simply rewrites float to min16float.

**Comment by Nerboruto** [comment]
in my opinion the bottleneck is between capture, texture transfer and display. even turning off all transformations and effects, latency remains. in fact the competitor also suffers albeit slightly less of the same overhead problems as magpie.
