### ISSUE TITLE
need scale bar back on the UI + fps drop  v0.7.1 

### ISSUE THREAD

**Issue by humanana** [Blinue/Magpie#233]
why not keep the scale bar on the UI? 

it's very useful than config the value in text and it is real time rendering

-also testing with vsyn on with 0.7.1 make framerate drop from the real fps

**Comment by hooke007** [comment]
We never had the scale bar...

**Comment by Blinue** [comment]
If you mean "FSR sharpness", I would say that this option is no longer available and you should use 0.7.0 preview instead.

**Comment by palxex** [comment]
> If you mean "FSR sharpness", I would say that this option is no longer available and you should use 0.7.0 preview instead.

A suggestion: now in fact many effects have a "sharpness" parameter, which shares same range. Why not introduce a slider again, and let it passes to those effects that has this parameter? For other effects it should be safe to just bypass it.

**Comment by Blinue** [comment]
The range of sharpness varies from effect to effect:

CAS: [0, 1]
FSR_RCAS: (0, +∞)
NIS: [0, 1]
NVSharpen: [0, 1]
AdaptiveSharpen (curveHeight): (0, +∞)

If there are multiple sharpening steps in a model, changing the sharpness of all of them may not be what you want.

**Comment by palxex** [comment]
> The range of sharpness varies from effect to effect:
> 
> CAS: [0, 1] FSR_RCAS: (0, +∞) NIS: [0, 1] NVSharpen: [0, 1] AdaptiveSharpen (curveHeight): (0, +∞)
> 
> If there are multiple sharpening steps in a model, changing the sharpness of all of them may not be what you want.

Thanks for detailed explanation.

**Comment by Blinue** [comment]
It is not technically difficult to implement this option, but I want to keep Magpie generic, meaning that I would not treat a particular effect in a special way.
If anyone needs this option please fork Magpie. And if you decide to maintain such a fork, I'll be glad to provide some help.
