### ISSUE TITLE
Window resizing (question)

### ISSUE THREAD

**Issue by Bxaa** [Blinue/Magpie#234]
Interesting project, Thx

I did try to use it for enchanting max resolution in game, but in this case i got a small part of screen game window. (most image is out of bounds) Also seems to be client rectangle not update correctly (only window size)

Tested with GDIDPISCALING DPIUNAWARE and HIGHDPIAWARE override flags. Same result...

**Comment by hooke007** [comment]
Where is the CASE? Please show more details and screenshot.

**Comment by Blinue** [comment]
Do you have multiple monitors?

**Comment by Bxaa** [comment]
> Where is the CASE? Please show more details and screenshot.
Just imagine small part of game screen

My case is:
1) Launch game (resolution in game already set for max available supported)
2) Alt+F11 cause resizing all window content, but not resize game window
Sometimes black areas appear (client rectangle not update correctly)

> Do you have multiple monitors?
Yes

Thx for programm. I'll fix it self and then report here how to fix it

**Comment by Blinue** [comment]
I suggest you start from dev branch

**Comment by Bxaa** [comment]
Hi, 
in my case - both DisableNXShowUI and  HighDpiAware (This AppCompatFlags fully resolve issue. No need any code change)
Using multi monitor config / May be it help someone...

Thx
