### ISSUE TITLE
"允许额外的延迟“随机的引起放大窗口帧率降低

### ISSUE THREAD

**Issue by palxex** [Blinue/Magpie#235]
### Program(Game) 游戏名

任意

### Capture method 捕获模式

任意

### Related screenshot (optional) 相关截图（可选）

触发时的配置和截图
![1 0](https://user-images.githubusercontent.com/58222/144704256-8c18ada0-895e-42dd-a297-7da0e0383e51.png)
![1 1](https://user-images.githubusercontent.com/58222/144704257-eda560cf-bd6c-46fd-8dfc-96bfa7deeb5f.png)
未触发时的
![2 0](https://user-images.githubusercontent.com/58222/144704259-520a85e8-3d80-49f7-a370-ae22cfe42de9.png)
![2 1](https://user-images.githubusercontent.com/58222/144704271-5dc6d892-7756-417c-a9b0-4a3311e29891.png)

### Other information (optional) 补充信息（可选）

此问题第一次发现是在11月20日左右，自己编译的magpie dev release，在Windows 11 Dev上发现，并在Windows 10 21H1上重现。但7天后再次尝试验证，该问题消失，无法重现。又过了7天也就是昨天，在Windows 11 Dev上再次发现（截图是当时的）。今天再次消失。
由截图可见触发时CPU/GPU/内存/显存都未占满，不大可能是资源的问题。另外游戏的原始帧数并未降低，降低的只是magpie的放大帧数。
另据当时测试记录，在（未知条件下）勾选“允许额外的延迟”导致magpie的放大帧数异常后，再勾选“禁用DirectFlip”可以解决此问题。当时及之前多次查看log时，Hardware Composition 支持和Multiplane Overlay 支持都是否，按理来说DirectFlip压根没有支持，这个选项勾不勾应该是无影响的才对。

### Log files 日志文件

昨天忘记留下完整log，今天想重现已经没有触发时的了……只能等下次（不知何时）重现时了。
未触发该bug（也就是正常）时的log：
[Runtime.log](https://github.com/Blinue/Magpie/files/7655688/Runtime.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/7655689/Magpie.log)

**Comment by Blinue** [comment]
https://www.intel.cn/content/www/cn/zh/developer/articles/code-sample/sample-application-for-direct3d-12-flip-model-swap-chains.html
默认使用 "Minimum Latency" 模式，允许额外的延迟则切换到 "Game Mode"。因为会在某一次重启后出现，所以我怀疑是操作系统或驱动的 bug。

所谓“禁用DirectFlip”是将全屏窗口设为稍微透明，这样可以强制 DWM 保持唤醒状态。因为这个选项可以修复这个问题，我觉得是 DWM 的锅

**Comment by palxex** [comment]
感谢剖析，下次触发后我计划分别强制重启驱动umd和dwm看看情况是否有变化。

**Comment by Blinue** [comment]
这种bug只有能在我的电脑上复现才能分析，你下次遇到时可以调试一下？

**Comment by palxex** [comment]
说实话magpie的runtime我现在就不会调试……正好请教下，VS里启动调试调试的似乎是magpie的GUI，runtime被唤起后我就没法依靠断点只能靠log了，应该怎样对该dll进行逐行调试？

**Comment by Blinue** [comment]
Magpie 属性->调试->打开调试启动配置文件 UI->启用本机代码调试

**Comment by Blinue** [comment]
> 甚至将帧率设为无限制都没用，设置完刚进去可见帧率飙到上百，没几秒又回到20+。

关闭垂直同步后“允许额外的延迟“应该是无效的，我认为这是一个切入点

**Comment by palxex** [comment]
又重现了一次。但这次的测试结果与之前再次抵触甚至开始自相抵触……感觉快要放弃理解了。
1. 游戏fps也开始随放大fps浮动，跟之前只有后者浮动完全不同。
2. 允许额外延迟+帧率无限制的测试，前后三次编译测试结果直接自相抵触。
第一次直接用dev的代码，结果跟之前一样同样降低到20+。
第二次修改了StepTimer.cpp（尝试记录每次Tick()的时间确定是不是CPU降频了导致调用次数降低)，同样配置不再降低，而且飙到了120+。
第三次直接还原修改，跟第一次同样代码同样配置莫名其妙的也120+了。
3. 唯一一个可能有用的新结果：允许额外延迟+手动限制帧率到60，帧率会维持到60，而不会跟额外延迟+垂直同步开时一样降低。
另外想逐行调试是不是只能双机或者至少双显示器进行？之前尝试在Renderer::_Render下断点，断到后回到VS窗口往下执行几行就在_CheckSrcState()检查时发现原窗口已经丢失焦点直接蹦出去了，注掉这段切走又有其他副作用。

**Comment by Blinue** [comment]
注释掉调用 _CheckSrcState() 的代码即可，只有 Desktop Duplication 捕获模式不兼容

**Comment by Blinue** [comment]
根据我的经验，性能问题是无法用单步调试解决的
![image](https://user-images.githubusercontent.com/34770031/145376629-2cc1195b-8edb-401e-9640-0eef7892e762.png)
你可以根据这张图改变这些参数看看效果。从你的描述看，这个问题和垂直同步无关，限制帧率时也是关闭垂直同步的

**Comment by palxex** [comment]
找到了稳定重现的方法：关闭HDR。之前一直没找到还是控制变量有问题——因为我常测的两个游戏都是不支持HDR的，开关对其观感无影响，而因为看视频的需要，我频繁开关HDR。
更新描述：关闭HDR时，只打开”允许额外的延迟“在我机器上100%引发非HDR游戏放大后帧率降低——这是否意味着，打开HDR，对非HDR游戏会强制DWM保持唤醒，从而起到了类似禁用DirectFlip的效果？
另外使用如下补丁将”只允许额外的延迟“行为由Game Mode更改为Classic Game Mode（不过我没看懂上图中的FrameCount是怎么指定的，都是改的MaximumFrameLatency），结果不变，仍然会导致帧率降低，幅度也相同。附补丁写法，防止我理解有误
[classic.patch.zip](https://github.com/Blinue/Magpie/files/7694044/classic.patch.zip)

**Comment by Blinue** [comment]
如果和 HDR 有关的话就只能是系统或驱动原因了，我的显示器不支持 HDR 所以没法测试。

你可以用 [PresentMon](https://github.com/GameTechDev/PresentMon) 看看 Magpie 的延迟是多少，以及全屏时 DWM 是否是活动的。如果支持 DirectFlip，Magpie 的延迟在 16.6 ms 以内，并且全屏时 DWM 是休眠状态

**Comment by palxex** [comment]
> 如果和 HDR 有关的话就只能是系统或驱动原因了，我的显示器不支持 HDR 所以没法测试。
> 
> 你可以用 [PresentMon](https://github.com/GameTechDev/PresentMon) 看看 Magpie 的延迟是多少，以及全屏时 DWM 是否是活动的。如果支持 DirectFlip，Magpie 的延迟在 16.6 ms 以内，并且全屏时 DWM 是休眠状态

好的，我稍后测试一下。
感觉HDR还蛮重要的，现在支持hdr400的显示器也不是很贵，要不要考虑开个patreon看有多少人愿意捐献，说不定能凑一个？

**Comment by palxex** [comment]
不过说实话我不太能确定我这个真的跟HDR相关——如上所述，这个问题只在我不开HDR时才会出现。目前只有这个显示器，无法确定在不支持HDR的显示器上是否也会出现。

> 你可以用 PresentMon 看看 Magpie 的延迟是多少，以及全屏时 DWM 是否是活动的。如果支持 DirectFlip，Magpie 的延迟在 16.6 ms 以内，并且全屏时 DWM 是休眠状态

问一下，全屏时DWM是否休眠应该怎么看？我只有一个显示器，每次切回来DWM肯定是恢复存在的。
另外，Hardware: Legacy Flip 是DirectFlip吗？看[presentmon的定义](https://github.com/GameTechDev/PresentMon/blob/cf62c361fc3f93473a016b5cb5dfe1d2a14c6d74/PresentData/PresentMonTraceConsumer.hpp#L30)，直接表示DirectFlip的那个貌似被注掉了？

开启“允许额外的延迟”在SDR和HDR的情况下各录了一段（只留了magpie的部分，需要的话我再录一次）。看起来我这边SDR的情况下，开这个选项会导致msInPresentAPI和msUntilRenderComplete异常增大，达到了HDR时的3-4倍，并因此导致了有帧被轮空（好几帧0，然后一帧突然蹦出来）

**Comment by Blinue** [comment]
Hardware_Independent_Flip 和 Hardware_Composed_Independent_Flip 都是 DirectFlip

至于怎么看，直接放大控制台...
![屏幕截图(486)](https://user-images.githubusercontent.com/34770031/145710564-a3aacb2d-f1d0-4cdf-958f-bf3a1c300e47.png)

**Comment by palxex** [comment]
HDR时
![HDR](https://user-images.githubusercontent.com/58222/145712108-e9a2c776-c7b7-46f8-acf7-a4b729da3c01.png)
SDR时
![SDR](https://user-images.githubusercontent.com/58222/145712115-03ba057b-25bf-4a36-ad39-d9280dd223ea.png)
上帖忘记上传数据了，已补

**Comment by Blinue** [comment]
v0.9 对渲染进行了全面重写，帧率应该也更为稳定。像素着色器有很长的流水线，似乎容易遇到瓶颈。

**Comment by palxex** [comment]
上周日编译的dev仍然有这个问题，具体表现与第一次发现相同。
Win11正式版，22000.651，RX584 驱动是稳定版22.3.1。
估计找不出原因了，留作记录吧。
