### ISSUE TITLE
使用前端启动器启动软件时无法缩放游戏

### ISSUE THREAD

**Issue by Kanadeforever** [Blinue/Magpie#236]
### Magpie version 程序版本

0.7.1.0

### Windows version 系统版本

win10 21H2

### Related screenshot (optional) 相关截图（可选）

https://imgur.com/jMVKRjI

### Reproduction steps 复现步骤

1. 使用Playnite前端，添加进游戏（目前废都物语和使用了cnc-ddraw的刀剑封魔录是这样）
2. 在游戏设置菜单中【脚本】功能页的【启动游戏前执行的脚本】处添加【Start-Process "E:\Software\Magpie\Magpie.exe" -WindowStyle Minimized】
3. 点击前端的启动游戏按钮启动游戏
4. （以废都物语举例）窗口化启动废都物语，同时启动magpie，magpie成功启动后按快捷键ALT+F11缩放，即出现图片中的报错

补充：使用AutoHotKey制作GUI来启动Magpie、使用批处理的方式在启动游戏前启动Magpie，均会出现同样的情况

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7684841/Magpie.log)

**Comment by Blinue** [comment]
是工作路径的问题，Magpie 无法找到 Runtime.dll，试试这个命令 

``` powershell
Start-Process "E:\Software\Magpie\Magpie.exe" -WorkingDirectory "E:\Software\Magpie" -ArgumentList "-st"
```

-st 是 Magpie 内部使用的参数，可以最小化到任务栏

**Comment by Kanadeforever** [comment]
非常感谢，问题已解决

**Comment by Blinue** [comment]
这是一个 bug，以后 Magpie 不会使用工作目录，而是统一使用程序所在目录
