### ISSUE TITLE
Scaling doesn't work if Magpie is launched from powershell

### ISSUE THREAD

**Issue by darklinkpower** [Blinue/Magpie#237]
### Magpie version 程序版本

0.7.1

### Windows version 系统版本

win10 21H1

### Related screenshot (optional) 相关截图（可选）

![image](https://user-images.githubusercontent.com/1389286/145549866-7c6a13c9-b875-44be-9ea7-a4db9e06f1c2.png)

### Reproduction steps 复现步骤

1. Launch Magpie via Powershell with
```powershell
Start-Process "C:\Path\To\Magpie.exe"
```
or
```powershell
[System.Diagnostics.Process]::Start("C:\Path\To\Magpie.exe")
```

2. Attempt to scale a window using the configured hotkey

There are no issues scaling when launching Magpie normally by clicking the executable

### Log files 日志文件

[Runtime.log](https://github.com/Blinue/Magpie/files/7691575/Runtime.log)
[Runtime.1.log](https://github.com/Blinue/Magpie/files/7691576/Runtime.1.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/7691577/Magpie.log)

**Comment by Blinue** [comment]
#236

**Comment by darklinkpower** [comment]
Thankyou, that fixed it
