### ISSUE TITLE
Magpie works very inconsistently with NVDIA GameStream

### ISSUE THREAD

**Issue by davidmwest** [Blinue/Magpie#239]
### Magpie version 程序版本

.71

### Windows version 系统版本

Win 11 Professional

### Related screenshot (optional) 相关截图（可选）

![IMG_0752](https://user-images.githubusercontent.com/2710397/145630570-57eaccdb-affa-4b18-a5aa-e618b7329c54.jpeg)

### Reproduction steps 复现步骤

Set up https://moonlight-stream.org/

Stream to your device. With magpie running and enhancing the window, one of two things seems to happen:

1. The game works, but as soon as you alt tab, and come back, you have to restart both magpie and the game for it to work again. Otherwise magpie seems to "freeze". Audio still works and the mouse can still click, but the video is stuck on a single frame, and the displayed framerate is 0.
2. The game works, but only for about 5 seconds, then the video freezes. Audio continues and mouse clicking still works.

Given that magpie usually works when running Moonlight during a fresh stream (new instance of magpie, new instance of the game window), I suspect the fix is probably fairly simple, but of course I am no expert here.

Lastly, even while magpie appears to be frozen to the moonlight gamestream client, if I go to my PC, I can see that magpie is working as intended. So the bug here is likely at the intersection of magpie's "capture" feature and "gamestream". It would be nice to get some official developer support here. There are dozens of us playing via Gamestream. Dozens!

### Log files 日志文件

Latest experimental: 
[Magpie.log](https://github.com/Blinue/Magpie/files/7695014/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7695015/Runtime.log)

.71:
[Runtime.log](https://github.com/Blinue/Magpie/files/7695053/Runtime.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/7695054/Magpie.log)
[Runtime.1.log](https://github.com/Blinue/Magpie/files/7695055/Runtime.1.log)

**Comment by hooke007** [comment]
https://github.com/Blinue/Magpie/issues/141

**Comment by davidmwest** [comment]
Checking "Disable Directflip" in options seems to fix the issues I'm seeing. I was able to enjoy a mostly contiguous gaming session of "Boku to Koi Suru Ponkotsu Akuma". I will do more testing under other scenarios when I have time. 

I have no idea what "Directflip" is, but it does seem to cause interference with Gamestream.

**Comment by davidmwest** [comment]
https://devblogs.microsoft.com/directx/dxgi-flip-model/

When should I use blt model?
There is one piece of functionality that flip model does not provide: the ability to have multiple different APIs producing contents, which all layer together into the same HWND, on a present-by-present basis. An example of this would be using D3D to draw a window background, and then GDI to draw something on top, or using two different graphics APIs, or two swapchains from the same API, to produce alternating frames. If you don’t require HWND-level interop between graphics components, then you don’t need blt model.

**Comment by Blinue** [comment]
Directflip is a technique to reduce input latency, but it is incompatible with some games/streaming services, so I have provided an option to turn it off.

Go to #141 for further discussion

PS. Despite the work at hand, I will prioritize this issue.
