### ISSUE TITLE
无法在赛博朋克2077中使用

### ISSUE THREAD

**Issue by EdLovecraft** [Blinue/Magpie#24]
![UTIG_2ZWKQ`8Z(4XSA )P6C](https://user-images.githubusercontent.com/40231164/127971727-f10fea0c-43bc-4ab8-87de-a8515cb19ec2.png)
是不是因为这是DX12游戏

**Comment by Blinue** [comment]
这是个已知bug，出现这个错误之后鼠标可能会消失不见。我会进行修复。

**Comment by Blinue** [comment]
暂时的应对方法：进入游戏的菜单界面，即鼠标可以自由移动的时候进入全屏

**Comment by EdLovecraft** [comment]
> 这是个已知bug，出现这个错误之后鼠标可能会消失不见。我会进行修复。

鼠标会消失，但游戏并没有放大到全屏，还是原来窗口模式

**Comment by Blinue** [comment]
这是因为鼠标被设置为透明，但依然可以正常使用。
![image](https://user-images.githubusercontent.com/34770031/127982408-bc8dc043-72a4-4d6a-ae5b-76f645fd4639.png)
恢复鼠标的步骤：在设置里进入“其他鼠标选项”，转到“指针”一栏然后确定

**Comment by Blinue** [comment]
我会在今晚发布一个版本来修复这个bug，以及添加FSR

**Comment by LightMu** [comment]
> 我会在今晚发布一个版本来修复这个bug，以及添加FSR

感谢您为软件您的添加FSR，我很期待您的您的更新，这对游戏玩家来说将是一个巨大变革！
我注意到您的预览图和简单介绍已经更新，之后您可否在您的软件介绍页面发布Magpie正确配置和使用FSR的方法？

**Comment by Blinue** [comment]
v0.5.2修复了这个bug

**Comment by hooke007** [comment]
>Magpie可能无法在2K/4K分辨率下使用

一直在4k下正常使用....

**Comment by Blinue** [comment]
感谢老伙计的反馈

**Comment by eaglu** [comment]
我在2K分辨率也没遇到过问题
