### ISSUE TITLE
Where select MODE ????

### ISSUE THREAD

**Issue by sergeysaratov1991** [Blinue/Magpie#240]
### Magpie version 程序版本

0.7 

### Windows version 系统版本

win11

### Related screenshot (optional) 相关截图（可选）

![image](https://user-images.githubusercontent.com/94934983/145695286-57514771-0923-4596-9205-56878542815f.png)

### Reproduction steps 复现步骤

123

### Log files 日志文件

123

**Comment by Blinue** [comment]
Download latest release [here](https://github.com/Blinue/Magpie/releases)
