### ISSUE TITLE
求问能否像 mpv 一样 色度 和 明度 分开缩放，额

### ISSUE THREAD

**Issue by NeilTohno** [Blinue/Magpie#241]
### Expected behavior 预期的功能

https://github.com/mpv-player/mpv
![01](https://user-images.githubusercontent.com/28284594/145975031-a04b11de-8f5e-404e-852d-2a9b54122d0a.jpg)

如果实现不了就算了，拜谢大大
╮(￣▽￣)╭

**Comment by Blinue** [comment]
视频的输入是 yuv 格式，因此可以提供明度通道。Magpie 的输入是 rgb 格式，所以所有效果的输入都是 rgb，想操作亮度通道的话可以自己转换

``` hlsl
float get_luma(float3 rgb) {
	return dot(float3(0.299, 0.587, 0.114), rgb);
}
```

这方面 @hooke007 应该更清楚

**Comment by NeilTohno** [comment]
> 视频的输入是 yuv 格式，因此可以提供明度通道。Magpie 的输入是 rgb 格式，所以所有效果的输入都是 rgb，想操作亮度通道的话可以自己转换
> 
> ```hlsl
> float get_luma(float3 rgb) {
> 	return dot(float3(0.299, 0.587, 0.114), rgb);
> }
> ```
> 
> 这方面 @hooke007 应该更清楚

大大，这个给咱不会用啊，是不是改配置文件 ScaleModels.json 就能用啊，
谢

**Comment by Blinue** [comment]
> ```hlsl
> float get_luma(float3 rgb) {
> 	return dot(float3(0.299, 0.587, 0.114), rgb);
> }
> ```

这是给着色器作者用的，一般用户的话不需要关心这些

**Comment by hooke007** [comment]
...
常规视频编码到yuv420时色度产生了半采样
播放器在回放处理时中间需要转换为RGB，这时候需要chroma upscale补足缺失的色度信息
如果回放yuv444的视频，因为色度信息没有丢失，同样不需要cheoma upscale

--------

游戏-magpie 是rgb全程输入输出，不需要chroma upscale

**Comment by NeilTohno** [comment]
> 游戏-magpie 是rgb全程输入输出，不需要chroma upscale


见过大大，
咱不知道 这个啊，咱觉得 可以 RGB 转  YUV （YUV444 ?），只运算 luma 保留 chroma，最后合并，
只是假想而已，不知道可否实现，
拜谢。

**Comment by hooke007** [comment]
这个需求太奇怪了....为什么要引入完全多余的计算

**Comment by Blinue** [comment]
只在亮度分量上升频的技术挺常见的，人眼对亮度最敏感，因此可以有效节省算力。ACNet 和 FSRCNNX 都是这样实现的，以前的Anime4K 也是这样，但现在改成 rgb 了

**Comment by hooke007** [comment]
不清楚对magpie来讲 RGB -YUV- RGB 多走两步转换是否引入可观延迟
