### ISSUE TITLE
求增加几个锐化滤镜

### ISSUE THREAD

**Issue by NeilTohno** [Blinue/Magpie#242]
### Expected behavior 预期的功能

比如，
https://github.com/crosire/reshade-shaders/tree/master/Shaders
LumaSharpen，(可以和 https://github.com/Blinue/Magpie/issues/241 一起弄哈)
FineSharp

还有特殊的，
unmask Sharpen 

不知道能不能做，拜谢，主要现在是只有 FSR 锐化嘛，多个选择挺好

反正 3D 首选 FSR 锐化， 2D 可以选择其他锐化，恩

拜谢。

**Comment by Blinue** [comment]
自适应锐化和 CAS 都是很好的锐化效果。如果还有锐化算法更好/适用于新的场景，请放出对比图

**Comment by frdoma** [comment]
https://www.techspot.com/review/1884-amd-ris-vs-nvidia-freestyle-vs-reshade/这里有一篇对比不同锐化(lumasharpen、adaptivesharpen、RIS(CAS)、Nvidia Freestyle)的评测，在不需要很强锐化的情境下lumasharpen表现良好。

**Comment by NeilTohno** [comment]
reshade 的插件，看着很复杂，还不如做个接口，可以直接调用 reshade，个人拙见而已。

**Comment by Blinue** [comment]
Nvidia Freestyle 似乎没有开源，但我会移植 lumasharpen

不会集成 reshade，magpie 有自己的语法

**Comment by frdoma** [comment]
https://www.youtube.com/watch?v=EFY7_H6rvEw
Nvidia Freestyle里的锐化可能就是NIS里的锐化，这个视频有对比FSR和NIS的效果，得出的结论是两个算法本身的区别微乎其微，更多的是它们附带的锐化效果产生的差异，而NIS里的锐化相比CAS往往会带来更多细节上的瑕疵。

**Comment by Blinue** [comment]
已移植 LumaSharpen 和 FineSharp

**Comment by NeilTohno** [comment]
> 已移植 LumaSharpen 和 FineSharp

辛苦大大，能加个使用说明到 wiki 吗，我先试试？

**Comment by Blinue** [comment]
https://gist.github.com/hooke007/818ecc88f18e229bca743b7ae48947ad
