### ISSUE TITLE
请问今后有计划开发针对Oculus airlink（VR串流）的功能吗？

### ISSUE THREAD

**Issue by moiraroman** [Blinue/Magpie#243]
### Question 问题

VR中有很多游戏会因为性能问题无法达到需求帧率
但游戏中的锐化滤镜又产差不齐，有些甚至只有TAXX
这个时候如果有FSR的话可能能对帧率提升有很大帮助
请问有计划针对VR串流开发对应功能吗

**Comment by Blinue** [comment]
我没接触过 VR，Magpie 也不是为串流设计的。可预见的规划里都不会有这个功能。

Magpie 至少会引入一帧延迟，这在 VR 里可能是不可接受的。说不定只能从驱动层面解决...
