### ISSUE TITLE
捕获到意外窗口时导致出现白屏，且无法简单退出

### ISSUE THREAD

**Issue by codehz** [Blinue/Magpie#244]
### Magpie version 程序版本

v0.7.1

### Windows version 系统版本

win11

### Related screenshot (optional) 相关截图（可选）

(只能注消解决，所以截图也丢了)

### Reproduction steps 复现步骤

* 这是一个我这里100%复现的路径，并不是实际使用场景，只是为了复现 bug
1. 打开 记事本 （win11 insider里的那个不行）
2. 点击字体设置
3. 按下快捷键设置全屏
4. 出现全屏窗口，灰白色，无法通过 alt tab 切出
5. 任务管理器也不行
6. 注消后才能退出

### Log files 日志文件

```
2021-12-16 11:42:33.7396|INFO|Magpie.MagWindow|正在新线程中创建全屏窗口
2021-12-16 11:43:14.7293|WARN|Magpie.MagWindow|源窗口不合法
2021-12-16 11:43:16.6173|WARN|Magpie.MagWindow|源窗口不合法
2021-12-16 11:43:20.3453|WARN|Magpie.MagWindow|源窗口不合法
2021-12-16 11:43:22.2092|WARN|Magpie.MagWindow|源窗口不合法
```

**Comment by Blinue** [comment]
请发一下完整日志

**Comment by codehz** [comment]
[logs.zip](https://github.com/Blinue/Magpie/files/7724497/logs.zip)

**Comment by codehz** [comment]
@Blinue 清理了一下日志，这个应该只保留了出现 bug 的部分
[logs.zip](https://github.com/Blinue/Magpie/files/7724516/logs.zip)

**Comment by Blinue** [comment]
1. 日志里没有错误信息，只知道 Graphics Capture 不支持捕获弹窗，但这时应该会弹出错误提示
2. 其他捕获模式没有这个问题
3. alt tab无法切出的话可以使用热键

**Comment by codehz** [comment]
> 1. 日志里没有错误信息，只知道 Graphics Capture 不支持捕获弹窗，但这时应该会弹出错误提示

错误提示从 alt tab 界面里看到了，但是不幸的是，它也被挡住了，关键的问题在于，这个弹框顺便阻止了在任务栏中关闭窗口，只会标记闪铄一下。。。

>     2. 其他捕获模式没有这个问题

确实没有，但是遇到了就只能注消就麻烦了，有些游戏也会利用弹框做一些操作，如果不小心在弹框上点到快捷键（或者5秒后捕获）就没法切出了

>     3. alt tab无法切出的话可以使用热键

不幸的是，热键在弹框出现的时候并没有效果。。也没法对其他窗口继续使用弹框

**Comment by codehz** [comment]
![图片](https://user-images.githubusercontent.com/13158903/146312691-e0f387ba-3d81-4db7-9ab2-65fad9bfa4c2.png)
截图也拿到了（通过一顿操作意外退出了Magpie才把截图保留下来）

**Comment by codehz** [comment]
然后发现了 Workaround：通过aero preview标记Magpie错误弹框确认按钮的位置，用鼠标点对应位置关闭错误弹框，然后任务栏中关闭Magpie窗口，如果选择了最小化到通知区域，就在通知区域里右键关闭 Magpie

可见那个原本用于定位问题的错误弹框让问题更难解决了。。。

**Comment by Blinue** [comment]
是不是在设置中打开了“禁用 DirectFlip”？

**Comment by hooke007** [comment]
> （通过一顿操作意外退出了Magpie才把截图保留下来）

win+printscreen 在此时无效吗

**Comment by codehz** [comment]
> > （通过一顿操作意外退出了Magpie才把截图保留下来）
> 
> win+printscreen 在此时无效吗

哦，我把printscreen设置成win shift s一样的功能了，这个好像只存粘贴板）））
