### ISSUE TITLE
2D 抗锯齿功能？

### ISSUE THREAD

**Issue by NeilTohno** [Blinue/Magpie#246]
### Expected behavior 预期的功能

关于2D游戏，
有视觉小说游戏，720p ，画面人物边缘带比较明显的锯齿，
用 FSRCNNX 算法放大以后，就直接加上难看的纹理\锯齿

拜谢

[1.zip](https://github.com/Blinue/Magpie/files/7738963/1.zip)

**Comment by Blinue** [comment]
2D画面消除锯齿的方法基本都会对画面有破坏。Anime4K和ACNet可以消除小锯齿，但是对大锯齿无能为力，你可以试试 Anime4k restore

**Comment by NeilTohno** [comment]
> 2D画面消除锯齿的方法基本都会对画面有破坏。Anime4K和ACNet可以消除小锯齿，但是对大锯齿无能为力，你可以试试 Anime4k restore

ACNet

**Comment by NeilTohno** [comment]
> 2D画面消除锯齿的方法基本都会对画面有破坏。Anime4K和ACNet可以消除小锯齿，但是对大锯齿无能为力，你可以试试 Anime4k restore

ACNet个人觉得会损坏细节，不太喜欢。
反锯齿这个，动画压制组天天在用的啊，只要有 mask ，能控制好平衡度就行；
不然这个画面就是看着不完美，有点不舒服，
求大大考虑一下，谢

**Comment by Blinue** [comment]
如果你知道有这样的算法请提供算法名，有着色器实现的话请提供url

**Comment by NeilTohno** [comment]
> 如果你知道有这样的算法请提供算法名，有着色器实现的话请提供url

啊，只是写了一个帖子问老外了额，
https://forum.doom9.org/showthread.php?p=1959615

**Comment by hooke007** [comment]
mask。。。这玩意是avs的一个插件 https://github.com/pinterf/masktools

**Comment by Blinue** [comment]
感觉不像是能实时渲染的算法

**Comment by NeilTohno** [comment]
个人觉得还是把 2D 和 3D 拆分处理吧，要求的缩放算法和最终效果并不一样；
防止有人又用错误 算法玩 3D 游戏

**Comment by Blinue** [comment]
我不会创造新的算法，只会移植已有的。如果你有更具体的功能请求，重新打开此 issue。

**Comment by NeilTohno** [comment]
啊，
这里找到一个 TAA ,应该？

https://reshade.me/forum/shader-suggestions/2276-so-taa-with-smaa-possible-with-shaders-seems-so?start=20
