### ISSUE TITLE
New less intensive custom scaler

### ISSUE THREAD

**Issue by FineLine0** [Blinue/Magpie#247]
### Expected behavior 预期的功能

to be less intensive than NIS and FSR (magpie app), but better than Bilinear and Bicubic scalers.

This will help for people with 1440p/4K monitor who wants to play at 1080p without unnecessary blur of bilinear scaling.

**Comment by Blinue** [comment]
FSR is very fast and you can adjust its sharpness in Magpie. It's good enough for 3D games, is there anything to improve?

**Comment by FineLine0** [comment]
maybe add NIS with a somewhat less intensive sharpening effect, as the sharpening from control panel takes away 6% of the performance which is crazy!

**Comment by Blinue** [comment]
I will add NIS and NVSharpen in v0.8, this is an example of how to use them https://github.com/Blinue/Magpie/issues/202#issuecomment-981352269

**Comment by Blinue** [comment]
LumaSharpen and FineSharp are nice sharpening effects, and they are available in v0.8. If you want better performance, use CAS instead
