### ISSUE TITLE
缩放配置名称过长导致主窗口右侧出现黑边

### ISSUE THREAD

**Issue by NeilTohno** [Blinue/Magpie#251]
### Magpie version 程序版本

0.7.1

### Windows version 系统版本

win10 21H1

### Related screenshot (optional) 相关截图（可选）

窗口右面多了一粗线

![20211227003316](https://user-images.githubusercontent.com/28284594/147414547-f91408cc-772e-4258-9880-01ab38589421.png)

正常的情况

![20211227003705](https://user-images.githubusercontent.com/28284594/147414598-f0a2cadc-5068-4e4f-8309-399d46866ea6.png)

### Reproduction steps 复现步骤

无

### Log files 日志文件

无

**Comment by Blinue** [comment]
主界面布局问题，如何修复现在还没头绪

**Comment by Blinue** [comment]
v0.10 中这个问题不存在了
