### ISSUE TITLE
Disabling and Enabling DirectFlip multiple times causes strange power usage behavior

### ISSUE THREAD

**Issue by Z-Dante** [Blinue/Magpie#256]
### Program(Game) 游戏名

PotPlayer (EVR), Rewrite+ (SiglusEngine)

### Capture method 捕获模式

GDI / DwmSharedSurface

### Other information (optional) 补充信息（可选）

Enabling and disabling the "Disable DirectFlip" option multiple times from the options causes strange power behavior. Eg. initially the power usage remains somewhat high but after enabling and disabling the DirectFlip option two or three times, the power usage seems to drop significantly. Tested on a RTX 2060 with driver 510.06; running on Windows 11 build 22000.376. The behavior seems to be reproducible.

Steps to Reproduce: 
1. Start up magpie with default settings 
2. Enable DirectFlip from options
3. Scale to FullScreen using GDI / DwmSharedSurface 
4. Disable DirectFlip
5. Scale to FullScreen again
6. Repeat steps 2 to 5 multiple times (2-3 times usually)

Magpie scaling should consume much less power now. And this state persists as long as the Magpie process keeps running. The behavior resets if Magpie is restarted. 

Before: 
![Before](https://user-images.githubusercontent.com/34379513/147873444-1b7f255a-13f6-46e6-9ed8-cf9fbdc5a144.png)
After:  
![After](https://user-images.githubusercontent.com/34379513/147873456-2ea5e512-2cb3-4576-8f14-69e287703d34.png)

Effect used for this testing was Anime4k_Restore_VL with on a 1080p source with no additional scaling
```json
  {
    "name": "Anime4K_Restore_VL",
    "effects": [
      {
        "effect": "Anime4K_Restore_VL"
      }
    ]
  }
```

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7798922/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7798923/Runtime.log)

**Comment by Blinue** [comment]
Tested it and the power usage drops after a while with or without the switching option. This may be related to the driver.
