### ISSUE TITLE
FPS Counter Incorrect?

### ISSUE THREAD

**Issue by tooelitepete** [Blinue/Magpie#257]
### Question 问题

Game running at 60 FPS (MSI Afterburner FPS counter), but Magpie FPS counter says 120.
Does the game run at 60 or 120 FPS then?
Just trying to understand how the FPS counter works exactly or what the point of it is

**Comment by hooke007** [comment]
internal fps counter only reflect the situation of magpie.

**Comment by mrpeterd** [comment]
> internal fps counter only reflect the situation of magpie. https://github.com/Blinue/Magpie/wiki/FAQ#magpie-%E4%B8%AD%E6%98%BE%E7%A4%BA%E7%9A%84%E5%B8%A7%E7%8E%87%E6%98%AF%E4%BB%80%E4%B9%88

So then what is the point of the Magpie FPS counter?

**Comment by Blinue** [comment]
It is an indicator of Magpie's performance, not of the game.
