### ISSUE TITLE
Parse failture when changing ScaleModels.json many times

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Blinue/Magpie#261]
### Magpie version 程序版本

8.0

### Windows version 系统版本

win10 21H1

### Related screenshot (optional) 相关截图（可选）

![изображение](https://user-images.githubusercontent.com/4449851/148138773-6d1a0b53-76dc-46bd-b5de-2f97d2fccc9d.png)

### Reproduction steps 复现步骤

Try changing CRT-Geom settings while Magpie is running (i use notepad++)
```
[
  {
    "name": "Lanczos",
    "effects": [
      {
        "effect": "Lanczos",
        "scale": [ -1, -1 ]
      },
      {
        "effect": "AdaptiveSharpen",
        "curveHeight": 0.3
      }
    ]
  },
  {
    "name": "FSR",
    "effects": [
      {
        "effect": "FSR_EASU",
        "scale": [ -1, -1 ]
      },
      {
        "effect": "FSR_RCAS",
        "sharpness": 0.87
      }
    ]
  },
  {
    "name": "FSRCNNX",
    "effects": [
      {
        "effect": "FSRCNNX"
      },
      {
        "effect": "Bicubic",
        "scale": [ -1, -1 ],
        "paramB": 0.0,
        "paramC": 0.5
      }
    ]
  },
  {
    "name": "ACNet",
    "effects": [
      {
        "effect": "ACNet"
      },
      {
        "effect": "Bicubic",
        "scale": [ -1, -1 ],
        "paramB": 0.0,
        "paramC": 0.5
      }
    ]
  },
  {
    "name": "Anime4K",
    "effects": [
      {
        "effect": "Anime4K_Upscale_Denoise_L"
      },
      {
        "effect": "Bicubic",
        "scale": [ -1, -1 ],
        "paramB": 0.0,
        "paramC": 0.5
      }
    ]
  },
  {
    "name": "RAVU",
    "effects": [
      {
        "effect": "RAVU_Zoom_R3",
        "scale": [ -1, -1 ]
      }
    ]
  },
  {
    "name": "CRT-Geom",
    "effects": [
      {
        "effect": "CRT_Geom",
        "scale": [ -1, -1 ],
        "curvature": 0,
        "CRTGamma": 1.5,
        "monitorGamma": 2.2,
        "cornerSize": 0.001,
		"lum": 0,
      }
    ]
  },
  {
    "name": "CRT_Easymode",
    "effects": [
      {
        "effect": "CRT_Easymode",
		"scale": [ -1, -1 ]
      }
    ]
  },
  {
    "name": "CRT_Hyllian",
    "effects": [
      {
        "effect": "CRT_Hyllian",
		"scale": [ -1, -1 ]
      }
    ]
  },
  {
    "name": "CRT_Lottes",
    "effects": [
      {
        "effect": "CRT_Lottes",
		"scale": [ -1, -1 ]
      }
    ]
  },
  {
    "name": "Integer Scale 2x",
    "effects": [
      {
        "effect": "Nearest",
        "scale": [ 2, 2 ]
      }
    ]
  },
  {
    "name": "Integer Scale 3x",
    "effects": [
      {
        "effect": "Nearest",
        "scale": [ 3, 3 ]
      }
    ]
  }
]
```

### Log files 日志文件

2022-01-05 02:40:50.0943|INFO|Magpie.ScaleModelManager|已引发 ScaleModelsChanged 事件
2022-01-05 02:40:50.0943|INFO|Magpie.ScaleModelManager|缩放配置文件已更改
2022-01-05 02:40:50.1102|ERROR|Magpie.ScaleModelManager|读取缩放配置失败|The process cannot access the file 'A:\magpie\ScaleModels.json' because it is being used by another process.
2022-01-05 02:40:50.1102|ERROR|Magpie.ScaleModelManager|解析缩放配置失败|Error reading JArray from JsonReader. Path '', line 0, position 0.
2022-01-05 02:40:50.1102|INFO|Magpie.ScaleModelManager|已引发 ScaleModelsChanged 事件
2022-01-05 02:42:44.2953|INFO|Magpie.App|当前日志级别：Info
2022-01-05 02:42:44.2953|INFO|Magpie.App|程序启动
	进程 ID：7364
	Magpie 版本：0.8.0.0
	OS 版本：10.0.19043.0
2022-01-05 02:42:44.2953|INFO|Magpie.App|当前语言：ru-RU
2022-01-05 02:42:44.2953|INFO|Magpie.App|已有实例，即将退出
2022-01-05 02:42:44.3045|INFO|Magpie.MainWindow|收到 WM_SHOWME 消息
2022-01-05 02:42:44.3071|INFO|Magpie.App|程序关闭
	进程 ID：7364

**Comment by Blinue** [comment]
Since notepad++ did not close the file after modification, Magpie cannot read it. I suggest you change the editor.

**Comment by 0x4E69676874466F78** [comment]
But why does the Magpie break when doing this?

**Comment by Blinue** [comment]
This is not an issue. Change the configuration once more (and close notepad++ if necessary) then Magpie will parse it correctly.

**Comment by 0x4E69676874466F78** [comment]
I think that the correct behavior is not to break the application if new parsing was not successful. 
Just create pop up an error message, but keep the list as it was.

**Comment by Blinue** [comment]
I don't want to create pop-ups, which would be intrusive to the user. As an alternative, Magpie will save the scaling mode when parsing fails, instead of resetting it to lanczos.

**Comment by 0x4E69676874466F78** [comment]
@Blinue but the user must know that Magpie could not parse.

> instead of resetting it to lanczos

There is not always a reset in Lanczos, instead Magpie shows as on the screenshot "<Parse Failture>" and no longer wants to parse (if I try change ScaleModels.json).

**Comment by Blinue** [comment]
![1](https://user-images.githubusercontent.com/34770031/148386350-d13c5723-eb80-44f8-b747-c64cbd448ffe.gif)

**Comment by 0x4E69676874466F78** [comment]
@Blinue I think just coincided that several times successively there was this error. My oversight.

**Comment by MuhammadUsmanMithani** [comment]
The error shows when the JSON format gets broken, and the file cannot be parsed to JSON correctly. It can happen from just adding a seemingly unharmful comma to even forgetting an end bracket. IMO, it is best for people to know how to format JSON  correctly before editing any JSON file themselves
