### ISSUE TITLE
无法裁剪 RPGMZ 窗口的标题栏

### ISSUE THREAD

**Issue by killer8224** [Blinue/Magpie#268]
### Question 问题

感谢各位大大的辛苦开发，最新的8.0非常好！

请问是否有办法去掉某些窗口的标题呢？
目前大部分的窗口都能正常去掉标题栏并且正常显示，测试了8.0新版的 “剪裁UWP窗口的标题栏”，但好像并没有起作用。主要是rpgmz制作的相关游戏的标题栏。
现有的版本，是否有方式通过配置去掉该标题栏呢？（例如纵向截断部分像素）

我在测试过程中，发现如果通过 兼容模式，以win7兼容模式运行的话，就能在全屏的时候去掉标题栏。但是程序本身没法长期稳定运行。

**Comment by Blinue** [comment]
正在调查

**Comment by Blinue** [comment]
RPG Maker MZ 制作的游戏使用 NW.js，本身是一个 Chromium 窗口。它的标题栏是自己绘制的

![image](https://user-images.githubusercontent.com/34770031/148649629-ecb11a8c-cc42-4ac3-8bf8-b4471fc967eb.png)

可以看到和原生窗口是有一定差别的。

把兼容模式设为 win8 可以强制使用原生窗口，Magpie 就可以正确的裁剪标题栏。没发现没法长期稳定运行的情况。

**Comment by killer8224** [comment]
> RPG Maker MZ 制作的游戏使用 NW.js，本身是一个 Chromium 窗口。它的标题栏是自己绘制的
> 
> ![image](https://user-images.githubusercontent.com/34770031/148649629-ecb11a8c-cc42-4ac3-8bf8-b4471fc967eb.png)
> 
> 可以看到和原生窗口是有一定差别的。
> 
> 把兼容模式设为 win8 可以强制使用原生窗口，Magpie 就可以正确的裁剪标题栏。没发现没法长期稳定运行的情况。

感谢大佬测试！！
我这边刚刚又重新验证了一下，我的系统是win10 20H2 19042.1415，测试的过程中发现，一部分游戏设置兼容性后能稳定运行，也确实可以去掉标题栏；但是另一部分游戏，设置win8 兼容模式依然不能长期的稳定运行，程序会陷入假死，声音正常，画面定格。并且无法正常关闭，需要手动结束相关进程。怀疑可能和游戏作者使用的脚本有关。

请问大佬，以现在的程序架构，针对这种自己绘制标题栏的程序，通过对原始画面做部分的截取来去掉标题栏，有可行性吗？

**Comment by Blinue** [comment]
这确实是一个很有用的功能，一些游戏的四周有边框 https://github.com/Blinue/Magpie/issues/168#issuecomment-990814142 ，还有一些游戏自己绘制标题栏。让用户自己决定如何裁剪吧

**Comment by killer8224** [comment]
> 这确实是一个很有用的功能，一些游戏的四周有边框 [#168 (comment)](https://github.com/Blinue/Magpie/issues/168#issuecomment-990814142) ，还有一些游戏自己绘制标题栏。让用户自己决定如何裁剪吧

太棒了！感谢大佬！！

**Comment by Blinue** [comment]
已实现此功能，将在v0.8.1中发布

**Comment by killer8224** [comment]
> 已实现此功能，将在v0.8.1中发布

哦哦哦哦，太棒了~~~大佬太给力了！！！
