### ISSUE TITLE
Full Screen FSR (Kingdoms of Amalaur Re-Reckoning)

### ISSUE THREAD

**Issue by IzzacSturnburg** [Blinue/Magpie#269]
### Question 问题

When using Full Screen, FSR does not work and it gives no errors even when turned on, how ever when using (Borderless Window) it works fine and turns on fine. Is there a way to run in full screen? Borderless Window lowers my frame rate in the game.
Magpie 0.8.0 was used in this test.

Update:  V7.0 (preview) works fine in full screen. Maybe there is something that can be used from this version to fix 8.0 for Full Screen gaming.

**Comment by Blinue** [comment]
You must have the game windowed to use Magpie. I don't know why v0.7 works, but that's not what Magpie was designed for.

**Comment by IzzacSturnburg** [comment]
> You must have the game windowed to use Magpie. I don't know why v0.7 works, but that's not what Magpie was designed for.

i appreciate the reply Blinue, what ever the mystery may be i really appreciate that it can do full screen. Gives me better fps to. whatever the case may be i really appreciate the feater in v0.70 preview I heard that AMD is gonna release RSR freely open to all games in the driver settings update in the Quarter 1 of this year. But according the to the press conference its only gonna work in full screen. Not sure if you heard about it but thought i'd post it. My lack of knowledge what RSR is, i'm still kinda confused between FSR and RSR but i'll look into it later. Appreciate all the effort and i'm a big fan of the project. thank you for your good charity in the dev line.

**Comment by Blinue** [comment]
Magpie, reshade and Lossless Scaling are not good solutions for FSR. I hope the drivers will support these technologies soon, be it FSR, NIS, RSR or anything else.
