### ISSUE TITLE
Upscaled FPS limited at 60, game FPS much higher

### ISSUE THREAD

**Issue by CoderStone** [Blinue/Magpie#27]
Magpie has a hard limit of 60 even on higher refresh rate monitors, is this on purpose?

**Comment by Blinue** [comment]
Magpie does not impose any limits on frame rates.

Frame rate of windowed games are limited by the OS, I don't think it's an issue of Magpie.

**Comment by CoderStone** [comment]
Ah, makes sense, Windows has inbuilt windowed mode vsync, from the DWM.
I just thought that magpie would disable this. 
Is that not possible at all?

**Comment by Blinue** [comment]
In Windows 10, DWM is forced on. As far as I know, there is no way to turn it off.

**Comment by mirh** [comment]
DWM is forced, yes, but in no way compositing should stall rendering. 
If your application decides to do otherwise, it's their problem.

**Comment by Blinue** [comment]
You can disable VSync now
