### ISSUE TITLE
添加需要应用Magpie的程序列表，侦测到列表中的程序运行，自动全屏。

### ISSUE THREAD

**Issue by scutxd** [Blinue/Magpie#271]
### Expected behavior 预期的功能

感谢作者的辛苦付出！

**Comment by Blinue** [comment]
#224 https://github.com/Blinue/Magpie/issues/166#issuecomment-939413505

暂时没有添加这个功能的计划。

**Comment by scutxd** [comment]
好的，原来已经有人提了，那我先把这个关掉。
