### ISSUE TITLE
Add TXAA and MSAA effects

### ISSUE THREAD

**Issue by MuhammadUsmanMithani** [Blinue/Magpie#272]
TXAA and MSAA are multiple methods of anti-aliasing that smoothen the look of games. MSAA costs performance quite a lot, but looks really smooth and perfectly smoothens out jagged edges. TXAA meanwhile, does not affect performance as much, but is a mix of both, MSAA and FXAA, and does not look as perfect, but still looks a lot better. Maybe add different effects like "MSAA_x8.hlsl" and "TXAA_x4.hlsl" and with degrading number, etc.etc.

**Comment by 0x4E69676874466F78** [comment]
It's impossible.
These methods of anti-aliasing require access to the internal render pipeline.

In theory it is possible to make a postprocessing filter similar to TAA but this is a difficult problem and it will add a latency.

**Comment by MuhammadUsmanMithani** [comment]
I mean, to somehow make it similar to the LosslessScaling method of MSAA and TAA

**Comment by Blinue** [comment]
These algorithms are not designed for the post-processing stage. Use reshade instead.

**Comment by MuhammadUsmanMithani** [comment]
ig ill close this
