### ISSUE TITLE
When using Xbox Game Bar (Win+G) together with Magpie, performance goes UP

### ISSUE THREAD

**Issue by CeeJayDK** [Blinue/Magpie#280]
### Program(Game) 游戏名

Trine 4

### Capture method 捕获模式

Graphics Capture

### Other information (optional) 补充信息（可选）

I'm not complaining, I just find it strange that when you play Trine 4 with Magpie and FSR scaling, performance improves when you also use the Xbox Game Bar. I got around 10 extra fps from 41 to 51 fps.

To get the performance improvement Xbox Game Bar needs to display something - anything. A simple FPS counter will do.

I figured this would be useful information to help the developer improve performance of Magpie further.

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7899868/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7899869/Runtime.log)

**Comment by Blinue** [comment]
Thanks for report. Turning on Options->Advanced->Disable DirectFlip should achieve the same effect.

**Comment by CeeJayDK** [comment]
It doesn't.

When I turn on Options->Advanced->Disable DirectFlip performance drops to 36 fps.
I'm getting better performance without that, but with the Game Bar doing something.

**Comment by Blinue** [comment]
Okay, thanks for the report. I will try it myself.

**Comment by drdaxxy** [comment]
For me, Game Bar appears to produce the same performance increase as unchecking Vsync / 垂直同步.
Going by the logs, OP seems to have that disabled in the first place, though...
