### ISSUE TITLE
只有FSR有效果 其他效果沒有出來

### ISSUE THREAD

**Issue by s3327445** [Blinue/Magpie#282]
我是用10700+1063配備 win10 21h1 顯示驅動471.96
用瀏覽器 及potplayer測試 只有FSR跟LANCZO有效果 其他效果沒有出來  但gpu是有在吃效能的 
另外的問題是NIS 及XBRZ要到那邊開啓呢？
 anime4k看shader有很多選項是要怎麽切換呢？
謝謝

**Comment by Blinue** [comment]
> 用瀏覽器 及potplayer測試 只有FSR跟LANCZO有效果 其他效果沒有出來 但gpu是有在吃效能的

“没有出来”指什么？请提供截图和日志

> 另外的問題是NIS 及XBRZ要到那邊開啓呢？
anime4k看shader有很多選項是要怎麽切換呢？

[自定义缩放配置](https://github.com/Blinue/Magpie/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E6%94%BE%E9%85%8D%E7%BD%AE)

**Comment by s3327445** [comment]
原來是要修改json檔
magpie我有用成功了 謝謝你

倒是想試試看mpv的shader更好的效果 折騰了好久都失敗 想問你如果用mpv+glsl效果會比magpie的4kanime restore vl要好嗎？

**Comment by Blinue** [comment]
理论上效果相同，Anime4K 是 1:1 的移植

**Comment by s3327445** [comment]
1.再請問Gan系列有比cnn系列強很多嗎 想看看gan ul甚至是uul 有沒有比cnn系列強 

2.我沒有4k螢幕 不太懂 upscale 跟 reatore差別在那裡 我在rhd螢幕下 感覺同等級（s or m  or l）下不會差很多（ gan 對比原生）

**Comment by Blinue** [comment]
GAN 变体处于实验阶段，相比 CNN 可以保留更多细节。restore 可以还原线条，去除伪影。这方面的问题请向 [Anime4K](https://github.com/bloc97/Anime4K) 询问
