### ISSUE TITLE
建议移植 nnedi3

### ISSUE THREAD

**Issue by NeilTohno** [Blinue/Magpie#283]
### Expected behavior 预期的功能

感觉适合现代像素风格游戏、Horror games 、解密游戏

https://github.com/bjin/mpv-prescalers/tree/master/compute

nnedi3-nns128-win8x4.hook
nnedi3-nns256-win8x4.hook

现代像素风格游戏，虽然是 2D，但是画面图像、画面特效复杂，所以不适合现有的效果器

**Comment by Blinue** [comment]
正在调查

**Comment by NeilTohno** [comment]
> 正在调查


提一句 RAVU，我试了一下下面的参数，这个修改画面太多了（带特定的锐化和细节增强），基本不适合二次元类画面
      {
        "effect": "RAVU_Zoom_R3",
        "scale" : [ -1, -1 ]
      }

RAVU 的文档
https://ai.googleblog.com/2016/11/enhance-raisr-sharp-images-with-machine.html

**Comment by Blinue** [comment]
这个着色器效果很不错，表现均衡，我觉得可以替代 Lanczos，个人认为后面加个锐化步骤更好。我会在下个版本移植它

> 提一句 RAVU，我试了一下下面的参数，这个修改画面太多了（带特定的锐化和细节增强），基本不适合二次元类画面
{
"effect": "RAVU_Zoom_R3",
"scale" : [ -1, -1 ]
}

当然，它适合其他场景...

**Comment by Blinue** [comment]
我计划在下个版本移除 RAVU 预设，这个效果相比其他效果没有明显优势。感觉没有人在用它

**Comment by octopushugger** [comment]
I still use RAVU sometimes. I second the addition of nnedi3, its built-in anti-aliasing would be very useful. The nns16-win8x4 and nns64-win8x6 versions are probably what I'd use. The 128 and higher versions have so little difference they're almost never worth the extra performance cost. Moving from win8x4 to win8x6 is less taxing than going up to 128+ and can yield more noticeable improvement.

**Comment by Blinue** [comment]
已移植 nnedi3_nns16_win8x4 和 nnedi3_nns64_win8x6

nnedi3_nns64_win8x6 比 nnedi3_nns16_win8x4 慢 5 倍，但画面没有肉眼可见的改进。

**Comment by hooke007** [comment]
nnedi3的glsl版本基本只能靠神经元翻倍实现效果提升

**Comment by Blinue** [comment]
我在 mpv 里测试过所有变体，甚至是更复杂的版本也没有肉眼可见的质量提升，当前也有可能是我测试的源不适合 nnedi3。nns64已经非常慢了，在我的电脑上用时 10ms，128 基本上没有实用性。

**Comment by hooke007** [comment]
> 没有肉眼可见的质量提升

这是正常的，压制组用nnedi3作为升频手段的理由就是它的特性保持原始质感而不是提升观感（

**Comment by hooke007** [comment]
这版本依旧继承了glsl版的像素偏移，但不算大问题

**Comment by Blinue** [comment]
这个是实现原理的限制，没办法解决

**Comment by NeilTohno** [comment]
？额，这个不是都建议使用 win8x4，为什么移植 win8x6啊

**Comment by Blinue** [comment]
这见仁见智吧，我看不出区别来
