### ISSUE TITLE
Auto-Updater

### ISSUE THREAD

**Issue by ziplock9000** [Blinue/Magpie#287]
### Expected behavior 预期的功能

It would be excellent if the app auto-updated or at least prompted the user when there's a new version and then by clicking it updates.

**Comment by Blinue** [comment]
This feature is in the roadmap. I plan to implement it when I rework the UI.

**Comment by NeilTohno** [comment]
> This feature is in the roadmap. I plan to implement it when I rework the UI.

建议大佬看一下这个

https://greasyfork.org/zh-CN/scripts/412245-github-增强-高速下载

考虑一下镜像地址更新啥的

**Comment by Blinue** [comment]
Implemented in v0.10 🎉
