### ISSUE TITLE
开启和关闭的提示

### ISSUE THREAD

**Issue by seong1995** [Blinue/Magpie#290]
### Expected behavior 预期的功能

目前我遇到一个难点。

点下快捷键后不知道是什么状态，希望有一个功能就是点下快捷键后显示是开启，还是关闭。

目前我的解决办法是显示FPS，但我不需要知道FPS。

**Comment by Blinue** [comment]
> 点下快捷键后不知道是什么状态，希望有一个功能就是点下快捷键后显示是开启，还是关闭。

有没有进入全屏状态应该是一目了然的，”不知道是什么状态“是什么意思？

**Comment by seong1995** [comment]
理论上可以看见差异，但是还是需要观察啊。

因为我经常切换窗口，所以回到游戏会点一下快捷键，每一次都要观察一下会很不方便。

如果有在点击快捷键后显示以开启那就容易多了

**Comment by Blinue** [comment]
方便的话请提供截图说明。如果经常切换窗口推荐打开”源窗口重获焦点时自动恢复全屏“

**Comment by seong1995** [comment]
“源窗口重获焦点时自动恢复全屏”

有开这个，但是很不方便，因为我需要点开始菜单和任务栏的图表，开了就看不见鼠标，很麻烦操作。

所以我现在如果是需要点主要屏幕开始菜单和任务栏会先关掉，回去游戏的时候再点一次。

![image](https://user-images.githubusercontent.com/69965367/150714019-d98812bf-b245-4c6c-91d5-b3af2b38d90e.png)
![image](https://user-images.githubusercontent.com/69965367/150714069-db5ea373-de5c-421b-8cbd-ef1fba344649.png)

图片四方形表示屏幕，就是点击快捷键时候现实软件是开启还是关闭而已。

这样就很确定是开启还是关闭了。

**Comment by Blinue** [comment]
> 理论上可以看见差异，但是还是需要观察啊。

什么时候已经开启全屏了却不容易观察到？请在这方面提供截图

**Comment by seong1995** [comment]
我的游戏本来是无边框全屏啊。

观察软件是否打开了我只能看游戏里面的画质，有时候点几次快捷键看看差异。

所以我才说如果有弹出开启还是关闭的提示会方便很多，可以很肯定是开启还是关闭的状态啊。

**Comment by seong1995** [comment]
截图应该是没办法很好说明我遇到的问题，如果有需要我可以做一个视频解说一下情况，这样应该会比较容易明白。

我用magpie是用FSR把游戏里面的细节变得更好，更容易发现在草丛里面和很远的敌人。

**Comment by Blinue** [comment]
Magpie 只能用用于**窗口化**的游戏 https://github.com/Blinue/Magpie/issues/269#issuecomment-1008228779
