### ISSUE TITLE
"missing framework"

### ISSUE THREAD

**Issue by zby1211** [Blinue/Magpie#291]
### Magpie version 程序版本

v0.8.1

### Windows version 系统版本

win11 2022

### Related screenshot (optional) 相关截图（可选）

![Uploading 屏幕截图 2022-01-24 144411.png…]()

### Reproduction steps 复现步骤

一开始只是缺.net，但是装完.net就变成这样
framework的话因为版本低了（4.8）所以装不了
还有，这是Parallels Desktop的虚拟机

### Log files 日志文件

然而一条log也没有

**Comment by zby1211** [comment]
![屏幕截图 2022-01-24 144411](https://user-images.githubusercontent.com/54210771/150735141-d181a30e-bc92-4292-8816-dc29a1185a68.png)
好耶图片挂了（

**Comment by Blinue** [comment]
[.NET 6 Desktop 运行时](https://download.visualstudio.microsoft.com/download/pr/bf058765-6f71-4971-aee1-15229d8bfb3e/c3366e6b74bec066487cd643f915274d/windowsdesktop-runtime-6.0.1-win-x64.exe)

**Comment by zby1211** [comment]
不好意思，似乎只是我装错了版本。
