### ISSUE TITLE
VN Kami no Ue no Mahoutsukai borders

### ISSUE THREAD

**Issue by Geniusssmit** [Blinue/Magpie#294]
### Magpie version 程序版本

Magpie_Auto_Build_501081c

### Windows version 系统版本

win10 1809

### Related screenshot (optional) 相关截图（可选）

![紙の上の魔法使い_Gfekqdsqpr](https://user-images.githubusercontent.com/24941285/151670578-8c0a3607-3c3e-4db7-bdab-54b7fdccc62d.jpg)
![Xdd6YEy4i1](https://user-images.githubusercontent.com/24941285/151670580-723e8ae5-25f0-4357-9e3d-8a57858ae658.jpg)

### Reproduction steps 复现步骤

Start the game
Start scaling
As you can see, terrible borders won't disappear

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7964204/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7964205/Runtime.log)

**Comment by Geniusssmit** [comment]
same issue with Magpie_dev_5eb4ff6 version

**Comment by 0x4E69676874466F78** [comment]
Use Custom Cropping.

**Comment by Geniusssmit** [comment]
how?

**Comment by 0x4E69676874466F78** [comment]
> how?

Options -> 
![изображение](https://user-images.githubusercontent.com/4449851/151694607-a15970b9-d21b-413e-a16c-f009958de832.png)

**Comment by Geniusssmit** [comment]
Thank you, that worked perfectly!
