### ISSUE TITLE
Choosing a target resolution for FSR instead of changing desktop resolution

### ISSUE THREAD

**Issue by onyxtrooper** [Blinue/Magpie#296]
### Expected behavior 预期的功能

Hello and thank you very much for your work. I love this program!

Is what I said in the title possible? For example, I have a 1440p display and I use 2x DSR on every game, which is 3620x2036 in resolution. If I change my desktop resolution to this, Magpie will upscale the games without any issues but changing desktop resolution every time I open a game is a bit frustrating.

Can we get an option to set a fixed target resolution please? Or is there a way to do that already?

**Comment by motoleon** [comment]
It is the same query that i have

**Comment by motoleon** [comment]
https://github.com/Blinue/Magpie/issues/278

**Comment by Blinue** [comment]
Go to #278 for further discussion
