### ISSUE TITLE
游戏帧率不明原因下降

### ISSUE THREAD

**Issue by XiaofengdiZhu** [Blinue/Magpie#297]
### Program(Game) 游戏名

Rewrite+

### Capture method 捕获模式

Desktop Duplication

### Other information (optional) 补充信息（可选）

回到家只能用核显了~游戏标准720p，显示器1920*1200 60hz
使用Anime4K_Upscale_S+Nearest算法，不限制帧率，核显跑满，能跑到120帧，但游戏会从60帧下降到55帧；限制magpie帧率到60，核显占用率还是100%，但游戏仍然固执地下降到55帧
以下是更多测试，都是感觉的平均值，前两个限制到60后，游戏都是55帧上下
Nearest换成Bicubic，Magpie90，游戏51（莫名最低）
再换成Jinc，Magpie65，游戏53
再换成Lanczos，Magpie52，游戏52
————
单独使用以下算法，有：
Nearest，Magpie400，游戏60
Bicubic，Magpie160，游戏60
Jinc，Magpie120，游戏60
Lanczos，Magpie92，游戏**56**
FSR_EASU+FSR_RCAS，Magpie160，游戏60
————
我已经搞不懂了……只能请开发人员看看
还有个小bug：`"scale": [ -1, -1 ]`，窗口和屏幕比例不一致时，会水平居中但不会垂直居中

### Log files 日志文件

[Runtime.log](https://github.com/Blinue/Magpie/files/7980206/Runtime.log)

**Comment by Blinue** [comment]
desktop duplication 捕获模式比较特殊，fps和占用的系统资源不成正比。对于Anime4K_Upscale_S+Nearest，120fps和60fps占用的资源几乎相同

**Comment by XiaofengdiZhu** [comment]
> desktop duplication 捕获模式比较特殊，fps和占用的系统资源不成正比。对于Anime4K_Upscale_S+Nearest，120fps和60fps占用的资源几乎相同

又测了一下其他几种捕获方式：
Anime4K_Upscale_S + Jinc
捕获方式，游戏（主界面），Magpie
Graphics Capture，51~56（一直波动），46
Desktop Dulplication，53，65
GDI，52，52
DwmSharedSurface，36~44，55
可以说，Desktop Dulplication已经是效率最高的了……
缩小算法退一步成Bicubic，四种捕获方式仍然都不能两边都稳60帧，唉

**Comment by Blinue** [comment]
我正在做一些工作优化性能，希望可以降低magpie的使用门槛。

**Comment by XiaofengdiZhu** [comment]
> 我正在做一些工作优化性能，希望可以降低magpie的使用门槛。

例如实现60帧只要120帧的一半性能😂

**Comment by Blinue** [comment]
Desktop Duplication不比其他捕获模式更快，它的fps无法反应出性能，这是因为它包含了一个特殊的优化。
最终决定画面流畅度的还是显卡性能，一般的核显想流畅使用anime4k是不现实的，必须在画面或流畅度上做出牺牲

**Comment by Blinue** [comment]
这个功能已在计划中
