### ISSUE TITLE
1 : 1 upscale visual improvement

### ISSUE THREAD

**Issue by Tzugimaa** [Blinue/Magpie#299]
### Question 问题

Do upscaling algorithms like lanczos, jinc, fsr improve visual at all with 1:1 upscale(?) e.g. 1080p to 1080p or 1440p to 1440p?

**Comment by hooke007** [comment]
Don't you think it was a weird question...
if no resizing, how could it do scaling?

**Comment by 0x4E69676874466F78** [comment]
@hooke007 he probably means super sampling.
@Tzugimaa those algorithms that do not create new details do not improve the picture, but rather you get very small distorted (depends on the downsampling algorithm).

**Comment by Tzugimaa** [comment]
Thank you for the answer!
yes it was kinda weird question haha.
