### ISSUE TITLE
It does not switch to full screen on a 32:9 monitor.

### ISSUE THREAD

**Issue by HARUONN** [Blinue/Magpie#30]
Thank you for the good program.

If you use Magpie for games with a resolution of 3840x1080 (32:9), the full screen will not be applied with an EndDraw (HRESULT=0x88990027) error. However, most 16:9 or 21:9 resolution programs work fine.
If possible, I would also like the 32:9 ratio to be applied.

In addition, my monitor has a resolution of 5120x1440.

**Comment by Blinue** [comment]
Check out #17

**Comment by HARUONN** [comment]
Oh...thank you for your quick reply. Let me check the contents.
