### ISSUE TITLE
Godot Super Scaling

### ISSUE THREAD

**Issue by Tzugimaa** [Blinue/Magpie#302]
### Question 问题

Would it be good to add Godot Super Scaling to Magpie?

From what I have tried to translate godot to hlsl with my amateur skill, the performance is slightly higher than fsr.
Tested in World War Z from 1080p to 1440p the score are :

![FSR](https://user-images.githubusercontent.com/4981077/152634777-6ba3d6e4-802c-471f-9ec8-81c25705780e.png)
FSR : 6528

![Godot](https://user-images.githubusercontent.com/4981077/152634790-cd6304d7-2cab-4146-8f85-44f9e5d5439b.png)
Godot : 6638

CPU : AMD Ryzen 5800H
GPU : Nvidia 3060 6 GB Max-Q
RAM : 32 GB

**Comment by Blinue** [comment]
Thank you, we welcome any contribution. Post a pull request and you are a contributor!
