### ISSUE TITLE
Crash with every setting combination on mac bootcamp.

### ISSUE THREAD

**Issue by kato-megumi** [Blinue/Magpie#31]
Hi
Program worked excellently on my desktop computer, but refuse to work on my macbook running bootcamp.
It just silently crash no matter setting combination (WinRT or GDI, Injection or not).

Is there any way I can check and/or debug the problem?

Spec is MacBook 16inch (2019) 9980HK 5300M

**Comment by CoderStone** [comment]
> Hi
> Program worked excellently on my desktop computer, but refuse to work on my macbook running bootcamp.
> It just silently crash no matter setting combination (WinRT or GDI, Injection or not).
> 
> Is there any way I can check and/or debug the problem?
> 
> Spec is MacBook 16inch (2019) 9980HK 5300M

Try building it yourself, I had a similar issue but building it on the laptop itself worked just fine.

**Comment by kato-megumi** [comment]
@CoderStone thank you for your advice. After try to build myseft, it work flawlessly.
