### ISSUE TITLE
[Request] Intel Devices Fix for Games on Portrait Mode

### ISSUE THREAD

**Issue by shinra358** [Blinue/Magpie#315]
### Expected behavior 预期的功能

On  some intel devices like gpd win 3, some games will not start even in window mode because they try to start in portrait mode instead of landscape mode. The game reads the resolution backwards so the game doesnt start like Final Fantasy 12 on steam. Gamescope has a fix for these types of games. Can the solution be added to magpie as well?

**Comment by Blinue** [comment]
I think this should be taken cared by the OS or the launcher. Is there anything Magpie can do?
