### ISSUE TITLE
Magpie has a chance to cause the mouse cursor to become invisible when alt+tabbing 

### ISSUE THREAD

**Issue by LOuroboros** [Blinue/Magpie#318]
### Magpie version 程序版本

v0.8.1

### Windows version 系统版本

v21H2 (b19044.1415)

### Reproduction steps 复现步骤

Specifically, this has happened to me when using Magpie in "Danganronpa: Trigger Happy Havoc".
https://store.steampowered.com/app/413410/Danganronpa_Trigger_Happy_Havoc/

1) Boot up the game and apply a filter with Magpie. In my case, I'm using `Anime4K_Upscale_L` combined with `Jinc`.

I'm not sure if it's relevant, but game configuration wise, I'm playing on Windowed Mode at 1280x720 resolution.

2) Alt+tab in and out of the game until you notice your cursor no longer shows up on Windows' desktop.

3) Deal with it.

Just kidding. You can execute `taskkill /im magpie.exe /f` from an elevated command prompt to get your cursor back.

After that, you can open Magpie and apply a filter again, and keep playing normally.

### Log files 日志文件

[Runtime.log](https://github.com/Blinue/Magpie/files/8092634/Runtime.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/8092635/Magpie.log)
[Runtime.1.log](https://github.com/Blinue/Magpie/files/8092636/Runtime.1.log)

**Comment by Blinue** [comment]
The logs did not record any errors. Does this error happen often?

**Comment by LOuroboros** [comment]
> Does this error happen often?

Well, it can happen often if you alt+tab somewhat frequently.

> BTW, closing Magpie or toggling fullscreen again should also resolve this error.

The latter didn't work, and the former is accomplished by using `taskkill /im magpie.exe /f` from an elevanted command prompt, which thankfully doesn't need the user to see their cursor as it can be performed by doing Win Key + R, typing "cmd" and then pressing Shift+Enter :eyes:

**Comment by Blinue** [comment]
https://github.com/Blinue/Magpie/commit/c8c099a740aec272b3157d91c04be56e195eabc6 seems to fix this. If you still encounter this bug in the latest version, reopen this issue.
