### ISSUE TITLE
Mouse cursors, in dual screen, accross monitors when it should be blocked in the game screen

### ISSUE THREAD

**Issue by mouarfff** [Blinue/Magpie#321]
### Magpie version 程序版本

8.1

### Windows version 系统版本

win10 21H2

### Related screenshot (optional) 相关截图（可选）

i tried force theses parameters :
Confine cursor in 3d games
Simulate exclusive screen
 but nothing change.
When i play game, if i turn right (where is my second monitor) when i walk in a FPS, the windows cursor's mouse go to the right screen and if i clic the game AND the desktop will react
it's impossible to play in this condition

### Reproduction steps 复现步骤

have a dual screen (radeon rx5700xt) just install magpie, launch star citizen (windowed borderless mode) and move mouse

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/8115618/Magpie.log)
[Runtime.1.log](https://github.com/Blinue/Magpie/files/8115624/Runtime.1.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/8115626/Runtime.log)

**Comment by Blinue** [comment]
Thanks for your feedback, I will fix it soon.

When you enable "Confine cursor in 3D games", the cursor will be restricted to the current monitor.

**Comment by mouarfff** [comment]
> hen "Confine cursor in 3D games" is enabled, the cursor will be restricted to the current monitor.

No, i said in my message, this option don't change anything for me.

The only one workarround is installing this https://12noon.com/?page_id=641
and script a bat to save a special configuration screen (disposition wich it's almost impossible for the mouse to accross the second screens, with a diagonal disposition) and add another script to replace in normal configuration (horizontal disposition)

**Comment by Ning0627** [comment]
作者您好!我与他有相同的问题存在.

**Comment by mouarfff** [comment]
我希望这个提示能帮助你
I hope this tip helped you

**Comment by Blinue** [comment]
I've changed the behavior of "Confine cursor in 3D games" so that it prevents the cursor from going to other screens. This fix will be available in the next release.

**Comment by mouarfff** [comment]
> I've changed the behavior of "Confine cursor in 3D games" so that it prevents the cursor from going to other screens. This fix will be available in the next release.

thank you very much !

**Comment by Blinue** [comment]
> 你好，请问一下这个选项是不是实际上和“3D游戏”并没有关系？

这个选项最初是为了解决 #140 

Magpie 在进入全屏时会尝试将光标限制在窗口内，但这个操作在一些 3D 游戏中会失败，因为游戏本身就已经限制了光标。现在的问题是，还有一些3D游戏并不限制光标，只是将光标隐藏了，这就导致光标会跨越屏幕边界（从 v0.8.0 开始支持在限制光标的同时允许光标跨越显示器）。

在修复后这个选项的行为是：
1. 在每一帧都尝试限制光标，这可以解决 #140 
2. 禁止光标跨越显示器，即始终将光标限制在游戏窗口内，这可以解决此 issue 的问题

结论是：3D 游戏的光标行为特殊，需要特别处理。在 3D 游戏中使用 Magpie 时推荐打开此选项

**Comment by Blinue** [comment]
这个选项只改变鼠标的行为。Magpie 不关心游戏是什么类型的（以及它是不是游戏）
