### ISSUE TITLE
Start as Task

### ISSUE THREAD

**Issue by shinra358** [Blinue/Magpie#327]
### Expected behavior 预期的功能

For it to autostart with windows without having to manually press YES on the UAC prompt. Starting as task would prevent the UAC prompt from showing up but still allow UAC to continue working.

**Comment by Blinue** [comment]
Can you elaborate on this technique?

**Comment by shinra358** [comment]
manual just for knowledge:
https://www-howtogeek-com.cdn.ampproject.org/v/s/www.howtogeek.com/123393/how-to-automatically-run-programs-and-set-reminders-with-the-windows-task-scheduler/amp/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQKKAFQArABIIACAw%3D%3D#aoh=16458921079228&referrer=https%3A%2F%2Fwww.google.com&amp_tf=From%20%251%24s&ampshare=https%3A%2F%2Fwww.howtogeek.com%2F123393%2Fhow-to-automatically-run-programs-and-set-reminders-with-the-windows-task-scheduler%2F

A program you could look at that has this feature is ds4windows ryochan on
github.

also heres an example from ahk:
https://www.autohotkey.com/docs/commands/Run.htm#RunAs

visual studio:
https://sdivakarrajesh.medium.com/automating-task-to-run-on-startup-in-vscode-fe30d7f99454

**Comment by Blinue** [comment]
Seems to work, thanks for the suggestion.

**Comment by shinra358** [comment]
You're welcome!

**Comment by Blinue** [comment]
I haven't implemented this feature yet, but it is in the roadmap.

**Comment by Blinue** [comment]
Implemented in v0.10 🎉

**Comment by shinra358** [comment]
But it starts maximized. We need it to start minimized in the notification
area so we dont have to do it manually on every start up.

**Comment by Blinue** [comment]
You should turn on "Minimize to system tray at startup".

**Comment by shinra358** [comment]
doesnt work. starts maximized anyway. we know about the options.
