### ISSUE TITLE
GraphicsCaptureFrameSource::_OnFrameArrived LeaveCriticalSection(&_cs); Crash

### ISSUE THREAD

**Issue by Pijulin** [Blinue/Magpie#331]
### Magpie version 程序版本

0.8.1

### Windows version 系统版本

Windows 10 21H2

### Related screenshot (optional) 相关截图（可选）

使用GraphicsCapture

GraphicsCaptureFrameSource::_OnFrameArrived
中的LeaveCriticalSection(&_cs);崩溃

建议 Update中用额外状态保存_newFrameArrived
FrameSourceBase::UpdateState GraphicsCaptureFrameSource::Update() {
	// 每次睡眠 1 毫秒等待新帧到达，防止 CPU 占用过高
	BOOL update = FALSE;

	EnterCriticalSection(&_cs);

	if (!_newFrameArrived) {
		SleepConditionVariableCS(&_cv, &_cs, 1);
	}

	if (_newFrameArrived) {
		_newFrameArrived = false;
		update = TRUE;
	}

	LeaveCriticalSection(&_cs);

	if (update) {
		winrt::Direct3D11CaptureFrame frame = _captureFramePool.TryGetNextFrame();
		if (!frame) {
			// 缓冲池没有帧，不应发生此情况
			assert(false);

			return UpdateState::Waiting;
		}

		// 从帧获取 IDXGISurface
		winrt::IDirect3DSurface d3dSurface = frame.Surface();

		winrt::com_ptr<::Windows::Graphics::DirectX::Direct3D11::IDirect3DDxgiInterfaceAccess> dxgiInterfaceAccess(
			d3dSurface.as<::Windows::Graphics::DirectX::Direct3D11::IDirect3DDxgiInterfaceAccess>()
		);

		ComPtr<ID3D11Texture2D> withFrame;
		HRESULT hr = dxgiInterfaceAccess->GetInterface(IID_PPV_ARGS(&withFrame));
		if (FAILED(hr)) {
			SPDLOG_LOGGER_ERROR(logger, MakeComErrorMsg("从获取 IDirect3DSurface 获取 ID3D11Texture2D 失败", hr));
			return UpdateState::Error;
		}

		App::GetInstance().GetRenderer().GetD3DDC()
			->CopySubresourceRegion(_output.Get(), 0, 0, 0, 0, withFrame.Get(), 0, &_frameBox);

		return UpdateState::NewFrame;
	} else {
		return UpdateState::Waiting;
	}
}

经过连续50次开启与退出没有崩溃

### Reproduction steps 复现步骤

多次进行开启与退出操作，捕获游戏时出现

### Log files 日志文件

捕获游戏时出现

**Comment by Blinue** [comment]
如果你认为这里有一个bug，请描述一下这个bug的成因以及你的修改的理由。如果你想修改代码，请提交 pull request
