### ISSUE TITLE
mega/compute分支 双显示器时，不勾选，在3D游戏中限制光标，退出时会崩溃

### ISSUE THREAD

**Issue by Pijulin** [Blinue/Magpie#335]
### Magpie version 程序版本

mega/compute

### Windows version 系统版本

Windows 10 21H2

### Reproduction steps 复现步骤

双显示器时，不勾选，在3D游戏中限制光标，退出时会崩溃

### Log files 日志文件

[GPPMagicGlassRuntime.log](https://github.com/Blinue/Magpie/files/8284002/GPPMagicGlassRuntime.log)

**Comment by Blinue** [comment]
已修复，感谢反馈。此分支还在开发中，请在了解风险的情况下使用。

**Comment by Blinue** [comment]
我注意到日志文件名被改了，是不是在进行二次开发？请确保遵守 GPL 协议。

**Comment by Pijulin** [comment]
是的哈 在进行二次开发，我将在这边完成后进行开源，确保遵守GPL协议

**Comment by Blinue** [comment]
对开源社区的任何贡献都是欢迎的，但我不会让贡献者们的劳动成果被闭源软件窃取，这是我选择 GPL 的初衷。

在闭源软件中直接使用 Magpie 的源码或者静态/动态链接都是不允许的（通过操作系统调用可执行文件不在此列）。如果程序的一部分使用了 Magpie 的功能，整个程序都应该遵守 GPL。

最后，感谢你在本项目上花费的时间。当你有了更多提交，我会把你加入贡献者列表。

**Comment by Pijulin** [comment]
我已经将对MagpieRuntime部分封装为服务全部开源在我的GitHub上
