### ISSUE TITLE
Possible to use with Chrome & comic readers?

### ISSUE THREAD

**Issue by kanjieater** [Blinue/Magpie#336]
### Question 问题

I use a comic reader called Komga https://github.com/gotson/komga on my desktop.
I view it through the browser, so Chrome.

I was hoping that I could use magpie to auto upscale the images, but when I try to use it, it shows no difference in chrome. Here's an image to test:
![image](https://user-images.githubusercontent.com/32607317/159041050-89747e74-334f-465d-91a3-62c0420fc2bb.png)
Can you open this image in a new tab and get Magpie to clean it up?

I expected magpie to clean up the image, but none of the settings made this image any cleaner.

Can we use magpie in Chrome?

**Comment by Onurtag** [comment]
Yes, it is possible to use magpie with chrome. But you will have to use an addon to get rid of the tabs and the urlbar.  

1. First of all you should change the default magpie keybind from F11 to something else.  F11 triggers chrome's fullscreen view but magpie requires the window to be smaller than fullscreen.   
2. Install a popup / picture in picture extension like this to get rid of chrome's ui (tabs, adress bar etc.).  
I haven't tested [this extension](https://chrome.google.com/webstore/detail/separate-window/cbgkkbaghihhnaeabfcmmglhnfkfnpon) on latest chrome but you can try that one.   
3. Resize your browser window and make it small enough that the blurry image looks good (maybe around ~720p for your image)  
4. Enable magpie with the scaler you want to use (FSRCNNX, ACNet, Anime4K etc.)  

Let us know if it works.
