### ISSUE TITLE
打开没有任何反应

### ISSUE THREAD

**Issue by deadblue0910** [Blinue/Magpie#337]
### Magpie version 程序版本

0.8.1 

### Windows version 系统版本

win10 21h2

### Reproduction steps 复现步骤

尝试过重新安装MSVC 运行库，修复framework，以管理员运行无任何反应，也没有错误提示，没有生成log文件。0.7.1,0.6.1同样情况

### Log files 日志文件

无

**Comment by Blinue** [comment]
进入 事件查看器->Windows日志->应用程序 查看系统记录的错误

**Comment by deadblue0910** [comment]
日志没有变化
![Uploading Snipaste_2022-03-19_22-37-59.png…]()

**Comment by deadblue0910** [comment]
![Snipaste_2022-03-19_22-37-59](https://user-images.githubusercontent.com/48860218/159125510-e8be1123-db68-4473-8d43-c9f1d19a5c21.png)

**Comment by Blinue** [comment]
从表现看 Magpie 没有启动。操作系统没有记录错误，说明并不是缺少运行时框架。我怀疑是你的操作系统环境问题，比如杀毒软件。

**Comment by Blinue** [comment]
建议更新.NET运行时。如果你在最新版本上遇到这个问题，请重新打开此 issue
