### ISSUE TITLE
Can't Install Magpie.

### ISSUE THREAD

**Issue by dhung2010** [Blinue/Magpie#338]
I am a really, really bad person in stuffs like this. The problems that I have when trying to install Magpie are:
-When I try to build `CONAN_INSTALL`, there are 7 errors, do they cause anything?
-I don't know how to pack `Magpie`, can you please help me?
-How do I use it? Do I just open visual studio everytime and press the green button there?

Thanks a ton if you can help me?
P/S: Don't know if my grammar is good or not. Hopefully, it is.

**Comment by Blinue** [comment]
Download the binaries [here](https://github.com/Blinue/Magpie/releases).

**Comment by dhung2010** [comment]
What do I do with the _binaries_?

**Comment by dhung2010** [comment]
um, ok, im dum. I was messing with source code. Thanks a lot!!
