### ISSUE TITLE
玩糖调（一个galgame）时无法使用独显

### ISSUE THREAD

**Issue by szlysms** [Blinue/Magpie#339]
### Magpie version 程序版本

0.8.1

### Windows version 系统版本

版本	Windows 10 专业工作站版 版本号	21H2 操作系统内部版本	19044.1586 体验	Windows Feature Experience Pack 120.2212.4170.0

### Related screenshot (optional) 相关截图（可选）

![Snipaste_2022-03-22_09-04-36](https://user-images.githubusercontent.com/99026228/159387239-535a6f23-0c13-42dc-a8e8-64c3d798fb21.png)

### **第一次**：
打开糖调（我的游戏
运行magpie（animate 4k，desk top duplication)
按下快捷键
出错
### 第二次：
（PS：因为不想再经历没有鼠标光标瞎点瞎抢救的情况所以这部分没有日志上传）
对游戏打开高dpi缩放
使用graphics capture
原窗口出现黄色边框，鼠标光标消失，没有出现全屏
再次使用快捷键，没有反应，鼠标光标仍然不可见
在没有光标的情况下关闭游戏
切桌面，开浏览器搜索“光标消失怎么办”
再次切回桌面，突然全屏白色，中央突然显示magpie无响应
尝试各种方法关闭magpie。。。。。
### 第三次：
这次游戏没有开高dpi缩放
animate 4k，graphics capture
按下快捷键，游戏窗口出现黄色边框，鼠标光标消失
关闭游戏，鼠标光标恢复

### Log files 日志文件

第一次：
[Runtime.log](https://github.com/Blinue/Magpie/files/8320058/Runtime.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/8320059/Magpie.log)
第三次：
[Runtime.log](https://github.com/Blinue/Magpie/files/8320127/Runtime.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/8320128/Magpie.log)

**Comment by szlysms** [comment]
以上是独显的经历，换集显之后可以了（但是为啥啊。。。

**Comment by Blinue** [comment]
GDI 和 DwmSharedSurface 可以工作吗？

**Comment by yaqinking** [comment]
说下个人的使用经验：

笔记本，集显 + 独显，使用非默认显卡时，不要使用 Desktop Duplication，大多数情况下都不会正常工作。

糖调和类似的 KirikiriZ 引擎的 GALGAME，系统默认显卡（集显）时可使用 DD 捕捉模式放大。
旧的 Kirikiri2 引擎的 GALGAME，推荐使用 GDI 模式捕捉，兼容性很好。

运行糖调日文版游戏，使用笔记本独显 NVIDIA 940MX

- Graphics Capture
- GDI

以上两种捕获模式都可正常运行。

DD 和 DwmSharedSurface 都无法正常工作。

**Comment by Blinue** [comment]
一般而言，最好使用直接连接到显示器的显卡。对于双显卡的笔记本，推荐开启独显直连。

这有两点好处：一是 Magpie 使用的捕获模式比较底层，对驱动有依赖。如果 Magpie 使用的显卡不负责屏幕渲染，可能会捕获失败。二是可以避免在显卡间拷贝纹理，以提高性能。

**Comment by BLACKCHARGE** [comment]
我试了一下，同样的游戏我只用独显是可以正常放大的，估计是双显卡切换的问题

**Comment by szlysms** [comment]
> 说下个人的使用经验：
> 
> 笔记本，集显 + 独显，使用非默认显卡时，不要使用 Desktop Duplication，大多数情况下都不会正常工作。
> 
> 糖调和类似的 KirikiriZ 引擎的 GALGAME，系统默认显卡（集显）时可使用 DD 捕捉模式放大。 旧的 Kirikiri2 引擎的 GALGAME，推荐使用 GDI 模式捕捉，兼容性很好。
> 
> 运行糖调日文版游戏，使用笔记本独显 NVIDIA 940MX
> 
> * Graphics Capture
> * GDI
> 
> 以上两种捕获模式都可正常运行。
> 
> DD 和 DwmSharedSurface 都无法正常工作。

然而事实上独显情况下我任何一个模式都用不了，dd还好，只是不能正常工作，gc直接把我鼠标光标弄看不见，快捷键这时候还失效，再也不想尝试了

**Comment by szlysms** [comment]
> GDI 和 DwmSharedSurface 可以工作吗？

都不行，都试过了，只要是独显都不行，只能集显。。。:（

**Comment by BLACKCHARGE** [comment]
> > GDI 和 DwmSharedSurface 可以工作吗？
> 
> 都不行，都试过了，只要是独显都不行，只能集显。。。:（

你的电脑是不是不支持独显直连，如果是的话那就只能用集显先玩了，因为就算你调用独显，也是用集显输出的画面

**Comment by yaqinking** [comment]
> 
> 然而事实上独显情况下我任何一个模式都用不了，dd还好，只是不能正常工作，gc直接把我鼠标光标弄看不见，快捷键这时候还失效，再也不想尝试了

更新到最新版显卡驱动，或者卸载显卡驱动，使用 Windows 自动安装显卡驱动试试？

说个无关的别的问题，我的台式机用最新版显卡驱动，Chrome 开启硬件加速模式，开机播放视频时会黑屏，得等一会儿才恢复。所以一直用的 Windows 自动安装的显卡驱动

**Comment by szlysms** [comment]
> > 然而事实上独显情况下我任何一个模式都用不了，dd还好，只是不能正常工作，gc直接把我鼠标光标弄看不见，快捷键这时候还失效，再也不想尝试了
> 
> 更新到最新版显卡驱动，或者卸载显卡驱动，使用 Windows 自动安装显卡驱动试试？
> 
> 说个无关的别的问题，我的台式机用最新版显卡驱动，Chrome 开启硬件加速模式，开机播放视频时会黑屏，得等一会儿才恢复。所以一直用的 Windows 自动安装的显卡驱动

emmmmm，好吧，看来也只能这样了。。谢谢你

**Comment by szlysms** [comment]
> > > GDI 和 DwmSharedSurface 可以工作吗？
> > 
> > 
> > 都不行，都试过了，只要是独显都不行，只能集显。。。:（
> 
> 你的电脑是不是不支持独显直连，如果是的话那就只能用集显先玩了，因为就算你调用独显，也是用集显输出的画面

的确是，看来也没有办法了，谢谢
