### ISSUE TITLE
关于性能方面一个可行的妥协方法

### ISSUE THREAD

**Issue by linserv33** [Blinue/Magpie#34]
在使用Magpie的时候 我尝试让他用集显来进行画面捕获 而游戏则是用独显进行游戏（对于笔记本来说） 我发现这种情况下 Magpie的开销基本都在集显上 而独显不会受到影响 从而不会导致帧数比原生帧数还低 有没有一种方法 能够直接集成在程序中 可以选择性的让它决定用独显还是集显 这样就不用到图形设置或者控制面板来进行切换

**Comment by Blinue** [comment]
感谢建议，我会尝试一下这个方法

**Comment by linserv33** [comment]
在测试多款游戏后发现一个问题，当我使用FSR的时候，我在自定义缩放那边添加了个锐化效果，使用Magpie的时候GPU使用率明显降低（帧数也随之变低）当我去掉那些锐化选项，我的GPU使用率又恢复正常。
我比较想知道，如果我不去添加锐化选项，那么FSR的锐化是否生效？

**Comment by Blinue** [comment]
FSR始终包含一个锐化的步骤

**Comment by dakkidaze** [comment]
不过大部分Intel核显其实还是不够强，而且因为部分笔记本上核显要负担视频输出的职责，有时候反而会导致独显吃不满，帧数还是上不去

**Comment by tigerinus** [comment]
现在的集显没有想象中的那么差了。Intel HD630 玩 Minecraft 都很不错的帧率，何况还有 VEGA，Iris 这类新集显。

**Comment by linserv33** [comment]
锐炬显卡确实能够胜任这些，至少在我这边4600h的集显，表现就不怎么好

**Comment by Blinue** [comment]
https://github.com/Blinue/Magpie/releases/tag/v0.7.1
