### ISSUE TITLE
部分游戏无法使用，部分游戏使用后无效

### ISSUE THREAD

**Issue by Druame-Deemo** [Blinue/Magpie#340]
### Magpie version 程序版本

0.8.1

### Windows version 系统版本

win11 21H2

### Reproduction steps 复现步骤

因电脑内游戏不多，仅用了5款游戏测试，其中两款游戏正常运行，其余会分别出现“源窗口尺寸不能超过屏幕大小”报错，以及使用后自动全屏其运行分辨率变回原生分辨率且无加载FSR的问题，还有使用后出现自动设置为全屏化并没有应用FSR滤镜的情况，且经测试，目前电脑内常用非游戏软件使用mapie均无任何问题

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/8324381/Magpie.log)
[Runtime.1.log](https://github.com/Blinue/Magpie/files/8324382/Runtime.1.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/8324383/Runtime.log)

**Comment by Blinue** [comment]
游戏必须在窗口模式下才能使用 Magpie。

有些自动全屏化的游戏是不是快捷键冲突问题？修改 Magpie 的快捷键
