### ISSUE TITLE
How DwmSharedSurface works？Will it cause online accounts to be blocked?

### ISSUE THREAD

**Issue by yan32020** [Blinue/Magpie#342]
### Question 问题

Snap mode: **DwmShared Surface**
When using this mode with FSR, I find it very smooth, especially with very low latency, even at average frame rates.
But at the same time, I don't know **if it's an "injected game run"** , which will **pose a risk to my playing online games and may result in my game account being banned.**
So I want to know **if this pattern will be detected by the game background as cheating.**
@Blinue

**Comment by Blinue** [comment]
https://github.com/Blinue/Magpie/wiki/FAQ_EN#will-using-magpie-in-multi-player-games-be-detected-as-cheating

Use at your own risk.
