### ISSUE TITLE
关闭“提高指针精确度”时无法正确调整光标速度

### ISSUE THREAD

**Issue by ljx0772** [Blinue/Magpie#345]
### Expected behavior 预期的功能

![QQ截图20220406092420](https://user-images.githubusercontent.com/33015846/161877010-904c13a1-0a4f-48d8-961b-486877acf461.png)

首先感谢作者提供如此不可思议的软件。但我有个小建议，在win10系统高分辨，高缩放的情况下（4K，250%），使用软件。如果不勾选“缩放时调整光标速度”会出现光标移动过快的问题，但如果勾选此选项后又会出现光标移动过慢的问题。
所以，请求新增缩放时自定义调整光标速度的功能。感谢！

**Comment by hooke007** [comment]
这个光标速度就是你系统设置里的光标速度

**Comment by ljx0772** [comment]
> 这个光标速度就是你系统设置里的光标速度

是的，我了解。可能是我表述不够清楚，我的意思是：
现在软件在勾选“缩放时调整光标速度”后，会在缩放时调整系统设置里的光标速度，但软件自动调整的“数值”可能不够合适，所以可不可以自定义软件自动调整的这个“数值”呢？ （当然，现在可以直接在系统中设置，但这样会出现在缩放时合适鼠标速度，在闭关缩放后，又不合适了）。 
感谢你的回复！

**Comment by hooke007** [comment]
我只是提供一个临时解决方案，是否执行请求。。
It's up to Owner —— Blinue, I'm just a Contributor. (

**Comment by Blinue** [comment]
谢谢反馈。你的系统鼠标指针速度是多少？以及你的屏幕相对于原始窗口放大了多少倍？
![image](https://user-images.githubusercontent.com/34770031/161988701-cb3caa1f-d559-4efd-b76d-1674cbca185e.png)

**Comment by ljx0772** [comment]
> 
![image](https://user-images.githubusercontent.com/33015846/162095967-6c8fd1c3-df97-48db-9bd7-48a9264f8a55.png)
![image](https://user-images.githubusercontent.com/33015846/162095981-9d5de6f6-5f09-4a40-a1d8-7a7259d139ad.png)

鼠标型号：罗技M590，测试游戏为“恋×シンアイ彼女”，原始窗口大小为720P。显示器分辨率为4K，win10系统缩放250%。

**Comment by Blinue** [comment]
从1280x720 放大到3840x2160 刚好 3 倍，Magpie 会将系统的光标速度降低 3 倍，也就是 4，这里不存在误差。这时光标移动速度很慢就有点奇怪。

> 当然，现在可以直接在系统中设置，但这样会出现在缩放时合适鼠标速度，在闭关缩放后，又不合适了）。

系统的光标速度设置为多少时，缩放后光标的速度合适？以及请提供日志，它们在 logs 文件夹下。

**Comment by ljx0772** [comment]
[Magpie.log](https://github.com/Blinue/Magpie/files/8438808/Magpie.log)
[Runtime.1.log](https://github.com/Blinue/Magpie/files/8438810/Runtime.1.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/8438811/Runtime.log)
请稍等，缩放后合适的光标速度值我今晚回去测试将发出。

**Comment by ljx0772** [comment]
> 从1280x720 放大到3840x2160 刚好 3 倍，Magpie 会将系统的光标速度降低 3 倍，也就是 4，这里不存在误差。这时光标移动速度很慢就有点奇怪。
> 
> > 当然，现在可以直接在系统中设置，但这样会出现在缩放时合适鼠标速度，在闭关缩放后，又不合适了）。
> 
> 系统的光标速度设置为多少时，缩放后光标的速度合适？以及请提供日志，它们在 logs 文件夹下。

刚刚我直接在系统桌面进行测试：同样让鼠标物理移动1厘米的距离。当光标速度设置为12时，鼠标在屏幕上移动的距离远远大于光标速度为4时的3倍。我猜测是win10对光标速度的调整并非线性的。

**Comment by Blinue** [comment]
> 我猜测是win10对光标速度的调整并非线性的。

应该就是这样。我在 1080p 的显示器上测试了一下，光标速度大体上是线性的，所以猜测是高 DPI 下的特殊机制或者和驱动相关。这是一个bug，如何修复它目前还没头绪。最不济的情况下可以提供手动调整光标速度的选项。

**Comment by Blinue** [comment]
Windows 提供了一个“鼠标加速”功能，你可以尝试关闭它。

**Comment by ljx0772** [comment]
> Windows 提供了一个“鼠标加速”功能，你可以尝试关闭它。

是指“提高指针精确度”吗？我并没有打开它

**Comment by Blinue** [comment]
> 是指“提高指针精确度”吗？我并没有打开它

根据 https://liquipedia.net/counterstrike/Mouse_Settings#Windows_Sensitivity ，打开这个选项会使光标速度的调整呈线性，否则是非线性。打开试试

**Comment by ljx0772** [comment]
> > 是指“提高指针精确度”吗？我并没有打开它
> 
> 根据 https://liquipedia.net/counterstrike/Mouse_Settings#Windows_Sensitivity ，打开这个选项会使光标速度的调整呈线性，否则是非线性。打开试试
> 
> > <img alt="" height="14" src="/counterstrike/extensions/SearchEngineOptimization/resources/images/favicon-196x196.png"> Liquipedia Counter-Strike Wiki**[Mouse Settings](https://liquipedia.net/counterstrike/Mouse_Settings)**This article details the various mouse settings both in and out of Counter-Strike: Global Offensive that affect gameplay.

好的，我回去测试后给你反馈（不过打开这个选项后，鼠标使用起来真不习惯呀）

**Comment by Blinue** [comment]
测试了一下，关闭“提高指针精确度”选项确实会使全屏时光标速度过慢。我会修复这个 bug

**Comment by Blinue** [comment]
在 https://github.com/Blinue/Magpie/suites/5981300340/artifacts/205972376 下载最新版本

**Comment by ljx0772** [comment]
> 在 https://github.com/Blinue/Magpie/suites/5981300340/artifacts/205972376 下载最新版本
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e3498776c2fc6e103c368b2e0a90aac9dbb53e742fc03c294b4c4073cc7e7bd0/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f6f70656e5f67726170682f6769746875622d6c6f676f2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Build software better, together](https://github.com)**GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects.

感谢！我测试了下，确实有用，比原先改善了不少
