### ISSUE TITLE
Filter only active image area after cropping

### ISSUE THREAD

**Issue by sharsys** [Blinue/Magpie#347]
### Expected behavior 预期的功能

Right now the cropping feature only blacks out the cropped part of the picture, resulting in wasted space on the screen regardless of capture method.
It would be ideal to only apply filtering to the resulting image size to make better use of the space and particularly improve the look of CRT filters that benefit from high resolution headroom.

**Comment by Blinue** [comment]
> Right now the cropping feature only blacks out the cropped part of the picture, resulting in wasted space on the screen regardless of capture method.

That's not how cropping works.

Before copping:
![屏幕截图(1230)](https://user-images.githubusercontent.com/34770031/162625632-619426b3-9916-4437-b157-42ee57bf0e0d.png)

After cropping:
![屏幕截图(1231)](https://user-images.githubusercontent.com/34770031/162625640-b9ad11b8-54fb-4314-b876-8f66aa066009.png)

There will be no black bars when the input image and the screen have the same ratio. If you don't want black bars, set the *scale* parameter to [0,0].

**Comment by sharsys** [comment]
Oh no .. I humbly apologize for my lapse in logic. It is just like you said.
It's just that I was trying it in a virtual machine while simulating a larger display resolution than my display and didn't realize I was cropping a 4:3 window while using a 4:3 resolution since a part of the screen was obscured.
