### ISSUE TITLE
用于游戏会有显著的降刷新率。

### ISSUE THREAD

**Issue by recordholder3000** [Blinue/Magpie#348]
### Program(Game) 游戏名

APEX

### Capture method 捕获模式

all capture mretod

### Other information (optional) 补充信息（可选）

用fsr时或者FSR跟NIS结合时，会有降刷新率的感觉，比如我是144hz，会降低到60hz左右。

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/8464218/Magpie.log)

**Comment by Blinue** [comment]
在设置中打开帧率显示看看

**Comment by recordholder3000** [comment]
> 在设置中打开帧率显示看看
我看了，帧率很高，甚至能达到300多，但是游戏画面就会有卡顿感。

**Comment by Blinue** [comment]
Magpie 的垂直同步打开时帧率不会超过屏幕刷新率。请发日志。
FSR 2.0 不太可能移植，因为它不是单纯的图像后处理。
