### ISSUE TITLE
希望在面板上添加每个算法的简介

### ISSUE THREAD

**Issue by RxinnotRstar** [Blinue/Magpie#352]
### Expected behavior 预期的功能

![图片](https://user-images.githubusercontent.com/56676566/163802430-955be198-793c-471e-96e7-d9590a8f5c1c.png)

![图片](https://user-images.githubusercontent.com/56676566/163802789-3910d31d-2e84-4735-8d5c-9c6458e609f0.png)

例如，可以在这里加一个【?】按钮，点击之后弹出一个弹窗，提供每个算法的简介和适用场景（可以直接将 readme.md 的“缩放模式”放到弹窗里）。
“捕获模式”也可以这么做，不过似乎可有可无。

### Alternative behavior (optional) 近似的功能（可选）

![图片](https://user-images.githubusercontent.com/56676566/163803314-e98f40bd-eb96-45df-9377-9f87695658a4.png)

![图片](https://user-images.githubusercontent.com/56676566/163803203-725f7163-e9e8-4036-9035-2faac9136f1f.png)
隔壁30块钱的小黄鸭就有类似的功能，点击“手册”就可以打开弹窗。

**Comment by Blinue** [comment]
Magpie 支持很多算法，用户可以修改缩放模式。关于每种算法的说明见 https://github.com/Blinue/Magpie/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E6%94%BE%E9%85%8D%E7%BD%AE

**Comment by RxinnotRstar** [comment]
> Magpie 支持很多算法，用户可以自定义缩放模式。关于每种算法的说明见 https://github.com/Blinue/Magpie/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E6%94%BE%E9%85%8D%E7%BD%AE
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/20d5277eb83584a89964bc2125055850aeb91ead265bd6f0b8e7563883bc9cd6/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f316464363739643435366262323238313830356361613864613063313265633435393833343163363863313832323763666337323132336665326131626431382f426c696e75652f4d6167706965"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[自定义缩放配置 · Blinue/Magpie Wiki](https://github.com/Blinue/Magpie)**使游戏窗口全屏显示. Contribute to Blinue/Magpie development by creating an account on GitHub.

您似乎没有理解我的意思。我的意思是说，如果用户需要查询每种算法的详细情况，可以直接在软件内查询，而不是跳转到浏览器来查询。

**Comment by Blinue** [comment]
给每个效果添加描述确实有必要。重写 UI 已在计划中，将来会实现在 UI 中编辑缩放模式（现在是通过编辑 json），用户编辑时将可以查看每个效果和其参数的描述。

Lossless Scaling 的“缩放配置”只有几个选择，因此可以给每个配置添加描述，而 Magpie 中的“缩放模式”是由用户定义的，也鼓励用户进行更改，因此给缩放模式添加描述就没有必要了。

**Comment by RxinnotRstar** [comment]
> 给每个效果添加描述确实有必要。重写 UI 已在计划中，将来会实现在 UI 中编辑缩放模式（现在是通过编辑 json），用户编辑时将可以查看每个效果和其参数的描述。
> 
> Lossless Scaling 的“缩放配置”只有几个选择，因此可以给每个配置添加描述，而 Magpie 中的“缩放模式”是由用户定义的，也鼓励用户进行更改，因此给缩放模式添加描述就没有必要了。

好的，我知道了，感谢您的解答
