### ISSUE TITLE
使用GDI和DwmSharedSurface捕获方式放大VLC播放器的时候VLC内的视频黑屏

### ISSUE THREAD

**Issue by RxinnotRstar** [Blinue/Magpie#353]
### Magpie version 程序版本

0.8.1

### Windows version 系统版本

Windows 10 21H1

### Related screenshot (optional) 相关截图（可选）

放大前：![图片](https://user-images.githubusercontent.com/56676566/163925348-079af0db-1662-41e7-9da2-2f53a023a9ba.png)
放大后：
![图片](https://user-images.githubusercontent.com/56676566/163925414-969b85e1-27a0-488d-aefd-db7a3fe10ad9.png)

### Reproduction steps 复现步骤

0.安装vlc播放器最新版本（http://www.videolan.org/）
1.使用vlc播放器播放任意视频
2.使用GDI或者DwmSharedSurface捕获窗口
3.vlc的UI正常工作，但是视频不显示画面（有声音）

### Log files 日志文件

[Runtime.log](https://github.com/Blinue/Magpie/files/8510058/Runtime.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/8510059/Magpie.log)

**Comment by Blinue** [comment]
GDI 和 DwmSharedSurface 无法捕获到使用 DirectComposition 绘制的内容（比如 UWP 和一些游戏）。这种情况下推荐使用 Graphics Capture。见[捕获模式对比](https://github.com/Blinue/Magpie/wiki/%E6%8D%95%E8%8E%B7%E6%A8%A1%E5%BC%8F%E5%AF%B9%E6%AF%94)

（图太辣眼睛，麻烦换一下）
