### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by Mstdream** [Blinue/Magpie#356]
Magpie version 程序版本
0.8.1

Windows version 系统版本
win10 专业版 10.0.19044

Related screenshot (optional) 相关截图（可选）
![image](https://user-images.githubusercontent.com/63949691/165994740-37ce2085-475c-4cb9-a02e-963e6e75e31f.png)

Reproduction steps 复现步骤
之前能使用，今晚重装最新windows系统后不能使用
已经修复并更新 dotnet 和 MSVC 运行库
日志中提到的DLL就在同目录下，已经尝试拷贝到系统目录下，无效
目前有两台电脑都是这个问题，而且系统不一样（一个是官网下载的，一个是买惠普笔记本自带的）
![image](https://user-images.githubusercontent.com/63949691/165995112-60dd5e88-d3a5-461f-b0cf-d37e9dd3fec2.png)

Log files 日志文件

2022-04-30 01:37:20.9781|INFO|Magpie.App|当前日志级别：Info
2022-04-30 01:37:20.9826|INFO|Magpie.App|程序启动
	进程 ID：3372
	Magpie 版本：0.8.1.0
	OS 版本：10.0.19044.0
2022-04-30 01:37:20.9826|INFO|Magpie.App|当前语言：zh-CN
2022-04-30 01:37:20.9826|INFO|Magpie.ScaleModelManager|已读取缩放配置
2022-04-30 01:37:20.9826|INFO|Magpie.ScaleModelManager|正在监视 ScaleModels.json 的更改
2022-04-30 01:37:21.1576|INFO|Magpie.MainWindow|当前热键：Alt+F11
2022-04-30 01:37:21.2466|WARN|Magpie.MagWindow|未找到 Runtime.dll|Unable to load DLL 'MagpieRT' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
2022-04-30 01:37:21.2478|WARN|Magpie.MagWindow|LoadLibrary 失败
	LastErrorCode=126
2022-04-30 01:37:21.2478|ERROR|Magpie.MagWindow|Initialize 失败|Unable to load DLL 'MagpieRT' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
2022-04-30 01:37:21.2478|FATAL|Magpie.MagWindow|初始化 Runtime 失败
2022-04-30 01:37:22.7396|INFO|Magpie.App|程序关闭
	进程 ID：3372

**Comment by Mstdream** [comment]
从steam上随便下载了几个游戏，打开的时候会下载一些乱七八糟的依赖，把这个问题规避掉了。。应该是有依赖没有写明在依赖表中

**Comment by Blinue** [comment]
依赖已在虚拟机中测试过，出现这个问题很可能是 MSVC 运行库版本太旧。

最新 MSVC 运行库下载地址：
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by zhencaozi** [comment]
> 依赖已在虚拟机中测试过，出现这个问题很可能是 MSVC 运行库版本太旧。
> 
> 最新 MSVC 运行库下载地址： https://aka.ms/vs/17/release/vc_redist.x64.exe

您好，安装了这个运行库后还是初始化失败

**Comment by Blinue** [comment]
建议你下载最新版本，不需要安装任何运行库

**Comment by zhencaozi** [comment]
> 建议你下载最新版本，不需要安装任何运行库

我是需要在win7系统下运行

**Comment by Blinue** [comment]
> 我是需要在win7系统下运行

旧版本也不支持 win7，试试这个：https://github.com/HIllya51/Magpie9_win7

**Comment by zhencaozi** [comment]
> > 我是需要在win7系统下运行
> 
> 旧版本也不支持 win7，试试这个：https://github.com/HIllya51/Magpie9_win7
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/cb0ffb1a9d9d7be1dcba74f0824223b20fed2819bf23e789b00faed9061d4eb0/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f383734336530646437653037303261656266383933346434643038346235356364333938623163336338323365623835396430333135643564333631346436312f48496c6c796135312f4d6167706965395f77696e37"><img alt="" height="14" src="https://camo.githubusercontent.com/c7475aac04b72ccdbdab6d5f8abf505c824fdb625ef049acf2c773106c631bff/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[GitHub - HIllya51/Magpie9_win7: Magpie9的win7适配](https://github.com/HIllya51/Magpie9_win7)**Magpie9的win7适配. Contribute to HIllya51/Magpie9_win7 development by creating an account on GitHub.

用这个并且安装了.NET 48后还是初始化失败
![333](https://github.com/user-attachments/assets/eb33d6d9-e7b0-4636-bd1a-41ec4f51b495)
![222](https://github.com/user-attachments/assets/6b4e39ab-baf6-4baa-bfb2-ff89f3d71a74)
![111](https://github.com/user-attachments/assets/1849d72b-e245-4855-8559-281fd51265e0)

**Comment by zhencaozi** [comment]
> > > 我是需要在win7系统下运行
> > 
> > 
> > 旧版本也不支持 win7，试试这个：https://github.com/HIllya51/Magpie9_win7
> > > <img alt="" width="48" src="https://camo.githubusercontent.com/cb0ffb1a9d9d7be1dcba74f0824223b20fed2819bf23e789b00faed9061d4eb0/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f383734336530646437653037303261656266383933346434643038346235356364333938623163336338323365623835396430333135643564333631346436312f48496c6c796135312f4d6167706965395f77696e37"><img alt="" height="14" src="https://camo.githubusercontent.com/c7475aac04b72ccdbdab6d5f8abf505c824fdb625ef049acf2c773106c631bff/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[GitHub - HIllya51/Magpie9_win7: Magpie9的win7适配](https://github.com/HIllya51/Magpie9_win7)**Magpie9的win7适配. Contribute to HIllya51/Magpie9_win7 development by creating an account on GitHub.
> 
> 用这个并且安装了.NET 48后还是初始化失败 ![333](https://private-user-images.githubusercontent.com/97510410/394209010-eb33d6d9-e7b0-4636-bd1a-41ec4f51b495.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjYwNjksIm5iZiI6MTczMzgyNTc2OSwicGF0aCI6Ii85NzUxMDQxMC8zOTQyMDkwMTAtZWIzM2Q2ZDktZTdiMC00NjM2LWJkMWEtNDFlYzRmNTFiNDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEwMTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Y2NkZDRlY2MyYmRhYTU0MThmOGE3ZTU2NWIwMjdmMDA3NDI4MzFmMDkzODYxYmYxOGZhNjY4ZGUwNzA1N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.21RtEa4qtpp4eKqU3DWwn_03tIdqQxiBl0wP8QdEARs) ![222](https://private-user-images.githubusercontent.com/97510410/394209025-6b4e39ab-baf6-4baa-bfb2-ff89f3d71a74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjYwNjksIm5iZiI6MTczMzgyNTc2OSwicGF0aCI6Ii85NzUxMDQxMC8zOTQyMDkwMjUtNmI0ZTM5YWItYmFmNi00YmFhLWJmYjItZmY4OWYzZDcxYTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEwMTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzU1MmIyODE3OTMxODljNjk1YTNhNTQzZTNjZGU2NTNmNWUwMGFiMjM5MDIwNmNjOWI4MmZjMjgxNjczZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YWt2YqNYMvdj5ajW05fxpy8t1aIcTWS_h8-bBpxkHgI) ![111](https://private-user-images.githubusercontent.com/97510410/394209029-1849d72b-e245-4855-8559-281fd51265e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjYwNjksIm5iZiI6MTczMzgyNTc2OSwicGF0aCI6Ii85NzUxMDQxMC8zOTQyMDkwMjktMTg0OWQ3MmItZTI0NS00ODU1LTg1NTktMjgxZmQ1MTI2NWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEwMTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyODViNTVhMzQ0OGM4NTE5YzRmNDM4NjdhN2E4NzVhYmRhNWM5NWM0ZTYyOThhMWZkMTZiZmQyMWRkMjljYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k2i8Ub9iesZXNP1ESkWqh3wy9dI5wjfcYsMhDFm5SFE)
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/cb0ffb1a9d9d7be1dcba74f0824223b20fed2819bf23e789b00faed9061d4eb0/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f383734336530646437653037303261656266383933346434643038346235356364333938623163336338323365623835396430333135643564333631346436312f48496c6c796135312f4d6167706965395f77696e37"><img alt="" height="14" src="https://camo.githubusercontent.com/c7475aac04b72ccdbdab6d5f8abf505c824fdb625ef049acf2c773106c631bff/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[GitHub - HIllya51/Magpie9_win7: Magpie9的win7适配](https://github.com/HIllya51/Magpie9_win7)**Magpie9的win7适配. Contribute to HIllya51/Magpie9_win7 development by creating an account on GitHub.

修复DLL后可以打开程序了
