### ISSUE TITLE
请求支持触屏时鼠标指针位置的校准

### ISSUE THREAD

**Issue by Zero-Dragon** [Blinue/Magpie#357]
### Expected behavior 预期的功能

目前使用触摸屏在已经全屏放大的图片上点击会根据点击的屏幕坐标不同发生不同大小的偏移，希望未来可以在触摸屏上指哪点哪

**Comment by Blinue** [comment]
善用搜索 https://github.com/Blinue/Magpie/issues/218#issuecomment-980506414
