### ISSUE TITLE
Magpie won't start after updating to v0.8.2

### ISSUE THREAD

**Issue by darklinkpower** [Blinue/Magpie#359]
### Magpie version 程序版本

v0.8.2

### Windows version 系统版本

win10 21H2

### Related screenshot (optional) 相关截图（可选）

![image](https://user-images.githubusercontent.com/1389286/166118999-23e33c48-c286-453b-a14d-c29a3fa5cbfb.png)

![image](https://user-images.githubusercontent.com/1389286/166119029-84a79a47-21e1-478b-a52a-1cfe8b404872.png)

### Reproduction steps 复现步骤

1. Open Magpie v0.8.2
2. Magpie won't open, generate log files or config file

Magpie v0.8.1 starts without any issues.

### Log files 日志文件

Logs are not generated

**Comment by Blinue** [comment]
[Magpie_v0.8.2.zip](https://github.com/Blinue/Magpie/files/8598706/Magpie_v0.8.2.zip)
Try this build.

**Comment by motoleon** [comment]
> [Magpie_v0.8.2.zip](https://github.com/Blinue/Magpie/files/8598706/Magpie_v0.8.2.zip) Try this build.

That is not 0.8.2 version, is 0.8.1 .exe version plus 0.8.2 dll version...
Not solution.

**Comment by darklinkpower** [comment]
> [Magpie_v0.8.2.zip](https://github.com/Blinue/Magpie/files/8598706/Magpie_v0.8.2.zip) Try this build.

Thanks for the quick response. I can confirm this build is working

![image](https://user-images.githubusercontent.com/1389286/166167831-4c04b2a4-fd08-4a9a-8873-61858d135cd4.png)

Just one thing, it says 0.8.1 on settings, is that intended?

**Comment by Blinue** [comment]
> That is not 0.8.2 version, is 0.8.1 .exe version plus 0.8.2 dll version...

This is okay, because v0.8.2 didn't modify the exe.

**Comment by Blinue** [comment]
I presume this is a bug in NLog. Does this build work?
https://github.com/Blinue/Magpie/suites/6341410428/artifacts/228479768

**Comment by Blinue** [comment]
I suggest you reinstall the .NET runtime, if it doesn't work, use this version which has the same functionality as v0.8.2.

> [Magpie_v0.8.2.zip](https://github.com/Blinue/Magpie/files/8598706/Magpie_v0.8.2.zip)
> Try this build.

I'm planning to remove the dependency on .NET, although it will be a while.

**Comment by wzol** [comment]
Same happens with Magpie_v0.9.0_preview1 - won't start.

**Comment by Blinue** [comment]
Have you tried updating .NET runtime? https://github.com/Blinue/Magpie/discussions/361#discussioncomment-2701431

**Comment by darklinkpower** [comment]
Sorry for the late reply. I installed .net 6 runtime from here and I can confirm it fixes the issue https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.4-windows-x64-installer

**Comment by wzol** [comment]
Thanks for the link, can confirm, it fixes the issue.
