### ISSUE TITLE
Would it be possible to fix Magpie's FPS to the source window?

### ISSUE THREAD

**Issue by canceralp** [Blinue/Magpie#36]
I have zero knowledge about programming but I know that Reshade does it. In a way, Reshade is an extra layer on top of the game's window and it works as injecting itself into the game's exe. And Reshade update itself only when the game's window updates itself. So, their FPSs are exactly same. Magpie has an injection solution, too. Would it be possible to do the same approach so they both act together at the same FPS, eliminating any (or most of the) performance issues? 

I don't know if what I ask would be a DirectX/Vulkan/OpenGL specific solution, because 2D elements may be drawn differnetly but maybe Magpie can have a performance oriented injection way for games. 

I hope it is not too much to ask but your FSR implementation is already becoming popular. BTW, I made a video of Magpie working at 1080p and upscaling to 1440p vs 1440p native with Assassin's Creed Valhalla. Can I share it (and possibly more) on Youtube? Of course, I'll be mentioning the names and giving the appropiate links. 

edit: typo

**Comment by Blinue** [comment]
Hi, thanks for your feedback.

Magpie and Reshade are completely different. Magpie is designed to be non-intrusive and application-independent, it cannot detect the rendering technology used by the source window now. Your suggestion is great and I will consider its feasibility.

Magpie is free and open source, you can do anything with it, as long as you follow its license.

**Comment by mirh** [comment]
Reshade isn't an extra layer, as far as programs are concerned. 
By injecting it inside the process it's a single whole thing with the game code. 

Then, it would certainly be nice for magpie to be able to hook just the rendering buffer (as opposed to more generally the window surface), but it would be something completely different.

**Comment by Blinue** [comment]
For compatibility with multiplayer games, Magpie will never inject.
