### ISSUE TITLE
Does Magpie capture have an accessible stream URL

### ISSUE THREAD

**Issue by SgtBlade** [Blinue/Magpie#360]
### Question 问题

I am looking for a program that is able to capture any window and open that live stream in video players like VLC and MPV player. 
Is Magpie able to do this? From my understanding it does seem to capture the window but I cannot find if it has an URL available that can be used as a livestream URL in the VLC or MPV players.

My goal is to use the [Anime4K](https://github.com/bloc97/Anime4K) upscaler which I've added to the MPV player to upscale any game in real-time.

**Comment by Blinue** [comment]
> My goal is to use the [Anime4K](https://github.com/bloc97/Anime4K) upscaler which I've added to the MPV player to upscale any game in real-time.

That's what Magpie does. Just select Anime4K scale mode and press the hotkey when the game is in the foreground.

Magpie does not provide streaming capabilities.

**Comment by SgtBlade** [comment]
Oh I see, then this does make it easier. 
Thanks for the response!
