### ISSUE TITLE
windows game bar 显示帧率和magpie显示不同

### ISSUE THREAD

**Issue by fatinghenji** [Blinue/Magpie#365]
### Magpie version 程序版本

0.9.0

### Windows version 系统版本

Windows 11 专业版 22H2 22616.1

### Related screenshot (optional) 相关截图（可选）

![V4C$DH2AXY%4O3LKKI8 3UW](https://user-images.githubusercontent.com/37131177/167679965-22e0e46f-73c9-4db0-97f0-417960b2d887.png)

### Reproduction steps 复现步骤

1.使用第三方启动器启动原神（该步骤仅为解决游戏设定的帧率锁）
2.启动Windows game bar，并pin fps显示框
3.使用magpie进行缩放
4.两者显示帧率不同

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/8663472/Magpie.log)

**Comment by hooke007** [comment]
月经问题，magpie不显示游戏帧率
https://github.com/Blinue/Magpie/wiki/FAQ#magpie-%E4%B8%AD%E6%98%BE%E7%A4%BA%E7%9A%84%E5%B8%A7%E7%8E%87%E6%98%AF%E4%BB%80%E4%B9%88

**Comment by Blinue** [comment]
看起来游戏有120帧而magpie只有60帧？试试更换捕获模式

**Comment by fatinghenji** [comment]
> 看起来游戏有120帧而magpie只有60帧？试试更换捕获模式（magpie 的帧率取决于屏幕刷新率）

那应该是我屏幕刷新率的问题了
