### ISSUE TITLE
Error creating window

### ISSUE THREAD

**Issue by dante42lk** [Blinue/Magpie#37]
![image](https://user-images.githubusercontent.com/73885599/128468728-8680c5d6-639b-454b-a9db-ccc481311196.png)
Happens with every game/version that i try to access.
Upd.
Ryzen 1600
rx 570
1809

**Comment by Blinue** [comment]
Does GDI capture mode work?

**Comment by dante42lk** [comment]
GDI capture works, actually

**Comment by Blinue** [comment]
WinRT capture is not supported in v1809. If you want to use it, you have to upgrade your OS to v1903 or a later version.

**Comment by dante42lk** [comment]
Oh, ok, thank you
