### ISSUE TITLE
在某些游戏中，鼠标移动至最右侧，会瞬移回中间

### ISSUE THREAD

**Issue by lilingxi1998** [Blinue/Magpie#372]
### Magpie version 程序版本

0.9.0

### Windows version 系统版本

win11 21h2

### Reproduction steps 复现步骤

打开某些游戏后，鼠标移动到右侧会瞬移到屏幕中间。
希望将鼠标移动功能修复一下，或者改为可选功能
例如：红警2

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/8698632/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/8698633/Runtime.log)

**Comment by Blinue** [comment]
正在调查

**Comment by Blinue** [comment]
在红警中使用的操作步骤：
1. 窗口化运行游戏，网上很容易找到操作步骤
2. 如果游戏以管理员身份运行，Magpie 也应以管理员身份运行
3. 按下快捷键即可全屏
