### ISSUE TITLE
Xess

### ISSUE THREAD

**Issue by recordholder3000** [Blinue/Magpie#373]
### Expected behavior 预期的功能

随后可以支持吗，不会像FSR2.0一样只能游戏适配吧

**Comment by Blinue** [comment]
XeSS 目前没有开放源代码，而且它基于英特尔的专有硬件，移植的希望不大。

**Comment by Blinue** [comment]
https://www.techpowerup.com/294898/intel-xess-launches-on-may-20-with-dolmen

似乎基于时域和运动矢量，因此没法移植。
