### ISSUE TITLE
A4K-3D迷你

### ISSUE THREAD

**Issue by zxyyangxz** [Blinue/Magpie#374]
### Question 问题

你好，软件太棒了。
新版本9.0 A4K-3D全屏的时候画面太大超出屏幕，结果显示的不完整了。自定义裁剪的话也是如此。

**Comment by Blinue** [comment]
Anime4K_3D_Upscale_US 固定的将画面放大一倍，为了适应屏幕，应后跟一个缩放算法。

```json
{"name":"A4K-3D-迷你","effects":[
    {"effect": "Anime4K_3D_Upscale_US"},
    {"effect": "CatmullRom", "scale": [-1, -1]}
]},
```

**Comment by zxyyangxz** [comment]
谢谢。
不好意思，纯小白。看不懂，不会编译。



在 2022-05-17 13:51:59，"刘旭" ***@***.***> 写道：

Anime4K_3D_Upscale_US 固定的将画面放大一倍，为了适应屏幕，应后跟一个缩放算法。

{"name":"A4K-3D-迷你","effects":[

    {"effect": "Anime4K_3D_Upscale_US"},

    {"effect": "CatmullRom", "scale": [-1, -1]}

]},

**Comment by Blinue** [comment]
在 Magpie.exe 的同级目录下找到 ScaleModels.json，用法见 https://github.com/Blinue/Magpie/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E6%94%BE%E9%85%8D%E7%BD%AE

将
```json
{"name":"A4K-3D-迷你","effects":[
    {"effect": "Anime4K_3D_Upscale_US"},
    {"effect": "CatmullRom", "scale": [-1, -1]}
]}
```
复制到 ScaleModels.json 中

**Comment by zxyyangxz** [comment]
好家伙，竟然可以了。
太厉害了。
谢谢。



在 2022-05-22 13:59:30，"刘旭" ***@***.***> 写道：

在 Magpie.exe 的同级目录下找到 ScaleModels.json，用法见 https://github.com/Blinue/Magpie/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E6%94%BE%E9%85%8D%E7%BD%AE

将

{"name":"A4K-3D-迷你","effects":[

    {"effect": "Anime4K_3D_Upscale_US"},

    {"effect": "CatmullRom", "scale": [-1, -1]}

]}

复制到 ScaleModels.json 中

GitHub
自定义缩放配置 · Blinue/Magpie Wiki
使游戏窗口全屏显示. Contribute to Blinue/Magpie development by creating an account on GitHub.
