### ISSUE TITLE
v.0.9.0 wont launch

### ISSUE THREAD

**Issue by zaifan** [Blinue/Magpie#377]
### Magpie version 程序版本

0.9.0

### Windows version 系统版本

win11 21H2 22000.708

### Reproduction steps 复现步骤

Magpie wont launh after i open it, tried run as administrator and got same result. im currently on win 11 build 22000.708.

### Log files 日志文件

 i got 2 error in event viewer.

*first error :
Application: Magpie.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

*second error :
Faulting application name: Magpie.exe, version: 0.9.0.0, time stamp: 0x622f78e0
Faulting module name: KERNELBASE.dll, version: 10.0.22000.708, time stamp: 0x89f799f7
Exception code: 0xe0434352
Fault offset: 0x000000000004474c
Faulting process ID: 0x184c
Faulting application start time: 0x01d871c08acb940b
Faulting application path: C:\Users\a*****\Downloads\Compressed\Magpie_v0.9.0\Magpie.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 8f5a20cc-041d-4a62-b6a3-0da61f19b2e7
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Blinue** [comment]
You should update your .NET runtime.
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.4-windows-x64-installer
