### ISSUE TITLE
建议添加1/2垂直同步或帧率限制功能

### ISSUE THREAD

**Issue by xsdianeht** [Blinue/Magpie#378]
### Expected behavior 预期的功能

我用的高刷屏幕，玩gal的时候不需要那么高的帧数，如果能内建一个限制帧数的功能会很方便
1/2垂直同步也是同样的效果，限制帧数为屏幕刷新率的1/2

**Comment by Blinue** [comment]
这个功能在v0.9中被删除了，因为很少有人用它，另外还会导致鼠标卡顿。除了使用旧版（v0.8.2）以及降低显示器的刷新率，你还可以查看[性能优化建议](https://github.com/Blinue/Magpie/wiki/%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E5%BB%BA%E8%AE%AE#%E6%88%91%E6%83%B3%E9%99%8D%E4%BD%8E-magpie-%E7%9A%84%E5%8A%9F%E8%80%97)。

**Comment by xsdianeht** [comment]
> 这个功能在v0.9中被删除了，因为很少有人用它，另外还会导致鼠标卡顿。除了使用旧版（v0.8.2）以及降低显示器的刷新率，你还可以查看[性能优化建议](https://github.com/Blinue/Magpie/wiki/%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E5%BB%BA%E8%AE%AE#%E6%88%91%E6%83%B3%E9%99%8D%E4%BD%8E-magpie-%E7%9A%84%E5%8A%9F%E8%80%97)。

感谢，用了RTSS限制帧数后发现了明显的鼠标卡顿，确实是没法用
