### ISSUE TITLE
[Question] XBRZ Freescale Multipass - How Do I Set It Up

### ISSUE THREAD

**Issue by shinra358** [Blinue/Magpie#380]
### Question 问题

I see the config for the normal freescale: 
  {"name":"xBRZ-任意倍","effects":[
    {"effect":"xBRZ_Freescale","scale":[-1,-1]},
  ]},

But how do I do it for Freescale Multipass?

**Comment by Blinue** [comment]
The "xBRZ_Freescale" is multi-pass in v0.9, the single-pass version was removed due to poor performance.

**Comment by shinra358** [comment]
what should the scale value be for freescale? with those -1 values, it crashes the shader.

also last question, when i use xbrz x6 or the others, the screen zooms in too much. How do I get it not to exceed screen size?

**Comment by Blinue** [comment]
```json
[
  {
    "name": "xBRZ_Freescale",
    "effects": [
      {
        "effect": "xBRZ_Freescale",
        "scale": [-1,-1]
      }
    ]
  },
  {
    "name": "xBRZ_6x",
    "effects": [
      {
        "effect": "xBRZ_6x"
      },
      {
        "effect": "CatmullRom",
        "scale": [ -1, -1 ]
      }
    ]
  }
]
```

**Comment by Blinue** [comment]
Maybe you are using it incorrectly, please read the README first. In addition, xbrz is only suitable for pixel games. https://github.com/Blinue/Magpie/issues/62#issuecomment-898892821

**Comment by NeilTohno** [comment]
Just use MMPX, better picture.
https://github.com/Blinue/Magpie/issues/349
