### ISSUE TITLE
对NVIDIA GPU上的CNN算法使用CUDA来运行超分网络

### ISSUE THREAD

**Issue by tosaki-up** [Blinue/Magpie#381]
### Expected behavior 预期的功能

目前看来Magpie的DNN相关的超分算法都是直接用DirectX着色器实现的，有没有可能加入一个使用DL库的版本？这样运行对N卡来说更高效，并且Tensor Core可以减少对流处理器的占用。

**Comment by Blinue** [comment]
首先，为了和 Windows 集成（在桌面上呈现以及降低延迟），使用 DirectX 是必须的。虽然可以将中间步骤转移到 NVIDIA 的专有 API 上（如 NVAPI），但我担心它们之间互操作的成本高于迁移获得的性能提升。

性能上说，NVIDIA 的专有 API 性能可能比 DirectCompute 高，但不会有很大的差距。NVIDIA 的 DirectCompute 驱动也可以充分利用 CUDA 核心，最终决定性能的还是硬件。

另外，Magpie 使用的效果语法完全基于计算着色器，转移到其他技术意味着所有效果都需要重写，这是不现实的。
