### ISSUE TITLE
If you can, Can you add a FSR 2.0 option and a RTX option too? and also can you make it compatible for Minecraft Bedrock edition?

### ISSUE THREAD

**Issue by ItsVictorTube** [Blinue/Magpie#382]
### Expected behavior 预期的功能

When you use FSR 2.0 it should most your performance like the FPS should raise and when you use RTX it should like nice like it should have all the reflections and shadows and it should also work with Minecraft Bedrock Edition.

**Comment by Blinue** [comment]
FSR 2.0 and RTX can only be implemented by game developers. Magpie is compatible with Minecraft Bedrock edition as far as I know.

**Comment by matt22207** [comment]
FSR2 was just open-sourced. Does this allow you to integrate it into Magpie?

Code: https://github.com/GPUOpen-Effects/FidelityFX-FSR2
Announcement: https://gpuopen.com/fsr2-source-available/

Thanks!!

**Comment by Blinue** [comment]
https://github.com/Blinue/Magpie/discussions/284#discussioncomment-2400536
