### ISSUE TITLE
大佬有兴趣再集成Real-CUGAN或者waifu2x算法吗

### ISSUE THREAD

**Issue by Gott-L** [Blinue/Magpie#383]
### Expected behavior 预期的功能

感觉Real-CUGAN和waifu2x算法虽然慢一点，但是效果明显，很适合galgame这种不要求啥速度的游戏，佬不知道有无兴趣

**Comment by Blinue** [comment]
帧率影响到鼠标流畅度，所以应越高越好。这两个算法速度太慢，一般硬件根本无法实时渲染，而且没有着色器实现，参数太多，移植很困难。

**Comment by hooke007** [comment]
gal只是静止帧多，实际帧率一般也是30到60，远大于常规视频的24FPS；
waifu2x目前的最快实现是ncnn-vulkan，即便如此在我的机器上（2070s mobile）依然无法实现360p源（x2，无降噪）的实时处理；

除非大幅精简优化网络和模型（SRCNN→FSRCNNX就是这么来的），否则没有实用的意义。
当然精简了也未必有预期的效果，因为你说的“明显效果”大部分就是数倍于实时级算法的网络和模型换来的，在我看来anime4k这个一开始就是从实时级用途设计的着色器就是当前gal的最优解了。

**Comment by Gott-L** [comment]
原来如此，那也许只能指望未来硬件的提升了，感谢大佬们

**Comment by dtlnor** [comment]
题外话，在限制条件非常严苛的情况下，waifu2x的upconv_7_anime_style_art_rgb是可以在3080Ti显卡上实时输出1080->4K的30fps视频。（cunet不行）
（经由vapoursynth滤镜vs-mlrt使用tensorRT优化过的waifu2x https://github.com/AmusementClub/vs-mlrt/wiki/waifu2x）
但由于硬件限制以及**没有着色器实现**的原因，也只有这种情况下（顶配N卡+支持vapoursynth滤镜的播放器播放30fps的1080p以下的视频）可以用了。~~如果要另辟蹊径可以用采集卡捕获hdmi信号输出给potplayer再让potplayer使用vapoursynth放大（这非常丧心病狂）~~
但这样折腾的效果，在同样硬件条件下其实并不会比合理地选择magpie里面最优秀的滤镜搭配输出的效果更好
（比如nnedi3再搭配合适的收线滤镜画面已经可以很好看了，甚至一般的anime4k的“目视优化”效果都可以已经非常够用了）

**Comment by Gott-L** [comment]
> 

原来如此，那如果可以的话，大佬方便集成一波waifu2x的upconv_7_anime_style_art_rgb的测试性选项，如果可以输出30fps其实对galgame啥的已经绰绰有余，是一个非常有意义的增加，硬件配置其实40系显卡出来后说不定会更宽松一些，这样也能让高配置的用户拥有更多选择与尝试...

**Comment by dtlnor** [comment]
> > 
> 
> 原来如此，那如果可以的话，大佬方便集成一波waifu2x的upconv_7_anime_style_art_rgb的测试性选项，如果可以输出30fps其实对galgame啥的已经绰绰有余，是一个非常有意义的增加，硬件配置其实40系显卡出来后说不定会更宽松一些，这样也能让高配置的用户拥有更多选择与尝试...

之所以我说是题外话的原因就在于，这是完全不是magpie的实现方式（或者说不相关）。“集成”需要重写一个全新的了。对于magpie来说这不是“现成的”可以移植的东西。

**Comment by Gott-L** [comment]
> > > 
> > 
> > 
> > 原来如此，那如果可以的话，大佬方便集成一波waifu2x的upconv_7_anime_style_art_rgb的测试性选项，如果可以输出30fps其实对galgame啥的已经绰绰有余，是一个非常有意义的增加，硬件配置其实40系显卡出来后说不定会更宽松一些，这样也能让高配置的用户拥有更多选择与尝试...
> 
> 之所以我说是题外话的原因就在于，这是完全不是magpie的实现方式（或者说不相关）。“集成”需要重写一个全新的了。对于magpie来说这不是“现成的”可以移植的东西。我只是针对“waifu2x的最快实现”做出补充而已。

原来如此，是我理解错了，打扰了

**Comment by frdoma** [comment]
希望anime4k的更顶配版能移植出来，这应该就是实时放大的极限了。

**Comment by Blinue** [comment]
https://github.com/Blinue/Magpie/issues/323
