### ISSUE TITLE
Doesnt work in windows 7

### ISSUE THREAD

**Issue by AnkitSinghGTHB** [Blinue/Magpie#389]
Please can anyone tell me how to get this working in windows 7  and i cant upgrade my pc further. If the devs find a way for windows 7 upscaling then i can pay for a premium version of that.

**Comment by Blinue** [comment]
It's out of the question. Windows 7 lacks the key APIs needed to run Magpie.

**Comment by mirh** [comment]
If you really have the money, you could look into paying somebody to implement [one of these](https://github.com/loki-47-6F-64/sunshine/issues/36#issuecomment-877318788) alternatives.
But everything should be possible to upgrade.

**Comment by AnkitSinghGTHB** [comment]
Wow u remember this mail 😂
I upgraded to windows 11
