### ISSUE TITLE
fps lock is gone in 0.9.0? 

### ISSUE THREAD

**Issue by yourmom2002** [Blinue/Magpie#390]
### Expected behavior 预期的功能

would be nice to have option to set X fps lock via optons, not just vsync
for example, i have 144 hz display, but i don't need that much fps whenever i use magpie for visual novel, 60 or even 30 is more than enough to me, but i can't set 30/60 fps via magpie settings anymore
in some cases more fps just gives my gpu unnecessary load
changing disaply fresh rate to 60 solves issue, but would be nice to bring fps lock back if possible

**Comment by hooke007** [comment]
dup https://github.com/Blinue/Magpie/issues/378#issuecomment-1140141711

**Comment by yourmom2002** [comment]
oops
