### ISSUE TITLE
用于调节亮度的效果

### ISSUE THREAD

**Issue by Kylejustknows** [Blinue/Magpie#391]
### Expected behavior 预期的功能

此软件是否能在不损失太多性能的情况下，增加亮度调节？

**Comment by Blinue** [comment]
能举个具体游戏吗，为什么窗口模式下不能调节亮度？

**Comment by Kylejustknows** [comment]
太多了，从Dota2 到 Starcraft II，印象里好像还有Bioshock系列，还有很多source引擎的游戏，都是 全屏时支持“亮度调节”，窗口化时不支持。（没什么具体原因，就是一旦选择窗口化，亮度调节栏就灰色禁用了，可能跟3d引擎有关。）

我在窗口化玩时，一直用显示屏上的（显示器硬件上的）亮度调节按钮，来增加亮度玩，就是麻烦。

我对图像处理的算法完全没入过门，也不知道是否有低CPU开支增加一层亮度调节的“滤镜”。所以也只是建议新功能，并不是什么刚需。


另一个功能建议是，窗口变全屏时的瞬间，自动把游戏“中心对齐”。
原因是，比如Nier游戏是典型的 “窗口化时1080是真的1080，全屏用1080却是模糊的720” 游戏。
最佳显示效果达成方法是：游戏选窗口1080，然后用您的工具把它变成全屏的1080 （1:1 near缩放性能损失很小）

但是，在1080屏幕上，开1080窗口化游戏，窗口总是有一部分会在屏幕之外。然后转成全屏时，有一部分白边不会渲染。

我现在是用一些特殊手段（游戏内切换全屏和分辨率），把游戏强制和屏幕的左上角1:1坐标对其后，再使用您的工具把它全屏化，才能完整显示游戏所有内容。 如果这个操作您的小软件能自动化处理，就太好了。

**Comment by Blinue** [comment]
通过着色器可以粗略模拟调节亮度，比不上游戏内置的，尤其是 3D 游戏。我会添加一个用于调节各种杂项参数的效果，参考 https://github.com/libretro/slang-shaders/blob/master/misc/image-adjustment.slang

> 比如Nier游戏是典型的 “窗口化时1080是真的1080，全屏用1080却是模糊的720” 游戏。

我不会添加用于给某些游戏擦屁股的功能。1080P 的屏幕上不可能完美操作 1080P 的窗口化游戏，这是操作系统的限制。

**Comment by Kylejustknows** [comment]
> 通过着色器可以粗略模拟调节亮度，比不上游戏内置的，尤其是 3D 游戏。我会添加一个用于调节各种杂项参数的效果，参考 https://github.com/libretro/slang-shaders/blob/master/misc/image-adjustment.slang
> 
> > 比如Nier游戏是典型的 “窗口化时1080是真的1080，全屏用1080却是模糊的720” 游戏。
> 
> 我不会添加用于给某些游戏擦屁股的功能。1080P 的屏幕上不可能完美操作 1080P 的窗口化游戏，这是操作系统的限制。
> 
嗯嗯明白。不过看起来还是好沉重啊。在画面输入、输出的环节上，没有什么“投机取巧”快速实现亮度调节的方法了是吧？

**Comment by Blinue** [comment]
更改显示器或系统亮度就不会有性能损失了...

Magpie 的渲染是完全在 GPU 上执行的，所以增加功能必定要修改着色器。如果将调整亮度的功能内置，理论上可以更快，但这会让所有人都付出计算成本，即使大部分人用不上它。

**Comment by hooke007** [comment]
此外 N卡的experience软件里是有这个功能的

<img src="https://user-images.githubusercontent.com/41094733/174064978-62ba44d3-1ba4-47f3-8db4-fe46dc95272c.jpg" height=500>

**Comment by Blinue** [comment]
使用 ImageAdjustment 效果调节亮度。
