### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by wukibaka** [Blinue/Magpie#392]
### Magpie version 程序版本

0.9.0

### Windows version 系统版本

win10 LTSB2015

### Related screenshot (optional) 相关截图（可选）

![image](https://user-images.githubusercontent.com/51240031/174059980-64b9405a-10e1-4d9d-80d3-7f7ed373e2d3.png)
![image](https://user-images.githubusercontent.com/51240031/174060591-69c28745-2cae-41ca-b0c6-7c60c1185195.png)

### Reproduction steps 复现步骤

下载并解压Magpie
安装所需的两个依赖
打开

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/8918401/Magpie.log)

**Comment by Blinue** [comment]
需要先安装运行时 https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by wukibaka** [comment]
> 需要先安装运行时 https://aka.ms/vs/17/release/vc_redist.x64.exe

已安装

**Comment by Blinue** [comment]
[Magpie_dev_92c7719.zip](https://github.com/Blinue/Magpie/files/8923629/Magpie_dev_92c7719.zip)
这个版本能运行吗

**Comment by wukibaka** [comment]
> [Magpie_dev_92c7719.zip](https://github.com/Blinue/Magpie/files/8923629/Magpie_dev_92c7719.zip) 这个版本能运行吗

依旧是初始化失败

**Comment by wukibaka** [comment]
> 不确定少了哪个依赖，10240 太旧了。
> 
> [Dependencies_x64_Release.zip](https://github.com/Blinue/Magpie/files/8924198/Dependencies_x64_Release.zip)
> 
> 这是一个用于检测依赖的软件，打开 DependenciesGui.exe 然后拖入 MagpieRT.dll 看看是哪些 dll 缺失了。

![image](https://user-images.githubusercontent.com/51240031/174216289-83a2307e-92d7-4f82-b318-4f1614e715e2.png)
怎么看 不懂这些东西

**Comment by wukibaka** [comment]
> 谢谢，我找到问题所在了。因为使用了 [GetDpiForWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow)，现在 Magpie 要求 v1607 (build 14393)。10240 已不再支持。你可以用老版本试试。

大概要多老的版本呢

**Comment by hooke007** [comment]
> 大概要多老的版本呢

上个版本 0.8.2 都无法使用吗

**Comment by wukibaka** [comment]
> > 大概要多老的版本呢
> 
> 上个版本 0.8.2 都无法使用吗

可以用
