### ISSUE TITLE
在Sandboxie沙箱里使用Magpie捕获视窗出现双光标问题。

### ISSUE THREAD

**Issue by lalic9** [Blinue/Magpie#393]
### Magpie version 程序版本

0.9.0

### Windows version 系统版本

win11 22H2 22621.105

### Reproduction steps 复现步骤

1.在win11 22H2内开启Sandboxie沙箱。
2.Sandboxie沙箱内开启Magpie与其他程序。
3.尝试捕获模式(DD/GDI/DSS)捕获视窗。
4.出现双光标。

*捕获后的光标可正常使用、仅源光标无法被正常隐藏。

这可能是小众问题，任何的回答都不胜感激，谢谢。

### Log files 日志文件

无

**Comment by Blinue** [comment]
在 VMware 中也会遇到同样的问题，大概虚拟机会对光标做特别处理，可能会自己绘制，因此不会遵守隐藏光标的调用。

这个 bug 影响不大，因此没有修复计划。
