### ISSUE TITLE
建议：截屏时隐藏光标 / Magpie自带忽略光标的截屏

### ISSUE THREAD

**Issue by hiroi-sora** [Blinue/Magpie#394]
### Expected behavior 预期的功能

win截屏（Win+PrtSc或Win+Shift+S）默认不会截到屏幕上的光标。而开启Magpie后，截屏始终能截到光标。

能否添加功能：系统截屏时隐藏光标。或者软件内自带截图功能：保存不含光标的当前全屏截图到指定路径。

您的项目非常好用。感谢！！

另：我尝试用AHK脚本来在截屏时隐藏光标。这段代码在别的场景中运行良好，可惜还是不能用在Magpie中；隐藏光标的`ChangeCursor()`不生效。

**Comment by Blinue** [comment]
Magpie 中的光标是自行绘制的，实际上是画面的一部分。在系统截屏时隐藏光标或许可行，只需监测 PrintScreen 键，我会调查一下。

你使用的 AHK 脚本将系统光标替换为透明，但这对 Magpie 不起作用。Magpie 不会检测系统光标的变化，这是出于性能考虑。

**Comment by Blinue** [comment]
经过测试，检测 PrintScreen 键是可行的。这个功能将在 v0.10 提供，谢谢建议！

**Comment by hiroi-sora** [comment]
> 经过测试，检测 PrintScreen 键是可行的。这个功能将在 v0.10 提供，谢谢建议！

感谢你的开发。非常期待新功能~

**Comment by Blinue** [comment]
v0.10 已发布 🎉
