### ISSUE TITLE
有没有可能增加waifu2x

### ISSUE THREAD

**Issue by zdrzdr** [Blinue/Magpie#401]
### Expected behavior 预期的功能

会不会考虑加入waifu2x呀
720→1440的缩放在我机器（2080）差不多1秒1-2帧，如果有简化的模型加上马上出40系显卡，估计可以到10帧左右，对galgame来说是非常可用的级别了（其实现在的2帧也是可用的）
对比现在所有滤镜的效果来说，waifu2x在galgame缩放方面可以说是完美的

**Comment by Blinue** [comment]
Duplicate of #383
