### ISSUE TITLE
无法正常运行问题

### ISSUE THREAD

**Issue by Johnson847** [Blinue/Magpie#409]
### Question 问题

您好，我在下载解压.zip包后，双击运行.exe文件没有任何反应（默认管理员权限运行），任务管理器中也没有新增任务，请问有否解决方法？
我另在Bilibili看到一个介绍如何使用Magpie的视频，其中我注意到.zip解压出来后根目录下有一个.json文件，而我这里没有，不知和这个问题是否有关

**Comment by Blinue** [comment]
试试更新.net运行时

**Comment by Johnson847** [comment]
感谢回复，不过我检查下来电脑里只有.Net Runtime 6.0.1，没有常见的Framework，用工具在Powershell里查了下，版本显示为“4.8 or later”，在官网安装4.8也提示我无法安装，这种情况应该是最新了吧？不好意思这方面知识贫乏...

**Comment by Blinue** [comment]
需要 6.0.4 版本， [系统需求](https://github.com/Blinue/Magpie#%E7%B3%BB%E7%BB%9F%E9%9C%80%E6%B1%82)里有下载链接。

**Comment by Johnson847** [comment]
噢噢看到了，第一时间没反应过来“运行时”就是“Runtime”，那求教Framework和Runtime的关系？

**Comment by Blinue** [comment]
.NET 和 .NET Framework 是不同的东西，Magpie 使用的是 .NET。简单说 .NET (也叫 .NET Core) 是  .NET Framework 的开源版本和继任者，具体区别自行百度。

**Comment by Johnson847** [comment]
噢噢多谢解答，程序已经可以正常使用了
