### ISSUE TITLE
How do you use it ( new to Github and stuff )

### ISSUE THREAD

**Issue by MorderczkazPolski12** [Blinue/Magpie#41]
Hello.

Recently I've read about Magpie on Tom's Hardware, and wanted to give this a try, have few games that I would want to have FSR in, but it is what it is, so I tried to download this, pressed "< > Code " then  green button with "Code" and " download as ZIP ".

BUT... how do I use it? tried opening everything i saw as " Application " but nothing would work, It's my first time on Github and completely lost already. Not sure if I write this in the right thread but this is too advance for me

**Comment by Blinue** [comment]
Hello, you can download binary from [here](https://github.com/Blinue/Magpie/releases). [This link](https://www.reddit.com/r/Amd/comments/oxcqfy/magpie_allows_fsr_modded_into_any_windows_game/h7o5bd0?utm_source=share&utm_medium=web2x&context=3) explains how to use it.

**Comment by MorderczkazPolski12** [comment]
> Hello, you can download binary from [here](https://github.com/Blinue/Magpie/releases). [This link](https://www.reddit.com/r/Amd/comments/oxcqfy/magpie_allows_fsr_modded_into_any_windows_game/h7o5bd0?utm_source=share&utm_medium=web2x&context=3) explains how to use it.

thanks!
