### ISSUE TITLE
How can you use magpie to downscale a higher application resolution to a smaller screen resolution?

### ISSUE THREAD

**Issue by kanjieater** [Blinue/Magpie#410]
### Question 问题

Is there any way to get a downscaler working with a smaller monitor? So if I have a 640x480 tv that I'm trying to get a 800x600 game to run on, it can run full screen via magpie?

I tried using the SSimDownscaler, but when I try to run a 800x600 game on my 480i screen, the parts that are not on the screen of the 800x600 app don't get updated on the 480i screen.

**Comment by kanjieater** [comment]
Alternatively, could I run the game on one screen and use magpie to "fullscreen" it to another screen?

**Comment by Blinue** [comment]
> Is there any way to get a downscaler working with a smaller monitor? So if I have a 640x480 tv that I'm trying to get a 800x600 game to run on, it can run full screen via magpie?

You shouldn't use magpie to downscale. Select "Duplicate displays" in your display settings.
https://www.tenforums.com/tutorials/21084-multiple-displays-change-settings-layout-windows-10-a.html

> Alternatively, could I run the game on one screen and use magpie to "fullscreen" it to another screen?

No, you can't. Magpie is not designed for this use.

**Comment by kanjieater** [comment]
Thank  you. While it would be nice to be able to support downscaling, I understand. For anyone else, I found this link: https://superuser.com/questions/1371923/cloning-a-4k-panel-to-a-1080p-monitor

I am using the OBS mirroring solution
