### ISSUE TITLE
开启全屏后光标回弹

### ISSUE THREAD

**Issue by k2250761** [Blinue/Magpie#411]
### Magpie version 程序版本

0.91

### Windows version 系统版本

win10

### Related screenshot (optional) 相关截图（可选）

如题、全屏后光标会有重影 并且有回弹的问题 像是被锁定了一
![HJNX7{~CGRENL@}VB 1CSM0](https://user-images.githubusercontent.com/61865659/182496536-0f0daeaf-bccf-4147-8e9b-d53e8127e78b.png)

https://user-images.githubusercontent.com/61865659/182496574-f1a0fde7-4a70-41b4-a95a-624f2227b066.mp4

### Reproduction steps 复现步骤

开启全屏后点击就会出现

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/9246844/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/9246845/Runtime.log)

**Comment by Blinue** [comment]
你的操作系统版本是 20H2，理论上不会遇到双光标问题。所有游戏都有这个问题吗？注意Magpie 只能在窗口化的游戏中使用。

**Comment by k2250761** [comment]
视觉小说游戏肯定是窗口化，这个问题前几个版本也有，别类型游戏没测，我玩的视觉小说游戏几乎都是这个情况

**Comment by k2250761** [comment]
> 你的操作系统版本是 20H2，理论上不会遇到双光标问题。所有游戏都有这个问题吗？注意Magpie 只能在窗口化的游戏中使用。

视觉小说游戏肯定是窗口化，这个问题前几个版本也有，别类型游戏没测，我玩的视觉小说游戏几乎都是这个情况

**Comment by Blinue** [comment]
试试更换捕获模式，双光标问题只在 Graphics Capture 捕获模式下存在

**Comment by k2250761** [comment]
> 试试更换捕获模式，双光标问题只在 Graphics Capture 捕获模式下存在

我发现了,全屏化的时候 某些窗口前置了就会变成这样,这个能解决吗

**Comment by Blinue** [comment]
打开3D游戏模式。是不是有其他透明且置顶的窗口，能找到是什么程序创建的吗？

**Comment by k2250761** [comment]
> 打开3D游戏模式。是不是有其他透明且置顶的窗口，能找到是什么程序创建的吗？

3D模式有效,已经解决,感谢
