### ISSUE TITLE
Absolute mouse positioning / lightgun aim

### ISSUE THREAD

**Issue by cor094** [Blinue/Magpie#413]
When using this program with PC lightguns, the aim is way off. I'm guessing it has to do with their use of rawinput and absolute mouse coordinates. Not sure if there is any way to fix this. I tried messing with the cursor speed setting, but it didn't make any difference. When using BorderLessGaming to resize the game from windowed to fullscreen, the aim is still good, but of course it has bad pixelation without your program. Thanks

**Comment by Blinue** [comment]
Unlike BorderlessGaming, Magpie does not support input devices other than the mouse.
