### ISSUE TITLE
有没有可能限制magpie的采集率和游戏帧率相同

### ISSUE THREAD

**Issue by Ptilopsis01** [Blinue/Magpie#414]
如题，我的游戏帧率只有50几，但ctrl+alt+d显示的帧率能达到100帧，反而影响了原本游戏的性能
有没有可能增加一个选项，可以限制magpie的窗口采集率和窗口实际帧率相同，这样可以尽最大可能把显卡资源留给游戏本体

**Comment by hooke007** [comment]
dup? https://github.com/Blinue/Magpie/issues/378

**Comment by Blinue** [comment]
1. Magpie 是非侵入性的，否则无法在联机游戏中使用。这种情况下无法检测游戏帧率。
2. 即使注入游戏进程，获得游戏帧率也是非常困难的，这涉及到图形 API 的检测和注入。
3. Magpie 不支持以可变帧率渲染，这会使鼠标卡顿。

总之虽然这是个实用的功能，但目前看来不可能实现。

**Comment by Ptilopsis01** [comment]
> 1. Magpie 是非侵入性的，否则无法在联机游戏中使用。这种情况下无法检测游戏帧率。
> 2. 即使注入游戏进程，获得游戏帧率也是非常困难的，这涉及到图形 API 的检测和注入。
> 3. Magpie 不支持以可变帧率渲染，这会使鼠标卡顿。
> 
> 总之虽然这是个实用的功能，但目前看来不可能实现。

我也猜到了恐怕不太可行，感谢解答
