### ISSUE TITLE
CRT-Geom Causing Image Retention on ips displays

### ISSUE THREAD

**Issue by ps1freak26** [Blinue/Magpie#415]
### Expected behavior 预期的功能

There should not be interlacing in the CRT Geom shader since this program is mainly for pc games with progressive resolutions. This has caused temporary image retention on my LG 32 inch QHD IPS monitor but goes away eventually since I don't use it for hours so my monitor is fine but used enough hours will cause permanent burn in.

Solution: In the shader CRT_Geom.hlsl the default should be set to this

//!PARAMETER
//!DEFAULT 0
//!MIN 0
//!MAX 1
int interlace;

**Comment by Blinue** [comment]
The default value comes from upstream:
https://github.com/libretro/common-shaders/blob/master/crt/shaders/crt-geom.cg#L16

As you said, since Magpie is mainly for PC, it makes more sense to turn off interlacing by default.
