### ISSUE TITLE
能参考obs那样抓“游戏源”窗口吗？

### ISSUE THREAD

**Issue by clatv** [Blinue/Magpie#418]
### Expected behavior 预期的功能

特别是一些模拟器玩游戏就不会被抓到菜单栏了，有利于画面完美缩放
手动裁剪对强迫症来说调整起来有些麻烦

**Comment by Blinue** [comment]
默认捕获窗口的客户区，因此是不会捕获到系统菜单的。请放和 obs 的对比

**Comment by clatv** [comment]
> 默认捕获窗口的客户区，因此是不会捕获到系统菜单的。请放和 obs 的对比

https://www.youtube.com/watch?v=3HOwM9d4N5o

**Comment by Blinue** [comment]
谢谢反馈。这个菜单不是系统菜单，但 OBS 可以自动裁剪，我会研究一下 OBS 的实现。

**Comment by Blinue** [comment]
1. 为什么会捕获到菜单栏？
这类模拟器使用 QT 作为 UI 框架，QT 中的菜单不是系统菜单，而是自行创建的子窗口，因此在操作系统看来，此菜单是客户区的一部分。

2. 为什么 OBS 没有捕获到菜单栏？
OBS 有多种捕获模式，Magpie 中的捕获模式类似于“窗口采集”功能。在 OBS 中使用窗口采集时，菜单栏也会被捕获到。
OBS 的“游戏源”功能非常复杂，它注入游戏进程，hook 多种图形 API，包括 DirectX 的所有版本、OpenGL、Vulkan 等，每当游戏呈现新的帧，都将此帧传送给 OBS 呈现。mGBA 使用了某种图形接口呈现内容，于是被 OBS 捕获到了。

3. 如果解决这个 bug？
没有办法。我不会在 Magpie 种实现“游戏源”功能，这种捕获方法很脆弱，维护也很麻烦，很有可能被反作弊软件误判（为什么 OBS 不会？因为它位于这些软件的白名单中）。
最后的解决办法是自定义裁剪，v0.10 将实现针对特定窗口的配置，那时这个功能会好用很多。
