### ISSUE TITLE
希望增加锁帧功能

### ISSUE THREAD

**Issue by bbc117** [Blinue/Magpie#419]
### Expected behavior 预期的功能

在玩ADV和RPG游戏时使用Magpie帧数会到屏幕的刷新率的帧数，但实际上60pfs就已经够用了，但程序没有锁帧功能显卡会到最高工作状态，此时显卡温度会很高噪声也很大，会造成不必要的显卡资源浪费，所有希望增加锁帧功能。

**Comment by Blinue** [comment]
和 #378 重复。以及一个计划中的替代方案 https://github.com/Blinue/Magpie/discussions/362#discussioncomment-3035551

**Comment by Blinue** [comment]
如果静止画面较多使用 Desktop Duplication 捕获模式可以大幅降低功耗

**Comment by bbc117** [comment]
> 如果静止画面较多使用 Desktop Duplication 捕获模式可以大幅降低功耗

使用 Desktop Duplication会报原窗口尺寸不能超过屏幕大小，我最后使用NIVEA的驱动来完成的锁帧功能。
