### ISSUE TITLE
请问自定义裁剪功能应该怎么使用？

### ISSUE THREAD

**Issue by Gott-L** [Blinue/Magpie#420]
### Question 问题

上下左右四个值应该怎么计算获取，希望大佬解答一下，感激不尽。

**Comment by Blinue** [comment]
自行测量或多次尝试，单位为像素。

**Comment by hooke007** [comment]
截图边缘之后图片的宽高信息

**Comment by Gott-L** [comment]
> 自行测量或多次尝试，单位为像素。



> 截图边缘之后图片的宽高信息


测了很多次，4k屏幕，4k分辨率，potplayer拉到1920*1080尺寸，放到左上角。
比如
上0 下1080 左0 右1920
会出现窗口不够，但是实际应该是够得
然后
上0 下720 左0 右1280
会出现只截取很小的一部分窗口
调大
上0 下900 左0 右1500
反而也没有截取增多，因此发现这些都有点问题，且没有规律，在想是不是自己理解错误。

**Comment by Gott-L** [comment]
查阅了0.81的说明，也完全没有详细计算和上下左右的定义，因此希望您可以补充一下

**Comment by Blinue** [comment]
这个选项的意思是在四个方向各裁剪多少像素，没想到你在这里有误解

**Comment by Gott-L** [comment]
> 抱歉，还是有点疑惑，中心点是哪，是在原有的画面裁剪吗

**Comment by Gott-L** [comment]
感谢大佬们~
