### ISSUE TITLE
Frame duplication and interpolation.

### ISSUE THREAD

**Issue by s-andro** [Blinue/Magpie#421]
### Expected behavior 预期的功能

They should produce stable visual effects even at low frame rates.

The following will be necessary

- Make it possible to set the frame rate for capturing in the application settings.
- A way to know if the current frame is a duplicate.
- Two color buffers for the previous frame, the original and the effect was applied.

**Comment by Blinue** [comment]
Unfortunately there is no efficient way to compare two frames. The method you describe is similar to Graphics Capture, which captures new frames only when the screen changes. The biggest problem with low frame rates is mouse lag.
