### ISSUE TITLE
光标在放大后与更上层的屏幕覆盖产生交互，导致光标位置移出源程序边界

### ISSUE THREAD

**Issue by Cecropis** [Blinue/Magpie#422]
### Magpie version 程序版本

0.9.1

### Windows version 系统版本

win10 21H1

### Related screenshot (optional) 相关截图（可选）

![2022-09-05 022724](https://user-images.githubusercontent.com/30413607/188323516-63ca583b-9aad-4b5a-b4d2-64e94cc183fb.png)

### Reproduction steps 复现步骤

启用任意显示在其他程序之上的overlay，如Crosshair，visual novel reader，misakatranslator等。再启用magpie放大目标程序，当光标运动到上述程序的overlay之上时就会产生闪烁，同时光标突破原有应用的边界或产生不可预知的运动。
在0.8.0版本没有类似问题。

### Log files 日志文件

[Runtime.log](https://github.com/Blinue/Magpie/files/9485058/Runtime.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/9485059/Magpie.log)
log涵盖一次启动放大到鼠标失控然后停止放大的全过程，测试放大的是windows资源管理器窗口，屏幕覆盖用的是微软商店的Crosshair V2。
本次测试中打开了不绘制光标，点击overlay区域后光标会消失。不打开不绘制光标选项时会观察到光标强制返回原区域。

**Comment by Blinue** [comment]
正在调查

**Comment by Cecropis** [comment]
打开 3D 游戏模式确实有效

**Comment by Blinue** [comment]
这个 bug 已被修复。谢谢反馈
