### ISSUE TITLE
Doesn't start after version 0.8.1

### ISSUE THREAD

**Issue by r57zone** [Blinue/Magpie#429]
### Magpie version 程序版本

0.8.2

### Windows version 系统版本

Win 10 21H2 Professional x64

### Related screenshot (optional) 相关截图（可选）

Starting from version 0.8.1, new versions of MagPie are not start. Version 0.8.1 is last working.

### Reproduction steps 复现步骤

1. Run Win 10 21H2 Professional x64 (maybe).
2. Start MagPie 0.8,2 or newer.

### Log files 日志文件

No logs are written, it just doesn't start.

**Comment by Blinue** [comment]
https://github.com/Blinue/Magpie/issues/377

**Comment by r57zone** [comment]
This helped, thanks!
