### ISSUE TITLE
关于程序弹出需要.net环境之后点击是跳转到的连接有问题

### ISSUE THREAD

**Issue by Roc893158890** [Blinue/Magpie#430]
### Magpie version 程序版本

0.9.1

### Windows version 系统版本

win11

### Reproduction steps 复现步骤

再没有安装.net6 的电脑上打开软件会提示需要安装.net，点击是后会调转到.net下载页面，但跳转的下载页面有误。
实际上[v0.9.0](https://github.com/Blinue/Magpie/releases/tag/v0.9.0)中提到了需要的是
[.NET 6.0.4 Desktop 运行时](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.4-windows-x64-installer)
而实际跳转地址是
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.9-windows-x64-installer
这导致了安装完了这个.net之后仍然会提示未安装.net，直到安装了desktop版本的.net

### Log files 日志文件

无

**Comment by Blinue** [comment]
这是 .NET 的已知错误 https://github.com/dotnet/runtime/issues/36765
v0.10 不再依赖 .NET，这个问题也就不存在了。

**Comment by Roc893158890** [comment]
啊,真的很抱歉,我没有看完全部的列表.感谢您的回复.
