### ISSUE TITLE
部分游戏放大后游戏内画面速度显著变慢

### ISSUE THREAD

**Issue by Ptilopsis01** [Blinue/Magpie#432]
### Magpie version 程序版本

0.9.1

### Windows version 系统版本

win11 22H2

### Reproduction steps 复现步骤

在用magpie放大i社新作roomgirl的时候发现放大后游戏内画面速度会显著变慢
游戏帧率约为40帧，显示器刷新率165hz，而游戏画面变慢的速度目测正好是原来的四分之一，不知道有没有什么联系
窗口采集模式GDI和Dwmxxx无法正常工作，而graphic capture和desktop duplication都有这一现象，应该不是窗口采集模式的原因
ctrl+alt+d显示的采集帧率基本一直稳定在165hz，放大后游戏内帧率并未有明显变化（只有magpie占用显卡资源导致的略微降低）

### Log files 日志文件

[Magpie.1.log](https://github.com/Blinue/Magpie/files/9690850/Magpie.1.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/9690851/Magpie.log)
[Runtime.1.log](https://github.com/Blinue/Magpie/files/9690852/Runtime.1.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/9690853/Runtime.log)

**Comment by Blinue** [comment]
关闭directflip有用吗？

**Comment by Ptilopsis01** [comment]
> 关闭directflip有用吗？

画面速度正常了，但是似乎会出现跳帧的问题，画面非常不流畅

**Comment by Blinue** [comment]
看来有兼容性的问题，我怀疑这个游戏在渲染上有骚操作。这种问题很难修复，只能把它当作一个已知的不兼容的游戏。
