### ISSUE TITLE
Is it possible to use AdaptiveSharpen together with FSR?

### ISSUE THREAD

**Issue by Com3Carne** [Blinue/Magpie#434]
### Question 问题

If this has already been asked, I'm sorry. There must be a way? If there is, what would be the configuration to put in **ScaleModels.json**?

**Comment by Blinue** [comment]
Docs for ScaleModels.json is [here](https://github.com/Blinue/Magpie/wiki/Customizing_Scaling_Configurations). In order to edit this file, you need to understand json first.
