### ISSUE TITLE
Magpie does not work properly on monitors with different orientations

### ISSUE THREAD

**Issue by MarvNC** [Blinue/Magpie#436]
### Magpie version 程序版本

0.9.1

### Windows version 系统版本

win 10 2006

### Related screenshot (optional) 相关截图（可选）

![image](https://user-images.githubusercontent.com/17340496/195261151-2ef1429c-fc73-4658-b301-8fef90bdcc12.png)
![image](https://user-images.githubusercontent.com/17340496/195261533-9a5db47e-4259-4d29-89ec-4820bbe53736.png)
![image](https://user-images.githubusercontent.com/17340496/195261542-bcfbf910-610f-4f0f-8849-2f1664fc5caf.png)

### Reproduction steps 复现步骤

- Enable Magpie on a window in a monitor that has a different orientation

### Log files 日志文件

[Magpie.1.log](https://github.com/Blinue/Magpie/files/9761944/Magpie.1.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/9761945/Magpie.log)
[Runtime.1.log](https://github.com/Blinue/Magpie/files/9761946/Runtime.1.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/9761948/Runtime.log)

**Comment by Blinue** [comment]
Duplicate of #435 

As far as I know, only Desktop Duplication has this issue.

**Comment by MarvNC** [comment]
Thanks for the response. It's not an issue for me but I didn't expect that it was already reported.
