### ISSUE TITLE
当系统本身设置了缩放之后，无法全屏。

### ISSUE THREAD

**Issue by cexer** [Blinue/Magpie#437]
### Magpie version 程序版本

0.9.1.0

### Windows version 系统版本

win10专业版19043.1023

### Related screenshot (optional) 相关截图（可选）

![剪贴板图片](https://user-images.githubusercontent.com/14016313/196019347-d661907c-c0b4-456b-9905-892d332100aa.jpg)

![剪贴板图片 (1)](https://user-images.githubusercontent.com/14016313/196019352-3f8b267d-cd69-41bf-bc88-40e18ebd5665.jpg)

### Reproduction steps 复现步骤

设置系统缩放比例为200，使用magpie对游戏进行缩放，
预期效果：铺满全屏
实际效果：缩放后的游戏只覆盖屏幕左上角部分。

### Log files 日志文件

[Runtime.log](https://github.com/Blinue/Magpie/files/9793600/Runtime.log)
[Magpie.log](https://github.com/Blinue/Magpie/files/9793601/Magpie.log)

**Comment by Blinue** [comment]
显然你有某种特殊的屏幕配置。Magpie 是 DPI 感知的，但检测到你的屏幕分辨率为 1024x768。以及你缩放的窗口 DPI 缩放是 **0.5**，这很不正常，应该是 1（如果窗口是 DPI 感知的）或 2（如果不是）。

你能试试其他配置吗？

- 其他系统缩放比例下能否工作？
- 在其他窗口上能否工作？

**Comment by cexer** [comment]
> 显然你有某种特殊的屏幕配置。Magpie 是 DPI 感知的，但检测到你的屏幕分辨率为 1024x768。以及你缩放的窗口 DPI 缩放是 **0.5**，这很不正常，应该是 1（如果窗口是 DPI 感知的）或 2（如果不是）。
> 
> 你能试试其他配置吗？
> 
> * 其他系统缩放比例下能否工作？
> * 在其他窗口上能否工作？

多谢老哥。根据你说的测试：
1. 150%缩放比下，也不正常，效果和200时差不多，这时候magpie本身显示也有点不对了，右边多了黑色的背景。
2. 100%时是正常的，鼠标也正常。不过触屏位置不正常。

另外我这个设备是个win10的平板，游戏设置的DPI处理是“应用程序”（试过不设置这个也一样的效果）

![剪贴板图片 (2)](https://user-images.githubusercontent.com/14016313/196020348-1874a602-c0d7-49e8-abdd-0823bd7ae096.jpg)

![剪贴板图片 (3)](https://user-images.githubusercontent.com/14016313/196020354-467e1b81-4bf0-4535-aef4-f2b071b74aa2.jpg)

**Comment by Blinue** [comment]
触控问题见 #218 

将 Magpie 的 DPI 缩放设成“应用程序”试试。你正在远程桌面吗？

**Comment by cexer** [comment]
> 触控问题见 #218
> 
> 将 Magpie 的 DPI 缩放设成“应用程序”试试。你正在远程桌面吗？
好的，触控的我另外看下。

把 magpie  的DPI设置成"应用程序“，这个尝试过，效果是一样的。
平板上没鼠标，所以我是远程的，不过在平板上本地测试，也是一样的效果。

**Comment by Blinue** [comment]
我本地的测试结果：

150% 缩放
![image](https://user-images.githubusercontent.com/34770031/196021056-3f369af7-1af3-4f92-bbb4-ed2b7209c28c.png)
![image](https://user-images.githubusercontent.com/34770031/196021079-0f624129-c4b2-4f0b-8c1d-661adaed0d31.png)

自从 v0.8 以来没有其他人反馈过 DPI 缩放问题，Magpie 甚至支持跨越 DPI 缩放不同的多屏幕。你可能有某种配置使 Magpie 无法正常工作，比如显示器驱动。据我所知，远程桌面软件通常会安装特殊驱动改变屏幕的工作方式。

**Comment by cexer** [comment]
> 我本地的测试结果：
> 
> 150% 缩放 ![image](https://user-images.githubusercontent.com/34770031/196021056-3f369af7-1af3-4f92-bbb4-ed2b7209c28c.png) ![image](https://user-images.githubusercontent.com/34770031/196021079-0f624129-c4b2-4f0b-8c1d-661adaed0d31.png)
> 
> 自从 v0.8 以来没有其他人反馈过 DPI 缩放问题，Magpie 甚至支持跨越 DPI 缩放不同的多屏幕。你可能有某种配置使 Magpie 无法正常工作，比如显示器驱动。据我所知，远程桌面软件通常会安装特殊驱动改变屏幕的工作方式。

好的，我换个驱动试试。谢谢老哥。
