### ISSUE TITLE
[Feature Request] Allow the usage of the Tab key to upscale things with Magpie

### ISSUE THREAD

**Issue by LOuroboros** [Blinue/Magpie#443]
### Expected behavior 预期的功能

While setting up a hotkey to upscale things with Magpie, I can type certain combos of keys and they work fine.

For example, I can type "Alt + F" in the text box and it works as expected.

However, if I type "Tab + F", the text appears in red color implying it's not a valid key for some reason.

![Magpie_20221025_140617138](https://user-images.githubusercontent.com/4485172/197837773-27b88479-f8dc-4d94-9555-7d05d9cbcdb6.png)

![Magpie_20221025_140621191](https://user-images.githubusercontent.com/4485172/197837780-37facd69-ac4d-417b-b83f-7d1b00e97126.png)

And effectively, if I leave it like that, pressing "Tab + F" does not allow me to upscale a game's window using Magpie.

"Alt+F" does work fine though.

### Alternative behavior (optional) 近似的功能（可选）

I'd like to see Magpie allow the usage of the Tab key for its hotkey combos.

**Comment by Blinue** [comment]
Tab is not allowed to be used as a shortcut key. On the one hand, it is a special system key to navigate between controls, and on the other hand, Tab is not supported by [globalmousekeyhook](https://github.com/gmamaladze/globalmousekeyhook), which is the hotkey implementation in v0.9.

v0.10 changed the way hotkeys are implemented, but Tab is still not supported. Some keys are special and should not be used as shortcut keys, such as Tab, Esc, CapsLock, PrintScreen, etc.

![hotkey](https://user-images.githubusercontent.com/34770031/197910874-fcd0a69c-e4d4-4e55-9fa1-d2437238de5f.gif)

**Comment by LOuroboros** [comment]
I mean, Windows itself uses Tab for some of its shortcuts such as Alt+Tab, and there's actually a program that is similar to Magpie called "Lossless Scaling", and it allows you to use the Tab key for its shortcut combo too.

But I understand you made up your mind and this is not going to change, so I'll just get used to Alt+F. Closing. Thanks for the reply!
