### ISSUE TITLE
建议增加功能：窗口失焦后保持全屏

### ISSUE THREAD

**Issue by EXBJAN** [Blinue/Magpie#447]
### Expected behavior 预期的功能

感谢大佬辛劳！
希望增加该功能的原因是，比如在搭配如翻译器使用时，常常因为选择或拖动翻译器导致窗口恢复，游戏体验不佳。

**Comment by Blinue** [comment]
我不认为这是常见的需求。翻译器应该是非侵入性的，不应该接收焦点，可以使用 WS_EX_NOACTIVATE 达到这一点。

**Comment by Blinue** [comment]
[LunaTranslator](https://github.com/HIllya51/LunaTranslator) 目前使用修改版本来实现这个功能，如果原生支持会很有用。

第三方程序将可以使用 Windows 消息和[窗口属性](https://learn.microsoft.com/en-us/windows/win32/winmsg/about-window-properties)和 Magpie 交互。
