### ISSUE TITLE
使用v0.10.0-preview1遇到了好几个问题

### ISSUE THREAD

**Issue by pxk888** [Blinue/Magpie#448]
### Magpie version 程序版本

v0.10.0-preview1

### Windows version 系统版本

Win11 家庭版 22H2 22621.755

### Related screenshot (optional) 相关截图（可选）

快捷键不起作用(管理员也不行)，但可以使用5秒后缩放;使用ACNet上下有黑边,不能自适应到全屏
![1新建 BMP 图像 (2)](https://user-images.githubusercontent.com/25244319/200587919-8ff5977e-6e11-4119-9abe-18d5b9e09f2e.png)

重启资源管理器后任务栏图标没了
![image](https://user-images.githubusercontent.com/25244319/200588694-5aa9461f-134e-4b1a-9c01-07a458127170.png)

### Reproduction steps 复现步骤

显卡GTX 1650Ti,笔记本,分辨率1920x1080
(1)玩东方project系列作品时放大的快捷键不起作用,管理员也没用(神灵庙汉化版除外),但可以使用5秒后缩放。0.9.1版本无此问题。[(在这里下的游戏)](https://cloud.lilywhite.cc/s/4ZUW?path=%2F%E4%B8%9C%E6%96%B9Project%2F%E5%AE%98%E6%96%B9%E6%B8%B8%E6%88%8F%2F%E6%95%B4%E6%95%B0%E4%BD%9C)

(2)使用ACNet、Anime4K、FSRCNNX等放大比较小的窗口时只能放大到原来的2倍,不能自适应到全屏。0.9.1版本无此问题

(3)资源管理器崩溃重启后任务栏图标不见了
[config.json.txt](https://github.com/Blinue/Magpie/files/9961994/config.json.txt)

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/9962081/magpie.log)

**Comment by Blinue** [comment]
谢谢反馈。第二点不是 bug，v0.10 中的算法有所改变，默认配置不会放大窗口。如果你想获得和 v0.9 相同的行为，在 ACNet 后添加 Bicubic 即可，虽然我更推荐使用其他更好的放大算法。

第一点和第三点正在调查中。

**Comment by Blinue** [comment]
热键问题已经修复🎉 再次感谢反馈！
