### ISSUE TITLE
打开“缩放模式”页面会卡死闪退

### ISSUE THREAD

**Issue by Ptilopsis01** [Blinue/Magpie#456]
### Magpie version 程序版本

0.10.0-preview1

### Windows version 系统版本

win11 22621.819

### Reproduction steps 复现步骤

此前一直是正常的，某一次启动后就一直出现这一问题，即使把文件夹内所有文件都删除后重装也无法解决

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/10034583/magpie.log)

**Comment by Blinue** [comment]
Magpie 的配置文件存储在 "C:\Users\(用户名)\AppData\Local\Magpie\config\config.json"，请贴出。你也可以试试删除这个文件

**Comment by Ptilopsis01** [comment]
> Magpie 的配置文件存储在 "C:\Users\(用户名)\AppData\Local\Magpie\config\config.json"，请贴出。你也可以试试删除这个文件

这个也删除试过，还是会有一样的问题

**Comment by Blinue** [comment]
请上传你正在使用的配置，否则我没法复现

**Comment by Ptilopsis01** [comment]
> 请上传你正在使用的配置，否则我没法复现

我又尝试了一下，完全清除之后重新安装可以正常使用，但只要导入我此前的配置文件就会卡死
[config.zip](https://github.com/Blinue/Magpie/files/10038643/config.zip)

**Comment by Ptilopsis01** [comment]
> 崩溃是因为未找到 CRT_Cathode，将 CRT_Cathode.hlsl 复制到 effects 文件夹即可。
> 
> 未找到某个效果时应显示错误而不是崩溃，这是一个已知问题。
明白了

**Comment by Blinue** [comment]
v0.10 中已修复。
