### ISSUE TITLE
拖动模式内缩放配置顺序闪退 0.10-preview1

### ISSUE THREAD

**Issue by sha7dowXX** [Blinue/Magpie#457]
### Magpie version 程序版本

最新构造0.10preview

### Windows version 系统版本

win11 22H2

### Reproduction steps 复现步骤

重装电脑前后都是这样
拖动模式内缩放配置顺序闪退
简单复现

### Log files 日志文件

2022-11-18 10:17:30.391|info|XamlApp.cpp:Initialize|程序启动
	版本：v0.10.0-preview1
	管理员：否
2022-11-18 10:17:31.363|info|XamlApp.cpp:Run|程序退出
2022-11-18 10:17:31.382|info|XamlApp.cpp:Initialize|程序启动
	版本：v0.10.0-preview1
	管理员：是
2022-11-18 10:17:49.837|info|XamlApp.cpp:Initialize|程序启动
	版本：v0.10.0-preview1
	管理员：否
2022-11-18 10:17:50.784|info|XamlApp.cpp:Run|程序退出
2022-11-18 10:17:50.805|info|XamlApp.cpp:Initialize|程序启动
	版本：v0.10.0-preview1
	管理员：是

**Comment by Blinue** [comment]
请上传配置文件。进入设置>便携模式->打开配置文件位置

**Comment by sha7dowXX** [comment]
![动画](https://user-images.githubusercontent.com/53045584/202604738-288163fc-f757-41ae-a663-fb440df6a51b.gif)
{
    "version": 0,
    "theme": 2,
    "windowPos": {
        "x": 540,
        "y": 142,
        "width": 1280,
        "height": 820,
        "maximized": false
    },
    "hotkeys": {
        "scale": 2369,
        "overlay": 2372
    },
    "autoRestore": false,
    "downCount": 5,
    "debugMode": false,
    "disableEffectCache": false,
    "saveEffectSources": false,
    "warningsAreErrors": false,
    "simulateExclusiveFullscreen": false,
    "alwaysRunAsElevated": true,
    "showTrayIcon": true,
    "inlineParams": true,
    "scalingModes": [
        {
            "name": "Lanczos",
            "effects": [
                {
                    "name": "Lanczos",
                    "scalingType": 1,
                    "scale": {
                        "x": 1.0,
                        "y": 1.0
                    }
                }
            ]
        },
        {
            "name": "FSR",
            "effects": [
                {
                    "name": "FSR\\FSR_EASU",
                    "scalingType": 1,
                    "scale": {
                        "x": 1.0,
                        "y": 1.0
                    }
                },
                {
                    "name": "FSR\\FSR_RCAS",
                    "parameters": {
                        "sharpness": 0.8700000047683716
                    }
                }
            ]
        },
        {
            "name": "FSRCNNX",
            "effects": [
                {
                    "name": "FSRCNNX\\FSRCNNX"
                }
            ]
        },
        {
            "name": "ACNet",
            "effects": [
                {
                    "name": "ACNet"
                }
            ]
        },
        {
            "name": "Anime4K",
            "effects": [
                {
                    "name": "Anime4K\\Anime4K_Upscale_Denoise_L"
                }
            ]
        },
        {
            "name": "CRT-Geom",
            "effects": [
                {
                    "name": "CRT\\CRT_Geom",
                    "scalingType": 1,
                    "scale": {
                        "x": 1.0,
                        "y": 1.0
                    },
                    "parameters": {
                        "monitorGamma": 2.200000047683716,
                        "cornerSize": 0.0010000000474974513,
                        "curvature": 0.0,
                        "interlace": 0.0,
                        "CRTGamma": 1.5
                    }
                }
            ]
        },
        {
            "name": "Integer Scale 2x",
            "effects": [
                {
                    "name": "Nearest",
                    "scalingType": 0,
                    "scale": {
                        "x": 2.0,
                        "y": 2.0
                    }
                }
            ]
        },
        {
            "name": "default",
            "effects": [
                {
                    "name": "Anime4K\\Anime4K_Upscale_GAN_x2_S"
                },
                {
                    "name": "Anime4K\\Anime4K_3D_AA_Upscale_US"
                }
            ]
        }
    ],
    "scalingProfiles": [
        {
            "scalingMode": 7,
            "captureMethod": 0,
            "multiMonitorUsage": 0,
            "graphicsAdapter": 0,
            "disableWindowResizing": false,
            "3DGameMode": false,
            "showFPS": false,
            "VSync": true,
            "tripleBuffering": true,
            "reserveTitleBar": false,
            "adjustCursorSpeed": true,
            "drawCursor": true,
            "disableDirectFlip": false,
            "cursorScaling": 2,
            "customCursorScaling": 1.0,
            "cursorInterpolationMode": 0,
            "croppingEnabled": false,
            "cropping": {
                "left": 0.0,
                "top": 0.0,
                "right": 0.0,
                "bottom": 0.0
            }
        }
    ]
}

**Comment by Blinue** [comment]
谢谢反馈。我已经复现了，正在调查中

**Comment by Blinue** [comment]
这是 WinUI 的已知问题。当以管理员身份运行时，拖拽会导致崩溃 https://github.com/microsoft/microsoft-ui-xaml/issues/7690 。老实说我受够了 WinUI 的各种 bug。

目前只能变通一下，在管理员身份下提供另一种重新排序效果的方式。
