### ISSUE TITLE
NETFLIX以及DISNEY+不能縮放？

### ISSUE THREAD

**Issue by s3327445** [Blinue/Magpie#458]
### Question 问题

是因爲DRM的關係嗎？ 不論是app或者網頁版均不能縮放 會黑屏 換其他的捕獲模式也一樣
被magpie養慣了 一模糊就會受不了 呵呵

**Comment by Blinue** [comment]
很遗憾，这些服务在中国大陆不可用，所以我没法测试。不过它们会采取措施防止录屏也是情理之中的事。

**Comment by hooke007** [comment]
我认为这应该属于 wontfix
NETFLIX甚至禁止截屏，尝试绕过网飞的版权保护可能涉及侵权问题

**Comment by Blinue** [comment]
@hooke007 多谢提醒。我希望 Magpie 广泛可用，用户应为自己的行为负责。但现实中，这里是灰色地带，尤其在国内广泛的监管下，因为制作“工具”被起诉的例子数不胜数。

我决定保留这个“特性”。

**Comment by s3327445** [comment]
原來如此 還是感謝作者 我有介紹很多朋友用           
用過都說讚

**Comment by Blinue** [comment]
谢谢支持！
