### ISSUE TITLE
增加最大帧数可选项，而不是只有垂直同步和非同步

### ISSUE THREAD

**Issue by kuuhaku1314** [Blinue/Magpie#460]
### Expected behavior 预期的功能

有些游戏不需要太高的fps，举个例子用了多个算法的pipeline后开启垂直同步，因为显示器是150fps的，所以显卡直接占满，实际上我只需要60fps，显卡占用高风扇呼呼响也耗电，希望可以加几个预设的fps选项，如30，60等

**Comment by Blinue** [comment]
Duplicate of #378
计划中的替代方案 https://github.com/Blinue/Magpie/discussions/362#discussioncomment-3035551
