### ISSUE TITLE
Change language?

### ISSUE THREAD

**Issue by areasudon** [Blinue/Magpie#461]
### Question 问题

Can I change language somehow? I dont speak Taiwanese and I dont understand what it says exactly.

**Comment by Blinue** [comment]
Currently Magpie supports Chinese, English and Russian. Here are the English docs:
https://github.com/Blinue/Magpie/blob/main/README_EN.md
https://github.com/Blinue/Magpie/wiki/Home_EN

> I dont speak Taiwanese and I dont understand what it says exactly.

Of course you don't, you should learn *Chinese* :)

**Comment by vlascik** [comment]
@Blinue I think what he meant is that the docs seem to be for an older version of the program and do not mention any way to switch the language to English anyway. 

As of v0.10.0-preview1, there is also no button to switch the language in the Settings either, or if there is, it's impossible to find if you don't read Simplified Chinese.

**Comment by Blinue** [comment]
@vlascik Thank you! I've updated the release note. The UI changes a lot during development, so I plan to localize it at the end.
