### ISSUE TITLE
窗口化显示（Windows Mode ）

### ISSUE THREAD

**Issue by kurikomoe** [Blinue/Magpie#462]
### Expected behavior 预期的功能

能否将缩放后的画面用窗口模式显示，而非全屏显示。

e.g，在工位 28 寸 4k 显示器上玩上古 720p 的 galgame，希望能把游戏缩放到 1080p or 2k 同时在可以任意缩放大小的窗口模式中显示出来。毕竟在 28 寸显示器上全屏玩 galgame 还是挺尴尬的。

**Comment by hooke007** [comment]
dup https://github.com/Blinue/Magpie/issues/135
