### ISSUE TITLE
开启垂直同步后帧数表现异常

### ISSUE THREAD

**Issue by Ptilopsis01** [Blinue/Magpie#463]
### Magpie version 程序版本

0.10.0-preview1

### Windows version 系统版本

win10 22621.963

### Reproduction steps 复现步骤

软件内开启垂直同步后，显卡占用率极低，此时帧率仅有20左右，画面严重卡顿撕裂
显示器刷新率为165hz
怀疑和我之前提的issue #459 是同一个原因导致

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/10239707/magpie.log)

**Comment by Ptilopsis01** [comment]
> Graphics Capture 的帧率由操作系统控制，你试试更换捕获模式

尝试了GDI，即使关闭垂直同步也会有一样的问题；desktop dumplication由于我系统开启了HDR会导致输出画面过曝，可能这种捕捉方式捕获画面位于渲染管线的最末端，但帧数是正常了；dwmsharedsurface依然有此问题

**Comment by Blinue** [comment]
我也认为和 #459 有相同的原因。多显示器的垂直同步问题统一在 #459 讨论。
