### ISSUE TITLE
放大windows边栏小工具出现紫色背景

### ISSUE THREAD

**Issue by pxk888** [Blinue/Magpie#464]
### Magpie version 程序版本

v0.10.0-preview1

### Windows version 系统版本

Win11 家庭版 22H2 22621.963

### Reproduction steps 复现步骤

放大windows边栏小工具出现紫色背景,此问题在0.9.1也存在
[(在这下载可用于win11,win10,win8.1的windows边栏)](https://gadgetsrevived.com/download-sidebar/)
1.使用Graphics Capture:按下放大快捷键后出现紫色背景;
![image](https://user-images.githubusercontent.com/25244319/210255935-19c51a32-417a-42fe-906c-c5c3502a8f5b.png)
停止放大后紫色背景没有消除,需要移除小工具再重新添加才能消除
![image](https://user-images.githubusercontent.com/25244319/210255757-a502c1c3-0596-4c3f-81db-2816f1f61ba2.png)

2.使用Desktop Duplication:按下放大快捷键后无反应,5秒后缩放也不行

3.使用GDI:放大后有紫色背景,但停止放大后紫色消失
![image](https://user-images.githubusercontent.com/25244319/210256490-20a4a01a-15b2-4377-b2ac-184c9dbdbdaf.png)

4.使用DwmSharedSurface:按下快捷键后无反应,但是光标不见了,再按一次快捷键光标就回来了;5秒后缩放也是

### Log files 日志文件

[magpie.1.log](https://github.com/Blinue/Magpie/files/10332645/magpie.1.log)
[magpie.2.log](https://github.com/Blinue/Magpie/files/10332646/magpie.2.log)
[magpie.log](https://github.com/Blinue/Magpie/files/10332647/magpie.log)
[config.json.txt](https://github.com/Blinue/Magpie/files/10332649/config.json.txt)

**Comment by Blinue** [comment]
有紫色背景的原因是它使用特殊的机制实现不规则形状窗口，这种情况下 GDI 和 dwm 不起作用。Graphics Capture 没适配这种窗口，我会尽快修复。Desktop Duplication 可以工作，你只需切换显卡
