### ISSUE TITLE
v0.10.0部分遊戲使用anime4k無法全螢幕

### ISSUE THREAD

**Issue by vbvb1234** [Blinue/Magpie#466]
### Question 问题

![螢幕擷取畫面_20230105_110348](https://user-images.githubusercontent.com/122035153/210813649-6bcecc40-58d3-4880-ada8-392b2b7d5ae0.png)
![螢幕擷取畫面_20230105_110630](https://user-images.githubusercontent.com/122035153/210813687-7ef01203-6d98-4a02-ace9-88d77c8c1666.png)

如題會像這樣有黑邊

但是v0.9.1版本卻是可以正常全螢幕的

![螢幕擷取畫面_20230105_110257](https://user-images.githubusercontent.com/122035153/210812235-35312c8f-16ed-4236-ae1b-d1f68089b82e.png)
![螢幕擷取畫面_20230105_110424](https://user-images.githubusercontent.com/122035153/210812281-e8b4300f-7c48-45e0-acbc-81197db6fe4a.png)

DPI縮放開不開都沒影響

![螢幕擷取畫面_20230105_110459](https://user-images.githubusercontent.com/122035153/210813504-bbd97157-4e1f-440d-9d42-3b32401b7129.png)

**Comment by Blinue** [comment]
这是因为游戏窗口太小，经过 Anime4K 放大一倍也无法填充屏幕。你应在 Anime4K 后添加放大算法。
https://github.com/Blinue/Magpie/issues/448#issuecomment-1308045339
