### ISSUE TITLE
在远程串流软件Moonlight中的游戏画面卡死及光标位置被限制的问题

### ISSUE THREAD

**Issue by xiaobaiwud12** [Blinue/Magpie#467]
### Magpie version 程序版本

v0.9.1&v0.10.0-preview1

### Windows version 系统版本

Windows 11 Pro 22H2

### Related screenshot (optional) 相关截图（可选）

开始缩放后Moonlight串流画面的游戏画面立即卡死，此时仅有光标未卡死可以使用Moonlight控制移动，光标在Moonlight中被限制在未缩放前游戏窗口的范围内，游戏画面在电脑显示器上显示正常未卡死

### Reproduction steps 复现步骤

此bug在安装于安卓7及13设备的Moonlight软件（版本10.11）上均能复现，不限Magpie的缩放模式及捕获模式：
1.在PC端GeForce Experience中添加任意Galgame游戏
2.在安卓端Moonlight开始远程串流添加的游戏
3.运行Magpie
4.使用快捷键开启缩放

### Log files 日志文件

Log：[magpie.zip](https://github.com/Blinue/Magpie/files/10367911/magpie.zip)

**Comment by Blinue** [comment]
串流的问题统一在 #141 讨论。禁用 DirectFlip 似乎可以解决画面卡死的问题，但双光标问题无法解决。
