### ISSUE TITLE
[Preview version] 缺失 dependency?

### ISSUE THREAD

**Issue by luojunyuan** [Blinue/Magpie#468]
### Magpie version 程序版本

v0.10.0-preview1

### Windows version 系统版本

win11 22h2

### Reproduction steps 复现步骤

启动报错缺少 MSVCP140.dll, VCRuntime140, VCRuntime140_1.dll 等依赖
程序应该附加这些依赖么。。

### Log files 日志文件

⁣⁣⁣

**Comment by Blinue** [comment]
v0.10.0-preview1 依然要求用户安装 MSVC 运行时。
在最新的开发版中，编译时会自动复制这些 dll，因此无需用户安装任何环境。
