### ISSUE TITLE
Mouse cursor looks double when I zoom in with FSR.

### ISSUE THREAD

**Issue by jovechiere** [Blinue/Magpie#47]
Just that problem, Magpie shows two cursors in every game that I try to apply the FSR effect.
https://i.imgur.com/eibC7tI.jpg
Each mouse cursor is independent and moves differently on the screen.
https://i.imgur.com/FPDTw9l.mp4
https://i.imgur.com/YwpnrxE.mp4

**Comment by tiagoplacido** [comment]
Try this on the magpie window, on the 3rd drop down menu chose the 2nd option, see if it works

**Comment by jovechiere** [comment]
> Try this, on the magpie window, on the 3rd drop down menu choose the 2nd option, see if it works

The option 运行 时 注入 is tested and it doesn't work.
I also tried the third before launching the application and it is the same problem.
It even happens using Lanczos or anyone else.

Everything else works perfectly, my monitor is a 4K 4096x2160, but I have changed it to UHD and it remains the same.
I have looked on the internet for some solutions, but I still do not solve it.

**Comment by zaifan** [comment]
yeah, same here, mouse cursor is double, but not in every games. Usually this happens if the game can't activate FSR with alt f11. must use the 5 seconds button

**Comment by Blinue** [comment]
Hi, this issue has nothing to do with resolution or scale mode, it is a limitation of the Magpie's implementation principle.

I have provided the third drop down menu to solve this problem, which uses process injection technique. As you know, it is a hack and may fail for many reasons.

The game to be scaled may prohibit process injection, and your antivirus or OS may also prohibit this operation for security reasons.

**Comment by Blinue** [comment]
@zaifan  If this issue occurs occasionally, you can try the third option "Inject at startup".

**Comment by hooke007** [comment]
>must use the 5 seconds button

You can try run the magpie as admin.

**Comment by CapitaineJSparrow** [comment]
Same here, upscaling works really well thanks for your awesome tool ! However, the cursor is cloned for some games not capturing mouse. The "injection at startup" works well, but games require to be launched from launcher so it's not always usable

**Comment by Blinue** [comment]
Thanks, I will consider these suggestions carefully.

**Comment by notNSANE** [comment]
hi, I just wanted to replicate my concern for this, since it makes magpie practically unusable for me :( Also, using the alternative FSR option isn't ideal since it halves my FPS from 60 to 30, at least with my old GPU. 

I think if there exists a way to even artifically or hacky way to remove this duplicate cursor, it hopefully gets implemented.

And maybe keep the issue open, since it's not fixed? Mostly because I was going to post for this exact issue and remembered to search.

**Comment by CapitaineJSparrow** [comment]
I'm giving my 2 cents to find a solution, maybe with a hacky way, to hide the duplicated cursor.

**Comment by jovechiere** [comment]
Mainly I have closed it, because if the developer tells me that he will consider how to solve this problem, for me I am more than satisfied.
Just be patient.

**Comment by hooke007** [comment]
link https://github.com/Blinue/Magpie/issues/121
