### ISSUE TITLE
Debanding shader

### ISSUE THREAD

**Issue by Freestalkerdotfr** [Blinue/Magpie#472]
### Expected behavior 预期的功能

Hello,

I would like to have a gradient debanding shader because I use Magpie to upscale videos. I use youtube and there is compression banding. Here is a Reshade forum where someone created a HLSL shader for it but I didn't managed to make it work. [HLSL for MPC-HC](https://reshade.me/forum/shader-discussion/5116-deband-for-videoplayers)

If you can add this feature, it would be nice

**Comment by NeilTohno** [comment]
其实有部分 3D 游戏，为了追求画面，可以加上这个功能，缩放始终是会引入一些 artifact，哈哈

[![vogAQ.png](https://imglink.win/image/2023/01/17/vogAQ.png)](https://imglink.org/image/vogAQ)

You can try this, 
https://github.com/akiirui/mpv-handler

**Comment by Blinue** [comment]
Found another implementation:
https://github.com/libretro/slang-shaders/blob/master/misc/shaders/deband.slang

I will port it later. Since I'm busy with other work, this will take a while.

**Comment by Freestalkerdotfr** [comment]
OK thank you ! I hope it will be fast to do it.

**Comment by kato-megumi** [comment]
I have already ported deband shader here. https://gist.github.com/kato-megumi/36812b9330ac4185fd4528e33f8c2963
Just throw it in Effects folder and modify your ScaleModel.json file.

**Comment by Blinue** [comment]
@kato-megumi Thank you! Would you like to contribute it to this repository?

**Comment by kato-megumi** [comment]
Sure!
I make a PR here: #479

**Comment by Freestalkerdotfr** [comment]
> I have already ported deband shader here. https://gist.github.com/kato-megumi/36812b9330ac4185fd4528e33f8c2963 Just throw it in Effects folder and modify your ScaleModel.json file.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e249f005c9359542c16b3dc40dbe3e950c23c49a86601d5d2461a59834675446/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> Gist**[port mpv deband shader for magpie](https://gist.github.com/kato-megumi/36812b9330ac4185fd4528e33f8c2963)**port mpv deband shader for magpie. GitHub Gist: instantly share code, notes, and snippets.

THX ! Awesome !

**Comment by Blinue** [comment]
Merged.
