### ISSUE TITLE
Simple fullscreen borderless bilinear interpolation mode please

### ISSUE THREAD

**Issue by Axer128** [Blinue/Magpie#475]
### Expected behavior 预期的功能

I see bilinear interpolation is supported in v0.9 under options.

However it can't be used without a related zoom mode, and all the zoom modes also filter the image further in other ways. Except integer scaling, but that's fixed at 2x or 3x.

Instead a simple borderless fullscreen mode that just scales to the current monitor rez + bilinear is what im requesting please. (Same as most of the modes like FSR work to scale the full current resolution, but without any processing except bilinear)

I know it's a semi odd request.. But a ton of old school RPGs simply don't support bilinear and instead only have insanely awful Fullscreen modes (eg: Most rpg maker xp/vx/etc games only support a really bad exclusive 640x480@60hz, and while some related mods/scriptz exist to give a fake borderless fullscreen effect - they only do so in nearest neibour)

Cuz yea, it's just nostalgic for me to use bilinear, since when I was growing up playing games like those, my CRT was huge, but awful quality, so was very blurry like bilinear. Didn't really look like any of the available CRT filters of today.. But yea bilinear reminds me of how it looked.

Related: Simple borderless fullscreen toggle for nearest neighbor. Also not possible atm. Both should work if you just add a "zoom only" scaler and keep the nearest neighbor vs bilinear toggle.

The 2x integer mode does work well with select RPG maker XP titles depending on base and target resolution, but not some others, nor with most high rez games.

I think you have seperate the zoom and the scaling mode in v10 which is nice, but I can't quite understand how to exactly use it , since it has no english translation yet.

Cheers for your hard work. Happy to contribute via paypal/patreon if you have one.

**Comment by Blinue** [comment]
[Here](https://github.com/Blinue/Magpie/wiki/Customizing_Scaling_Configurations) is the documentation for custom scaling modes. In order to use bilinear, add this to ScaleModels.json:
```json
{
    "name": "Bilinear",
    "effects": [
      {
        "effect": "Bilinear",
        "scale": [ -1, -1 ]
      }
    ]
}
```
