### ISSUE TITLE
English translation for preview builds

### ISSUE THREAD

**Issue by Axer128** [Blinue/Magpie#476]
### Expected behavior 预期的功能

I know your working on this but figured we could have a feature request thread for people to +1 to see how many are excited to see the latest versions in english.

Perhaps a talented programmer can also volunteer to do this for you, someone used to maintain english translations of your mod here:
https://github.com/7Brandyn7/Magpie/releases/

But it is no longer maintained as he assumed you will always release english versions yourself.

**Comment by kaldeqca** [comment]
patience dear

**Comment by Blinue** [comment]
Thank you. This issue will be used to track the localization of v0.10.

ref: https://github.com/Blinue/Magpie/issues/461#issuecomment-1341061741
