### ISSUE TITLE
能否在缩放模式中加入“默认升采样效果”

### ISSUE THREAD

**Issue by cqaqlxz** [Blinue/Magpie#478]
### Expected behavior 预期的功能

**Magpie version 程序版本**
0.10.0-preview1

我的屏幕是分辨率是4K，用magpie放大720p的窗口，放大图像的滤镜只加了一层Anime4K_Upscale，游戏不能放大到全屏，我必须在每一项缩放模式后都加上Bicubic。

请问能否在缩放模式，通用，那里改为两项：默认升采样效果和默认降采样效果

**Comment by Blinue** [comment]
没有默认升采样的原因是，相比于缩小，放大更容易导致图像失真。720p 分辨率为 1280×720，经过 Anime4K 放大一倍后为 2560x1440，远未达到 4k 的分辨率。在你的配置中，接下来使用 Bicubic 放大至 4k，但 Bicubic 在放大时效果很差，我推荐你换成其他高级缩放算法，比如 Anime4K、Lanczos、NNEDI3 等。

不同的场景适用不同的放大算法，难以找到一个通用的。如果用户发现放大后未填满屏幕，他需要根据使用场景自行添加放大算法，而不是寄希望于全局的默认算法。
