### ISSUE TITLE
提高图标分辨率

### ISSUE THREAD

**Issue by liJie-wk** [Blinue/Magpie#481]
### Magpie version 程序版本

v0.10.0-preview1

### Windows version 系统版本

win11 22h2

### Related screenshot (optional) 相关截图（可选）

![微信图片_20230215091816](https://user-images.githubusercontent.com/57932868/218900241-aa781b49-68af-4e16-80d0-b04156ddf230.png)

### Reproduction steps 复现步骤

图标不适配会有边框，很丑很丑

### Log files 日志文件

无

**Comment by Blinue** [comment]
很遗憾现在的图标最大分辨率是 64x64。这是临时使用的，正在征集图标 -> #370
我个人认为现在的图标挺好的，只要提高分辨率即可。
