### ISSUE TITLE
找不到Anime4K_Upscale_UL

### ISSUE THREAD

**Issue by kakarisu** [Blinue/Magpie#482]
### Question 问题

0.9.1版本写着有添加 可是我打开软件却找不到这选项

**Comment by Blinue** [comment]
你需要[自定义缩放配置](https://github.com/Blinue/Magpie/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E6%94%BE%E9%85%8D%E7%BD%AE)。如果使用 v0.10 则可以在用户界面中配置这些。

**Comment by cqaqlxz** [comment]
你要自己手动编辑ScaleModels.json文件，或者直接使用0. 10版本
