### ISSUE TITLE
FPS capped to half refresh rate on 75Hz monitor

### ISSUE THREAD

**Issue by DeVelox** [Blinue/Magpie#486]
### Magpie version 程序版本

v0.10.0-preview2

### Windows version 系统版本

Win11 22H2

### Reproduction steps 复现步骤

Set monitor in Windows to 75Hz.
Enable Magpie using Graphics Capture and FSR.
Turn on FPS counter in Magpie.
FPS is locked to 37-38.

This does not happen when monitor is set to 60Hz, FPS goes up to 60 as expected.

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/10823449/magpie.log)

**Comment by Blinue** [comment]
Have you tried other capture methods?

**Comment by DeVelox** [comment]
I have tried them all now and here are the results (keep in mind this is a 3D game):
Desktop Duplication - FPS is fully unlocked but my GPU gets pushed to 100% resulting in even worse performance.
GDI and DWM aren't able to display the 3D game, only a frozen frame of the main menu.

Interestingly, switching to one of those and back to Graphics Capture actually solved the problem and I'm no longer capped to 37 FPS.

**Comment by Blinue** [comment]
The performance of Magpie is largely determined by the OS and display driver. Try increasing the priority of Magpie in the display driver to see if it helps.

**Comment by DeVelox** [comment]
It's actually okay now, Graphics Capture works best for me, no performance issues other than the artificial cap which got removed by switching between modes. Desktop Duplication by itself seems to use too much GPU due to fully unlocked FPS so it takes away from the game.

I'm considering this solved for now, unless you have a way of fixing the Graphics Capture FPS being locked to half refresh rate *without* switching to another mode and back. Thank you for your time and the amazing app!

**Comment by Blinue** [comment]
You're welcome. Since the issue has been resolved, I will close it.
