### ISSUE TITLE
缩放模式添加效果闪退

### ISSUE THREAD

**Issue by HIllya51** [Blinue/Magpie#488]
### Magpie version 程序版本

v0.10.0-preview2

### Windows version 系统版本

Win10 20H2 19042.867

### Reproduction steps 复现步骤

点击添加效果，在菜单中来回切换看里面的内容，几次之后就会闪退。
尤其是在SMAA Sharpen xBRZ上，闪退概率极高。
Win10 20H2 19042.867
CPU AMD R5 4600U

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/10831115/magpie.log)

**Comment by Blinue** [comment]
这是一个操作系统的 bug，参见 https://github.com/microsoft/microsoft-ui-xaml/issues/3529 。从评论看，你需要安装 [KB5007253](https://support.microsoft.com/en-gb/topic/november-22-2021-kb5007253-os-builds-19041-1387-19042-1387-19043-1387-and-19044-1387-preview-d1847be9-46c1-49fc-bf56-1d469fc1b3af)

**Comment by HIllya51** [comment]
原来如此。感谢。😂
