### ISSUE TITLE
Yellow border around game window

### ISSUE THREAD

**Issue by rampaa** [Blinue/Magpie#489]
### Magpie version 程序版本

v0.10.0-preview2

### Windows version 系统版本

Windows 10, 22H2

### Reproduction steps 复现步骤

1) Add a new profile for a game*
2) Select "Graphics Capture" as your capture method and enable "Auto scale when in foreground"
3) Run the game.

The game will be scaled correctly but it will have a visible yellow border. The yellow border disappears once I switch to another window and switch back to the game.

*: Actually I can only replicate this problem with a specific game I have but unfortunately it doesn't have a trial.

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/10832083/magpie.log)

**Comment by Blinue** [comment]
Is the yellow border visible when scaling?

**Comment by rampaa** [comment]
> Is the yellow border visible when scaling?

Yes

> Can you provide a screenshot?

Sure, but note that when I try to take a screenshot of it, the result differs from what I actually see. i.e. I actually see the game scaled to fullscreen properly with a yellow border around it. The screenshot on the other hand does not show it being scaled at all.

![Garufura](https://user-images.githubusercontent.com/25622653/221387871-96d205ac-6ed3-444a-9e70-62426432e9b9.png)

**Comment by Blinue** [comment]
Generally, Graphics Capture does not capture the yellow border. For this window, window capture failed for some reason, and Graphics Capture fell back to capturing the entire screen, which resulted in the yellow border being visible.

Since I cannot debug it, you can try some workarounds:

1. Change the capture method.
2. Upgrade to Windows 11, which hides the yellow border by default.

**Comment by rampaa** [comment]
Thanks for the explanation.

Changing the capture method does fix the issue. Switching to another window and switching back to the game also fixes it.

**Comment by Blinue** [comment]
> Switching to another window and switching back to the game also fixes it.

There seems to be some magic happening here, and I'm not sure of the reason. Some game windows behave strangely, and Graphics Capture is the most compatible capture method, but it's not a silver bullet.

**Comment by rampaa** [comment]
> There seems to be some magic happening here, and I'm not sure of the reason

Maybe it fails to correctly capture the game window because it tries to capture it immediately after the game started. I don't see the yellow border if I manually activate scaling with Windows+Shift+A either. It only seems to happen if "Auto scale when in foreground" is enabled while the "Graphics Capture" is the selected capture method.

**Comment by Blinue** [comment]
Thank you for the feedback, I will take this as a failed case.

**Comment by rampaa** [comment]
FYI: The issue is fixed in v0.10.0. I'd guess https://github.com/Blinue/Magpie/commit/be59c6c7e334fbd6931902228f99c239ecb96957 is what fixed it. But anyway, thanks for creating this marvelous program!

**Comment by Blinue** [comment]
I have enhanced the compatibility of Graphics Capture, so the yellow border issue should no longer occur. In Windows 10, there will no longer be a fallback to screen capture.
