### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Blinue/Magpie#491]
I translated https://hosted.weblate.org/projects/magpie/ui/ru/

**Comment by Blinue** [comment]
Thank you! Check latest builds here: https://github.com/Blinue/Magpie/actions

**Comment by 0x4E69676874466F78** [comment]
I have corrected the translation a little bit, because in the window of changing the hotkey the lower text did not fit.
In addition, I noticed that when you change the language and restart an generic error window pops up, but the program restarts.
![image](https://user-images.githubusercontent.com/4449851/221871357-1b55d1d9-b74a-4d4e-a313-e5983a9c85d5.png)

Also Windows default for Language makes me English even though the default language in the system is Russian.

**Comment by Blinue** [comment]
> I have corrected the translation a little bit, because in the window of changing the hotkey the lower text did not fit.

Weblate synchronizes translation changes regularly, and I can also synchronize it manually.

> In addition, I noticed that when you change the language and restart an generic error window pops up, but the program restarts.

This is a mechanism in Windows that checks the compatibility of applications, which mistakenly assumes that Magpie has exited unexpectedly, but everything is normal, so it is safe to ignore.

> Also Windows default for Language makes me English even though the default language in the system is Russian.

This error should have been fixed in the latest build.

**Comment by 0x4E69676874466F78** [comment]
Magpie is no longer available on weblate.org 
Is it supposed to be like this?

**Comment by Blinue** [comment]
v0.10 is released 🎉

**Comment by Blinue** [comment]
The hosting request has been approved, and we can use Weblate again.
https://hosted.weblate.org/projects/magpie

**Comment by 0x4E69676874466F78** [comment]
How frequently is the translation in the repository updated?

**Comment by Blinue** [comment]
It will update if there are no changes within 24 hours. I'v just manually updated it.
