### ISSUE TITLE
Magpie doesn't work if you click the square icon at top right.

### ISSUE THREAD

**Issue by jeremylpro** [Blinue/Magpie#492]
### Magpie version 程序版本

0.9.1

### Windows version 系统版本

Windows 10 22H2 (19045.2604)

### Related screenshot (optional) 相关截图（可选）

[video.zip](https://github.com/Blinue/Magpie/files/10871290/video.zip)

### Reproduction steps 复现步骤

Click the square at the top right and try to scale it.

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/10871337/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/10871343/Runtime.log)

**Comment by Blinue** [comment]
Are you trying to scale a maximized window? To use Magpie, you need to unmaximize it first.

**Comment by jeremylpro** [comment]
Oh
