### ISSUE TITLE
打开游戏内显示时帧数异常

### ISSUE THREAD

**Issue by Ptilopsis01** [Blinue/Magpie#493]
### Magpie version 程序版本

0.10.0-preview2

### Windows version 系统版本

win11 22621.1344

### Related screenshot (optional) 相关截图（可选）

![20230303_000330](https://user-images.githubusercontent.com/93318731/222485900-82994f4d-8dce-4564-9ab0-a3b0b89cb388.gif)
![20230303_000407](https://user-images.githubusercontent.com/93318731/222486696-cd528b9f-ec8b-4c98-adda-52acd1a332d4.gif)

如图所示，第一张为关闭垂直同步时，正常状态下为90fps左右，打开游戏内覆盖后降至60fps，显卡占用率明显下降；第二张为打开垂直同步时（显示器刷新率为75hz），正常状态下为50-60fps，显卡占用率低（这里有第二个问题，实际渲染帧数可以超过刷新率，但开启垂直同步后帧率异常的低），打开游戏内覆盖后反而升至75hz

### Reproduction steps 复现步骤

如图所示

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/10873387/magpie.log)
[magpie.1.log](https://github.com/Blinue/Magpie/files/10873388/magpie.1.log)
[magpie.2.log](https://github.com/Blinue/Magpie/files/10873389/magpie.2.log)

**Comment by Blinue** [comment]
> 第一张为关闭垂直同步时，正常状态下为90fps左右，打开游戏内覆盖后降至60fps，显卡占用率明显下降

游戏内覆盖的渲染流程较长，但 GPU 的使用率并不高，它不是计算密集型的。

> 第二张为打开垂直同步时（显示器刷新率为75hz），正常状态下为50-60fps，显卡占用率低（这里有第二个问题，实际渲染帧数可以超过刷新率，但开启垂直同步后帧率异常的低），打开游戏内覆盖后反而升至75hz

打开垂直同步时，如果显卡性能不足，帧数不稳定是正常情况，推荐打开“允许额外的延迟以提高性能”。

**Comment by Ptilopsis01** [comment]
> > 第一张为关闭垂直同步时，正常状态下为90fps左右，打开游戏内覆盖后降至60fps，显卡占用率明显下降
> 
> 游戏内覆盖的渲染流程较长，但 GPU 的使用率并不高，它不是计算密集型的。
> 
> > 第二张为打开垂直同步时（显示器刷新率为75hz），正常状态下为50-60fps，显卡占用率低（这里有第二个问题，实际渲染帧数可以超过刷新率，但开启垂直同步后帧率异常的低），打开游戏内覆盖后反而升至75hz
> 
> 打开垂直同步时，如果显卡性能不足，帧数不稳定是正常情况，推荐打开“允许额外的延迟以提高性能”。

先不管垂直同步的问题，我的意思其实是按理说打开游戏内覆盖的时候显示的帧数应当和实际游戏内帧数相当，但这里明显帧数和显卡占用率都不一致，感觉有点问题

**Comment by Blinue** [comment]
这是正常的。渲染游戏内覆盖需要占用 GPU 资源，因此帧率会有所降低。和 Anime4K 相比，渲染游戏内覆盖不是计算密集型的，因此显卡占用率也会降低。
