### ISSUE TITLE
[BUG]每次重新打开Magpie，光标缩放方式都会重置为最近邻

### ISSUE THREAD

**Issue by Ptilopsis01** [Blinue/Magpie#496]
### Magpie version 程序版本

0.10.0-preview2

### Windows version 系统版本

win11 22621.1344

### Reproduction steps 复现步骤

将光标缩放方式调整为双线性；重新启动Magpie，可以看到缩放方法重置为最近邻
此外我的系统光标大小设置为大于最低值时，Magpie获取的鼠标指针仍然是最小的而不是光标的源图像，这个问题似乎在 #119 中提到过

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/10963720/magpie.log)
[magpie.1.log](https://github.com/Blinue/Magpie/files/10963722/magpie.1.log)
[magpie.2.log](https://github.com/Blinue/Magpie/files/10963723/magpie.2.log)

**Comment by Blinue** [comment]
> 将光标缩放方式调整为双线性；重新启动Magpie，可以看到缩放方法重置为最近邻

谢谢，我很快就会修复。

> 此外我的系统光标大小设置为大于最低值时，Magpie获取的鼠标指针仍然是最小的而不是光标的源图像，这个问题似乎在 https://github.com/Blinue/Magpie/issues/119 中提到过

这是已知问题，见 https://github.com/Blinue/Magpie/discussions/254#discussioncomment-2213503
