### ISSUE TITLE
Crash when use WinRT on windows 1809

### ISSUE THREAD

**Issue by lisovskij-martin** [Blinue/Magpie#50]
I use windows 1809 and i faced problem with winRT. When the application starts, an error appears when opening full-screen mode using WinRT. According microsoft, winRT supported by windows since 1803.
P.s. sorry for my english i am from Belarus

**Comment by lisovskij-martin** [comment]
![image](https://user-images.githubusercontent.com/61833817/128645172-91e68d68-446c-4c1f-9e4d-534c858de657.png)

**Comment by Blinue** [comment]
Hello, WinRT capture is not supported in v1809. Before v1903, this API is only available in UWP apps.

Check out [this blog](https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture).

**Comment by Blinue** [comment]
Hello, WinRT capture is not supported in v1809. Before v1903, this API is only available in UWP apps.

Check out [this blog](https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture).
