### ISSUE TITLE
无法为暗黑2创建配置文件

### ISSUE THREAD

**Issue by eriforce** [Blinue/Magpie#505]
### Magpie version 程序版本

0.10.0

### Windows version 系统版本

Win11 22H2 10.0.22621.1413

### Reproduction steps 复现步骤

1. 管理员或用户启动Magpie
2. 以-w启动游戏

### 问题

* New profile中选不到窗口

不知道是否和禁止特殊窗口有关？如果需要额外提供任何游戏窗口/进程的信息请告知。

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/11068939/magpie.log)

**Comment by Blinue** [comment]
从日志看 Magpie 并不是管理员身份？用管理员身份启动试试，要先在系统托盘里退出 Magpie。

**Comment by eriforce** [comment]
log里管理员和非管理员都有

**Comment by Blinue** [comment]
我是在你修改之前下载的...
我测试了一下，以管理员身份运行时无法创建配置，但可以正常缩放

**Comment by eriforce** [comment]
> 我是在你修改之前下载的... 我测试了一下，以管理员身份运行时无法创建配置，但可以正常缩放

啊  我蠢了。。Defaults的Scaling mode是None。。确实放大可以，issue重新编辑了一下

**Comment by Blinue** [comment]
初步认定是权限原因。如果我以管理员身份运行 VS 然后调试可以检测到暗黑2，如果在资源管理器中以管理员身份启动就检测不到。显然当附加了调试器时，EnumWindows 可以枚举到更多窗口。我还注意到暗黑2似乎是以兼容模式运行的，因为它的标题栏比较窄，且不支持 snap 布局。
<img width="446" alt="屏幕截图(9)" src="https://user-images.githubusercontent.com/34770031/227775535-a4d6a9ce-e3a7-4069-aea3-79ce834e6ae3.png">

**Comment by eriforce** [comment]
确实标题栏比正常的窄，属性里即使不选兼容模式还会以兼容模式运行的么？

**Comment by Blinue** [comment]
我不确定，这游戏太古老了，可能触发了 Windows 的某种兼容性机制。我测试了其他程序的兼容模式，可以被枚举到。发现 PowerToys 可以枚举到，我会调查一下

**Comment by eriforce** [comment]
发现每次匹配D2窗口这两处都会报错
https://github.com/Blinue/Magpie/blob/main/src/Magpie.App/AppXReader.cpp#L154
https://github.com/Blinue/Magpie/blob/main/src/Shared/Win32Utils.cpp#L44
> LastErrorCode：5

**Comment by Blinue** [comment]
OpenProcess 的结果是无权限，即使 PROCESS_QUERY_LIMITED_INFORMATION 也一样。暗黑2大概有某些操作防止其他程序操作自己的进程，比如为了防作弊。虽然有一些 hack 可以用，但我担心这会让 Magpie 被反作弊软件误判。

**Comment by Blinue** [comment]
我建议在找到解决方案前不要关，即使一直无法解决也是一个 bug 的记录

**Comment by Blinue** [comment]
我找到了解决方案：[GetProcessHandleFromHwnd](https://learn.microsoft.com/en-us/windows/win32/winauto/getprocesshandlefromhwnd) 。这是一个非常古老的函数，虽然文档有记录，但已经不存在于头文件中了。这个函数不太实用，但可以作为一个有用的回退。
