### ISSUE TITLE
建议：多个进程共用同一配置

### ISSUE THREAD

**Issue by eriforce** [Blinue/Magpie#506]
### Expected behavior 预期的功能

先讲一下想解决的问题：
1. 每个程序都要新建一个配置有点麻烦（尤其是如果想要更改一批配置的话）
  我觉得大部分的使用场景都是根据某类的游戏来选择一个缩放算法/配置，而不是真的需要每个游戏都定制化
2. 同一个exe但在不同电脑上路径不同
  使用portable config的情况下，就需要给实际同一个exe创建多个配置，和上面同样的情况需要修改的时候比较麻烦
3. exe本身在一个Junction目录中
  比如我有一个`D:\Game`->`C:\Game`的映射，启动`D:\Game\a.exe`的时候通过窗口捕获的路径是`C:\Game\a.exe`，`pathRule`会匹配不到

我想到的方案让同一个配置能应用到多个进程，大概是这个样子：
![image](https://user-images.githubusercontent.com/8393109/227726848-5f616e4f-05d8-46c3-be7e-761f719514db.png)
```json
{
    "name": "ProfileName1",
    "applications": [
        {
            "packaged": false,
            "pathRule": "C:\\Game\\a.exe",
            "classNameRule": "MainWnd"
        },
        {
            "packaged": false,
            "pathRule": "D:\\Game\\a.exe",
            "classNameRule": "MainWnd"
        }
    ]
    //...
}
```
new profile时也可以保留选窗口，这样也就不会增加`每个进程一个配置`的操作复杂度

**Comment by Blinue** [comment]
我知道的软件里基本都是每个窗口有自己的配置文件，多个窗口共享配置会增加逻辑复杂度。映射的问题我会调查一下。

**Comment by eriforce** [comment]
> 我知道的软件里基本都是每个窗口有自己的配置文件，多个窗口共享配置会增加逻辑复杂度。映射的问题我会调查一下。

即使不改UI，只通过手动改配置也行。功能本身没有很复杂吧，关键还是看大佬觉得这个功能合不合理。如果可以的话我很乐意贡献代码。

**Comment by Blinue** [comment]
这个功能确实不复杂，但我认为它没有带来很多好处：

1. 大多数时候用户不需要同时修改多个配置文件。对于你遇到的文件夹映射的问题我以后会调查。
2. 最常修改的配置项是“缩放模式”，而它是所有配置文件共享的。我在使用时很少会修改其他配置，当需要修改它们时，这个修改只适用于一个窗口。如果多个窗口共用一个配置文件，反而不好控制细粒度，操作并没有被简化。
3. 多个窗口共用一个配置文件意味着多了一层抽象，我认为这不易理解和使用。用户可能使用过其他有窗口配置的程序，比如 BorderlessGaming, Lossless Scaling 等，和它们逻辑一致便没有学习成本。如果为了功能强大而增加了配置的复杂度，我认为是得不偿失的。

你说的改 config 我也不认同，配置文件并不是用户界面的一部分，它是实现细节，不保证一致性。

最后感谢你的努力，如果有更多用户喜欢这个功能，我会实现它。

**Comment by eriforce** [comment]
这是支持此功能的fork
https://github.com/eriforce/Magpie/pull/4

**Comment by Blinue** [comment]
很好，我没想到有人能做修改，因为 Magpie 使用的技术栈非常前卫（cppwinrt+XAML Islands）。似乎为 UWP 窗口创建配置文件会崩溃？

**Comment by eriforce** [comment]
> 很好，我没想到有人能做修改，因为 Magpie 使用的技术栈非常前卫（cppwinrt+XAML Islands）。似乎为 UWP 窗口创建配置文件会崩溃？

因为有些C# WPF的基础所以基本都能看懂，而且需要的功能基本上代码里已经有类似的可以借鉴了。不过代码里有些格式editorconfig没覆盖到（比如idl和xaml），format document之后会产生很多修改。

因为我自己只用来放大桌面程序，没试过UWP，有空看看。

**Comment by Blinue** [comment]
我用 XamlStyler 格式化 XAML 文件，VS 对 idl 的支持不好，只能手动改。

**Comment by eriforce** [comment]
![image](https://user-images.githubusercontent.com/8393109/232382217-7383bbef-3847-4826-850c-49350aba5ae9.png)
本以为需要的时候再取theme就可以了，原来background上取theme会挂。现在放回到前面建UWP没问题了。

XamlStyler 是不是也需要额外的配置文件？默认的配置format出来和项目里的格式差别更大了。。
我看它配置里有个external configuration file，是不是可以也放在项目里？

**Comment by Blinue** [comment]
> 本以为需要的时候再取theme就可以了，原来background上取theme会挂。现在放回到前面建UWP没问题了。

UI 元素只能在主线程上操作。

> 我看它配置里有个external configuration file，是不是可以也放在项目里？

好主意。
