### ISSUE TITLE
被放大窗口在全屏画面上方

### ISSUE THREAD

**Issue by eriforce** [Blinue/Magpie#507]
### Magpie version 程序版本

0.10.0

### Windows version 系统版本

Win11 22H2 10.0.22621.1413

### Related screenshot (optional) 相关截图（可选）

![Untitled](https://user-images.githubusercontent.com/8393109/227727598-e41cf12c-b18a-4fa3-b25d-e18ba6a281bc.png)

### Reproduction steps 复现步骤

在和[DxWnd](https://sourceforge.net/projects/dxwnd/)配合使用的情况下，被放大的窗口会保持在全屏画面上方。切换过Graphics Capture、DwmSharedSurface、Desktop Duplication，也勾选过exclusive fullscreen都有这个问题。（0.9.1非exclusive都正常）

此外碰巧发现放大Magpie的窗口或者资源管理器的时候也有同样的现象（不知道能不能成为线索，并不是说要修这两个）。

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/11069326/magpie.log)

**Comment by Blinue** [comment]
全屏窗口是置顶的，出现这个情况的原因可能是游戏本身也是置顶，这导致会出现在全屏画面上方。你也检查一下是不是打开了“开发者选项”-“调试模式”。

**Comment by eriforce** [comment]
> 全屏窗口是置顶的，出现这个情况的原因可能是游戏本身也是置顶，这导致会出现在全屏画面上方。你也检查一下是不是打开了“开发者选项”-“调试模式”。
确实是开着调试模式造成的，之前查问题以为调试模式会多些log。
谢谢

**Comment by Blinue** [comment]
这个选项是为了方便在 VS 中触发断点，不是开发者的话不要打开
