### ISSUE TITLE
using FSR on certain games changes the way they play.

### ISSUE THREAD

**Issue by TheRaptorMovies** [Blinue/Magpie#51]
On Red Dead 2, it makes the performance worse.
On one of my other games (Saurian), it boosts to FPS from 50 to 120, but turns the game slow motion and kind of choppy.
As seen here: https://streamable.com/amaqyq

**Comment by Blinue** [comment]
Thanks for the feedback, many people complain about the performance of Magpie.

Making Magpie usable for everyone and every game is a daunting task. I'm looking for ways to optimize the performance, but I'd be happy if someone could help, since I can only maintain it outside of work.

**Comment by zaifan** [comment]
just additional feedback, magpie worked well on WatchDogs Legion, PES 21, Genshin Impact, no fps/performance loss. But on forza horizon 4 it had a problem with window mode (maybe due to microsoft store based game).

**Comment by canceralp** [comment]
Maybe you can create a version which the user manually injects a DLL in the game's folder and capturing is done through that, specifiaclly for games?

**Comment by Woovie** [comment]
Car Mechanic Simulator 2021 slows down the game's clock. everything is slower (Player movement, UI elements, etc.)

Using FSR, WinRT, runtime injection, otherwise default options.

**Comment by Blinue** [comment]
I am closing this as it is outdated. If you encounter this problem in the latest version, please file a new issue.
