### ISSUE TITLE
Values in the configuration file do not match interface values

### ISSUE THREAD

**Issue by Katzenwerfer** [Blinue/Magpie#510]
### Magpie version 程序版本

v0.10.0

### Windows version 系统版本

Windows 10 IoT Enterprise LTSC, Version 21H2, Kernel 10.0.19044.0

### Related screenshot (optional) 相关截图（可选）

![image](https://user-images.githubusercontent.com/53267697/227753809-a4b02c0d-3a3d-4b49-96fc-0c2ffe64d2cb.png)
![image](https://user-images.githubusercontent.com/53267697/227753822-a13139ec-546b-41c1-bbd0-b5b680703b39.png)

### Reproduction steps 复现步骤

1. Open the program and navigate to the `Scaling configuration` tab.
2. Expand any of the `Scaling modes` which have configurable shaders.
3. Adjust the values of a shader which has slider adjustable parameter.
4. Open the `config.json` where the application's settings are stored.
5. Compare the values stored in the configuration file with the values displayed in the interface.

### Log files 日志文件

I am uncertain if it would be useful for this type of issue.

**Comment by Blinue** [comment]
The settings file is an implementation detail that users do not need to be concerned with. However, if you are interested, I am happy to share the reason behind it: Magpie uses single-precision floating-point numbers to store parameter values, which are printed out as approximate values. But this is not a problem, as the shaders can only accept single-precision inputs as well.
