### ISSUE TITLE
启用“始终以管理员身份运行”后无法启动

### ISSUE THREAD

**Issue by hooke007** [Blinue/Magpie#511]
### Magpie version 程序版本

0.10.0

### Windows version 系统版本

win10 22H2

### Related screenshot (optional) 相关截图（可选）

![image](https://user-images.githubusercontent.com/41094733/227756143-998651ed-d244-4d90-af12-80e4bcd6d49e.png)

### Reproduction steps 复现步骤

ref https://github.com/Blinue/Magpie/discussions/504#discussioncomment-5427632

用管理员启动，设置里勾选“始终以管理员启动”，退出。
启动magpie，无响应（实际上任务管理器有个magpie进程）

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/11069419/magpie.log)

**Comment by Blinue** [comment]
我已经复现了，很快就会修复

**Comment by Blinue** [comment]
已修复

**Comment by ayanami-desu** [comment]
能否释放一个修复此bug的版本？我也遇到了无法启动的问题。
准备尝试退回旧版

**Comment by hooke007** [comment]
在action里获取

**Comment by ayanami-desu** [comment]
使用了最新的action版本，非管理员/管理员均无法启动……

**Comment by Blinue** [comment]
先在任务管理器里中止magpie进程

**Comment by ayanami-desu** [comment]
任务管理器中无进程

**Comment by ayanami-desu** [comment]
在目录下没发现log文件

**Comment by Blinue** [comment]
如果你用昨天编译出的版本没有日志说明不是同一个问题，请提一个新的 issue
