### ISSUE TITLE
After v0.10.0 can't interact with windows that have UI Access

### ISSUE THREAD

**Issue by rampaa** [Blinue/Magpie#515]
### Magpie version 程序版本

0.10.0

### Windows version 系统版本

Windows 10 22H2

### Related screenshot (optional) 相关截图（可选）

![HYmvhE2nXx](https://user-images.githubusercontent.com/25622653/227786578-4cb1b117-b1d2-4482-a15d-0318b7cd251f.png)
![hcHuSRdZAj](https://user-images.githubusercontent.com/25622653/227786506-02db18ca-3183-4e64-8304-d75070dd10bb.png)

### Reproduction steps 复现步骤

1) Open a program that has UI Access, e.g. On-Screen Keyboard
2) Shrink it vertically and place it at the top side of your screen (see the screenshots)
3) Scale a game with Magpie

You will be able to see the window that has UI Access even after you scale the game with Magpie (as expected) but you won't be able to interact with it. Before Magpie v0.10.0 (e.g. v0.10.0-preview2), we could interact with the window that has UI Access as well.

Interestingly enough, if you place the window that has UI access at the center of your screen, you will be able to interact with it.

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/11072092/magpie.log)

**Comment by Blinue** [comment]
I believe that this bug was introduced during the fixing of #422. I will fix it soon.

I also want to implement a mechanism for Magpie to collaborate with other programs. While windows with UIAccess permissions can currently stay on top during scaling, if I decide to [support touch input](https://github.com/Blinue/Magpie/issues/218), Magpie would also require UIAccess permissions, which would break these programs. This is [a game of walls and ladders](https://devblogs.microsoft.com/oldnewthing/20110310-00/?p=11253).

**Comment by Blinue** [comment]
> Do you have anything concrete in mind? I've developed a program called [JL](https://github.com/rampaa/JL) that let's you look up Japanese words and it works with Magpie quite well (it makes itself the topmost window on every clipboard change and you can interact with it with your mouse without it getting the focus) but I wonder if the experience can be made even smoother somehow.

For example,
* Magpie will not end scaling when your program gains focus.
* Magpie will maintain the Z-axis order to ensure that your program is not obscured.
* You can obtain the scaling factor to display the overlay in the correct position.

> If you ever decide to do that, please consider supplying an external manifest file so that we can use it without granting it the UI Access. (In case of JL, it would still be able to stay on top Magpie through the aforementioned method but users would need to grant JL the UI Access as well, which as you may know has some pretty inconvenient conditions that must be met.)

I plan to create a separate program with UIAccess privilege, which can be called when high privilege operations are needed. This way, Magpie itself doesn't need to have UIAccess privilege.

**Comment by Blinue** [comment]
<img width="1280" alt="无标题" src="https://user-images.githubusercontent.com/34770031/228549964-6df3f3ba-fad5-473c-8697-71dce8e5e0a0.png">

I can’t reproduce the issue on Win11. Magpie works fine with on-screen keyboard, but is incompatible with Magnifier.

**Comment by rampaa** [comment]
> Are you running the game as administrator?

Nope. But the bug only seems to happen if I don't run Magpie as administrator. Try shrinking the On-Screen Keyboard vertically as much as possible and run Magpie without the administrator privilege and hopefully you will be able to reproduce it. 

(If I run the game as administrator but don't run Magpie as administrator, it seems like Magpie cannot auto scale the game when it's in the foreground. Should I open another issue for this, or is this the expected behavior?)

**Comment by Blinue** [comment]
> (If I run the game as administrator but don't run Magpie as administrator, it seems like Magpie cannot auto scale the game when it's in the foreground. Should I open another issue for this, or is this the expected behavior?)

This bug has been fixed in the latest dev branch. However, if you want to scale windows with administrator privileges, it's recommended to run Magpie as administrator to avoid potential issues.

**Comment by rampaa** [comment]
Correction: The bug is also present in v0.10.0-preview2, I've just didn't notice it because I've always run it as administrator. (I've started to run Magpie without administrator privileges mostly due to https://github.com/Blinue/Magpie/issues/511.) Apologies for the misdirection. The bug is _not_ present in v0.9.1 though.

**Comment by Blinue** [comment]
Does [this build](https://github.com/Blinue/Magpie/suites/11978946678/artifacts/628610217) fix the issue?

**Comment by rampaa** [comment]
Yes, it does fix the issue. Thanks!
