### ISSUE TITLE
Anime4K_Upscale与RAVU_Zoom_R3搭配使用时，放大的图像会出现条纹

### ISSUE THREAD

**Issue by cocochick** [Blinue/Magpie#516]
### Magpie version 程序版本

0.10.0

### Windows version 系统版本

win11 22H2

### Related screenshot (optional) 相关截图（可选）

<img width="1920" alt="bug" src="https://user-images.githubusercontent.com/31812147/227793656-45c0618c-0a34-4b54-9d0b-3360d8cdc44c.png">

### Reproduction steps 复现步骤

缩放模式中，先选择Anime4K_Upscale_S(L、VL、UL以及Anime4K_Upscale_Denoise_S、L、VL、UL皆可)，再选择RAVU_ZOOM_R3，缩放任意程序即可复现。

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/11072463/magpie.log)

**Comment by Blinue** [comment]
RAVU_ZOOM 系列只支持放大，请看[内置效果介绍](https://github.com/Blinue/Magpie/wiki/%E5%86%85%E7%BD%AE%E6%95%88%E6%9E%9C%E4%BB%8B%E7%BB%8D)

**Comment by cocochick** [comment]
之前的使用场景是尝试将1280*720的应用缩放到3840*2160，此时应该为放大而非缩小？

**Comment by Blinue** [comment]
你提供的截图里 Magpie 窗口比较大，如果缩放 1280x720 的窗口应该没有这个问题

**Comment by cocochick** [comment]
em晚上补一张截图

**Comment by cocochick** [comment]
![bug1](https://user-images.githubusercontent.com/31812147/227972601-ad25c393-25d2-4ae3-abd0-94cb116a2512.png)
这是仅使用Anime4K_Upscale_S时的缩放结果
![bug2](https://user-images.githubusercontent.com/31812147/227972950-984f7379-9703-44dd-a15f-c10ac6960f17.jpg)
这是使用Anime4K_Upscale_S + RAVU_Zoom_R3时的缩放效果，可以看到明显网格状条纹

**Comment by Blinue** [comment]
![image](https://user-images.githubusercontent.com/34770031/227977807-0b1fa819-3190-4c20-8b7b-b28aa2e20f21.png)
我复现出了类似的情况。这确实是一个 bug，谢谢反馈！

**Comment by XiaofengdiZhu** [comment]
看起来修复了这个算法的错误，明天我试试（我遇到的问题是雪花点）
