### ISSUE TITLE
支持繁体中文

### ISSUE THREAD

**Issue by NeilTohno** [Blinue/Magpie#518]
### Expected behavior 预期的功能

v0.10.0 版没有看到繁体，这个不难，强烈建议追加繁体

繁化姬 
https://zhconvert.org/

**Comment by Blinue** [comment]
我看到你正在翻译成繁体中文，非常感谢！你还创建了一个日语翻译，你也会日语吗？

**Comment by NeilTohno** [comment]
> 我看到你正在翻译成繁体中文，非常感谢！你还创建了一个日语翻译，你也会日语吗？

只是用繁化姬弄的而已，日语不知道为啥删不掉额，
我不会日语额

**Comment by Blinue** [comment]
我已经把日语删了。

**Comment by Blinue** [comment]
你更改了一些专有名词：

scaling mode: 缩放模式->缩放方法
Scaling configuration: 缩放配置->缩放设定
Release notes: 发行说明->新版特性

原本的表述和英文是一致的，你的改动是处于什么考虑？

**Comment by NeilTohno** [comment]
> 你更改了一些专有名词：
> 
> scaling mode: 缩放模式->缩放方法 Scaling configuration: 缩放配置->缩放设定 Release notes: 发行说明->新版特性
> 
> 原本的表述和英文是一致的，你的改动是出于什么考虑？

不要直译这几个额，考虑一下国内软件的习惯、使用者的习惯
缩放模式，模式这个词，样式，套路，特征，不合适
缩放配置，配置，和后面的配置文件冲突

**Comment by Blinue** [comment]
其他的无所谓，但是缩放模式是一直以来的叫法，现在改是不合适的。我会把几个更改回退。关于表述的讨论可以另开 issue，这个 issue 只负责繁中翻译。

**Comment by NeilTohno** [comment]
> 其他的无所谓，但是缩放模式是一直以来的叫法，现在改是不合适的。我会把几个更改回退。关于表述的讨论可以另开 issue，这个 issue 只负责繁中翻译。

关于功能的描述就是翻译讨论的要点，我另一个 issue 也行

**Comment by NeilTohno** [comment]
感謝大大 @a0193143

但是還有部分內容沒有同步，待會編譯進去了，就是不完全的更新
