### ISSUE TITLE
求添加 pdf  帮助说明文件

### ISSUE THREAD

**Issue by NeilTohno** [Blinue/Magpie#519]
### Expected behavior 预期的功能

有个问题上就是 github 不自带梯子没法打开，
作为完整程序包的一部分， 带加密的 pdf  帮助说明文件是很好的东西，感谢大大

鄙人倒是刚刚写了一个文章，
https://www.bilibili.com/read/cv22703908
比如大大可以创个b站账号发布相关内容

**Comment by NeilTohno** [comment]
> Gitee 有一个镜像仓库 https://gitee.com/mirrors/blinue-magpie ，可惜不会同步 wiki。也可以用镜像网站，比如 https://kgithub.com/Blinue/Magpie

我知道 gitee，这个需要有人帮忙转镜像，无 发行版
kgithub.com 咱不知道，很多人也不知道吧额

> 感谢推广！ B 站账号我自然是有的，但只是用来娱乐。维护 Magpie 只是我的兴趣，我不想花很多功夫推广它。

既然如此，你只要 B站 写个 [Releases](https://github.com/Blinue/Magpie/releases) 的文章，标题写牛一点就行额，内容和你的介绍一样就行
没必要花精力、dollar 推广的，主要是 github 以外要有个写说明的地方

**Comment by Blinue** [comment]
> 我知道 gitee，这个需要有人帮忙转镜像，无 发行版

这个镜像是 gitee 官方维护的，大概每天同步一次。没有发行版是真的。

> 既然如此，你只要 B站 写个 [Releases](https://github.com/Blinue/Magpie/releases) 的文章，标题写牛一点就行额，内容和你的介绍一样就行
没必要花精力、dollar 推广的，主要是 github 以外要有个写说明的地方（稍微大众一点的地方）

一旦在其他平台发布，就有了维护成本。Magpie 本身是有一定门槛的软件，Github 可以过滤掉大部分小白用户，让我聚焦在有意义的问题上。总之谢谢你的建议，但我现在没有发布在其他平台的计划。

**Comment by NeilTohno** [comment]
> 一旦在其他平台发布，就有了维护成本。Magpie 本身是有一定门槛的软件，Github 可以过滤掉大部分小白用户，让我聚焦在有意义的问题上。总之谢谢你的建议，但我现在没有发布在其他平台的计划。

以前的版本要自己写配置，确实有点门槛，
v0.10.0 版本已经可以说很好用了，加上有人分享配置，使用难度下降很多。
你如果担心私信，回复啥的，很多B站的大UP都不看不管的，只要说明一下就行。

以上。
