### ISSUE TITLE
关于延迟、性能损失和画面效果

### ISSUE THREAD

**Issue by LightMu** [Blinue/Magpie#52]
我最近尝试了LosslessScaling的FSR缩放，相比较Magpie，它有着更低的延迟，但是相同的是，都有一定的性能损失。相对于原生游戏的FSR，它整个改变了游戏中所有渲染的分辨率，特别是和后处理抗锯齿一同使用时的效果，改用MSAA会好一点，但是通常需要很高的MSAA倍数来维持画面效果。事实上，可能目前缩放类软件的FSR效果甚至差于虚幻4引擎自带的TAAU，加上性能损失帧数提升也只接近TAAU。

我按照Reddit讨论的帖子调整进程优先级和利用监控类插件同步帧数的方式降低了Magpie的延迟和性能损失，现在它和LosslessScaling延迟接近（但是对于游戏玩家来说依旧有反应延迟），提升了一点性能。

另外，Magpie在双显卡电脑上还需要设置独显启动。

原谅我的吹毛求疵，因为原生的FSR带给我的效果实在太过惊艳，我现在有点迷恋它了。

**Comment by Blinue** [comment]
根据反馈，目前Magpie主要的问题是画面延迟。Magpie没有在2K/4K屏幕上测试过，因为我没有这样的屏幕用于测试，在我的1080P屏幕上它工作的很好 ;)

如果你有测试的环境和能力，欢迎贡献。

**Comment by palxex** [comment]
可以给一下reddit链接吗？想看看如何同步帧数。

**Comment by LightMu** [comment]
> 可以给一下reddit链接吗？想看看如何同步帧数。

大概就是
1.设置独显启动。
2.在图形面板里同时启用软件和游戏的超低延迟模式
3.使用Win10任务管理器或者三方任务管理器提高游戏和软件的优先级
4.RTSS（就是微星小飞机带的监控插件）里把游戏和软件加入监控，监控锁定同样的帧数

另外，不知道软件效果是否和游戏引擎有关系
Magpie在欧美游戏如虚幻引擎游戏的表现要比Lossless Scaling好，LosslessScaling在日厂游戏如RE引擎游戏表现好点

**Comment by LightMu** [comment]
> 根据反馈，目前Magpie主要的问题是画面延迟。Magpie没有在2K/4K屏幕上测试过，因为我没有这样的屏幕用于测试，在我的1080P屏幕上它工作的很好 ;)
> 
> 如果你有测试的环境和能力，欢迎贡献。

不好意思，因为计划更新电脑配置的时间正好撞上了互联网矿潮，所以我还停留在1080p时代，没办法提供高分辨率的测试。

**Comment by palxex** [comment]
@LightMu 
谢谢解说
问一下第二步的超低延迟模式是NVIDIA的Reflex吗？看来是专享福利了，试了下A卡的同类功能AntiLag，反而有点不跟手。
第四步RTSS加入EXE监控倒是找到了，锁定帧数的操作可以详解一下吗？

@Blinue 
关于高分屏，我目前用的是一块4K 60hz屏，倒是可以说一下体验。因为现在用的是几代前的RX580 4G（同属矿潮难民），原生4K分辨率想60帧跑游戏基本没指望，1080P全屏又感觉模糊，即使在驱动中打开锐化也不够锐利，Magpie算是圆了我让大部分游戏跑在4K上的梦。以原神为例，原生4K大概在25-35fps之间浮动（资源管理器里可以看到GPU 3D处理基本满载），1080P窗口化+Magpie FSR则在画质和锐度均可接受的情况下大部分时候维持60fps——长时间游玩时偶尔会因为显存撑不住帧率下降，但参照[这篇文章]（https://allthings.how/how-to-check-vram-usage-on-windows-10/）寻找其它显存占用大的app kill掉即可恢复（但很可惜常态占用极大的DWM不能干掉）；此外lanczos在1080P->4K 1:4时，速度远低于FSR，基本是60->10这种级别。用cemu模拟器跑botw，结果与原神接近（除了原生4K跑时间长了UI都会乱掉，推测也是显存问题）。从我的体验来看，magpie外挂的FSR基本没有增加太多GPU资源占用，但显存存在一个较为明显的上升，从资源管理器的曲线上事后推测大概有3~400M左右（1080P->4K，4K->4K约有1G），希望后续log可以增加一下这点，对小显存用户规划会非常有帮助。
当前master编译用户，有需要测试的情况直接@即可。但目前能测试的上述两个游戏均无高质量纹理，对3A的代表程度有限。无DLSS/TAAU体验。

**Comment by Blinue** [comment]
非常感谢，显存限制是我没考虑到的，很多卡顿的问题可能来源于此。FSR包含两个步骤，因此需要一个中间纹理。
减少显存占用是一个重要的优化方向。

**Comment by LightMu** [comment]
> @LightMu
> 谢谢解说
> 问一下第二步的超低延迟模式是NVIDIA的Reflex吗？看来是专享福利了，试了下A卡的同类功能AntiLag，反而有点不跟手。
> 第四步RTSS加入EXE监控倒是找到了，锁定帧数的操作可以详解一下吗？
> 
> @Blinue
> 关于高分屏，我目前用的是一块4K 60hz屏，倒是可以说一下体验。因为现在用的是几代前的RX580 4G（同属矿潮难民），原生4K分辨率想60帧跑游戏基本没指望，1080P全屏又感觉模糊，即使在驱动中打开锐化也不够锐利，Magpie算是圆了我让大部分游戏跑在4K上的梦。以原神为例，原生4K大概在25-35fps之间浮动（资源管理器里可以看到GPU 3D处理基本满载），1080P窗口化+Magpie FSR则在画质和锐度均可接受的情况下大部分时候维持60fps——长时间游玩时偶尔会因为显存撑不住帧率下降，但参照[这篇文章]（[https://allthings.how/how-to-check-vram-usage-on-windows-10/）寻找其它显存占用大的app](https://allthings.how/how-to-check-vram-usage-on-windows-10/%EF%BC%89%E5%AF%BB%E6%89%BE%E5%85%B6%E5%AE%83%E6%98%BE%E5%AD%98%E5%8D%A0%E7%94%A8%E5%A4%A7%E7%9A%84app) kill掉即可恢复（但很可惜常态占用极大的DWM不能干掉）；此外lanczos在1080P->4K 1:4时，速度远低于FSR，基本是60->10这种级别。用cemu模拟器跑botw，结果与原神接近（除了原生4K跑时间长了UI都会乱掉，推测也是显存问题）。从我的体验来看，magpie外挂的FSR基本没有增加太多GPU资源占用，但显存存在一个较为明显的上升，从资源管理器的曲线上事后推测大概有3~400M左右（1080P->4K，4K->4K约有1G），希望后续log可以增加一下这点，对小显存用户规划会非常有帮助。
> 当前master编译用户，有需要测试的情况直接@即可。但目前能测试的上述两个游戏均无高质量纹理，对3A的代表程度有限。无DLSS/TAAU体验。

打开RivaTuner Statistics Server主面板，在窗口左侧，点击绿色Add键加入magpie和游戏的exe主程序，右侧设置帧数限制通常略低于显示器刷新率，如60hz显示器设置为59.8hz。我不知道是否需要删除原本的Global全局，因为原帖子已经找不到了。它影响了我的其他游戏的帧计数，所以最后一项我也并没有再设置了

**Comment by palxex** [comment]
@LightMu 
谢谢！又学到了一个限制FPS的方法。
至于下面那项帧率同步，看说明是独占全屏下不引入额外输入延迟的VRR替代实现，按我理解只能在vsync关时生效，但Magpie目前最适应的窗口环境下DWM会强制vsync开，应该适用于不同的环境。

@Blinue 
很高兴能帮上忙:)

**Comment by Blinue** [comment]
现在如果遇到性能问题请另开issue
