### ISSUE TITLE
之前使用0.10预览版1，正式版释出后改用正式版无法启动

### ISSUE THREAD

**Issue by ayanami-desu** [Blinue/Magpie#523]
### Magpie version 程序版本

0.10相关版本

### Windows version 系统版本

win11 21h

### Reproduction steps 复现步骤

记得是下载正式版的压缩包，解压完成之后删掉了旧版的的程序目录（两者文件夹名不同，没有覆盖文件）。之后无法运行程序
更换回预览版1也无法启动

### Log files 日志文件

无日志文件产生

**Comment by Blinue** [comment]
[Magpie.zip](https://github.com/Blinue/Magpie/files/11108206/Magpie.zip)
这个版本有没有日志？日志在 logs 文件夹下。

**Comment by ayanami-desu** [comment]
没有日志，也没有响应。管理员/非管理员都试过

**Comment by ayanami-desu** [comment]
有个细节不知道没有帮助。
普通模式打开，状态栏不会出现输入法已禁用的标
管理员模式打开则会出现
![image](https://user-images.githubusercontent.com/105108444/228744024-b5089736-630e-4843-ac23-c622ec34c673.png)

**Comment by ayanami-desu** [comment]
没有相关错误

**Comment by Blinue** [comment]
我认为这不是 Magpie 本身的问题，可能被你的系统环境阻止了。你试试退出无关的软件，以及重启电脑有没有用。

**Comment by ayanami-desu** [comment]
重启后仍然异常，令人费解

**Comment by ayanami-desu** [comment]
0.9.1版本也不能使用
看来确实是我电脑的问题

**Comment by ayanami-desu** [comment]
偶然想着用命令行打开，结果真的打开了……
![image](https://user-images.githubusercontent.com/105108444/229127471-92f7b18e-4972-4cf7-a6e1-999dd972f2c7.png)

**Comment by ayanami-desu** [comment]
我刚才右键查看exe的属性，发现里面有一个此文件来自互联网，已被锁定。解除这个锁定之后就能正常打开了。
Windows还有这样的机制吗

**Comment by Blinue** [comment]
能截个图吗？

**Comment by ayanami-desu** [comment]
我解除了锁定。在网上找了一样的图
![image](https://social.microsoft.com/Forums/getfile/368459)

**Comment by Blinue** [comment]
我没遇到过，说不定是杀毒软件的锅。既然不是 Magpie 的错误，这个 issue 可以关了。
