### ISSUE TITLE
could you bring back scale after 5s back to right click on taskbar? old version had it

### ISSUE THREAD

**Issue by humanana** [Blinue/Magpie#524]
### Expected behavior 预期的功能

have features like old version [ old version had this function ]

becasue somtimes shortcut did not work so user need to open main windows and use scale after 5s to make it work

old version you can at least right click on the icon on task bar and then click on windows that you want to scale then after 5s it scale

but with [v0.10.0] this function was remove was left only main windows could you bring it back for easier usage like old version?

thank you > <'

**Comment by Blinue** [comment]
This feature is already planned, and I will also add more useful functions to the tray icon menu in the future.

**Comment by humanana** [comment]
thank you >v<'
