### ISSUE TITLE
希望增加HDR支持

### ISSUE THREAD

**Issue by nigyta8** [Blinue/Magpie#536]
### Expected behavior 预期的功能

目前HDR尚无法正确显示，希望可以在后续版本中添加支持

**Comment by 0x4E69676874466F78** [comment]
https://github.com/Blinue/Magpie/discussions/362#discussioncomment-5357699

**Comment by Blinue** [comment]
Duplicate of #55 

顺带一提，现在依然没有支持 HDR 的计划。从我的使用体验看，如果开启了 HDR，最好使用游戏原生全屏。

**Comment by nigyta8** [comment]
👌理解，感谢解答
