### ISSUE TITLE
建议增加时间抗锯齿（TAA）和多重采样抗锯齿（MSAA）效果

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [Blinue/Magpie#542]
### Expected behavior 预期的功能

目前的版本只提供FXAA和SMAA实在是太少了，能不能再新增一些抗锯齿选项，比如TAA和MSAA。
且目前SMAA的效果不敢恭维，质量调到ULTRA，画面扭曲变形的厉害，还不如游戏自带的SMAA，大概是这软件只能提取游戏窗口的画面而无法提取游戏内部渲染数据的缘故吧？

**Comment by hooke007** [comment]
时域抗锯齿也需要前后帧的数据，我认为和fsr2一样在原理上就行不通。

**Comment by Blinue** [comment]
Duplicate of #272
