### ISSUE TITLE
Dual graphic cards support?

### ISSUE THREAD

**Issue by alt-0191** [Blinue/Magpie#549]
### Expected behavior 预期的功能

Support dual graphic cards for better performance.

**Comment by Blinue** [comment]
I believe this is beyond the scope of this software. Multi-GPU rendering is not an area that I am familiar with.

**Comment by closer233** [comment]
I notice that you can choose different graphic cards in profiles,so is there any way to make different graphic cards to process different effects when use many effects?




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年4月6日(星期四) 下午4:41
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Blinue/Magpie] Dual graphic cards support? (Issue #549)





 
I believe this is beyond the scope of this software. Multi-GPU rendering is not an area that I am familiar with.
