### ISSUE TITLE
The recovery of mouse DPI

### ISSUE THREAD

**Issue by hooke007** [Blinue/Magpie#56]
在放大时，magpie 的进程若意外结束，鼠标的DPI会始终保持结束前的样子。
重启程序无法恢复，只能重启系统。

**Comment by Blinue** [comment]
鼠标的DPI可以在设置->设备->鼠标->光标速度里设置。[这里](https://github.com/Blinue/Magpie/issues/24#issuecomment-891640638)是鼠标消失的解决方案。

**Comment by hooke007** [comment]
嗯。。。放大前后这个系统设置的数值并没有变化，而且我鼠标驱动显示的dpi数值也没有变化。如果修改这个数值来恢复因意外结束产生的DPI偏移，重启之后DPI会再次变化

**Comment by Blinue** [comment]
Magpie会在进入全屏时修改光标速度，退出全屏时恢复，如果意外退出就没法恢复了。

“重启之后DPI会再次变化”指什么？

**Comment by hooke007** [comment]
>重启之后DPI会再次变化

这个表述有点歧义。就是这种修改的方法会导致重启之后鼠标移动速度过快。
我也可以通过鼠标驱动改为2000dpi来达到接近意外退出前1600dpi的移动速度，但重启之后鼠标就是真的2000dpi（速度过快）

**Comment by Blinue** [comment]
Magpie只修改光标速度，没有修改DPI。只要恢复系统的光标速度就行了

**Comment by hooke007** [comment]
<s>但是我前面提到的，这个系统光标速度并没有显示有更改</s>

好吧似乎是我win10的问题，这台电脑并不显示光标速度有更改，换台电脑就正常了。。。
