### ISSUE TITLE
Multiple monitor scaling makes mouse go out of bounds?

### ISSUE THREAD

**Issue by Helesiya** [Blinue/Magpie#569]
### Question 问题

When using Magpie scaling on a Windowed game whilslt having multiple monitors, the cursor will go out of bounds and click on a different application causing FPS games lose the aim function. The game itself stays scaled but having to click back at the game every time is rather annoying and i have not found a way to keep the cursor in the bounds. Without scaling the cursor stays in bounds all the time. Is there a way to make it not go out of bounds while scaling?

**Comment by Blinue** [comment]
Have you tried turning on "3D game mode"?
