### ISSUE TITLE
[Feature request] FSR sharpening textbox or slider

### ISSUE THREAD

**Issue by virtualbs** [Blinue/Magpie#57]
Please add a textbox or slider for controlling the RCAS sharpness in FSR (the default should be 0.2, according to the [official docs](https://github.com/GPUOpen-Effects/FidelityFX-FSR/raw/master/docs/FidelityFX-FSR-Overview-Integration.pdf)).

Also, from the same doc:
```
AU1 const0[4];

FsrRcasCon(const0, Sharpness); //Sharpness in range [0-2], 0 is sharpest
```

Thank you!

**Comment by Blinue** [comment]
Magpie provides a way to change the sharpness of FSR. Check out #43

**Comment by virtualbs** [comment]
Thanks! Does changing the .json takes effect immediately, or should I restart Magpie?

**Comment by virtualbs** [comment]
<img width="940" alt="RCAS Sharpening" src="https://user-images.githubusercontent.com/66136593/128949929-b5e9dca2-037d-4144-a9c5-4d3120e31291.png">

Values above 1.0 in the .json are giving me errors in Magpie, so I take it I am effectively changing 'Sharpness' and not 'RCAS Sharpness' stops, correct?

Thanks

**Comment by Blinue** [comment]
'RCAS Sharpness' = 2 - 'sharpness' * 2

**Comment by virtualbs** [comment]
Thanks, I've also checked https://github.com/Blinue/Magpie/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E6%94%BE and it was already detailed there.

Increasing RCAS strength and adding a step of CAS afterwards was just what I needed. Thank you for structuring ScaleModels like that, as a series of stacked effects. 👍

**Comment by Blinue** [comment]
Have fun
