### ISSUE TITLE
Start Magpie Minimized to Tray

### ISSUE THREAD

**Issue by ParasiteDelta** [Blinue/Magpie#574]
### Expected behavior 预期的功能

Related to #327, it would be nice if Magpie had the option to specify the default program startup behavior, such as starting minimized or minimized to tray. This could be done either through arguments passed through to Magpie (helpful for scripting purposes) or as a simple option in the settings menu. Working with Magpie using scripts currently requires either forcing the window to be hidden or waiting and closing the window after a set amount of time, so it would be nice to skip the middleman and have a Start Minimized to Tray option in the settings.

**Comment by Blinue** [comment]
The "-t" parameter can minimize Magpie to the system tray when it starts up. Note that the "Display the app on the system tray" option must be enabled for this to take effect.
