### ISSUE TITLE
启动应用时支持自定义参数

### ISSUE THREAD

**Issue by BLACKCHARGE** [Blinue/Magpie#575]
### Question 问题

  一部分游戏的程序自带了DPI缩放设置，即使设置了应用程序高DPI替代游戏也会自动按照系统的缩放设置使用比较差的插值算法放大窗口，magpie只能捕获到已经被放大后的窗口，无法以游戏的原生分辨率捕获到窗口。
  目前唯一的解决方案只有把系统的缩放设置为100%，这时游戏才会以原生分辨率窗口启动。
  不知道有没有什么办法能够禁用程序的DPI缩放设置，比如启动时欺骗程序以100%缩放运行.

**Comment by hooke007** [comment]
举个例子？

**Comment by Blinue** [comment]
GDI 和 DwmSharedSurface 可以捕获到原生分辨率。

**Comment by BLACKCHARGE** [comment]
> GDI 和 DwmSharedSurface 可以捕获到原生分辨率。

似乎是无效的，我上传的日志分别是对于200%和100%缩放下使用GDI进行捕获。可以看到源窗口分辨率是不一样的，帧数也不同；
[magpie.log](https://github.com/Blinue/Magpie/files/11302676/magpie.log)
至于游戏，就是某些日式RPG，窗口名为chrome legacy window，游戏引擎不确定，但是图标是一样的

**Comment by BLACKCHARGE** [comment]
![image](https://user-images.githubusercontent.com/57131319/233816654-778b2245-919a-47e0-ba7e-c639e9ad9814.png)
目前筛出来的几款，除了Material Girl以外都不支持GDI和Dwm捕获，会黑屏

**Comment by hooke007** [comment]
对主程序创建快捷方式，目标后缀两项启动参数，示例
```
"D:\SteamLibrary\steamapps\common\Summer Memories\Game.exe" --high-dpi-support=1 --force-device-scale-factor=1
```
steam的话留意会弹窗，比如
![Snipaste_2023-04-23_06-46-22](https://user-images.githubusercontent.com/41094733/233822159-db32a7ce-5571-443f-9748-95e5bb5dc9f4.jpg)

**Comment by BLACKCHARGE** [comment]
> 

谢谢，这个好用，DPI缩放消失了，如果使用magpie启动游戏的时候也支持加入参数就更方便了

**Comment by BLACKCHARGE** [comment]
> 对主程序创建快捷方式，目标后缀两项启动参数，示例
> 
> ```
> "D:\SteamLibrary\steamapps\common\Summer Memories\Game.exe" --high-dpi-support=1 --force-device-scale-factor=1
> ```
> 
> steam的话留意会弹窗，比如 ![Snipaste_2023-04-23_06-46-22](https://user-images.githubusercontent.com/41094733/233822159-db32a7ce-5571-443f-9748-95e5bb5dc9f4.jpg)

谢谢，这个好用，DPI缩放消失了，如果使用magpie启动游戏的时候也支持加入参数就更方便了

**Comment by Blinue** [comment]
这个参数不是通用的，但可以增加一个自定义参数选项，只能在通过 Magpie 启动时附加。

**Comment by BLACKCHARGE** [comment]
> steam的话留意会弹窗，比如

多提一嘴，用steam启动游戏可以设置启动参数的，不会弹窗
![image](https://user-images.githubusercontent.com/57131319/233830812-b79b80e9-677d-4a91-b799-14c68e3c2ae0.png)

**Comment by hooke007** [comment]
我知道，我就是演示给学习版用的
