### ISSUE TITLE
"Adjusting the cursor speed when zooming" does not work

### ISSUE THREAD

**Issue by 4ymnoy-doktor** [Blinue/Magpie#58]
On the desktop, the mouse speed is normal, and in the game in the zoom is somewhere twice as slow. This option should help in theory, but it is not enabled. I turn it on, exit the settings, go back there, and the option is turned off again. Perhaps this option was added by 7Brandyn7, but it seems that he only translated your program into English. If he really added this option, then I'm sorry. Sorry in advance for possible bad English.

**Comment by Blinue** [comment]
Hello. This option has not been implemented yet, I will implement it in the next version.
