### ISSUE TITLE
two Performance Panels 

### ISSUE THREAD

**Issue by kikilloy** [Blinue/Magpie#582]
### Magpie version 程序版本

v0.10.1

### Windows version 系统版本

win10

### Related screenshot (optional) 相关截图（可选）

![屏幕截图 2023-05-02 134505](https://user-images.githubusercontent.com/82642640/235588482-61fa4394-9cbd-4346-9e15-3cc13b54848e.jpg)

### Reproduction steps 复现步骤

use MSI Afterburner and Magpie  will get error （two Performance Panels ）
用 MSI Afterburner 和 Magpie会有两个性能面板，无论什么缩放模式，旧版本没有这个bug

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/11370114/magpie.log)

**Comment by hooke007** [comment]
dup https://github.com/Blinue/Magpie/issues/197

https://github.com/Blinue/Magpie/wiki/FAQ#%E5%8F%8C%E9%87%8D%E7%9B%91%E6%8E%A7

**Comment by kikilloy** [comment]
OK
