### ISSUE TITLE
Can't set to scale from 720p/1080p to upscale to 1440p! Help?

### ISSUE THREAD

**Issue by iSc0ttyathon** [Blinue/Magpie#584]
### Program(Game) 游戏名

Modern Warfare 2

### Capture method 捕获模式

GDI

### Other information (optional) 补充信息（可选）

How do I set the output size? I have a 1440p monitor but want to scale from 720p/1080p and idk how you do it......

HELP!

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/11392549/magpie.log)

**Comment by Blinue** [comment]
I'm sorry I don't understand what you mean, perhaps you should take a look at the [README](https://github.com/Blinue/Magpie#how-to-use).

**Comment by iSc0ttyathon** [comment]
> I'm sorry I don't understand what you mean, perhaps you should take a look at the [README](https://github.com/Blinue/Magpie#how-to-use).

I figured it out. I had to edit the Call Of Duty settings and set to 1080p. Then upscaled to 1440p!

Love your work!

Thanks.
