### ISSUE TITLE
部分游戏放大下切动图场景下Direct3D描画报错

### ISSUE THREAD

**Issue by MinaseInorin** [Blinue/Magpie#588]
### Magpie version 程序版本

0.10.1

### Windows version 系统版本

WIN10 21H2

### Related screenshot (optional) 相关截图（可选）

![VC) J647TZ_F`F{`CX B`UY](https://user-images.githubusercontent.com/52075351/236613877-09169110-6e6b-43e0-89cd-c2b063302be2.png)

### Reproduction steps 复现步骤

如标题说的，柚子部分游戏（目前接触并出现同样问题的：天使☆騒々 RE-BOOT！，喫茶ステラと死神の蝶，RIDDLE JOKER，千恋＊万花）在缩放下出现某些动态SD图会报错
DX和图形驱动该更新的都更了，这个一直保持最新的，问题没解决
按他说的禁止Direct3D描画确实不再报错，就是会掉帧，某些情况下还是有概率报错例如千恋＊万花

### Log files 日志文件

。

**Comment by Blinue** [comment]
正如 https://github.com/Blinue/Magpie/discussions/537#discussioncomment-5823164 所说，这个问题是“缩放时模拟独占全屏”选项导致的，和 #495 相同。

“缩放时模拟独占全屏”会使操作系统误以为有一个独占全屏的 Direct3D 游戏正在运行。D3D9 相当古老，可能不允许在这种情况下创建 D3D 设备（会返回 D3DERR_DVICELOST）。在 #495 里，游戏在启动时尝试创建 D3D 设备，这相对容易解决，将“缩放时模拟独占全屏”选项起作用的时间稍微推迟等待游戏初始化完成。而柚子社的游戏会在游戏过程中要显示动态画面时创建，这就导致了问题。

“缩放时模拟独占全屏”选项和在中途创建 D3D9 设备的游戏不兼容，建议在缩放这类游戏时关闭这个选项。

**Comment by BLACKCHARGE** [comment]
如果是这样的话吧"模拟独占全屏"这个选项从设置的高级部分中移动到每个游戏都有的单独配置中比较好

**Comment by Blinue** [comment]
"模拟独占全屏"和游戏本身无关，而是和第三方程序有关。比如 PowerToys 的“查找我的鼠标”功能会在独占全屏时暂时禁用，如果用户使用 PowerToys，肯定希望全局启用“模拟独占全屏”，反之则根本不需要启用。

"模拟独占全屏"是一个高级功能，如果你不知道它会影响哪些程序，那你就不需要它。

**Comment by MinaseInorin** [comment]
> "模拟独占全屏"和游戏本身无关，而是和第三方程序有关。比如 PowerToys 的“查找我的鼠标”功能会在独占全屏时暂时禁用，如果用户使用 PowerToys，肯定希望全局启用“模拟独占全屏”，反之则根本不需要启用。
> 
> "模拟独占全屏"是一个高级功能，如果你不知道它会影响哪些程序，那你就不需要它。

谢谢，问题解决了
