### ISSUE TITLE
Causes freezing and crashing on Black Ops Cold War

### ISSUE THREAD

**Issue by peteallelite** [Blinue/Magpie#59]
As soon as you run the program Black Ops Cold War crashes. Tried windowed, borderless and fullscreen modes.

**Comment by Blinue** [comment]
Magpie has almost no effect on the source window, you can try the "No Injection" option.

**Comment by peteallelite** [comment]
I did, but I had to edit the magpie.exer config file and set it to 0 because I cannot read the writing in the app

**Comment by Norqui789** [comment]
> Ok no injection mode works BUT now the game only displays on half the screen and doesn't scale to the display
> EDIT: Fixed that issue, but using this tool makes the game choppy compared to native 1440p where there is no choppiness at all.

how did u fixed the issue??

**Comment by peteallelite** [comment]
> 
> 
> > Ok no injection mode works BUT now the game only displays on half the screen and doesn't scale to the display
> > EDIT: Fixed that issue, but using this tool makes the game choppy compared to native 1440p where there is no choppiness at all.
> 
> how did u fixed the issue??

I will not be saying as no one was able to reply and help me with my latest issue even after numerous days have gone by.

**Comment by Norqui789** [comment]
> > > Ok no injection mode works BUT now the game only displays on half the screen and doesn't scale to the display
> > > EDIT: Fixed that issue, but using this tool makes the game choppy compared to native 1440p where there is no choppiness at all.
> > 
> > 
> > how did u fixed the issue??
> 
> I will not be saying as no one replied or was able to help me with my latest issue regarding the choppiness even after numerous days have gone by.
> I only help when I'm helped :)

bruh literally i just knew about this program yesterday and when i used it happened that issue and i just enter to github to see if someone have the same issue and i found your post after you solved the issue lol how dont be inmature and selfish literally i dont have the fault that other people before me ignore you lol inmature

**Comment by Norqui789** [comment]
pls say i need to fix that issue lol

**Comment by peteallelite** [comment]
> 
> 
> > > > Ok no injection mode works BUT now the game only displays on half the screen and doesn't scale to the display 
> > > > EDIT: Fixed that issue, but using this tool makes the game choppy compared to native 1440p where there is no choppiness at all.
> > > 
> > > 
> > > how did u fixed the issue??
> > 
> > 
> > I will not be saying as no one replied or was able to help me with my latest issue regarding the choppiness even after numerous days have gone by. 
> > I only help when I'm helped :)
> 
> bruh literally i just knew about this program yesterday and when i used it happened that issue and i just enter to github to see if someone have the same issue and i found your post after you solved the issue lol how dont be inmature and selfish literally i dont have the fault that other people before me ignore you lol inmature

I wasn't just talking about you not helping or replying. I was talking about mostly the developer/maintainer not replying and about others who lurk around.
As I said, I will not be saying how to fix that.
And btw I am immature when/if I need to be. Unfortunately if nobody else has helped me, I tend to not help others.

**Comment by Blinue** [comment]
There have been many reports of performance issues and there is no good solution at this time because there are many bottlenecks that limit performance. #52 is a discussion about improving performance.

If Magpie doesn't work, you should try other tools, such as Lossless Scaling.

**Comment by Norqui789** [comment]
> > > > > Ok no injection mode works BUT now the game only displays on half the screen and doesn't scale to the display
> > > > > EDIT: Fixed that issue, but using this tool makes the game choppy compared to native 1440p where there is no choppiness at all.
> > > > 
> > > > 
> > > > how did u fixed the issue??
> > > 
> > > 
> > > I will not be saying as no one replied or was able to help me with my latest issue regarding the choppiness even after numerous days have gone by.
> > > I only help when I'm helped :)
> > 
> > 
> > bruh literally i just knew about this program yesterday and when i used it happened that issue and i just enter to github to see if someone have the same issue and i found your post after you solved the issue lol how dont be inmature and selfish literally i dont have the fault that other people before me ignore you lol inmature
> 
> I wasn't just talking about you not helping or replying. I was talking about mostly the developer/maintainer not replying and about others who lurk around.
> As I said, I will not be saying how to fix that.
> And btw I am immature when/if I need to be. Unfortunately if nobody else has helped me, I tend to not help others.

and then you are doing to me the same as the people do to you is just inmature lol

**Comment by peteallelite** [comment]
> 
> 
> There have been many reports of performance issues and there is no good solution at this time because there are many bottlenecks that limit performance. [#52 ](https://github.com/Blinue/Magpie/issues/52) is a discussion about improving performance.
> 
> If Magpie doesn't work, you should try other tools, such as Lossless Scaling.

Only took you this long to reply. And no, lossless scaling won't be fit for my purpose. I WANT FSR

**Comment by peteallelite** [comment]
> 
> 
> > > > > > Ok no injection mode works BUT now the game only displays on half the screen and doesn't scale to the display 
> > > > > > EDIT: Fixed that issue, but using this tool makes the game choppy compared to native 1440p where there is no choppiness at all.
> > > > > 
> > > > > 
> > > > > how did u fixed the issue??
> > > > 
> > > > 
> > > > I will not be saying as no one replied or was able to help me with my latest issue regarding the choppiness even after numerous days have gone by. 
> > > > I only help when I'm helped :)
> > > 
> > > 
> > > bruh literally i just knew about this program yesterday and when i used it happened that issue and i just enter to github to see if someone have the same issue and i found your post after you solved the issue lol how dont be inmature and selfish literally i dont have the fault that other people before me ignore you lol inmature
> > 
> > 
> > I wasn't just talking about you not helping or replying. I was talking about mostly the developer/maintainer not replying and about others who lurk around. 
> > As I said, I will not be saying how to fix that. 
> > And btw I am immature when/if I need to be. Unfortunately if nobody else has helped me, I tend to not help others.
> 
> and then you are doing to me the same as the people do to you is just inmature lol

I admitted I was immature. I don't care. Get over it. Bad luck.
