### ISSUE TITLE
Hotkey without modifier (or mouse side button)

### ISSUE THREAD

**Issue by fuyu0425** [Blinue/Magpie#593]
### Expected behavior 预期的功能

原本在 v0.9 我可以使用單個鍵做為 hotkey (e.g. PrintScreen), 但 v0.10 強制要有 modifier like Crtl.

希望能 support 單個鍵 為 hotkey

Usecase: 有些遊戲可以只用滑鼠操作, 如果用 PrintScreen 做為熱鍵，我就可以全程用右手開關。

如果能支持鼠標側鍵，那就更棒了! (之前讀過一下 source code，但對 windows GUI 實在不熟，無法自行實現)

感謝

**Comment by NeilTohno** [comment]
你好，你可以看這裡
https://github.com/Blinue/Magpie/discussions/537#discussioncomment-5630254

**Comment by fuyu0425** [comment]
Ok 
看來只能用 auto hotkey 自己 mapping了
