### ISSUE TITLE
(Not really a issue) How do I download the new version?

### ISSUE THREAD

**Issue by 4ymnoy-doktor** [Blinue/Magpie#60]
7Brandyn7 updated the patch to the English translation, where he updated the sources from August 11. I want to download the original (from you), but I can't find this new version. Where can I download it? Thank you in advance!

**Comment by Blinue** [comment]
You can compile it from source. [Compilation Guide](https://github.com/Blinue/Magpie/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97)

**Comment by 4ymnoy-doktor** [comment]
Ok. Thanks!
