### ISSUE TITLE
希望可以有限制输出帧数的功能以限制功耗，不然4090玩galgame都能直接风扇起飞

### ISSUE THREAD

**Issue by xzf0509** [Blinue/Magpie#616]
### Expected behavior 预期的功能

Force FPS to a determined value such as 30 60 120 144 by magpie itself，not by NVIDIA control panel。

**Comment by xzf0509** [comment]
然后怎么保存超分后的界面截图？我按截图截的还是原窗口及分辨率的图

**Comment by Blinue** [comment]
Duplicate of #378

> 然后怎么保存超分后的界面截图？我按截图截的还是原窗口及分辨率的图

Desktop Duplication 捕获模式下不能截图，否则使用 PrintScreen 或 Win+PrintScreen。
