### ISSUE TITLE
窗口全屏问题

### ISSUE THREAD

**Issue by zhzlpl** [Blinue/Magpie#617]
### Magpie version 程序版本

v0.10.2

### Windows version 系统版本

win11 22h2

### Related screenshot (optional) 相关截图（可选）

![J7UK NWNHAOJF`C 13@0C$5](https://github.com/Blinue/Magpie/assets/52674960/66dbec0c-6434-45aa-b6e4-1ad35e5c21b5)
![AEC35YQXI2(HQJERS(88UPX](https://github.com/Blinue/Magpie/assets/52674960/ddf74a5b-ad2f-437b-a7d5-df631bc961fe)

### Reproduction steps 复现步骤

第一次使用缩放可以实现全屏例如图2，但是第二次游戏原有的窗口会显现出来例如图1，只有在关闭软件后重新开启才可以再次缩放独占全屏。这个问题在[v0.10.0-preview1](https://github.com/Blinue/Magpie/releases/tag/v0.10.0-preview1)这个版本中并没有，但是在这个[v0.10.0-preview2](https://github.com/Blinue/Magpie/releases/tag/v0.10.0-preview2)到最新版中都存在这个问题

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/11504134/magpie.log)

**Comment by Blinue** [comment]
你有没有打开开发者选项里的“调试模式”？

**Comment by zhzlpl** [comment]
> 你有没有打开开发者选项里的“调试模式”？

开启了

**Comment by zhzlpl** [comment]
> > 你有没有打开开发者选项里的“调试模式”？
> 
> 开启了

好像是默认开启的

**Comment by zhzlpl** [comment]
> 你有没有打开开发者选项里的“调试模式”？

关闭之后就好了，谢谢了
