### ISSUE TITLE
XBRZ之类的滤镜可以增加吗？

### ISSUE THREAD

**Issue by xuanyuanwu999** [Blinue/Magpie#62]
对2D老游戏的支持应该好过anime4k

**Comment by Blinue** [comment]
能放对比图吗，对于2D游戏FSRCNNX和ACNet都有很好的效果，如果XBRZ更好我会移植它。

**Comment by xuanyuanwu999** [comment]
> 能放对比图吗，对于2D游戏FSRCNNX和ACNet最好的效果，如果XBRZ更好的我会移植它。
主要是针对像素游戏的……
![ACNET](https://user-images.githubusercontent.com/75255450/129447335-6b3c33bc-93d8-4afd-ba7b-bb1e403e4faa.png)
![FSR](https://user-images.githubusercontent.com/75255450/129447338-cbc2b422-0870-45bc-ace8-8a830da1812a.png)
![XBRZ](https://user-images.githubusercontent.com/75255450/129447340-919f5df9-b830-44a3-aaae-dbc19a35f751.png)

**Comment by Blinue** [comment]
Magpie确实缺少像素画的缩放算法，我会在v0.7里移植它。
暂时可以试试像素缩放，但只能放大整数倍。

**Comment by palxex** [comment]
xbrz对老2D游戏的效果确实不错（除了对汉字字体）。提个建议，不知道有没有可能出一个shader规范（比如说通过一个单独的UserFilter Module），让用户像写userscript一样写新的filter？规范可以考虑参照RetroArch的Slang或者根据需要自己定制一个，另外它那里就有[xbrz的实现](https://github.com/libretro/slang-shaders/tree/master/xbrz)。

**Comment by Blinue** [comment]
这个功能太复杂了，而且只有极少数的用户能使用。对于需要自定义缩放效果的用户我会推荐向Magpie贡献代码或者实现自己的模块，因为Magpie所有的效果都是组织在模块里并在运行时动态加载的。

**Comment by palxex** [comment]
原来如此，谢谢提点

**Comment by LightMu** [comment]
似乎Reshade就有5xBR NoBlend滤镜和4xBRZ滤镜的着色器
https://reshade.me/forum/shader-presentation/4409-5xbr-filter
https://reshade.me/forum/shader-presentation/4416-4xbrz-filter

**Comment by Blinue** [comment]
我正在计划支持自定义着色器，使用自己的规范。下面是一个草稿

``` hlsl
//!TEXTURE
//!WIDTH INPUT.WIDTH
//!HEIGHT INPUT.HEIGHT
//!FORMAT B8G8R8A8
texture2D tex1;

//!TEXTURE
//!WIDTH 200
//!HEIGHT 200
//!FORMAT B8G8R8A8
texture2D tex2;

//!SAMPLER
//!FILTER LINEAR
SamplerState sam1;

//!SAMPLER
//!FILTER POINT
SamplerState sam2;

//!CONSTANT
//!DEFAULT 0
float sharpness;


//!COMMON

#define PI 3.14159265359

//!PASS
//!BIND tex1, sam1, sharpness
//!SAVE tex2

float func1() {

}

float4 Pass1(float4 coord) {

}

//!PASS
//!BIND tex1, tex2, sam2
//!SAVE OUTPUT

float Pass2(float4 coord) {

}

```

**Comment by Blinue** [comment]
基本使用mpv glsl hook的语法。几个要点：
1. 是合法的hlsl
2. 只需定义抽象的像素着色器（Pass）
3. 定义了需要的所有资源（纹理，采样器，参数）
4. 对资源的完全控制，这给予了着色器很大的优化空间

**Comment by JinhuaYe** [comment]
> 能放对比图吗，对于2D游戏FSRCNNX和ACNet都有很好的效果，如果XBRZ更好我会移植它。
测试过官方得xBRZ，执行效率不行，需要优化，如果原始分辨率不高可以满足实时处理需求，比如304*224分辨率的拳皇，再高的话处理太耗时了。
