### ISSUE TITLE
图像放大功能有可能集成到游戏中吗

### ISSUE THREAD

**Issue by JiaChen-Zeng** [Blinue/Magpie#621]
### Question 问题

我是游戏开发者，想问下这工具的功能有没有机会，容不容易直接集成进KIRIKIRI或Unity或RenPy等游戏引擎做的游戏中

**Comment by Blinue** [comment]
为什么不直接提高素材的分辨率呢？效果比实时放大好的多，也无需付出后处理的资源开销。

即使真要加后置滤镜，比起集成 Magpie，自己移植着色器更好。Magpie 的架构不适合集成进游戏，而且它是 GPL 协议的。

**Comment by hooke007** [comment]
而且就算要替代默认的劣质拉伸缩放，为什么不直接移植amd官方的fsr呢
