### ISSUE TITLE
希望能移植Reshade中的FakeHDR着色器

### ISSUE THREAD

**Issue by frdoma** [Blinue/Magpie#629]
### Expected behavior 预期的功能

这是一个很不错也很实用的着色器，在Reshade中是非常常用的着色器之一。不管原游戏和屏幕硬件支不支持HDR都能用这个着色器设置出模拟HDR的效果，也基本不会降低性能，希望Magpie未来的版本能添加这个着色器可供选择。

**Comment by Blinue** [comment]
源码：https://github.com/Mortalitas/GShade/blob/master/Shaders/FakeHDR.fx

看起来很容易移植，我或许会新建一个仓库来存放不那么流行的着色器。

**Comment by Blinue** [comment]
https://github.com/Blinue/MagpieExtras/blob/main/FakeHDR.hlsl

将此文件复制到 effects 文件夹，然后重启 Magpie。
