### ISSUE TITLE
Latest build from commits breaks, Windows 11

### ISSUE THREAD

**Issue by CoderStone** [Blinue/Magpie#63]
![image](https://user-images.githubusercontent.com/34324909/129449071-82525527-5327-459e-871b-bbc58a53af66.png)
Just unstable in general, spams the error above. Thought I should let you know :)

**Comment by Blinue** [comment]
Hello, are you using FSR?

**Comment by CoderStone** [comment]
> Hello, are you using FSR?

Yes! It doesn't appear to happen with anything else.

**Comment by Blinue** [comment]
I've split FSR into two effects, you need to delete ScaleModels.json and run again

**Comment by CoderStone** [comment]
> I've split FSR into two effects, you need to delete ScaleModels.json and run again

Seems to work, thanks. Also, just noting that the module selection doesn't save on rebooting magpie.

**Comment by CoderStone** [comment]
Also, what's the highest sharpness you can set for FSR?

**Comment by CoderStone** [comment]
> Also, what's the highest sharpness you can set for FSR? It appears to be 1.0 before it triggers that error.
![image](https://user-images.githubusercontent.com/34324909/129450177-36ffe5a3-ec02-40a5-9c6d-50161680a818.png)

**Comment by Blinue** [comment]
> Also, just noting that the module selection doesn't save on rebooting magpie.

The options are saved when the window is closed. If you restart Magpie in VS, the program is forced to end, so the options will not be saved.

**Comment by Blinue** [comment]
The sharpness of FsrRcas is limited in 0~1. You can add another FsrRcas or CAS effect if you need more sharpness.

**Comment by CoderStone** [comment]
> > Also, just noting that the module selection doesn't save on rebooting magpie.
> 
> The options are saved when the window is closed. If you restart Magpie in VS, the program is forced to end, so the options will not be saved.

No, I'm running this after build, not through VS. With the latest, all options save except what module I'm using, which returns to lanczos.

**Comment by Blinue** [comment]
Sorry it's a bug :)

I've fixed it.

**Comment by Blinue** [comment]
Now there is no limit to the sharpness of FsrRcas, but a sharpness greater than 1 is not recommended.
