### ISSUE TITLE
Fisheye (Bodycam) effect shader

### ISSUE THREAD

**Issue by IDDQD1337** [Blinue/Magpie#630]
### Expected behavior 预期的功能

I think it will be interesting if it is possible to transfer this shader to this program

Here source: https://www.shadertoy.com/view/4sSSzz

**Comment by Blinue** [comment]
Interesting shader, but not very practical. You can try to port it yourself.

**Comment by IDDQD1337** [comment]
I don't know how to port shaders yet, but I found another version: https://github.com/Oncorporation/obs-shaderfilter/blob/master/data/examples/fisheye.shader 

I think this will be much better

**Comment by Blinue** [comment]
``` hlsl
//!MAGPIE EFFECT
//!VERSION 3
//!OUTPUT_WIDTH INPUT_WIDTH
//!OUTPUT_HEIGHT INPUT_HEIGHT
//!USE_DYNAMIC

//!TEXTURE
Texture2D INPUT;

//!SAMPLER
//!FILTER LINEAR
SamplerState sam;


//!PASS 1
//!STYLE PS
//!IN INPUT

float4 Pass1(float2 pos) {
    float strength = sin(GetFrameCount() / 100.0) * 0.02;

    float2 inputSize = GetInputSize();
    float aspectRatio = inputSize.x / inputSize.y;
    float intensity = strength * aspectRatio;

    float2 coords = (pos - 0.5) * 2.0;
		
    float2 realCoordOffs = (1.0 - coords.yx * coords.yx) * intensity * coords;
    return INPUT.SampleLevel(sam, pos - realCoordOffs, 0);
}

```

**Comment by IDDQD1337** [comment]
Thanks for code i added the ability to adjust the strength of the fish eye

![image](https://github.com/Blinue/Magpie/assets/28530397/915a1c50-ba11-426f-a5a4-4a4721b2d67e)
