### ISSUE TITLE
Adding  Anime4K_Clamp_Highlights.glsl

### ISSUE THREAD

**Issue by YingDoge** [Blinue/Magpie#631]
### Expected behavior 预期的功能

This is an extremly useing addon to the anime4k. The creator said it self that it is recommened to put it before everythign.

https://github.com/bloc97/Anime4K/blob/master/md/GLSL_Instructions_Advanced.md

"It is recommended to always include Clamp_Highlights at the beginning to prevent 
ringing in some anime, but removing it will slightly improve speed."

and using in mpv the effect is quite noticeable while using very little bit of performance. Like another 3-5% in task manger. 

This is an extremly small file only 90 lines, even the Anime4K_Restore_CNN_S is about  137 lines so it look very easy to make it useable in the magpie. 

And are there anyway to sponsour you other than wechat like paypal account.  i would be more than happy to donate some cash to an wonderful personal like you who helped me get into visual novels.

**Comment by Blinue** [comment]
> And are there anyway to sponsour you other than wechat like paypal account. i would be more than happy to donate some cash to an wonderful personal like you who helped me get into visual novels.

Thank you very much. I maintain this software for free, but you can [buy me a coffee](https://www.buymeacoffee.com/blinue) if you like. ☕
