### ISSUE TITLE
black bar at the bottom

### ISSUE THREAD

**Issue by Zoommod** [Blinue/Magpie#637]
### Question 问题

I don’t know if this is a bug, but how do I remove this black bar at the bottom? Note: custom cropping is disabled.

Link to image for better viewing: https://ibb.co/R0Vf124
Game: A Plague Tale: Innocence
Scaling Mode: FSR

**Comment by Blinue** [comment]
Can you provide logs?

**Comment by Zoommod** [comment]
How can I do this?

**Comment by hooke007** [comment]
![image](https://github.com/Blinue/Magpie/assets/41094733/45344844-e1bb-45cd-b7df-372ddb1105c6)
_You will see it only if you choose the correct issue template_

**Comment by Zoommod** [comment]
> <img alt="" width="600" src="https://user-images.githubusercontent.com/41094733/243023325-45344844-e1bb-45cd-b7df-372ddb1105c6.png">
> _You will see it only if you choose the correct issue template_

But how do I generate this log?

**Comment by Blinue** [comment]
Log files are created automatically while the program is running, and you should be able to find them in the logs folder.

**Comment by Zoommod** [comment]
[magpie.log](https://github.com/Blinue/Magpie/files/11641927/magpie.log)
I hope I did it right

**Comment by Blinue** [comment]
Did you window the game when scaling?

**Comment by Zoommod** [comment]
> Did you window the game when scaling?
Yes. In other mode it doesn't work

**Comment by Blinue** [comment]
You should reduce the size of the game window, as it is too large and exceeds the screen size.

**Comment by Zoommod** [comment]
> You should reduce the size of the game window, as it is too large and exceeds the screen size.

It really worked. thank you very much s2
