### ISSUE TITLE
能否将将主页的“游戏内叠加层”更改为“游戏内打开性能监视器”

### ISSUE THREAD

**Issue by cqaqlxz** [Blinue/Magpie#648]
### Expected behavior 预期的功能

游戏内叠加层这个功能很好用，不仅能够查看帧数，还能够查看滤镜的用时，很方便调整滤镜。但我此前一直不知道它是这个功能。如果更改为“打开性能监视器”，会更加易于理解，比较直观。

**Comment by Blinue** [comment]
这个界面不仅用于监视性能，以后可能会用于在缩放时调整参数或选项。游戏内叠加层这个名字挺合适的，英文叫 in-game overlay

**Comment by cqaqlxz** [comment]
那么可以在FAQ里面写上一小段这个功能的介绍，这样就方便了。

**Comment by Blinue** [comment]
可以加上描述
![图片](https://github.com/Blinue/Magpie/assets/34770031/c68cf8a8-a2f5-4ed2-b0a1-b482a37882ad)
