### ISSUE TITLE
Cursor can't move freely between monitors

### ISSUE THREAD

**Issue by mez0ru** [Blinue/Magpie#65]
I'm using two monitors.
It seems that the mouse cannot move to the second monitor unless I leave the fullscreen.
Is it possible to make the cursor move freely between monitors while in fullscreen?
I tried using 3rd party tools to achieve this but it didn't work.

**Comment by Blinue** [comment]
Currently Magpie does not support multiple screens. You can't move the cursor to other screens as it is confined to the window.

**Comment by it0na72** [comment]
Do you think that this would be possible to implement? I tend to use my dictionary to check between multiple screens and this would be incredibly helpful. Thanks in advance.

**Comment by Blinue** [comment]
Cursor can move freely between monitors now, keep an eye on v0.8!

**Comment by it0na72** [comment]
Thanks! when is it coming out?

**Comment by Blinue** [comment]
v0.8 is almost ready to be released, maybe today or tomorrow
