### ISSUE TITLE
希望加入限制magpie帧率的功能/FPS-limited

### ISSUE THREAD

**Issue by sunlghr** [Blinue/Magpie#657]
### Expected behavior 预期的功能

运行magpie时，无法限制magpie的帧率
在没有高帧率需求的游戏内（例如galgame），magpie仍会运行到极高的帧率，使显卡满载，带来了极大的功耗和噪音
我尝试过在显卡驱动内限制游戏和magpie自身的帧率，并未生效

**Comment by Blinue** [comment]
Duplicate of #378

#643 将支持限制捕获帧率，用这个 issue 来追踪。

**Comment by 088uiop** [comment]
Excuse me, no matter how my computer is set, the fps will not exceed 55 after zooming, is it normal?
