### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by Inefficacious** [Blinue/Magpie#659]
### Magpie version 程序版本

0.10.3 x64

### Windows version 系统版本

win 11 pro version 22H2

### Reproduction steps 复现步骤

I start the program after 5 seconds it crashes

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/11763452/magpie.log)

**Comment by Blinue** [comment]
To help me identify the problem, please open the Event Viewer and select Windows Logs - Application, then paste the error message here.
