### ISSUE TITLE
画面拉伸功能

### ISSUE THREAD

**Issue by userName-Unavailble** [Blinue/Magpie#662]
### Expected behavior 预期的功能

某些老游戏窗口尺寸是4:3，16:9的屏幕使用Magpie缩放后有黑边，希望能够添加画面拉伸功能将其全屏缩放。Steam的Lossless Scaling就有类似效果。
![image](https://github.com/Blinue/Magpie/assets/96627940/057c113b-d6c2-40b8-a900-d5a9a849ebab)

**Comment by Blinue** [comment]
将缩放类型设为填充即可。
![image](https://github.com/Blinue/Magpie/assets/34770031/6c632926-48e5-4aa8-aa79-b27a4c792231)

**Comment by userName-Unavailble** [comment]
感谢提醒，之前没有注意到
