### ISSUE TITLE
触发“游戏内覆盖”导致magpie崩溃

### ISSUE THREAD

**Issue by Ptilopsis01** [Blinue/Magpie#666]
### Magpie version 程序版本

0.10.3

### Windows version 系统版本

win11 22621.1848

### Reproduction steps 复现步骤

使用magpie放大窗口——>快捷键触发游戏内覆盖——>magpie卡死并崩溃

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/11781028/magpie.log)

**Comment by Ptilopsis01** [comment]
补充一下，是0.10.3版本才出现的问题，但这个版本刚更新的时候我记得还是没有这个问题的，所以不能确定具体的触发原因

**Comment by Blinue** [comment]
表现和 #649 相同，在开发者选项里禁用字体缓存有用吗？

**Comment by Ptilopsis01** [comment]
> 表现和 #649 相同，在开发者选项里禁用字体缓存有用吗？

确实有用，禁用就能正常打开了

**Comment by Blinue** [comment]
因为我复现不了，你能调查一下是什么导致的吗？

**Comment by Ptilopsis01** [comment]
> 因为我复现不了，你能调查一下是什么导致的吗？

要怎么操作呢

**Comment by Blinue** [comment]
在出现错误前你有没有安装某个软件或改了某个设置？退出其他软件或重启电脑问题还在吗？

**Comment by Ptilopsis01** [comment]
> 在出现错误前你有没有安装某个软件或改了某个设置？退出其他软件或重启电脑问题还在吗？

之前重启试过了，是一样的情况

**Comment by watchingfun** [comment]
确实，开发者选项里禁用字体缓存就不会闪退了

**Comment by Blinue** [comment]
这个问题在 v0.10.4 里依然存在吗？

**Comment by Ptilopsis01** [comment]
> 这个问题在 v0.10.4 里依然存在吗？

没有复现，应该是正常了

**Comment by Blinue** [comment]
既然如此这个 issue 可以关闭了，虽然崩溃原因仍不清楚。 v0.10.4 没有修改字体缓存的逻辑。
