### ISSUE TITLE
怎么做到假全屏，也就是无边框的窗口填满4k屏幕以防止在副屏进行其他操作时主屏的magpie超分投屏自动退出

### ISSUE THREAD

**Issue by xzf0509** [Blinue/Magpie#669]
### Expected behavior 预期的功能

rt

**Comment by Blinue** [comment]
多屏幕的情况下在其他屏幕上操作不会退出缩放，你的场景是什么？

**Comment by xzf0509** [comment]
> 多屏幕的情况下在其他屏幕上操作不会退出缩放，你的场景是什么？

我在主屏对龙神模拟器窗口进行投屏，副屏点qq窗口回复信息时主屏就退出缩放了

**Comment by luojunyuan** [comment]
你的软件版本是？magpie理应早就提供这个功能。我在主屏幕全屏缩放时副屏点击不会退出。

**Comment by Blinue** [comment]
v0.11 应该不会有这个问题，如果在最新版本中依然存在请新开 issue。
