### ISSUE TITLE
magpie长时间使用系统显示占用剩余大部分现存

### ISSUE THREAD

**Issue by poliejun** [Blinue/Magpie#670]
### Magpie version 程序版本

0.10.3

### Windows version 系统版本

win10 22H2

### Related screenshot (optional) 相关截图（可选）

![占用显存过多](https://github.com/Blinue/Magpie/assets/33743173/bad9a7ac-f24d-4689-9159-266ca3a0340a)

### Reproduction steps 复现步骤

使用一段时间后，magpie会吃满大部分显存，虽然好像不影响正常使用，同时运行其他游戏也没问题，但是看到显存占用这么高，心里还是膈应。4070ti有这个问题，以前的版本用3070好像没这个问题。

### Log files 日志文件

[magpie.1.log](https://github.com/Blinue/Magpie/files/11857783/magpie.1.log)
[magpie.2.log](https://github.com/Blinue/Magpie/files/11857784/magpie.2.log)
[magpie.log](https://github.com/Blinue/Magpie/files/11857785/magpie.log)

**Comment by poliejun** [comment]
只要打开magpie，就算不对游戏进行超分辨率，只是挂后台，这个显存依旧占着。

**Comment by Blinue** [comment]
从你的截图里看不出是谁泄露的。试试重启电脑，然后缩放几次看显存是不是在持续增长。

**Comment by BLACKCHARGE** [comment]
任务管理器里面设置一下就可以看到哪个应用占用的显存，再排列一下，这个很好排查的
![image](https://github.com/Blinue/Magpie/assets/57131319/8eb869c5-6383-4897-a585-9dc7b5bc0cdc)
![image](https://github.com/Blinue/Magpie/assets/57131319/42f4a035-5a6d-44ae-aae3-12ac5fdf07d0)

**Comment by NeilTohno** [comment]
你这个问题，怕不是显卡的音频降噪功能造成的
