### ISSUE TITLE
缩放模式可以支持xBR模式吗

### ISSUE THREAD

**Issue by Vang-z** [Blinue/Magpie#684]
### Expected behavior 预期的功能

之前一直使用的是`Lossless Scaling`，近期发现了这个宝藏软件，但是没有`xBR`类型的缩放，所以想询问一下有可能添加这种模式吗💕

**Comment by Blinue** [comment]
支持 xBRZ，它是 xBR 的改进版。

**Comment by Vang-z** [comment]
> 支持 xBRZ，它是 xBR 的改进版。

好的，谢谢，请问`xBRZ`是打算在后期版本中更新吗，目前使用的`0.10.3`中并未看到有这个选项

**Comment by Blinue** [comment]
在缩放配置页面添加xBRZ效果即可
![image](https://github.com/Blinue/Magpie/assets/34770031/f62c3f1a-da4f-426d-b15c-1ef336fa34e7)

**Comment by Vang-z** [comment]
> 在缩放配置页面添加xBRZ效果即可 ![image](https://user-images.githubusercontent.com/34770031/258098801-f62c3f1a-da4f-426d-b15c-1ef336fa34e7.png)

好的，十分感谢，找了一会儿才发现怎么食用😂
