### ISSUE TITLE
Keyboard/controller input breaks down with FSR-filters

### ISSUE THREAD

**Issue by DD-Indeed** [Blinue/Magpie#689]
### Magpie version 程序版本

0.10.3

### Windows version 系统版本

Win10, 22H2

### Reproduction steps 复现步骤

Tested out scaling methods to get one game into fullscreen from 1280x960 window, all of them worked just fine, but for some reason, when I picked up FSR_EASU, keyboard and controller couldn't input anything to the game apart from F-keys. Keyboard and controller worked fine on other games thou after this. And input didn't work on this particular game using this app until I rebooted the whole computer. Never seen this happen before. Looks like either this program or FSR-plugin(s) hook to Dinput-system and mess it up somehow, but only with the program that you just used the scaler with. 

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/12178360/magpie.log)

**Comment by Blinue** [comment]
There is indeed a keyboard hook that may cause compatibility issues. I’m working on this.

**Comment by DD-Indeed** [comment]
> There is indeed a keyboard hook that may cause compatibility issues. I’m working on this.

Allright, good. Also, it seems that when going between different capture methods, it unlocks the framerate and shoots it up to 2000-3000fps in some cases. You could add some kind of cap for that or option to cap it. Graphics Capture-option uses the same what the game uses, but the other options freely jump up to maximum unless you use VSync.

**Comment by Blinue** [comment]
I suggest always enabling VSync to prevent Magpie from consuming excessive resources. I'm currently [rewriting the rendering process](https://github.com/Blinue/Magpie/pull/643) to completely address this issue.
