### ISSUE TITLE
After using Hotkey Application Crashing on Windows 7 (Game: DayZ)

### ISSUE THREAD

**Issue by muratcansimsek** [Blinue/Magpie#69]
![magpg](https://user-images.githubusercontent.com/25007736/129786586-2c4129ef-5054-46a8-8194-b11eba75c2a3.PNG)

**Comment by Blinue** [comment]
Hello, Magpie only supports Windows 10 v1903 and later versions.

**Comment by muratcansimsek** [comment]
> Hello, Magpie only supports Windows 10 v1903 and later versions.

Then F for me.

**Comment by MuhammadUsmanMithani** [comment]
WinRT capture only works in Windows 10 v1903 or above
try using GDI, not sure if that will work  in win 7

**Comment by muratcansimsek** [comment]
> WinRT capture only works in Windows 10 v1903 or above
> try using GDI, not sure if that will work in win 7

I tried, not worked :/

**Comment by CoderStone** [comment]
Magpie depends on the windows api from 1903 or later, so yeah, oof.

**Comment by Blinue** [comment]
In fact, Magpie never works on win7
