### ISSUE TITLE
add launch directly in the tray without a window , I do not use launching the program with a windows

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [Blinue/Magpie#698]
### Expected behavior 预期的功能

add launch directly in the tray without a window , I do not use launching the program with a windows

**Comment by Blinue** [comment]
You can enable the option “Minimize to system tray at startup”, which will make Magpie not show the main window when it starts with Windows.

**Comment by subsubsubsubsubsub** [comment]
without auto start system does not work
![image](https://github.com/Blinue/Magpie/assets/73518754/5a145a27-981a-4c07-9a30-d42dc5e2199f)

**Comment by Blinue** [comment]
It is natural to show the main window when manually launching, and I don’t intend to change this behavior. The `-t` parameter can force Magpie to start minimized to the system tray, and you can create a shortcut and add this parameter.
