### ISSUE TITLE
Anime4KxDeblur 会花屏

### ISSUE THREAD

**Issue by hooke007** [Blinue/Magpie#7]
如图
![Snipaste_2021-06-13_01-02-02](https://user-images.githubusercontent.com/41094733/121783759-0f525200-cbe3-11eb-8a30-4dfadd1e791a.jpg)

json部分应该是没写错
```
    "name": "A4K",
    "model": [
      {
        "effect": "scale",
        "type": "Anime4KxDeblur"
      }
```

**Comment by Blinue** [comment]
感谢提交issue，已确认这是一个bug🕷

Anime4KxDeblur移植自[这里](https://github.com/bloc97/Anime4K/wiki/Deblur-Shaders)，原理就是对Anime4K计算出的差值进行简单锐化（其实效果不好）。在dev分支里，这个效果被删除了，所以修复这个bug也没有意义。

dev分支进行了一些非常提升观感的改进，如果你有条件，可以自己编译。

**Comment by hooke007** [comment]
略可惜
Anime4K_Denoise_Bilateral_Mode ➕ Anime4K_Upscale_CNN_M_x2_Deblur 的效果在不加味精感的表现里是有较高的认可度的。
darkline和thinline的效果....

**Comment by Blinue** [comment]
感谢你的建议。虽然issue关闭了容我多嘴一句，游戏和番剧的视觉效果有很多不同

1. 游戏没有番剧里常见的高斯噪声，但可能会有压缩造成的质量损失，比如振铃
2. 游戏的画面细节较多，且饱和度较高
3. 我倾向于在放大图像的过程中尽量保留原始的视觉效果，因此预置的组合只是基于我的审美。我认为最完美的放大方式为Anime4K+锐化（Deblur）+ThinLines
4. 尽管算法一样，mpv的效果和本程序的效果也很不一样，因为mpv会进行一些后处理，包括细化线条。从视觉角度说，缩小图像会使线条加粗，因此放大后细化线条会更符合人们的心理预期
5. DarkLines效果不好，不建议使用

**Comment by hooke007** [comment]
我用这个也是基于我的状况并不全面，毕竟在我看来a4k的适用面非常狭窄，仅仅适用于老旧的gal，较新的gal即便只用lanczos不加锐化我都非常满意了。

**Comment by Blinue** [comment]
游戏愉快😉
