### ISSUE TITLE
Alt+F11 and Alt+Tab

### ISSUE THREAD

**Issue by ButtERRbrod** [Blinue/Magpie#70]
After turning the scaling mode, I change windows. Scale mode stops making any processing on screen and when I press Alt+F11 it turns off but it can't remember did it actually turn off. So the application wont start post-processing of your screen if you won't fix the current changed window.

**Comment by Blinue** [comment]
Can you describe how to reproduce this issue step by step?

**Comment by ButtERRbrod** [comment]
Start the FSR, then alt+tab to other window.

**Comment by Blinue** [comment]
Please check #16
