### ISSUE TITLE
 希望能增加“设置帧数上限”这个功能

### ISSUE THREAD

**Issue by hojotokimune** [Blinue/Magpie#705]
### Expected behavior 预期的功能

在使用这个软件放大一些2D游戏时经常会跑到1000帧左右，这远远超过了我的预期值，导致了很多不必要的显卡性能浪费，增加了不必要的功耗和发热。
因此，我希望能增加“设置帧数上限”的功能。

**Comment by Blinue** [comment]
Duplicate of #657
