### ISSUE TITLE
当使用多个屏幕启动主窗口时，更改屏幕显示设置之后无法重定位窗口到可用的屏幕

### ISSUE THREAD

**Issue by Howard20181** [Blinue/Magpie#706]
### Magpie version 程序版本

0.10.3 release

### Windows version 系统版本

Win11 10.0.22621.1992

### Reproduction steps 复现步骤

复现步骤一：
1. 连接多个屏幕，编号为1、2，输出模式设置为扩展
2. 启动主窗口，拖到屏幕1
3. 最小化到任务栏
4. 更改屏幕输出为仅屏幕2
5. 从任务栏打开主窗口

复现步骤二：
1. 连接多个屏幕，编号为1、2，输出模式设置为扩展
2. 启动主窗口，拖到屏幕1
3. 最小化到任务栏
4. 更改屏幕输出组合，偏移拼接方法

比如从
<img width="435" alt="image" src="https://github.com/Blinue/Magpie/assets/40033067/d02f29b2-802e-4c4f-95a3-c81c906bf16b">

变换到
<img width="390" alt="image" src="https://github.com/Blinue/Magpie/assets/40033067/ed0280fb-d754-43ad-abd2-06509eb485ef">

5. 从任务栏打开主窗口

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/12405935/magpie.log)

**Comment by Howard20181** [comment]
主窗口会定位到看不见的地方
https://github.com/Blinue/Magpie/assets/40033067/ab4982f7-2fa7-4793-bcd9-4ee8208e2319

**Comment by Howard20181** [comment]
目前绕过方法是在配置文件删掉 `windowPos` 节点

**Comment by Blinue** [comment]
这是因为窗口位置保存成了绝对坐标。这个 bug 很容易修复，谢谢汇报！
