### ISSUE TITLE
add values 0 secundi or 0.1

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [Blinue/Magpie#714]
### Expected behavior 预期的功能

![sshot-004](https://github.com/Blinue/Magpie/assets/73518754/9d7bf915-70db-4bb2-a023-134e77f86367)

**Comment by Blinue** [comment]
I don’t understand what you are saying. I guess you want to fine-tune the delay time?

**Comment by subsubsubsubsubsub** [comment]
The option was for 0 sec

**Comment by Blinue** [comment]
A very short delay is pointless, because you won’t have enough time to switch windows.
