### ISSUE TITLE
cursor out of window on multi monitor setup

### ISSUE THREAD

**Issue by yw4z** [Blinue/Magpie#718]
### Magpie version 程序版本

10.3

### Windows version 系统版本

win 10 ltsc

### Reproduction steps 复现步骤

cursor goes to secondary monitor and losing control of window of game

secondary monitor arrangement on left and move my mouse left loose control

same on other arrangements

tried desktop duplication and graphics capture and same result

my mouse speed is 17, main monitor 2k, secondary monitor 1080p

thanks

### Log files 日志文件

[magpie.2.log](https://github.com/Blinue/Magpie/files/12586347/magpie.2.log)
[magpie.log](https://github.com/Blinue/Magpie/files/12586348/magpie.log)
[magpie.1.log](https://github.com/Blinue/Magpie/files/12586349/magpie.1.log)

**Comment by Blinue** [comment]
This is a design, turn on "3D game mode" to suppress this behavior.

**Comment by yw4z** [comment]
lol :) thanks it works
