### ISSUE TITLE
Game freeze after pressing Magpie hotkeys 

### ISSUE THREAD

**Issue by Norqui789** [Blinue/Magpie#72]
I have an issue my game freeze everytime i press hotkeys when i use a gamepad it freeze or when im playing games with mouse and keyboard it freeze when the cursor disappear to play only works when the cursor is in the windows border  pls help

**Comment by Blinue** [comment]
Sorry, what does 'freeze' mean?

**Comment by Norqui789** [comment]
It means 冻结, the game do that but i can still move and there is audio but the image freeze

**Comment by Blinue** [comment]
You can try not to use the process injection option.

**Comment by Norqui789** [comment]
i tried everything the issue happens when the cursor disappear to play the game

**Comment by Blinue** [comment]
Obviously an unexpected error occurred when rendering the cursor. I will fix it soon.

**Comment by Norqui789** [comment]
Then when the cursor disappear the game just freeze i hope u can fix it

**Comment by HealGea** [comment]
Same thing happens in Kingdom come deliverance too. When you open waiting menu and start the wait timer in the game, the screen just freezes. If inject runtime is selected, Magpie just crashes itself.

**Comment by Blinue** [comment]
I am closing this as it is outdated. If you encounter this problem in the latest version, please file a new issue.
