### ISSUE TITLE
Magpie crashes upscaling game at 1080p or above in the newest windows 11 update 

### ISSUE THREAD

**Issue by YingDoge** [Blinue/Magpie#720]
### Magpie version 程序版本

Magpie_v0.10.3. 22621.2215

### Windows version 系统版本

Windows 11 Pro 22H2

### Related screenshot (optional) 相关截图（可选）

<img width="549" alt="image" src="https://github.com/Blinue/Magpie/assets/135021273/2c8f8680-4dc3-42c8-814d-1fcca90351f8">

<img width="592" alt="image" src="https://github.com/Blinue/Magpie/assets/135021273/7d653e3a-f033-4e0f-a67b-6a8a68ac633c">

<img width="520" alt="image" src="https://github.com/Blinue/Magpie/assets/135021273/1abf20dc-739b-409f-9470-5c597384fda7">

### Reproduction steps 复现步骤

Good Morning or evening everyone. That i have been using anime 4k on magpie for fast 2 years basically every day but after i update my pc to leastes windows 11 after few days it stopped working. The magpie would only crash when having 4 anime 4k at same time, my set up in the photo. But it is completely fine if it was 2.  Anything more than 2 would result in crash in the magpie and game in Win 11. 

As you can see i am a 4090 and it was running fine window 10 so performance is not a issue here i think it is magpie it self.  The PC was competely reset (reintall window). Win 11 was running fine for the first few days somehow. 

There here is video of what is happening 
https://www.youtube.com/watch?v=HoktjNnyZeo

So personall i think it is something do some with the code of Magpie that doesnt allow more than 2 Anime 4k in Win 11, or it is something do to with anime 4k restore.  Personal Opion could be total wrong.
 
So i would personally donate 20 USD  if anyone coudld help me solves it as magpie is really part of my daily life and i cant live with out it

Update!!!!!!!!!!!!!!!!!: I think it is the problem with anime 4k restore as soon as i removed them the game runned 
### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/12592343/magpie.log)

**Comment by Ptilopsis01** [comment]
I don't know what caused this problem, but you just need 1 anime4k upscale filter, for the source is 1920*1080, which just need to be doubling once to fit your 3840*2160 monitor.

**Comment by YingDoge** [comment]
> I don't know what caused this problem, but you just need 1 anime4k upscale filter, for the source is 1920x1080, which just need to be doubled once to fit your 3840x2160 monitor.

I have an samsumg QN990C 8k tv which i used to game on. and a 4k monitor for daily use

**Comment by YingDoge** [comment]
> I don't know what caused this problem, but you just need 1 anime4k upscale filter, for the source is 1920x1080, which just need to be doubled once to fit your 3840x2160 monitor.

But thanks though

**Comment by Blinue** [comment]
Have you tried using a lighter restore variant, such as VL? Changing the capture method might also help.

**Comment by YingDoge** [comment]
> Have you tried using a lighter restore variant, such as VL? Changing the capture method might also help.

No i tried Vl It still doesnt work

**Comment by YingDoge** [comment]
> Have you tried using a lighter restore variant, such as VL? Changing the capture method might also help.

Also This is only in W 11 dont know why. maybe a window bug ???

**Comment by Ptilopsis01** [comment]
Maybe you can try changing your capture method or turn 3d game mode on. I remember that I've met similar problem before, and it was a game settings problem, but I've just checked and not find the setting option in 千恋万花

**Comment by YingDoge** [comment]
> Maybe you can try changing your capture method or turn 3d game mode on. I remember that I've met similar problem before, and it was a game settings problem, but I've just checked and not found the specific setting option in 千恋万花

What setting have you changed just wondering

**Comment by YingDoge** [comment]
> Have you tried using a lighter restore variant, such as VL? Changing the capture method might also help.

Not tried all 4 and even changed into 3d mode and it still doestn wrok

**Comment by YingDoge** [comment]
Great New everyone i think i have fund the problem. Just set everything to auto in 千恋万花 and other game using the same engine would solve the problem (resoultion is not a problem just other small options).

**Comment by YingDoge** [comment]
> Maybe you can try changing your capture method or turn 3d game mode on. I remember that I've met similar problem before, and it was a game settings problem, but I've just checked and not found the specific setting option in 千恋万花

Yes i thin this problem only exists in Senren＊Banka (千恋万花) could you please tell me which option to disable please thanks. I could try to disable it somehow.

**Comment by YingDoge** [comment]
I think i reall find the reaosn why Guys. it crash only happens in 1080p visual novel game. i tried  Senren ＊ Banka (千恋万花) in 720 and other few game that is in 720p and it is completely fine. But it come to game that is 1080p it crashes when i have 3 or more anime 4k.

> Have you tried using a lighter restore variant, such as VL? Changing the capture method might also help.

**Comment by kato-megumi** [comment]
When you upscale a 1080p screen by a factor of 4, it will result in a resolution of 17280x30720, which exceeds the maximum texture limit (16384) of DirectX 11. 
https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-resources-limits

**Comment by Ptilopsis01** [comment]
> When you upscale a 1080p screen by a factor of 4, it will result in a resolution of 17280x30720, which exceeds the maximum texture limit (16384) of DirectX 11. https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-resources-limits
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/d1b22f6fdae5da26097e6e97640c77b3a619d0a28bcd1f6a6d92df35a14ff992/68747470733a2f2f6c6561726e2e6d6963726f736f66742e636f6d2f656e2d75732f6d656469612f6f70656e2d67726170682d696d6167652e706e67">**[Resource Limits (Direct3D 11) - Win32 apps](https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-resources-limits)**This topic contains a list of resources that Direct3D 11 supports (specifically feature level 11 or 9.x hardware).

But there are only two upscale filters in his settings, and the output should be only 8k.

**Comment by YingDoge** [comment]
> When you upscale a 1080p screen by a factor of 4, it will result in a resolution of 17280x30720, which exceeds the maximum texture limit (16384) of DirectX 11. https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-resources-limits
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/d1b22f6fdae5da26097e6e97640c77b3a619d0a28bcd1f6a6d92df35a14ff992/68747470733a2f2f6c6561726e2e6d6963726f736f66742e636f6d2f656e2d75732f6d656469612f6f70656e2d67726170682d696d6167652e706e67">**[Resource Limits (Direct3D 11) - Win32 apps](https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-resources-limits)**This topic contains a list of resources that Direct3D 11 supports (specifically feature level 11 or 9.x hardware).

Yes only 2 upscale. 2x 2x. i needed it for my 8k tv. This only happen on Win 11

**Comment by Ptilopsis01** [comment]
> > Maybe you can try changing your capture method or turn 3d game mode on. I remember that I've met similar problem before, and it was a game settings problem, but I've just checked and not found the specific setting option in 千恋万花
> 
> What setting have you changed just wondering, as this is hapeening all other games, and i have chcked chanign the capture mode and 3d mode it doesnt work

![image](https://github.com/Blinue/Magpie/assets/93318731/896a91a5-ff4f-46bd-b5b8-c4f0a51e0a64)
This setting can be found in some old krkr engine games, but I didn't find it in 千恋万花

**Comment by kato-megumi** [comment]
> But there are only two upscale filters in his settings, and the output should be only 8k.

Sorry, I misread the the settings.
Cant reproduce it though. It run just fine in my windows 11 PC.
<img width="1512" alt="Screenshot 2023-09-14 at 18 49 21" src="https://github.com/Blinue/Magpie/assets/29451351/2ef7f298-19f1-4d8b-9768-e29e54e34e9f">

**Comment by YingDoge** [comment]
> > But there are only two upscale filters in his settings, and the output should be only 8k.
> 
> Sorry, I misread the the settings. Cant reproduce it though. It run just fine in my windows 11 PC. <img alt="Screenshot 2023-09-14 at 18 49 21" width="1512" src="https://user-images.githubusercontent.com/29451351/267936219-2ef7f298-19f1-4d8b-9768-e29e54e34e9f.png">

Hmmm weird, so its my pc's problem i assum? i updated all the drivers too hmmmmm

**Comment by YingDoge** [comment]
@Blinue @kato-megumi @Ptilopsis01 Guys i finally out the fucking reason why. Why Fucking Stupid Ass roomate when overclocking my PC espically my grafic card. that this son of bitch over clocked my GPU by 500mgz. It is total fine to do that during the normal 3A title but not for magpie as it is overheat my GPU too quickly.  

I am deeply sorry eveyone for my stupidty and i will donate 20 USD to the owner later in the week after i got my paycheck for my redemption.

**Comment by boludoz** [comment]
@YingDoge francomaro@gmail.com for parches for Shin Megami Tensei V

**Comment by YingDoge** [comment]
@boludoz Wait is this for the person who made the patches ?

**Comment by boludoz** [comment]
He's called Frank

**Comment by YingDoge** [comment]
@boludoz ok thanks a lot i will get in contact wiht him regarding with the mod
