### ISSUE TITLE
请问未来会添加 FSR 3 的支持吗？

### ISSUE THREAD

**Issue by JipZeonGit** [Blinue/Magpie#724]
### Expected behavior 预期的功能

请问未来会添加 FSR 3 相关的支持吗？FSR 3 新增了AMD Fluid Motion Frames（AFMF）光流帧生成技术，有没有可能在不影响原来游戏的情况下使用Magpie实现给游戏补帧呢？

**Comment by kato-megumi** [comment]
Duplicate of #634
