### ISSUE TITLE
PIP (picture in picture)

### ISSUE THREAD

**Issue by 2ji3150** [Blinue/Magpie#728]
### Expected behavior 预期的功能

由于本软件是基于抓屏实现,我推测PIP应该是可以实现的.
具体的范例像是浏览器firefox的pip实装那样,能做到
1. always on top
2. 能控制
3. 可以变更大小

**Comment by Blinue** [comment]
理论上可以，但一般 PIP 不能操作源窗口（只支持简单的操作如暂停和继续视频），和 Magpie 功能不同。#135 应该能满足你的需求。
