### ISSUE TITLE
启动缩放后还有原本游戏的小窗

### ISSUE THREAD

**Issue by ljc1314** [Blinue/Magpie#732]
### Magpie version 程序版本

0.01.3

### Windows version 系统版本

Windows 11 教育版 版本	22H2 

### Related screenshot (optional) 相关截图（可选）

![5480e48f271ee8169b3f498497a2340](https://github.com/Blinue/Magpie/assets/105982229/b2177822-ac54-4f9b-815c-7c471d9f2fba)

### Reproduction steps 复现步骤

启动缩放后就是这样，切换缩放模式也不管用

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/12909417/magpie.log)

**Comment by Blinue** [comment]
你是不是在设置->开发者选项里启用了”调试模式“？
