### ISSUE TITLE
Phosphor as a dedicated effect and apply to whole desktop

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [Blinue/Magpie#733]
### Expected behavior 预期的功能

Recently I noticed there are people talking about CRT shaders, so I tried CRT-Geom, and very satisfied with the results. Then I tried CRT-Hyllian, finally discovered the key makes me feels satisfy is an option called "Phosphor".

1. Without Phosphor, CRT-Hyllian feels just like some sort of "Nearest" upscale and nothing special. So I start to think what if I use this effect with others exist upscale algorithm like FSRCNNX or FSR 1?

2. Also, what if I just apply this effect to my 2D desktop, skip the upscale?

So this feature request is,  
1: A new effect "Phosphor" that can work with other upscale algorithm  
2: Allow magipie to capture whole desktop instead of a specified window (no upscale, only effect Phosphor is applied)

### Alternative behavior (optional) 近似的功能（可选）

- CRT-Geom
- CRT-Hyllian
- FSR 1
- FSRCNNX

**Comment by mhtvsSFrpHdE** [comment]
What does it look like from top to bottom:
- Nearest (or integer)
- CRT-Hyllian with Phosphor off
- CRT-Hyllian with Phosphor on
![image](https://github.com/Blinue/Magpie/assets/10773245/05dadfc3-991d-4474-9eb9-8fd87413988f)

**Comment by Blinue** [comment]
Phosphor is a unique texture of CRT, which does not work well alone. Here is a simple implementation.
```hlsl
//!MAGPIE EFFECT
//!VERSION 3

//!TEXTURE
Texture2D INPUT;

//!SAMPLER
//!FILTER POINT
SamplerState sam;


//!PASS 1
//!STYLE PS
//!IN INPUT

float4 Pass1(float2 pos) {
    float3 dotMaskWeights = lerp(
        float3(1.0, 0.7, 1.0),
        float3(0.7, 1.0, 0.7),
        floor(fmod(pos.x * GetOutputSize().x, 2.0))
    );

    return float4(INPUT.SampleLevel(sam, pos, 0).rgb * dotMaskWeights, 1);
}
```

> Allow magipie to capture whole desktop instead of a specified window (no upscale, only effect Phosphor is applied)

You can use Magpie as a filter in fullscreen games. Just turn on the “Allow scaling maximized or fullscreen windows” option.

**Comment by mhtvsSFrpHdE** [comment]
@Blinue Oh my god! Your code runs perfectly! It did exactly what it should: it can append to after any other upscale algorithm and add Phosphor effect to them, so the upscale choices are not limited by CRT_Hyllian.

## not work well alone
When you mentioned "which does not work well alone", I have the other opinion.  
I believe the "Phosphor" works in LCD sub-pixel area, similar to ClearType, or RGB font antialiasing.  
If you just zoom it out 800% and compare to other algorithm 800%,  
it was basically a trash. However, when you put it on a 1:1 LCD screen, suddenly some unusual happened.

I even discovered without add upscale before Phosphor, just use the shader directly, it will use Nearest to scale up.  
In this case, the upscaled result is just the same as integer if 1920x1080 to 3840x2160, plus Phosphor.  
But when it goes on screen, I clearly see pixel and jagged edges were smoothed.  

This smooth only appears on eye visual and can not be preserved by screenshot,  
exactly like if you screenshot ClearType fonts, you just get some colored edge but no more smooth in screenshot.  
In this case, the FSR 1 can't even do better than just use Phosphor (Nearest) directly.

## whole desktop
"Allow scaling maximized or fullscreen windows" indeed works on fullscreen Firefox or mpv player.

**Comment by mhtvsSFrpHdE** [comment]
Update to magpie v4

https://github.com/mhtvsSFrpHdE/subpixel-nearest
