### ISSUE TITLE
希望能自动识别galgame进程并自动应用预设的全屏配置 

### ISSUE THREAD

**Issue by Betrayal0214** [Blinue/Magpie#734]
### Expected behavior 预期的功能

现在每次玩新游戏都要手动新建配置和改自动缩放，然而每个游戏我用的都是同一个配置，这太麻烦了

**Comment by Betrayal0214** [comment]
![屏幕截图 2023-10-17 172735](https://github.com/Blinue/Magpie/assets/132890238/aac39a88-e998-407f-9c7e-39b3a00308db)

**Comment by Blinue** [comment]
如果实现了 #721 会方便很多。每个人的配置和桌面分辨率都不同，自动应用是做不到的。
