### ISSUE TITLE
Run program at scale start and end

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [Blinue/Magpie#736]
### Expected behavior 预期的功能

According to https://github.com/Blinue/Magpie/issues/733, I use Phosphor now. But this effect loses some brightness as the cost.  
Luckily, my monitor supports DDD/CI, so I can run command like `ddccli.exe -b 15` with [ddccli](https://github.com/hensm/ddccli) tool.

The rest would be `ddccli.exe -b 30` when scale is started, and `ddccli.exe -b 15` when exit scale for any reason.  
Not yet sure how to do that.

**Comment by Blinue** [comment]
This is obviously not a common request. You can try using the **ImageAdjustment** effect to adjust the brightness. If you have some programming skills, you can also easily [monitor the creation and destruction of the scaling window](https://github.com/Blinue/Magpie/issues/503#issuecomment-1483759161).
