### ISSUE TITLE
每次退出缩放模式显存不会释放

### ISSUE THREAD

**Issue by poliejun** [Blinue/Magpie#738]
### Magpie version 程序版本

0.10.3

### Windows version 系统版本

win10 22H2

### Related screenshot (optional) 相关截图（可选）

使用anime4k进行缩放，大约2k占用0.2GB显存，4k占用0.5GB显存，问题是关闭缩放模式，切出去，再切回来，再次启动缩放，之前占用的显存就不会被释放，再次进入就会额外再占用显存，直到爆显存。

### Reproduction steps 复现步骤

使用anime4k进行缩放，大约2k占用0.2GB显存，4k占用0.5GB显存，问题是关闭缩放模式，切出去，再切回来，再次启动缩放，之前占用的显存就不会被释放，再次进入就会额外再占用显存，直到爆显存。

### Log files 日志文件

[log.txt](https://github.com/Blinue/Magpie/files/13072295/log.txt)

**Comment by Blinue** [comment]
鉴于无法复现，我要关闭这个 issue。如果要提供更多信息就重新打开它。
