### ISSUE TITLE
World of Horror Exits Magpie fullscreen on different load screens

### ISSUE THREAD

**Issue by kanjieater** [Blinue/Magpie#743]
### Magpie version 程序版本

v0.10.3

### Windows version 系统版本

Win 11

### Reproduction steps 复现步骤

Start World of Horror. Turn on Magpie with 1x integer scale resolution. Start the game from the main menu. When the loading screens start, the window moves and magpie fullscreen disappears.

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/13199083/magpie.log)

**Comment by Blinue** [comment]
This is expected. The scaling will end when the window is moved. If the “Auto restore” option is enabled, Magpie will automatically go back to fullscreen after the movement.
