### ISSUE TITLE
Auto Delayed Scrolling 

### ISSUE THREAD

**Issue by hlebushekhub** [Blinue/Magpie#748]
### Expected behavior 预期的功能

I use a lot of games with your app and sometimes adding all the games into the Magpie itself as a profiles is a little time consuming. One feature that I really need is to use auto delayed option whenever Magpie is opened. For example, I can manually add the app to the Playnite interface which allows you to run two applications at once (in my case it will be a game + Magpie). That way I will no longer have to use the option to add a game to profiles and each active window will automatically increase via Magpie when starting a new game

**Comment by Blinue** [comment]
This is a very useful feature that I think can be implemented by adding  a command-line option. See #686
