### ISSUE TITLE
Awesome Work, much Appreciate it, mainly interested for FSR, have a question about it

### ISSUE THREAD

**Issue by Predator4578** [Blinue/Magpie#75]
Hi i recently used this tool to test FSR in Videogames, it is a really nice Feature
i have Sucessfully Tested it on my Main Monitor in some games i play
the performance difference is feelable when i upscale from1920x1080 to 2560x1440 

Now i have 3 Monitors (same Size, in Nvidia Surround Configuration) in a Landscape Mode
resulting in a Resolution of 7850x1440 (Beezel corrected) or 7680x1440 (no Correction)

there are also some games that i can play on this resolution because they have good FOV/viwe settings
but somehow whenever i try to upscale from 5760x1080 (3xFullHD) any windowed game just quickly
displays the yellow indicator that the FSR injection is toggeled but the window does not change the size

Now the Question; is it a limitation in this Github App to not support "Ultra Extended Wide Screen" resolutions 
or is it a Limitation of the FSR Algorythm? 
i would really appreciate if it would be Possible to add support for those Resolutions

**Comment by Blinue** [comment]
GPU has limitations on image size. I guess your GPU can handle images up to 4096*4096, so it will fail on a resolution of 5760x1080.
Magpie currently has no plans to support widescreen.

**Comment by CoderStone** [comment]
> GPU has limitations on image size. I guess your GPU can handle images up to 4096*4096, so it will fail on a resolution of 5760x1080.
> Magpie currently has no plans to support widescreen.

Is 3440x1440 supported? ;-;

**Comment by Predator4578** [comment]
but this would be a very awesome feature, and tbh FSR would even make most sense to those Widescreen resolutions due it uses mostly more performance than the average 16:9 formats, and also todays GPUs have the WQHD Standart, meaning this resolution will be anyway in a good FPS range on not matter wich of the series u got...

i would also like to donate u upon implement this btw, just saying, it cant be the image size limitation else the 3090 would be a joke, i have also sucessfully tested DLSS on my widescreen setup in warthunder for example, also the GPU support Resolutions up to 8K, why it should be limited? i hope u will increase your support for widescreens, i bet its possible to do

**Comment by Blinue** [comment]
This issue should have been resolved. Magpie can be used on any resolution now.

**Comment by Predator4578** [comment]
> This issue should have been resolved. Magpie can be used on any resolution now.

oh i didnt know that before writing this in https://github.com/Blinue/Magpie/issues/278

i will today evening Test this out and report to you! if its working i will held my Word! Thank you in advance

**Comment by Predator4578** [comment]
Do u might know where i can Find an Updated V8 english version of Magpie? or do i need to compile myown?

**Comment by Blinue** [comment]
No update required, v0.8 should work well

**Comment by Predator4578** [comment]
I can Confirm FSR apply on my Resolution now Very Nice!!! Tested With Warframe Free to Play Game, Running in windowed mode at 5870x1080 stretches flaweless to 7850x1440 !!! Good work here, even the App now Features English by default Great!
Just one Question, NIS is not showing up in the List, is it because it is not Supported by the Nvidia Driver to have the NIS Menu enabled in Global Settings while having Nvidia Surround enabled? so it is not available even with a "Trick"?

how can i reach u for a donation? paypap  prefered

**Comment by Predator4578** [comment]
would it be possible to Scale to a Borderless window with Custom Size instead to enter a "Fullscreen" like window?

**Comment by Blinue** [comment]
> would it be possible to Scale to a Borderless window with Custom Size instead to enter a "Fullscreen" like window?

#135 This feature is difficult to implement, but not impossible.

> NIS is not showing up in the List

You can customize the scaling configuration to use NIS, but it's very slow now. https://github.com/Blinue/Magpie/issues/202#issuecomment-981352269

> how can i reach u for a donation?

I'm not accepting donations. If this project has been helpful to you, please give more feedback.
