### ISSUE TITLE
這個適合用來玩第一人稱射擊遊戲嗎？

### ISSUE THREAD

**Issue by tak40548798** [Blinue/Magpie#76]
如題?

如果螢幕是2k
顯卡性能不足
為了更高的fps
所以只能把遊戲變成1080p
全螢幕放大到2k
肯定會糊掉

如果用這種縮放程式是否有可能讓畫面清晰一點？
比方說apex legends這類的fps game
這個的原理和外掛是否類似？
會不會被偵測外掛的程式偵測到有異常？

**Comment by hooke007** [comment]
https://github.com/Blinue/Magpie/issues/28#issuecomment-892598968

**Comment by CoderStone** [comment]
Magpie adds a bit of input delay in my experience, so it's not really viable for competitive shooters in the first place.
Additionally, it doesn't have an inbuilt AA, so it will look blurry.
