### ISSUE TITLE
Ability to upscale to another monitor

### ISSUE THREAD

**Issue by bakwas247** [Blinue/Magpie#77]
In the scenario that a user has a 720p monitor and a 1080p monitor, it'd be useful to be able to upscale an application from the 720p monitor to the 1080p monitor. I believe this could get rid of the double cursor issue without hooking onto anything, since the image on 1080p monitor won't include the system cursor. If this is possible, then using virtual monitors you could circumvent the double cursor issue on games that can't be hooked onto (anticheats, hook doesnt work etc.)

**Comment by Predator4578** [comment]
you could already do this when u would select the 720P monitor as second Monitor and let the to be scaled Application to be Runned in 720p on the Main Monitor (1080p) and then it will upscale it to 1080p from 720p? or wdym?

the scenario u describing in fact would mean u are trying to Render the Window 720p on output 1 (720p) and simultanous Render it also on output 2 (1080p) but upscaled?  o.O

**Comment by Blinue** [comment]
I'm closing this issue because it's obsolete. The double cursor issue was fixed in v0.6.1 and multi-monitor support was added in v0.8.0.
