### ISSUE TITLE
N卡546.01之后的驱动使用anime4k restore UL模型性能开销几乎翻倍

### ISSUE THREAD

**Issue by gman771** [Blinue/Magpie#782]
### Program(Game) 游戏名

potplayer

### Capture method 捕获模式

graphics capture

### Other information (optional) 补充信息（可选）

测试显卡为3070，平常用anime4k restore soft UL+fsrcnnx补番用，今天把驱动升级到546.33后发现帧数下降了很多，观察性能监测发现其中anime4k restore soft UL开销比之前驱动大了近乎一倍，安装上一个版本驱动546.01也一样，退回之前用的537.58版本后才正常。

### Log files 日志文件

[magpie.1.log](https://github.com/Blinue/Magpie/files/13694021/magpie.1.log)

**Comment by Blinue** [comment]
驱动的 bug 请耐心等待英伟达修复。Magpie 只使用 Direct3D 接口，没有针对特定显卡品牌的优化。

**Comment by cqaqlxz** [comment]
直接用magpie拉potplayer的窗口显得有点不太合适，可以使用mpv套anime4k滤镜
