### ISSUE TITLE
Is it possible to get the FSRCNNX models in tensorflow/pytorch/onnx format for experimenting?

### ISSUE THREAD

**Issue by kristoftunner** [Blinue/Magpie#788]
### Expected behavior 预期的功能

FSRCNNX models are uploaded as an artifact or directly to the source repo in order to experiment with it instead of only storing it in the shader file.

**Comment by hooke007** [comment]
You must misunderstood sth. https://github.com/yifanw90/FSRCNN-TensorFlow
This repo just port its fork version.

**Comment by Blinue** [comment]
The statement 'stored in the shader file' is not entirely accurate; we need to port FSRCNNX into a format understandable by Magpie, namely HLSL. There's a plan in place to [support ONNX](https://github.com/Blinue/Magpie/issues/772), but other formats won't be accommodated.

**Comment by kristoftunner** [comment]
onnx format would be super heplful!
