### ISSUE TITLE
galgame致命错误

### ISSUE THREAD

**Issue by EiennoXc** [Blinue/Magpie#789]
### Magpie version 程序版本

0.10.4 ; 0.9.1

### Windows version 系统版本

win10 22h2

### Related screenshot (optional) 相关截图（可选）

galgame《无法忍耐的处男哥哥和不直率的叛逆妹妹》，成功运行一分钟左右出现错误弹出。
Direct3DCreate9::CreateDevice() failed
![捕获](https://github.com/Blinue/Magpie/assets/93081744/2ff34be4-c298-4576-87bc-19ab9865c988)

### Reproduction steps 复现步骤

运行游戏1分钟左右即可复现。

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/13734452/magpie.log)

**Comment by Blinue** [comment]
看起来和 #588 相同
