### ISSUE TITLE
自动隐藏光标

### ISSUE THREAD

**Issue by 2ji3150** [Blinue/Magpie#794]
### Expected behavior 预期的功能

不知道能不能实现这样的功能。

```
超过5秒没感知到鼠标操作，自动隐藏光标。
再度感知到鼠标操作时，显示光标。
```

**Comment by Blinue** [comment]
这超出了 Magpie 的职能，我记得有专用的软件。而且不想看见光标的话移到右下角即可。

**Comment by Blinue** [comment]
这超出了 Magpie 的职能，我记得有专用的软件。而且不想看见光标的话移到右下角即可。

**Comment by 2ji3150** [comment]
因为设置里面有绘制光标与否的选项。
想说这个若是可以动态切换的话。

**Comment by Blinue** [comment]
这个软件可以满足你的需求：https://www.softwareok.com/?seite=Microsoft/AutoHideMouseCursor
这个功能超出了 Magpie 的边界，我不打算实现，但如果有贡献我很乐意接受。谢谢你的建议！
