### ISSUE TITLE
主屏开用magpie全屏后，副屏的帧率也跟着一起掉了

### ISSUE THREAD

**Issue by Estelle-Bright** [Blinue/Magpie#796]
### Question 问题

大佬好，我用主屏来打游戏时，同时想在副屏放个视频，但是主屏开了magpie后两个屏都掉帧了，我应该如何设置来让副屏的帧率不掉，好播放视频

**Comment by Blinue** [comment]
是不是用了重量级的效果让 GPU 满载了？

**Comment by Estelle-Bright** [comment]
抱歉了，没注意看，确实时开了太高级的效果导致GPU跑到100%了
