### ISSUE TITLE
Performance Halved with Magpie FSR

### ISSUE THREAD

**Issue by Gamcoaster** [Blinue/Magpie#798]
### Program(Game) 游戏名

Grand Theft Auto 5

### Capture method 捕获模式

GraphicsCapture

### Related screenshot (optional) 相关截图（可选）

![Grand Theft Auto V 1_1_2024 9_57_19 PM](https://github.com/Blinue/Magpie/assets/97459855/abe3d010-49f8-4a66-8c7e-764ad7f8cf82) The higher FPS one is the game running itself

![Grand Theft Auto V 1_1_2024 10_00_50 PM](https://github.com/Blinue/Magpie/assets/97459855/03130ddc-d9f9-407a-8673-6372b6ce6b46)
The lower FPS is with Magpie FSR scaling

### Other information (optional) 补充信息（可选）

I downloaded Magpie because I got to know I could use FSR with it.
The tutorials I saw said I need to run the game in windowed mode and FSR will upscale it to native resolution. So I lowered the setting to the max I could, turned off shadows and did 640x480p resolution in game files so that I could achieve 25-30 playable FPS. But when I upscale with Magpie, the game looks the exact same but the FPS drop to 15-16. This is the exact opposite of what I want.
Is there any fix for this problem?

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/13805271/magpie.log)

**Comment by Blinue** [comment]
Hello, you may have misunderstood how to use Magpie. Please refer to https://github.com/Blinue/Magpie/issues/494#issuecomment-1455274744. If the scaling fails, try changing the capture method.

**Comment by Gamcoaster** [comment]
> Hello, you may have misunderstood how to use Magpie. Please refer to [#494 (comment)](https://github.com/Blinue/Magpie/issues/494#issuecomment-1455274744). If the scaling fails, try changing the capture method.

The game does scale but the fps drops a lot. I tried with Genshin Impact, it does have FSR 2 but I can't fullscreen unless I do 1920x1080, which is unplayable on my Intel iGPU. I get around 20-25 in windowed mode. But after scaling, I suddenly have 2 RivaTuner overlays with the bigger size saying about the same fps I would get in windowed mode normally, and smaller one in the top left on top the black bars saying 3 fps. Downpoint, the game feels like 3 fps.
Same thing with GTA 5, I feels like 15-16 fps. I can't even look around smoothly in any game. They give better expirence without Magpie.
And yeah, I did read the comment thread but couldn't find anything regarding my problem except for the second last comment of yours explaining some functionality of Magpie.

**Comment by Blinue** [comment]
If the graphics card has enough resources, running Magpie has much lower overhead than running the game in full screen mode, so it can improve the frame rate. Otherwise, it will cause the frame rate to drop, because the graphics card is already overloaded. Playing modern 3D games with an integrated graphics card is unrealistic, and Magpie cannot change that.

**Comment by Gamcoaster** [comment]
So do you mean that I need a new PC to actually benefit from Magpie? If yes, then let me tell you that the framerate also drops on a simple browser. Even the scrolling feels laggy and I get sub 30 fps. Plus the GPU usage climbs to 99%. The max I could get it to is 21% on fullscreen while scrolling at the most speed I can. No way that my iGPU is that weak to handle scaling. It's on Intel 10th gen. The natively supported FSR 2 in Genshin was fine then why can't FSR 1 work properly?

**Comment by Blinue** [comment]
Magpie is not optimized for low-end devices, as this is a trade-off for low latency and high availability. I’m sorry that Magpie didn't meet your expectations, it is not a magic solution to improve game performance, and this is not even one of its goals. I hope Magpie is helpful, and if not, no one loses anything - it's open source and free, and everyone can contribute. You can also try the paid software [Lossless Scaling](https://store.steampowered.com/app/993090/Lossless_Scaling/) on Steam, some people find it performs better. Thank you for your feedback!

**Comment by Gamcoaster** [comment]
I get that it doesn't improve the fps why does it drop them like crazy, even on a literal browser. Is that also an optimization problem?

**Comment by AbhiMayadam** [comment]
> I get that it doesn't improve the fps why does it drop them like crazy, even on a literal browser. Is that also an optimization problem?

Magpie is quite literally screen recording, then upscaling the screen recording, then displaying it. That is a lot of extra overhead to do. 

Older intel igpus suck at doing the type of upscaling that magpie etc does.

Since genshin is doing it within the game itself, you don't get the screen recording overhead and it works fine for you.

This is a gross oversimplification but its the best way I can describe it. 

Also on my old laptop when doing some upscaling of some images, doing it via CPU and iGPU took exactly the same time. This was a i5-7200U.

**Comment by ro6axe** [comment]
just use lossless scaling its better for performance but a tiny bit worse image quality

**Comment by ro6axe** [comment]
and yes magpie needs rescources and if ur gpu doesnt have enough rescources u are bound to lose tons of fps

**Comment by ro6axe** [comment]
or downgrade magpie verisons see if that can fix the performance issues u have
