### ISSUE TITLE
Add Anime4K_Upscale_GAN series. please 

### ISSUE THREAD

**Issue by YingDoge** [Blinue/Magpie#800]
### Expected behavior 预期的功能

Much Better Grafic than the curretn CNN. Espically the Anime4K_Upscale_GAN_x4_UUL.glsl. 
Current Without it i had to do,  Retore + Upscale 2x + restore + upscale 2x. Which is not efficent 
With the Anime4K_Upscale_GAN_x4_UUL.glsl. it can be simply 
Anime4k Restore + Anime4K_Upscale_GAN_x4_UUL.glsl.      
I currently have a 8k samusmg tv, 4090 + 64gm ram.
If you think this is tooo bothering i would also offer an 50 dollar US bounty. (i have donated before)
Sorry for my bad english and i apoliges if i offend you in any way.
Have a great day. 

YingDoge

PS which would be better [mpv-upscale-2x_animejanai] or Anime4K_Upscale_GAN_x4_UUL.glsl.

**Comment by Blinue** [comment]
Hello, thank you for your suggestion (and donation)! The current architecture is not very suitable for running heavy shaders, I am working on improving it #643. Anime4K_Upscale_GAN_x4_UUL might be better imported as onnx format, I will consider porting it after #772 is implemented, please be patient.

The porting of Anime4K is tracked in #534.

This project is no longer accepting donations, but thank you for your kindness anyway.
