### ISSUE TITLE
Scaling window to a specific size (scaling factor),

### ISSUE THREAD

**Issue by CortexReaver** [Blinue/Magpie#809]
### Expected behavior 预期的功能

Right now I cannot find any prompt where I can specify how big I want the scaled image to be relative to original size - a 2 times bigger, or 3 times for example. Here's example of another program that I am using for RPG maker games, it's called Lossless Scaling:

![13-01-2024 064736](https://github.com/Blinue/Magpie/assets/34350690/93942040-6aa2-4633-b55e-13bb0e79fdb5)

Its "Scale factor" is set to "1,5" right now. It can be quickly changed depending on the game, because I don't want the scaled image to fill up the screen completely but just make it slightly bigger. And I am totally fine with black bars (black background rather) around the scaled image, no need to change this part.
Maybe you can do it through "effects" somehow, and there is also something called SSimDownscaler. But seems like it just changes the size of the window BEFORE or AFTER the scaling was done, not an actual scaling factor (or size) for the algorithm itself.

**Comment by hooke007** [comment]
seems dup https://github.com/Blinue/Magpie/issues/278

**Comment by hauuau** [comment]
If the effect algorithm supports arbitrary scaling (Bicubic, Lanczos, RAVU-Zoom, etc) then there are settings available where you could set scaling factor explicitly or set absolute size for the output of the effect:
![magpie_scaling](https://github.com/Blinue/Magpie/assets/52239673/695fa5e7-ca9c-4df3-9073-d7b63af09683)

Isn't it what you want?

**Comment by Joackk** [comment]
I have the same need, can he just zoom in instead of full screen?

**Comment by Blinue** [comment]
@CortexReaver You can change the scaling factor in the scaling configuration page, as @hauuau suggested.

@Joackk Your request is a different topic, please go to #135 to discuss.

**Comment by CortexReaver** [comment]
> If the effect algorithm supports arbitrary scaling (Bicubic, Lanczos, RAVU-Zoom, etc) 

Ok, Now I see it. So FSR does also supports scaling. But there seems no such option for Anime4k

![01-2024 124643](https://github.com/Blinue/Magpie/assets/34350690/37a66eb9-10c1-4ba5-9159-8557bc9ad666)

I mean, another another application does support scaling for this algorithm, but not in Magpie.

**Comment by hooke007** [comment]
That's the issue I mentioned.

**Comment by hooke007** [comment]
What @hauuau talking about is a workaround for it.
![PixPin_2024-01-14_18-08-05](https://github.com/Blinue/Magpie/assets/41094733/f657befc-6236-472f-9a38-5dde13fdcb54)

Anime4k_scale always does 2x, so you have to append another effect to downscale the output.
