### ISSUE TITLE
fps capped when i turn on

### ISSUE THREAD

**Issue by wefghjk** [Blinue/Magpie#81]
i have a 75hz monitor but when i use magpie all games are capped at 30fps even with no limit on the game settings

**Comment by Blinue** [comment]
Is it caused by performance issues? Is there a visible latency?

**Comment by wefghjk** [comment]
> 
> 
> Is it caused by performance issues? Is there a visible latency?

the latency is good but has this 30fps problem, i guess it is a performance problem, because i got 40/50 fps on the games that i tested but when i turn magpie on it caps to 30

**Comment by wefghjk** [comment]
I fixed the problem, I deleted ScaleModels.json and then tested it on the same games, now it no longer has a frame limit and it reached 60fps easily
