### ISSUE TITLE
Powershell command not working ? 

### ISSUE THREAD

**Issue by Thibaut-tech** [Blinue/Magpie#811]
### Magpie version 程序版本

v0.10.4

### Windows version 系统版本

 Win 10 22H2

### Reproduction steps 复现步骤

I use the powershell command [System.Windows.Forms.SendKeys]::SendWait('%L') to send Alt + L (my upscale shortcut) but it's not working. 
With an older version of magpie (v0.8.1) the powershell command work. 

### Log files 日志文件

**Comment by Blinue** [comment]
`"%L"` actually sends `Alt+Shift+L`. When L is uppercase, [VkKeyScan](https://github.com/dotnet/winforms/blob/90c1b35e975d513e7b0ca5c2a56d938ca5df9969/src/System.Windows.Forms/src/System/Windows/Forms/SendKeys/SendKeys.cs#L136) will parse it as `Shift+L`. You should use `"%l"` instead.

**Comment by Thibaut-tech** [comment]
Ok thanks it's work for me.
I just have one other question FSR 3 or frame generation are planned for magpie?

**Comment by Blinue** [comment]
#802
