### ISSUE TITLE
Upscale to Specific Resolution in Windowed Mode Instead of Full Screen

### ISSUE THREAD

**Issue by mariop64** [Blinue/Magpie#817]
### Expected behavior 预期的功能

Implement the option to upscale a window to a different, non-full screen resolution. Such as 640x480 to 1920x1080. For my purpose, full screen makes it difficult to multi-task. This would be a great addition, not sure if there is already a way to do this. Please let me know!

### Alternative behavior (optional) 近似的功能（可选）

Option to set desired resolution instead of fullscreen
1280x720
1920x1080
2560x1440
4K Windowed

**Comment by hooke007** [comment]
dup https://github.com/Blinue/Magpie/issues/135
