### ISSUE TITLE
Frame generation?

### ISSUE THREAD

**Issue by MMMXXXZZZ** [Blinue/Magpie#818]
### Expected behavior 预期的功能

Is frame generation not contemplated? Lossless Scaling has it and it looks really effective

**Comment by hooke007** [comment]
https://github.com/Blinue/Magpie/issues/815

**Comment by hooke007** [comment]
@Blinue 我建议置顶一个issue，这样防止issue不断出现重复问题。

**Comment by Blinue** [comment]
@hooke007 最多置顶三个 issue，我把触控撤下了。不过还是有两个问题，一是中文和英文的 issue 都有，搜索时会遗漏，导致会有重复的，二是软件里的反馈按钮会进入新建 issue 页面，是看不到置顶的。

我想可以把这个问题加入 FAQ，然后在新建 issue 的表单里加一个“我已阅读 FAQ”的选择框。

重复的 issue 你直接关闭即可，Collaborator 有这个权限。
