### ISSUE TITLE
WinRT捕获无法使用，只能使用GUI

### ISSUE THREAD

**Issue by assacat** [Blinue/Magpie#82]
如上所述，使用WinRT会弹窗警告。
还有希望下个版本是直接编译好的，我这里第一步克隆资源库卡住了，无数次克隆失败，不得已找了一份已经编译好了的。

**Comment by Blinue** [comment]
是什么样的错误，能给张截图吗？另外Release都是已经编译的，下载zip文件。

**Comment by assacat** [comment]
![image](https://user-images.githubusercontent.com/89467353/130638130-9cdf2431-487b-415f-8176-385315afa6b4.png)
像这样的

**Comment by Blinue** [comment]
WinRT只在v1903或更新版本上可用。另外在每个窗口上都有这个错误吗？有些窗口是无法用WinRT捕获的

**Comment by assacat** [comment]
测试下来好像是刚好我开的那个galgame不行，其他游戏似乎是都没问题的了（时间不够，没办法一个一个全部排查了）
谢谢解答。
