### ISSUE TITLE
一个可能算不上bug的小小的异步问题

### ISSUE THREAD

**Issue by HIllya51** [Blinue/Magpie#826]
### Magpie version 程序版本

0.10.5

### Windows version 系统版本

win10

### Reproduction steps 复现步骤

MagRuntime初始化后不能立即Run(hwnd,opion)，否则Stop不能正确结束。
检查后发现Run把_hwndSrc设为hwnd总会赶在_MagWindThreadProc的while (true)之前，然后后面都会把_hwndSrc重新清零，然后导致IsRunning为false，从而无法真Stop。
这个小问题对您来说可能没有任何影响，因为实际上人工操作不可能触发这个问题。。。
不过还是希望您能优化一下，不然我在写[CLI](https://github.com/HIllya51/Magpie/blob/dev/src/Magpie.Core/CLI.cpp#191)版本的时候就必须在初始化之后Sleep一下，或者直接调MagApp::Get().Stop()。。。
感谢。

### Log files 日志文件

空文件
[magpie.log](https://github.com/Blinue/Magpie/files/14143353/magpie.log)

**Comment by Blinue** [comment]
写这个类时没考虑过初始化后立刻缩放的情况，要实现命令行 #686 的话这是应该支持的。这个 bug 涉及到复杂的线程同步，我计划在 1.0 里修复。

**Comment by HIllya51** [comment]
好的👌

**Comment by Blinue** [comment]
这个 issue 是追踪用的，我建议在修复之后再关闭

**Comment by Blinue** [comment]
已修复🎉
另外原定的 1.0 改为 0.11 了，很快会发布测试版。
