### ISSUE TITLE
How can I solve an inaccurate touch screen in a scaled window on a Steam Deck running Windows?

### ISSUE THREAD

**Issue by mendegen** [Blinue/Magpie#828]
### Question 问题

Hi,

I've installed some Popcap games, which won't natively fullscreen on the Deck running Windows for, I believe, driver reasons. The touchscreen works great when these games are in a window, but where I press and what the games think I'm pressing is inaccurate: if it thinks I'm touching outside the window, it will unfocus the window. Just generally, there's little precision in what I'm doing.

I haven't filed this as a bug because, technically speaking, it's not anything Magpie is doing wrong. However, I am curious if anyone has run into this issue, and if workarounds exist.

Thanks!

**Comment by Blinue** [comment]
Please check [FAQ](https://github.com/Blinue/Magpie/wiki/FAQ%20(EN)#does-magpie-support-touch-input). I plan to add touch support in v1.0.

**Comment by Blinue** [comment]
> One thing to note with touch support in mind is that the on-screen touch keyboard in Windows doesn't render properly in a scaled window. It appears for a moment, then disappears.

Thank you for the feedback. As discussed in https://github.com/Blinue/Magpie/issues/218#issuecomment-1533993491, the fix in v1.0 will not have this issue.
