### ISSUE TITLE
希望增加一个切换无边框窗口的功能

### ISSUE THREAD

**Issue by BlankMya** [Blinue/Magpie#831]
### Expected behavior 预期的功能

windows11下很多窗口是圆角的，部分窗口缩放后会把圆角也缩放进去。
能否在程序内置一个将其他窗口变为无边框窗口的功能。这个功能可以现在的缩放功能很好配合，不需要再另外寻找软件去修改圆角或者强制无边框。
感谢！

**Comment by Blinue** [comment]
Win11 中缩放的时候会自动禁用圆角，不起作用可能有两个原因：
1. 要缩放的窗口权限比 Magpie 更高，你可以以管理员身份启动 Magpie。
2. 圆角是窗口自己实现的，不是系统默认圆角，这没有通用的解决方案。

**Comment by BlankMya** [comment]
非常感谢，管理员启动很多之前圆角的都好了
