### ISSUE TITLE
屏幕边缘卷动

### ISSUE THREAD

**Issue by zivilyyyn** [Blinue/Magpie#836]
### Expected behavior 预期的功能

玩老版博德之门三部曲的时候，鼠标移动到屏幕边缘是可以卷动地图的。但是全屏之后鼠标好像就跑到窗口外面去了，无法在边缘卷动，有没有办法把鼠标锁定在当前窗口的范围内？

**Comment by Blinue** [comment]
缩放时鼠标会被限制的窗口内，除非是多屏幕。试试打开3D游戏模式
