### ISSUE TITLE
Window mode and MSI AfterBurner and HWINFO shows FPS, GPU etc TWICE.

### ISSUE THREAD

**Issue by SW1TCH0NY0U** [Blinue/Magpie#837]
### Magpie version 程序版本

0.10.5

### Windows version 系统版本

Win10 22H2

### Related screenshot (optional) 相关截图（可选）

![magpie](https://github.com/Blinue/Magpie/assets/159654070/e7136404-d481-471d-b734-0fe7ece07ef6)

### Reproduction steps 复现步骤

Only does it when it's in window mode.

### Log files 日志文件

.

**Comment by kato-megumi** [comment]
dup #197 
https://github.com/Blinue/Magpie/wiki/FAQ%20(EN)#duplicate-monitoring
Read FAQ before asking.

**Comment by SW1TCH0NY0U** [comment]
> dup #197 https://github.com/Blinue/Magpie/wiki/FAQ%20(EN)#duplicate-monitoring Read FAQ before asking.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/340660525/5232eb8b-a9c7-4113-9b9c-eccbc30256bf"><img alt="" height="14" src="https://camo.githubusercontent.com/95e35b1ddbd18e9680ef4876f3544fdf46e2116b5fefc3f6a48e1e427ea75b59/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[FAQ (EN)](https://github.com/Blinue/Magpie/wiki/FAQ-(EN))**An all-purpose window upscaler for Windows 10/11. Contribute to Blinue/Magpie development by creating an account on GitHub.

Idk what DED is though so how can I blacklist something that I don't know what it is???

**Comment by SW1TCH0NY0U** [comment]
> dup #197 https://github.com/Blinue/Magpie/wiki/FAQ%20(EN)#duplicate-monitoring Read FAQ before asking.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/340660525/5232eb8b-a9c7-4113-9b9c-eccbc30256bf"><img alt="" height="14" src="https://camo.githubusercontent.com/95e35b1ddbd18e9680ef4876f3544fdf46e2116b5fefc3f6a48e1e427ea75b59/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[FAQ (EN)](https://github.com/Blinue/Magpie/wiki/FAQ-(EN))**An all-purpose window upscaler for Windows 10/11. Contribute to Blinue/Magpie development by creating an account on GitHub.

Tried adding magpie to the RTSS blacklist but it still doubles up.....................
