### ISSUE TITLE
Magpie Not Applying Resizing

### ISSUE THREAD

**Issue by JUNINDAGOIABA** [Blinue/Magpie#838]
### Magpie version 程序版本

v0.10.5

### Windows version 系统版本

win10

### Reproduction steps 复现步骤

The error occurs when activating Magpie

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/14471422/magpie.log)

**Comment by Blinue** [comment]
To use Magpie, you need a graphics card that supports DirectX feature level 11. If no suitable graphics card is detected, Magpie should switch to CPU rendering, but there is a bug that prevents this from happening. I will fix this bug as soon as possible. However, CPU rendering is usually very slow, so I recommend using a modern graphics card for a better experience.
