### ISSUE TITLE
About bilinear cursor upscaling in recent versions

### ISSUE THREAD

**Issue by BG-Mania** [Blinue/Magpie#853]
### Magpie version 程序版本

0.10.6

### Windows version 系统版本

Windows 10 Pro 64bit v2009(20H2)

### Related screenshot (optional) 相关截图（可选）

![Magpie v0 8 0 Cursor Bilinear](https://github.com/Blinue/Magpie/assets/110537643/9ab36fae-c6f3-4e26-8720-169978897931)
![Magpie v0 10 6 Cursor Bilinear](https://github.com/Blinue/Magpie/assets/110537643/01632297-f23f-46ed-9f72-93d2b3fd427f)

### Reproduction steps 复现步骤

v0.8.0 > [Cursor] > [Zoom Factor of the Cursor] 'Same as Source Window' & [Interpolation Mode] 'Bilinear'

v0.10.6 > [Cursor] > [Draw Cursor] 'On' > [Scaling factor] 'Same as source window' & [Interpolation algorithm] 'Bilinear'

Hello,
First of all, Thank you so much for developing such a brilliant application!
I play mostly classic games in 800x600 resolution upscaled.
In version 0.8.0, the mouse cursor was upscaled nicely with the "Interpolation Mode" - "Bilinear" method, but in recent versions since 0.10.0, it doesn't upscale nicely with the same options.
This is not a issue for games that have specialized cursors within the game itself, but it is for games that use Windows-style cursors (e.g. RollerCoaster Tycoon 1, The Sims 1, etc.).
I've tried opening the source code files one by one, but I don't have any programming knowledge, so I have no idea what to do.

How can I get the cursor to upscale cleanly in the latest version like it did in the past in 0.8.0?

### Log files 日志文件

[Magpie_v0.8.0.log](https://github.com/Blinue/Magpie/files/14627746/Magpie_v0.8.0.log)
[Runtime_v0.8.0.log](https://github.com/Blinue/Magpie/files/14627747/Runtime_v0.8.0.log)
[magpie_v0.10.6-x64.log](https://github.com/Blinue/Magpie/files/14627750/magpie_v0.10.6-x64.log)

**Comment by Blinue** [comment]
Thank you for the feedback! The cursors in these games are what’s known as “[monochrome cursors](https://learn.microsoft.com/en-us/windows-hardware/drivers/display/drawing-monochrome-pointers)”. According to the documentation, they only have four states, so bilinear interpolation doesn’t make sense for them. If you’re interested, here is the code for drawing them.

https://github.com/Blinue/Magpie/blob/b536d957a73b91bdb4ef02d2a45a1bd69a3e5ec9/src/Magpie.Core/EffectCompiler.cpp#L1240-L1250

 The new version is actually more “correct,” but the outcome doesn’t align with user expectations: the cursor seems don’t adhere to the “bilinear interpolation” option, so I consider this a bug rather than a feature, and I plan to fix it in the next release.

**Comment by BG-Mania** [comment]
I'm appreciate you taking this into consideration. :)

**Comment by Blinue** [comment]
Does this build fix the issue?

https://github.com/Blinue/Magpie/actions/runs/8342762488/artifacts/1338693167

**Comment by BG-Mania** [comment]
![Same as Source Window   Bilinear](https://github.com/Blinue/Magpie/assets/110537643/73c05d2d-7be4-4d17-a100-b75d7d76807c)

I'm so sorry. It's obviously much better than before, but I still feel like 0.8.0 is better. 😅
It's fine when upscaling 640x480 and 1024x768, but 800x600 is the exception.

**Comment by Blinue** [comment]
I’ve resolved the issue within the development branch, and this particular fix will not be backported to v0.10. Should you wish to test it immediately, the development build is available for download [here](https://github.com/Blinue/Magpie/actions/runs/8401675890/artifacts/1352401477). To prevent any overwriting of the global configuration files, it’s advisable to turn on portable mode.

**Comment by BG-Mania** [comment]
![thank you magpie](https://github.com/Blinue/Magpie/assets/110537643/040e98a9-179b-4263-b94c-5a7b63267ed9)

PERFECT! Thank you for your efforts. You're a Hero of old-school gamers. 😃

**Comment by Blinue** [comment]
Thank you for your feedback and testing. Have a blast playing!
