### ISSUE TITLE
onnx版本部分软件窗口缩放为黑屏

### ISSUE THREAD

**Issue by HIllya51** [Blinue/Magpie#854]
### Magpie version 程序版本

onnx

### Windows version 系统版本

win11 22h2 amd r6-6600h 

### Reproduction steps 复现步骤

测试缩放explorer和一些游戏（例如真愛の百合は赤く染まる）会黑屏，
记事本/windowsterminal/计算器/微信等都不会黑屏，正常缩放

### Log files 日志文件

[logs.zip](https://github.com/Blinue/Magpie/files/14635351/logs.zip)

**Comment by Blinue** [comment]
试试删除 model.json，如果可以正常缩放说明是 onnx 错误。

**Comment by HIllya51** [comment]
删除model.json后正常缩放了
