### ISSUE TITLE
Which Caputre mode is best for grafic 

### ISSUE THREAD

**Issue by YingDoge** [Blinue/Magpie#858]
### Question 问题

Sorry about my english so just wondering will GDI provide the best grafic if performcne is not an issue. that i have an 4090 so performacne is not an issue. 
![image](https://github.com/Blinue/Magpie/assets/135021273/918ff824-9913-4306-ade5-8ead699ade75)

**Comment by Blinue** [comment]
Graphics Capture offers the best compatibility and should be used whenever possible. For windows that do not support high DPI scaling, you can set ‘High DPI scaling override’ to prevent OS from performing bicubic interpolation, as detailed in the [README](https://github.com/Blinue/Magpie?tab=readme-ov-file#hints).
