### ISSUE TITLE
 low FPS AND low usage of GPU(AMD 6650XT)

### ISSUE THREAD

**Issue by AdachiAndShimamura** [Blinue/Magpie#859]
### Program(Game) 游戏名

樱色之云＊绯色之恋

### Capture method 捕获模式

Graphics Capture

### Related screenshot (optional) 相关截图（可选）

![655889700f3e8e8ec52b3e67287c9fe](https://github.com/Blinue/Magpie/assets/95117705/92199984-30fd-45d5-9383-0ac75c4b8b5d)
![079678acbc3560331bd0e0b5885adea](https://github.com/Blinue/Magpie/assets/95117705/d9778890-c99f-49d6-b463-db5a3361636c)

### Other information (optional) 补充信息（可选）

![image](https://github.com/Blinue/Magpie/assets/95117705/e7034975-fa1c-4eaa-b49b-340ff57cb111)
![image](https://github.com/Blinue/Magpie/assets/95117705/3b11aec1-aa4f-40fc-8893-dcfb2baa787e)

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/14735019/magpie.log)

**Comment by Blinue** [comment]
看起来你用的是 ONNX 版本，由于会在第一个效果之前应用 ONNX，所以帧率很低。由于游戏内叠加层还没有适配，所以应用 ONNX 的时间会被合并到第一个效果的第一个通道。

GPU 之所以没有跑满，是因为 Magpie 追求的是低延迟而不是高吞吐量，CPU 和 GPU 有很大程度的串行。

**Comment by AdachiAndShimamura** [comment]
好的，感谢回答
