### ISSUE TITLE
无法加载DLL"Runtime":找不到指定的模块。

### ISSUE THREAD

**Issue by Splerfiea** [Blinue/Magpie#86]
异常来自HRESULT:0x8007007E
使用设备为AMD 2500U核显笔记本 系统为win10 1909 18363.418

**Comment by Splerfiea** [comment]
> 说明没有找到Runtime.dll，这个文件应该和Magpie.exe在同一个目录下

我确定给予了magpie管理员权限且在软件根目录下运行了magpie.exe >_>

**Comment by Blinue** [comment]
如果有Runtime.dll但没法加载，就是.net framework的问题，建议重装一下4.7版本。
