### ISSUE TITLE
为每个游戏的配置文件追加一个缩放延迟时间

### ISSUE THREAD

**Issue by Kanadeforever** [Blinue/Magpie#863]
### Expected behavior 预期的功能

即，在已有配置文件的程序启动后，不立刻进行缩放，而是等待预设的延迟时间后再缩放

因部分游戏如果在启动后缩放会导致程序崩溃或是缩放出现问题（如SchoolDaysHQ、ShinyDays、部分RPGMAKER游戏和一部分老3d游戏），又或者写一个bat脚本以供steam上的游戏使用时（通常需要先启动magpie），需要延迟一段时间再缩放

### Alternative behavior (optional) 近似的功能（可选）

[Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming)中，的“延迟无边框化窗口”

<img width="461" alt="屏幕截图 2024-03-28 085128" src="https://github.com/Blinue/Magpie/assets/20147029/74e1364a-6a65-41a0-b932-3db735882954">
效果为程序启动之后一段时间后才处理窗口。

但BG无法自定义延迟秒数，可以的话希望可以自定义延迟秒数

**Comment by Blinue** [comment]
游戏崩溃是不是“模拟独占全屏”选项导致的？

**Comment by Kanadeforever** [comment]
sd确实是这个问题，解决了，谢谢

**Comment by Blinue** [comment]
模拟独占全屏已经尝试延迟激活
https://github.com/Blinue/Magpie/blob/b536d957a73b91bdb4ef02d2a45a1bd69a3e5ec9/src/Magpie.Core/MagApp.cpp#L175-L188
但处理不了初始化很慢或中途尝试创建 D3D9 设备。我计划给这个选项加一个提醒。
