### ISSUE TITLE
Upscaling particular window at chosen scale.

### ISSUE THREAD

**Issue by depeschzeu** [Blinue/Magpie#870]
### Expected behavior 预期的功能

Is it possible to add a feature to upscale entire window of a programm and choose needed scale like 125%/150% etc, literally resizing it without touching other windows?
I am using some old programms with pixel graphics GUI which appears too small on modern monitor and thus hard to read and see what happens on it.

**Comment by Blinue** [comment]
Do you mean [windowed mode](https://github.com/Blinue/Magpie/issues/135)?

**Comment by depeschzeu** [comment]
Yes you are correct.
I am sorry I didn't notice that this thread already exists.
I have used translator and as far as I can see this function is currently impossible to implement.
It is very sad, because it is like people say a 'must have' function. Specially when using some obsolete applications with drawn interface, which uses bitmap sprites as GUI elements. Technical progress doesn't stop and those programms that looked good on CRT and old tech LCD displays now are very hard to operate. GUI appears very small and everything on it displays tiny because of high resolution of modern displays.

**Comment by Blinue** [comment]
You may need integer scaling, which can be achieved through the **Nearest** effect. Implementing windowed mode isn't impossible; in fact, it's on the roadmap, but there are more pressing tasks at hand right now. Please be patient.
