### ISSUE TITLE
Scaling over monitor size

### ISSUE THREAD

**Issue by banjorae** [Blinue/Magpie#875]
### Magpie version 程序版本

0.10.6

### Windows version 系统版本

W10 22H2 

### Related screenshot (optional) 相关截图（可选）

So, basically, for anything that isn't 800x600 when I do the upscaling it goes so big it only shows a part of it on my screen
![ss](https://github.com/Blinue/Magpie/assets/122685071/e0e580be-3f02-4794-9171-1882d458c73a)

### Reproduction steps 复现步骤

Just scale up anything that isn't 800x600 either windowed or fullscreen, I'm using anime 4k

### Log files 日志文件

No logs

**Comment by Blinue** [comment]
Try setting the "Default downscaling effect" option to Bicubic.

**Comment by aserrallerios** [comment]
@Blinue has been the "Default downscaling effect" option been removed in v0.11.0? Does it mean that it's handled automatically by the program?

In my case I wanted to use None as "Default downscaling effect", this was a handy alternative to custom cropping.

**Comment by aserrallerios** [comment]
Thanks for your answer!

May I humbly suggest the inclusion of a toggle to disable downscaling and just show the center of the window?

-[x] Enable downscaling to fit window

My use case is quite simple, sometimes you just care about the center of the window. and you don't care about the rest. This is very common with emulation, where the program window usually show bezels around the actual game. To get the sharpest image possible on those cases I think we need to disable the downscaling.
