### ISSUE TITLE
全屏下开启Magpie后显示不全

### ISSUE THREAD

**Issue by Hacinsl** [Blinue/Magpie#876]
### Magpie version 程序版本

v0.11.0-preview1

### Windows version 系统版本

win11 23H2

### Related screenshot (optional) 相关截图（可选）

![屏幕截图(152)](https://github.com/Blinue/Magpie/assets/63764883/cab64313-a655-4e01-86f0-0bd5e0c8ee64)
![屏幕截图(153)](https://github.com/Blinue/Magpie/assets/63764883/f03aa7bd-c247-4e03-abb3-d053974222b1)
如图，开启后画面上下出现黑边，原画面下部被裁剪。
是最近的预览版本的特有bug，回退v0.10.6后正常。

### Reproduction steps 复现步骤

捕获方式：Graphics Capture
算法：Anime4K Restore
实测捕获方式和算法对上述问题无影响。
bilibili pc客户端全屏后使用快捷键启用Magpie出现bug，换用其他程序（如Firefox）全屏后问题仍然存在。

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/14871667/magpie.log)

**Comment by Blinue** [comment]
谢谢反馈。我已经复现了这个 bug，肯定是 #864 引入的。打开“捕获标题栏”可以临时修复这个错误，具体原因还在调查。

**Comment by Hacinsl** [comment]
感谢，但我打开捕获标题栏并未修复该问题（测试了B站PC客户端，Firefox，edge，mpv.net全屏均出现此问题）。
另外我还注意到，PotPlayer全屏无论是否开启捕获标题栏都不会出现画面异常。

**Comment by Blinue** [comment]
试试这个版本
https://github.com/Blinue/Magpie/actions/runs/8556134985/artifacts/1385054230

**Comment by Hacinsl** [comment]
> 试试这个版本 https://github.com/Blinue/Magpie/actions/runs/8556134985/artifacts/1385054230

这个版本没有问题了，辛苦了。
