### ISSUE TITLE
Regarding competition with other software.

### ISSUE THREAD

**Issue by tomo25neko** [Blinue/Magpie#881]
### Question 问题

Since it's a translation, it might not be accurate.
Since starting to use Magpie, GeForce Experience and app overlays have stopped functioning properly. They work when I restart and open them, but when I start using Magpie, the overlay's behavior becomes unstable.
Are other people experiencing this issue as well?

**Comment by Blinue** [comment]
You may need to blacklist Magpie in GeForce Experience, otherwise, it might detect Magpie instead of the game itself.
