### ISSUE TITLE
检测重复帧时增加一个mask，排除UI动画

### ISSUE THREAD

**Issue by mrl998** [Blinue/Magpie#883]
### Expected behavior 预期的功能

![image](https://github.com/Blinue/Magpie/assets/18524100/e71f966d-2666-443d-9472-e51351608d94)
GAL的UI里经常有个循环播放的小动画，导致即使画面整体没有变化，magpie依然会重复渲染画面
希望能引入一个mask（自动检测或用户手动框选），在检测重复帧时排除这个区域

**Comment by Blinue** [comment]
这个功能和 #610 相似，不过用途更窄。想降低功耗的话建议使用轻量的效果或限制帧率。

**Comment by mrl998** [comment]
> 这个功能和 #610 相似，不过用途更窄。想降低功耗的话建议使用轻量的效果或限制帧率。

感谢回复！
排除了UI动画之后，在无立绘演出的大多数时间里只需要每隔两三秒（读完一句话）渲染一帧

**Comment by Blinue** [comment]
考虑之后，我认为这个功能不值得实现。自动检测是不现实的，只能由用户框选，这需要定制 UI，也增加了操作的复杂性。我希望 Magpie 保持简单和通用，而这个功能是特定场景的深度定制，目的仅仅是降低功耗，和实现它的代价相比不值得。

虽然如此，还是谢谢你的建议！
