### ISSUE TITLE
About FSR

### ISSUE THREAD

**Issue by tomo25neko** [Blinue/Magpie#884]
### Question 问题

I'm sorry if the meaning was unclear.
In the response to previous inquiries, it was mentioned that implementing FSR2 into Magpie would be difficult. However, would it also be impossible to incorporate new algorithms such as EASU or RCAS, which are believed to be improved along with FSR updates? If feasible, wouldn't it be possible to create code with less overhead than the existing one?

**Comment by Blinue** [comment]
![image](https://github.com/Blinue/Magpie/assets/34770031/7c2071c2-d4bb-4993-beb6-97865f59354e)
FSR consists of two passes: EASU and RCAS, both of which are already integrated into Magpie.
