### ISSUE TITLE
为 Magpie 增加 缩放模式编辑重置 功能   Added the Zoom Mode Edit Reset feature for Magpie

### ISSUE THREAD

**Issue by RimacC2-EV** [Blinue/Magpie#886]
### Expected behavior 预期的功能

这个功能可以重置被编辑过的缩放模式，以便在误删除一种/多种 Magpie 自带的缩放模式之后撤销
![image](https://github.com/Blinue/Magpie/assets/125170682/7a715226-2c47-44f0-8633-d5aa2cea975b)

**Comment by RimacC2-EV** [comment]
![image](https://github.com/Blinue/Magpie/assets/125170682/a77bc5cf-4758-4ed0-b0cc-520783ea4c59)

**Comment by Blinue** [comment]
自带的几个缩放模式只是演示，你应该针对使用场景定制缩放模式。确实想还原的话可以删除 %LocalAppData%\Magpie\config\v2\config.json（如果没有打开便携模式），这会将软件重置为默认配置。

**Comment by RimacC2-EV** [comment]
谢谢，但我仍然有一个建议：可以尝试为每种缩放模式添加描述说明，方便初学者学习。（若您觉得短期时间内不会实现，请告知我，我会关闭这个issue，因为它已被解决。）

**Comment by Blinue** [comment]
不是为缩放模式，而是应该为每个效果添加说明，因为缩放模式是用户定义的。我计划未来实现这个功能，但它有点麻烦，因为要支持多语言。

你可以新建一个 issue，这个 issue 的问题已经解决。

**Comment by RimacC2-EV** [comment]
OK，感谢您的支持！
