### ISSUE TITLE
自动隐藏鼠标指针

### ISSUE THREAD

**Issue by Ptilopsis01** [Blinue/Magpie#892]
### Expected behavior 预期的功能

如题，有些游戏虽然能自己隐藏鼠标指针，但在窗口模式下magpie放大时无法生效，也有一些游戏本身就不支持
希望magpie能支持在特定时长未移动光标后将其自动隐藏，再次移动时再重新渲染，非常感谢

**Comment by Blinue** [comment]
Duplicate of #794 

Magpie 的理念是保持游戏原有风格，如果游戏没有隐藏光标，我们也不应该隐藏。

> 但在窗口模式下magpie放大时无法生效

这是兼容性问题，你能举个例子吗？

**Comment by Ptilopsis01** [comment]
> 这是兼容性问题，你能举个例子吗？

这个得分情况，有的游戏窗口化下就不会隐藏而全屏会隐藏，有的则是普通游玩时会隐藏但用magpie放大则无法隐藏

前者我一下想不起来，后者似乎紫社的作品都是这种

**Comment by Blinue** [comment]
自动隐藏光标超出了 Magpie 的职能。针对后一个问题你可以再提一个 issue。
