### ISSUE TITLE
How to add effects to 0.9.1???????????????

### ISSUE THREAD

**Issue by SW1TCH0NY0U** [Blinue/Magpie#896]
### Question 问题

How do I add effects into 0.9.1? I tried with the following code:

[
  {
    "name": "Lanczos",
    "effects": [
      {
        "effect": "Lanczos",
        "scale": [ -1, -1 ]
      }
    ]
  },
  {
    "name": "FSR",
    "effects": [
      {
        "effect": "FSR_EASU",
        "scale": [ -1, -1 ]
      },
      {
        "effect": "FSR_RCAS",
        "sharpness": 0.87,
        "effect": "Anime4K_Denoise_Bilateral_Mode",
        "effect": "SMAA_Low",
      },
    ]
  },
  {
    "name": "FSRCNNX",
    "effects": [
      {
        "effect": "FSRCNNX"
      },
      {
        "effect": "Bicubic",
        "scale": [ -1, -1 ],
        "paramB": 0,
        "paramC": 0.5
      }
    ]
  },
  {
    "name": "ACNet",
    "effects": [
      {
        "effect": "ACNet"
      },
      {
        "effect": "Bicubic",
        "scale": [ -1, -1 ],
        "paramB": 0,
        "paramC": 0.5
      }
    ]
  },
  {
    "name": "Anime4K",
    "effects": [
      {
        "effect": "Anime4K_Upscale_Denoise_L"
      },
      {
        "effect": "Bicubic",
        "scale": [ -1, -1 ],
        "paramB": 0,
        "paramC": 0.5
      }
    ]
  },
  {
    "name": "CRT-Geom",
    "effects": [
      {
        "effect": "CRT_Geom",
        "scale": [ -1, -1 ],
        "curvature": 0,
        "cornerSize": 0.001,
        "CRTGamma": 1.5,
        "monitorGamma": 2.2,
        "interlace": false
      }
    ]
  },
  {
    "name": "Integer Scale 2x",
    "effects": [
      {
        "effect": "Nearest",
        "scale": [ 2, 2 ]
      }
    ]
  },
  {
    "name": "Integer Scale 3x",
    "effects": [
      {
        "effect": "Nearest",
        "scale": [ 3, 3 ]
      }
    ]
  }
]

But when I open the config, it just shows fsr/fsrcas. Am I missing something?

**Comment by SW1TCH0NY0U** [comment]
It doesn't show in the game overlay............

**Comment by Blinue** [comment]
Try this
```json
{
    "name": "FSR",
    "effects": [
        {
            "effect": "FSR_EASU",
            "scale": [
                -1,
                -1
            ]
        },
        {
            "effect": "FSR_RCAS",
            "sharpness": 0.87
        },
        {
            "effect": "Anime4K_Denoise_Bilateral_Mode"
        }
    ]
}
```

There are plenty of configuration examples available [here](https://gist.github.com/hooke007/818ecc88f18e229bca743b7ae48947ad).

**Comment by SW1TCH0NY0U** [comment]
Any chance you can add sma low too? I've been trying for hours.

**Comment by Blinue** [comment]
```json
{
  "name": "FSR",
  "effects": [
    {
      "effect": "FSR_EASU",
      "scale": [-1, -1]
    },
    {
      "effect": "FSR_RCAS",
      "sharpness": 0.87
    },
    {
      "effect": "Anime4K_Denoise_Bilateral_Mode"
    },
    {
      "effect": "SMAA_Low"
    }
  ]
}
```
I recommend upgrading to v0.10 so you can use the UI to edit the scaling mode.

**Comment by SW1TCH0NY0U** [comment]
Doesn't work mate. Says parse failure.

**Comment by SW1TCH0NY0U** [comment]
Thanks so much 😊☺️ working great. Really appreciate it!!!!
