### ISSUE TITLE
缩放后鼠标光标的分辨率变的很糟糕

### ISSUE THREAD

**Issue by yanyurua** [Blinue/Magpie#897]
### Question 问题

如标题所说，缩放后光标会被压缩成一个很小块很糊的光标，使用绘制光标放大后仍然是个不太好看的光标；

能否在缩放以后，让光标的图案不被压缩呢？
![被压缩后](https://github.com/Blinue/Magpie/assets/64131648/430473d9-4b46-4645-ad66-497731cef984)
![被压缩前](https://github.com/Blinue/Magpie/assets/64131648/5a7b5d81-6fd9-462a-ad8a-6f308a886b71)

**Comment by Blinue** [comment]
光标绘制有一些限制：https://github.com/Blinue/Magpie/discussions/254#discussioncomment-2213503

你有没有更改光标大小或有多屏幕？

**Comment by Blinue** [comment]
> 不过我在录取光标的时候发现一个现象，进行缩放以后，录制界面里有着最初的光标以及被压缩后的光标（也就是两个光标），但他们错位了。

这个问题在 #141 中追踪。
