### ISSUE TITLE
加入“最小帧率限制”功能

### ISSUE THREAD

**Issue by sunlghr** [Blinue/Magpie#899]
### Expected behavior 预期的功能

现在的0.11pre版本已经可以限制最大帧率，但在我的体验中，重复帧检测活动的太过积极了，导致无论什么样的动效，画面切换都只有25帧左右，肉眼可见明显比放大之前卡的多，在视觉小说游玩中，文字的渐显动效卡顿最为明显
故建议加入最小帧率限制，无论是否有重复帧，采样帧率都在此帧率之上，既保证了静止状态下的低功耗，又保证了基本的流畅需求
谢谢！

**Comment by BLACKCHARGE** [comment]
开发者选项里面可以关掉检测，而且gal哪怕只有个位数帧率我没觉得有什么明显卡顿

**Comment by Blinue** [comment]
卡顿可能是 GPU 频率降低导致的。当画面长时间静止，GPU 会自动降低频率来减小功耗，画面变化后就需要更长的时间处理。如果画面一直变化反而不会卡顿。

能否提供显卡型号和使用的缩放模式？

**Comment by sunpenghao** [comment]
同样希望加入这个功能。

> 当画面长时间静止，GPU 会自动降低频率来减小功耗，画面变化后就需要更长的时间处理。

在VN里这种情况挺多的，现在是把GPU电源策略设成了最高性能优先当作workaround，但后果就是功耗比引入重复帧检测前还要高。

> 能否提供显卡型号和使用的缩放模式？

我这里是4070 + RAVU_Zoom_R3。
