### ISSUE TITLE
[feature request] 更多着色器移植？

### ISSUE THREAD

**Issue by hooke007** [Blinue/Magpie#9]
虽然写的是fr但只是建议。
似乎开发者在移植mpv可用的着色器，那我就发一下目前我收集的所有可用的着色器以供考量。
https://hooke007.github.io/mpv-lazy/[01]_%E7%AC%AC%E4%B8%89%E6%96%B9%E7%9D%80%E8%89%B2%E5%99%A8%E4%BB%8B%E7%BB%8D.html

另一个链接是理论指标的参考
https://artoriuz.github.io/blog/mpv_upscaling.html#results

**Comment by Blinue** [comment]
文章很有帮助，非常感谢
因为现在着色器比较多，我打算将它们分离为插件，也在考虑移植更多的着色器
如果你有中意的着色器也请提出来，我对这方面的了解有限

**Comment by hooke007** [comment]
个人来讲比较中意 ravu-zoom-r4.hook 和 ravu-lite-r4.hook 但是用在游戏上延迟不会很好看估计只能用低阶的r2

**Comment by Blinue** [comment]
目测比较棘手，我会在手头的工作完成之后着手移植

**Comment by Blinue** [comment]
ravu已移植完毕，除了zoom变体有个小bug让我头疼
我计划移植你的文章里的大部分着色器，可能要花费相当久的时间。在此之前请不要关闭这个issue

**Comment by hooke007** [comment]
感谢采纳此功能请求

**Comment by Blinue** [comment]
所有计划的移植工作都完成了
至今为止移植了：FSRCNNX，SSimDownscaler，SSimSuperRes，RAVU和CAS。其他的我认为没有移植的价值。
我将关闭这个issue
