### ISSUE TITLE
Latest commits: broken settings

### ISSUE THREAD

**Issue by CoderStone** [Blinue/Magpie#90]
Auto-Fullscreen on alt-tab,
Saving which module,
etc are currently broken, thought I should let you know.

**Comment by Blinue** [comment]
I've fixed the first one. What does "Saving which module" mean?

**Comment by CoderStone** [comment]
> I've fixed the first one. What does "Saving which module" mean?

Never mind, that works fine lol. Was a momentary glitch.
On some occasions, it fails to parse, any ideas why?

**Comment by Blinue** [comment]
Change the scaling configuration carefully. Any format error or illegal value will cause the parser to fail.

**Comment by CoderStone** [comment]
> Change the scaling configuration carefully. Any format error or illegal value will cause the parser to fail.

By the way, the fullscreen fix is still very spotty.
Tends to break on alt tab on occasion.

**Comment by CoderStone** [comment]
Happened again, fullscreen seems to be broken when alt tabbing for MC Dungeons, any ideas?

**Comment by Blinue** [comment]
Please post the log

**Comment by CoderStone** [comment]
[Magpie.log](https://github.com/Blinue/Magpie/files/7112281/Magpie.log)
[CursorHook.log](https://github.com/Blinue/Magpie/files/7112282/CursorHook.log)

**Comment by Blinue** [comment]
Thanks for the feedback. Sometimes it's very slow when exiting fullscreen, which will cause alt+tab to fail. I will try to fix it in the next version.

**Comment by Blinue** [comment]
This issue has been fixed in v0.7
