### ISSUE TITLE
在win11的虚拟机连接中左侧任务栏错误

### ISSUE THREAD

**Issue by BLACKCHARGE** [Blinue/Magpie#903]
### Magpie version 程序版本

0.10之后所有版本

### Windows version 系统版本

win11

### Related screenshot (optional) 相关截图（可选）

https://github.com/Blinue/Magpie/assets/57131319/e803136f-18cb-454c-95b2-a562c785f189
win11 23H2与Windows Server 2022 - 虚拟机连接
https://github.com/Blinue/Magpie/assets/57131319/2ce36a1d-2b89-4180-9f48-574f4599fe40
win11 23H2的Windows 沙盒 

### Reproduction steps 复现步骤

  在使用win11物理机系统时使用远程桌面(包括hyper-v虚拟机连接的增强会话模式与Windows 沙盒 )连接到其他Windows11虚拟机(也包括Windows Server 2022)系统时，被连接机器上的magpie左侧任务栏似乎回退到了与win11任务管理器相同的可收放状态
  使用win10连接到win11或者win11连接到win10时均无此问题，似乎只有win11连接到其它win11时才有此问题，我知道hyper-v虚拟机连接的增强模式的部分窗口是在访客机的本地渲染的，可能与这个有关系，使用hyper-v虚拟机连接的经典模式以及sunshine等方式串流可以发现窗口是在宿主机上渲染的，就没这个问题，至于win11物理机使用mstsc远程桌面串流到到别的win11物理机我这边测起来有点麻烦，改天再试情况
  这个是比较很罕见的情况，一般也没啥人这么用，姑且这么报告一下

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/15228397/magpie.log)

**Comment by Blinue** [comment]
我没理解问题所在，宽度不够时左侧导航栏会自动收起以节省空间，你可以试试调整窗口宽度

**Comment by BLACKCHARGE** [comment]
原来如此，是我误会了，之前以为左侧不能再收放了
