### ISSUE TITLE
与aida64悬浮窗抢占焦点（ 正式版0.10.6中无此问题）

### ISSUE THREAD

**Issue by yutouyes** [Blinue/Magpie#905]
### Magpie version 程序版本

0.11.0 preview1

### Windows version 系统版本

windows 11 23h2

### Related screenshot (optional) 相关截图（可选）

https://github.com/Blinue/Magpie/assets/17039457/30a1e426-e13b-4025-8772-19b34f11e4a0
https://github.com/Blinue/Magpie/assets/17039457/7c4b9d78-f605-4815-aa44-d2050ff55d97

### Reproduction steps 复现步骤

如视频所示，aida64 v7.20提供OSD悬浮窗功能，设置快捷键Alt+O/Alt+Shift+O切换悬浮窗显示与隐藏，在使用magpie 0.10.6放大窗口（以edge为例，其他窗口情况相同）到全屏后，aida64的悬浮窗能在全屏画面上正常显示/隐藏，但是在0.11.0 preview1中，输入快捷键呼出aida64悬浮窗时，magpie会判断焦点更换，已放大到全屏的edge窗口退出全屏状态。

### Log files 日志文件

[magpie.2.log](https://github.com/Blinue/Magpie/files/15256925/magpie.2.log)
[magpie.log](https://github.com/Blinue/Magpie/files/15256926/magpie.log)
[magpie.1.log](https://github.com/Blinue/Magpie/files/15256927/magpie.1.log)

**Comment by Blinue** [comment]
谢谢反馈。v0.10.6 不会退出缩放是一个拼写错误导致的，我已经修复了 https://github.com/Blinue/Magpie/commit/8e0fb380196b1051cf936d03d2309954f304c9cb

根据目前的规则，当前台窗口改变 Magpie 退出缩放是预期行为。OSD 一般不需要焦点，aida64 的实现方式导致它和 Magpie 不兼容。

我已经添加了一个机制来和其他程序合作 #895，这可以实现当其他窗口在前台时保持缩放，但 AIDA64 恐怕不会关心和 Magpie 的兼容性。

**Comment by yutouyes** [comment]
> 谢谢反馈。v0.10.6 不会退出缩放是一个拼写错误导致的，我已经修复了 [8e0fb38](https://github.com/Blinue/Magpie/commit/8e0fb380196b1051cf936d03d2309954f304c9cb)
> 
> 根据目前的规则，当前台窗口改变 Magpie 退出缩放是预期行为。OSD 一般不需要焦点，aida64 的实现方式导致它和 Magpie 不兼容。
> 
> 我已经添加了一个机制来和其他程序合作 #895，这可以实现当其他窗口在前台时保持缩放，但 AIDA64 恐怕不会关心和 Magpie 的兼容性。

所以实际上0.11的表现才是符合预期的，而0.10.6则是bug？
（啊这可真是）
