### ISSUE TITLE
多显示器支持。

### ISSUE THREAD

**Issue by zhisenyang** [Blinue/Magpie#91]
多显示器的情况下，只能扩展到主屏幕，而且仅显示一部分，大概全屏到3/2左右，具体晚点我截图一下。
大佬有没有打算支持多显示器呢。

**Comment by hooke007** [comment]
https://github.com/Blinue/Magpie/wiki/FAQ#%E6%98%AF%E5%90%A6%E6%94%AF%E6%8C%81%E5%A4%9A%E5%B1%8F

**Comment by stydxm** [comment]
你显示器是不是分辨率不一样，我也发现不是全屏，分辨率改成一样之后就正常了

**Comment by Blinue** [comment]
这是一个bug，全屏窗口的分辨率是源窗口所在屏幕的分辨率，但全屏窗口始终创建在主屏幕上。如果它们分辨率不同，全屏窗口就不能覆盖主屏幕。

现在将始终在源窗口所在屏幕上创建全屏窗口。
