### ISSUE TITLE
无法启动：critical|App.cpp:39|operator ()|未处理的异常 HRESULT: 0x802B000A

### ISSUE THREAD

**Issue by coddoge** [Blinue/Magpie#912]
### Magpie version 程序版本

v0.11.0-preview2

### Windows version 系统版本

Windows 10 企业版 LTSC 10.0.17763.5458

### Reproduction steps 复现步骤

从 https://github.com/Blinue/Magpie/releases/tag/v0.11.0-preview2
下载 https://github.com/Blinue/Magpie/releases/download/v0.11.0-preview2/Magpie-v0.11.0-preview2-x64.zip
解压 Magpie-v0.11.0-preview2-x64.zip 到文件夹 Magpie-v0.11.0-preview2-x64 并进入
双击 Magpie.exe
然后除了打log什么都没有发生

### Log files 日志文件

2024-05-14 23:06:48.644|info|main.cpp:77|wWinMain|程序启动
	版本: v0.11.0-preview2
	管理员: 是
2024-05-14 23:06:48.887|critical|App.cpp:39|operator ()|未处理的异常
	HRESULT: 0x802B000A
2024-05-14 23:07:56.646|info|main.cpp:77|wWinMain|程序启动
	版本: v0.11.0-preview2
	管理员: 是
2024-05-14 23:07:56.797|critical|App.cpp:39|operator ()|未处理的异常
	HRESULT: 0x802B000A

**Comment by Blinue** [comment]
请看[系统需求](https://github.com/Blinue/Magpie/blob/dev/README_ZH.md#%E7%B3%BB%E7%BB%9F%E9%9C%80%E6%B1%82)。Magpie 要求 Win10 v1903，版本号 18362。

**Comment by coddoge** [comment]
看来被抛弃了 😟

**Comment by Blinue** [comment]
主要原因是 Magpie 的 UI 框架 XAML Islands 是 v1903 引入的。缩放模块甚至可以在 Win7 上运行 https://github.com/HIllya51/Magpie9_win7

提高 OS 版本要求也有助于简化代码库，减少维护负担。微软的第一方软件如 PowerToys 和 Terminal 都将要求提高到 v2004。
