### ISSUE TITLE
使用magpie时无法正常使用moonlight串流

### ISSUE THREAD

**Issue by relifenoxiao** [Blinue/Magpie#914]
### Question 问题

# 使用magpie时无法正常使用moonlight串流

## 问题描述

**在使用magpie放大gal后（尝试过许多不同的和游戏,应该和是什么游戏无关），使用安卓手机上最新版的moonlight串流时会出现如下问题:**   

- 对于Desktop Duplication的捕获方式，一旦进行缩放，moonlight会串流失败，出现如下报错。
![db9b5ad8e46d3a954d694163583dc0f8](https://github.com/Blinue/Magpie/assets/116488736/45ba57f2-dac9-4d04-b77d-078f64626960)

- 使用其他捕获方式及串流成功后使用magpie放大则画面会卡住，不再发生变化，只能看到鼠标的移动和听到声音。
![9189b44145e573ad9b8b4ee7a09829b2](https://github.com/Blinue/Magpie/assets/116488736/5ce806cc-29c2-4a98-9aed-98bb43065766)
- 使用其他捕获方式先放大后串流会黑屏（手机端），只能听到声音和移动鼠标（电脑端的画面）

## 配置：

```
处理器	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
版本	Windows 11 家庭中文版
版本	23H2
安装日期	‎2023/‎6/‎20
操作系统版本	22631.3527
体验	Windows Feature Experience Pack 1000.22700.1003.0
```
---

## 其他相关信息

我在百度贴吧看到别人说用a卡的时候就没这个问题。

**Comment by Blinue** [comment]
Duplicate of #141 

Desktop Duplication 是不支持串流的，因为串流软件可能也使用这个 API 来捕获屏幕。
