### ISSUE TITLE
Shift + xx 的放大快捷键在 steam 启动的游戏中失效

### ISSUE THREAD

**Issue by BrokenMyth** [Blinue/Magpie#915]
### Magpie version 程序版本

0.10.6

### Windows version 系统版本

win11

### Reproduction steps 复现步骤

1. 在主页->快捷键->缩放快捷键中, 设置缩放快捷键为 shift+q
2. 启动 steam 相关的游戏并且保持窗口状态
3. 使用 shift+q 快捷键无法放大
4. 启动非 steam 相关的游戏并且保持窗口状态, 使用 shift+q 快捷键成功放大/缩小 √

无论是 shift+q 还是加其他的字母的快捷键(shift+e) , 在 steam 启动的游戏中放大都会失效，如果改为 ctrl+q 是可以成功放大。

### Log files 日志文件

[magpie.1.log](https://github.com/Blinue/Magpie/files/15345335/magpie.1.log)
[magpie.2.log](https://github.com/Blinue/Magpie/files/15345337/magpie.2.log)
[magpie.log](https://github.com/Blinue/Magpie/files/15345338/magpie.log)

**Comment by Blinue** [comment]
我尝试了一下复现不了这个错误，看来和驱动有关
