### ISSUE TITLE
Nvidia gpu stuck at low power mode

### ISSUE THREAD

**Issue by Panjaksli** [Blinue/Magpie#92]
When using magpie, my RTX 2060 gets stuck at low P level (1200MHz 700mv).  CPU usage is low. Freesync off.

**Comment by Panjaksli** [comment]
Okay, found the problem.
It was caused by using "scale on GPU" option instead of "scale on monitor".

**Comment by bakwas247** [comment]
Please close the issue if not actually a bug.
