### ISSUE TITLE
使用Anime4K放大植物大战僵尸杂交版四周会出现黑边

### ISSUE THREAD

**Issue by wyllwyc** [Blinue/Magpie#922]
### Magpie version 程序版本

0.11

### Windows version 系统版本

win11 23H2

### Related screenshot (optional) 相关截图（可选）

![屏幕截图 2024-05-22 081802](https://github.com/Blinue/Magpie/assets/118519866/8dc9b8ce-c22a-4bd4-b12e-ebdb23543f4f)

### Reproduction steps 复现步骤

![屏幕截图 2024-05-22 082016](https://github.com/Blinue/Magpie/assets/118519866/f3cb4726-c493-4dd6-9537-529bba167f76)
使用Anime4K放大植物大战僵尸杂交版，四周会出现相关截图所示黑边，使用0.5.2则无此问题

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/15396670/magpie.log)

**Comment by Blinue** [comment]
游戏的分辨率为 880x600，经过 Anime4K 放大一倍变为 1760x1200，仍不足以填满屏幕，这是四周有黑边的原因。你应在缩放模式的最后添加新的效果来放大到填充屏幕，比如再加一个 Anime4K 或者 Lanczos。
