### ISSUE TITLE
缩放后鼠标点击经常无效

### ISSUE THREAD

**Issue by Mao0509** [Blinue/Magpie#927]
### Magpie version 程序版本

Magpie-v0.11.0-x64

### Windows version 系统版本

Windows 11 22631.3593

### Related screenshot (optional) 相关截图（可选）

[Root Double -Before Crime _ After Days- Xe Ver.1.00 2024-05-26 15-14-54.zip](https://github.com/Blinue/Magpie/files/15446534/Root.Double.-Before.Crime._.After.Days-.Xe.Ver.1.00.2024-05-26.15-14-54.zip)

视频中9秒点击Help 多次点击后成功

### Reproduction steps 复现步骤

Root Double -Before Crime After Days- Xtend Edition 
缩放后鼠标点击失灵 多次点击才成功 但是鼠标是可以正常移动的

### Log files 日志文件

[logs.zip](https://github.com/Blinue/Magpie/files/15446529/logs.zip)

**Comment by Blinue** [comment]
这个 bug 只在这一个游戏中出现吗

**Comment by Mao0509** [comment]
> 这个 bug 只在这一个游戏中出现吗

找了几个游戏试了一下     目前别的游戏没有复现这个问题

**Comment by KagariTank** [comment]
我也是玩Root Double， 发现更新到最新0.11.0会出现同样情况。回退到0.10.6可以正常使用

**Comment by Blinue** [comment]
试试这个版本：https://github.com/Blinue/Magpie/actions/runs/9534439651/artifacts/1605834168

**Comment by Mao0509** [comment]
> 试试这个版本：https://github.com/Blinue/Magpie/actions/runs/9534439651/artifacts/1605834168

该版本不再复现问题

**Comment by Blinue** [comment]
谢谢测试！
