### ISSUE TITLE
软件导致 DirectX 9 软件崩溃

### ISSUE THREAD

**Issue by spr-equinox** [Blinue/Magpie#928]
### Magpie version 程序版本

0.11.0

### Windows version 系统版本

win11 23H2

### Related screenshot (optional) 相关截图（可选）

![image](https://github.com/Blinue/Magpie/assets/66425054/f7ba8879-8e7b-476d-aacd-026c58539f54)
![image](https://github.com/Blinue/Magpie/assets/66425054/52f5a598-929d-4a16-b31f-70cd6f30e182)
![image](https://github.com/Blinue/Magpie/assets/66425054/b4dac16f-a8dc-4c5e-bd49-c513cc907c27)

### Reproduction steps 复现步骤

启动软件，对任意窗口放大，alt tab切走，此时打开dx9游戏大多会崩溃，退出软件恢复

### Log files 日志文件

[magpie.log](https://github.com/Blinue/Magpie/files/15446933/magpie.log)

**Comment by Blinue** [comment]
Duplicate of #588
