### ISSUE TITLE
是否有兴趣支持Intel的XeSS？

### ISSUE THREAD

**Issue by LightMu** [Blinue/Magpie#93]
网上已经有诸多报道，英特尔开发了类似DLSS和FSR的超级采样技术，命名为XeSS。
XeSS在XeHPG通过硬件XMX实现，在其他大多数显卡产品通过DP4A实现，开源。

**Comment by Blinue** [comment]
Magpie只能进行后处理，无法提供运动矢量。XeSS应该集成在引擎或者驱动里，reshade也有可能实现它。
