### ISSUE TITLE
Depth buffer

### ISSUE THREAD

**Issue by AccountTaken** [Blinue/Magpie#932]
### Expected behavior 预期的功能

Is there some kind of way to get the depth buffer trough images. something that gets the depth data would be nice as I am planning on trying to get reshade shaders to work on magpie.                                                          

An user interface to add shaders would be nice too.

**Comment by Blinue** [comment]
Depth buffer can only be acquired by injecting into the game process. Unlike ReShade, Magpie is designed to be non-intrusive.
