### ISSUE TITLE
DirectDraw报错

### ISSUE THREAD

**Issue by qwer666qwer** [Blinue/Magpie#937]
### Magpie version 程序版本

0.11.0

### Windows version 系统版本

win11专业版 操作系统版本：22631.3672

### Related screenshot (optional) 相关截图（可选）

![Snipaste_2024-06-05_16-42-41](https://github.com/Blinue/Magpie/assets/79153400/24b7bbd6-0347-4738-b0d8-6c9bcf7ff77f)

### Reproduction steps 复现步骤

1. 打开magpie，用magpie随意放大一个窗口几秒，然后退出放大模式。
2. 之后打开游戏，大概率会报错：Failed to initialize DirectDraw: RESULT SURFACE FAILCreateSurface Windowed Primary: DDERR NOEXCLUSIVEMODE。（报错的游戏有：植物大战僵尸杂交版2.0.88,樱色之云-绯色之恋，奇异恩典圣夜的小镇）。
3. 然后关闭magpie程序，可以重新打开游戏。

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/15581943/magpie.log)

**Comment by Blinue** [comment]
这确实是个 bug，正常情况下退出缩放后也会中止模拟独占全屏。这个 bug 是 #894 引入的。
