### ISSUE TITLE
0.11删除了帧生成时间监控？后续是否会恢复？

### ISSUE THREAD

**Issue by Alex76251** [Blinue/Magpie#939]
### Question 问题

重复帧检测的活跃，让传统的（计算一段时间内帧数平均值）的帧数显示不再能直观的体现流畅度。

在静态，动态快速反复切换的VN里面，帧数显示只是在波浪般飘动。难以得知动态部分的帧数是否达到了设置的帧数上限。

之前“游戏内叠加层”里面的帧生成时间监控窗可以很好的分辨不同工作状态的帧数，但是0.11版本删除了这个窗口。

我长期在笔记本和win掌机等用电池的设备上使用magpie放大VN，重复帧检测和CuNNy的加入真是惊喜。但是帧生成时间监控的消失让针对vn调整电源变难了。

**Comment by Blinue** [comment]
v0.10 的帧时间是根据帧率的倒数计算出来的，参考价值不大，如果想监控电源最好使用 RTSS 等第三方软件。

帧数统计被删除有两个原因，一是它会增加渲染游戏内叠加层的开销，即使帧率为 0，它也需要更新，二是由于实现了重复帧检测，帧率的参考价值大大降低了，帧时间是不准确的。

**Comment by Alex76251** [comment]
感谢！
用rtss确实可以看见静态和动态部分帧数的“方波”，也许只有1%max之类的帧数统计可以直观显示动态部分帧数。

btw，刚才测试时发现。有“眨眼动画”的galgame，目前的重复帧检测会把眨眼动画“跳过”，或者只抽取了其中2-3帧。

**Comment by Blinue** [comment]
> btw，刚才测试时发现。有“眨眼动画”的galgame，目前的重复帧检测会把眨眼动画“跳过”，或者只抽取了其中2-3帧。

可能是因为 #899

**Comment by Alex76251** [comment]
我观察到了原因。

很多galgame喜欢在文本框角落上加入一个循环播放的logo/转圈。
magpie成功识别了这个小动画，将帧数降低到与这种小动画一致的4fps，可以完美的处理它。

而眨眼动画每3秒才播放0.5秒，magpie因此忽略了眨眼，继续保持在4fps，所以转圈小动画依旧完美，眨眼却只有2帧。

而 #899 提到的翻页卡顿，在我测试的这个游戏里，翻页时旋转的小图标会消失，但是
伴随翻页出现的，立绘移动和眨眼，会出现卡顿

可能是当多个不同帧率的动画出现，magpie会手忙脚乱。

我对加入最低帧限制能解决这个问题持怀疑态度。

**Comment by Alex76251** [comment]
一个令人不安的事实：
我打开开发者模式，关闭了重复帧检测
VN运行在60帧，将magpie限制在60帧，扔有50%的眨眼只有2帧，30%只有3-4帧
切换到120帧也没有改善

我想问题应该出在这些VN本身，这些VN在播放眨眼等动画的时候，帧生成时间完全就是大裂谷，比如我测试的这个vn，播放眨眼的时候帧生成时间会从16.6上升到25ms。vn制作者本身就没有让动画帧数同步的意识😰😰

**Comment by Blinue** [comment]
谢谢测试。如果你确认是 Magpie 的问题导致丢帧，请新建 issue 讨论。
