### ISSUE TITLE
开着Magpie时打开一些游戏会有错误弹窗，之前的版本是从来没有过的，更新到现在这个版本才出现的

### ISSUE THREAD

**Issue by ljc1314** [Blinue/Magpie#941]
### Magpie version 程序版本

0.11.0

### Windows version 系统版本

Windows 11 教育版 23H2

### Related screenshot (optional) 相关截图（可选）

![1](https://github.com/Blinue/Magpie/assets/105982229/11430c9c-4717-4721-8685-c0efef599fac)
![2](https://github.com/Blinue/Magpie/assets/105982229/ce3f482e-2ad4-42e9-a992-c4b23764ae69)

### Reproduction steps 复现步骤

打开Magpie后打开游戏《Rewrite+》《植物大战僵尸杂交版》《秽翼的尤斯蒂娅》等2D游戏会出现错误弹窗，弹窗内容：（
Direct3D のデバイスの作成に失敗しました。
関数 CreateDevice においてエラーが発生しました。
hr = 0x88760868 (D3DERR_DEVICELOST)
[ サポート情報 ]
このメッセージは Ctrl+C でコピーできます。）
只要关闭Magpie就不会出现弹窗，3D游戏没有出现过这种问题

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/15751687/magpie.log)
[magpie.1.log](https://github.com/user-attachments/files/15751688/magpie.1.log)
[magpie.2.log](https://github.com/user-attachments/files/15751689/magpie.2.log)

**Comment by Blinue** [comment]
Duplicate of #937 

#938 已经修复了。
