### ISSUE TITLE
拆分config.json

### ISSUE THREAD

**Issue by Kanadeforever** [Blinue/Magpie#945]
### Expected behavior 预期的功能

现在的config.json文件包含了软件设置、渲染器（应该说是清单）、缩放模式清单和游戏预设。
虽然这样方便备份但过于冗余了，所以希望拆分成：

- 软件设置
- 渲染器
- 缩放模式清单
- 游戏预设（最好是每个游戏单独一个）

这样在复制他人预设or缩放模式清单的时候可以直接复制单独文件去；有时使用他人预设的时候也会存在和本地有重合的部分，这样直接对照修改文件而不用在一长串清单里寻找差异项了（虽然这个并不难）

### Alternative behavior (optional) 近似的功能（可选）

游戏预设类似RTSS目录下，profile目录里那样？
（文件格式无所谓，文件名称可以是游戏预设名称，在文件内记录exe路径或者启动的命令行）
![image](https://github.com/Blinue/Magpie/assets/20147029/5be73c96-bfb1-4c33-9101-973df0beca5c)

**Comment by Blinue** [comment]
现在所有配置都保存在 config.json，如果分成多个文件会增加管理的复杂性，性能也会降低。config.json 是程序内部使用的，不建议直接改。

关于分享，缩放模式页面提供了导出/导入功能，游戏预设不支持分享，因为游戏路径、捕获方式、显卡都是不能通用的。
