### ISSUE TITLE
因为ScaleModels.json和config.json代码格式不同出现的问题

### ISSUE THREAD

**Issue by xiaoyuanjun233** [Blinue/Magpie#949]
### Question 问题

你好，因为从0.9.1之后的版本不支持windows10 1903以下的版本，而我朋友不能打开新版本，所以我尝试将新版本的配置文件移植到旧版本（已经去除了旧版未添加的着色器比如0.10.3添加的Anime4K Restore_U），但是新版本有图形化UI很方便编辑缩放模式，旧版本却是手动编写，我不懂代码，我看到新版本config.json的代码格式和旧版ScaleModels.json的代码格式略有不同，导致移植后解析失败
新版本有将ScaleModels.json转化为config.json的功能，能否单独出一个程序将config.json转化为ScaleModels.json，或者帮帮我，我添加您的联系方式可以吗
谢谢

**Comment by Blinue** [comment]
关于如何配置 ScaleModels.json 你可以参考 https://gist.github.com/hooke007/818ecc88f18e229bca743b7ae48947ad

> 能否单独出一个程序将 config.json 转化为 ScaleModels.json

我没有兴趣做这个。旧版本 Windows 早就停止维护，推荐升级操作系统。你也可以把你的配置发出来，我帮你转成 ScaleModels.json

**Comment by xiaoyuanjun233** [comment]
[Uploading config.json…]()

**Comment by xiaoyuanjun233** [comment]
[config.json](https://github.com/user-attachments/files/15858250/config.json)

**Comment by Blinue** [comment]
[ScaleModels.json](https://github.com/user-attachments/files/15860688/ScaleModels.json)

v0.9.1 不支持 CuNNy，我把它换成了 Anime4K_Upscale_S
