### ISSUE TITLE
更新至0.11.0版本后，在打开magpie的情况下会导致很多gal的Direct3D报错无法启动，或是白屏

### ISSUE THREAD

**Issue by L1ghtNight** [Blinue/Magpie#951]
### Magpie version 程序版本

0.11.0

### Windows version 系统版本

win10 22H2

### Related screenshot (optional) 相关截图（可选）

![屏幕截图 2024-06-18 162342](https://github.com/Blinue/Magpie/assets/93395745/05ca2121-78aa-4fe6-a29e-2b20dd582761)
![屏幕截图 2024-06-18 162417](https://github.com/Blinue/Magpie/assets/93395745/cecc6e87-1d13-4f57-b81d-145a7b0bd6ac)

### Reproduction steps 复现步骤

打开magpie，无论是在前后台运行，均会导致一些galgame的Direct3D报错，无法运行或是白屏，后台退出magpie后恢复正常，更新前使用0.10版本无此问题

### Log files 日志文件

[magpie.1.log](https://github.com/user-attachments/files/15882841/magpie.1.log)

**Comment by Blinue** [comment]
Duplicate of #937
