### ISSUE TITLE
Magpie seems to run off cpu instead of GPU

### ISSUE THREAD

**Issue by ineedsomehelp-please** [Blinue/Magpie#957]
### Program(Game) 游戏名

any (all)

### Capture method 捕获模式

Graphics capture

### Related screenshot (optional) 相关截图（可选）

![image](https://github.com/Blinue/Magpie/assets/68510202/8b0aa9c7-8d78-4524-a8e0-08a47c1c1bc1)

### Other information (optional) 补充信息（可选）

Laptop: Dell Latitude e6410
ram: 4GB
cpu: i5 M540 (2.53ghz base) (2.7ghz turbo)
gpu: Nvidia NVS 3100M

any games that i ran with magpie had same issue, cpu usage was through the roof and gpu usage was 7-34% normally
and ran at about 6-7fps

i ran barotrauma on it once and here are the results:

fps (without magpue): 30-40fps
fps (with magpie): 4-7fps

i fiddled around settings, i turned on and off 3d game mode, same issue reguardless

### Log files 日志文件

[magpie.1.log](https://github.com/user-attachments/files/15949847/magpie.1.log)
[magpie.2.log](https://github.com/user-attachments/files/15949848/magpie.2.log)
[magpie.log](https://github.com/user-attachments/files/15949849/magpie.log)

**Comment by Blinue** [comment]
Magpie requires a graphics card that supports DirectX feature level 11, but your graphics card does not meet this requirement. Consequently, Magpie has switched to CPU rendering, which is causing your CPU to be overburdened.

The NVIDIA NVS 3100M, released in 2010, can no longer handle modern games effectively. Upgrading your computer is the best solution.

**Comment by ineedsomehelp-please** [comment]
can dx 10.1 support be implemented sometime in future?

**Comment by Blinue** [comment]
Support for feature level 10.1 was dropped due to the transition to compute shaders. The last version that supported feature level 10.1 was [v0.8.2](https://github.com/Blinue/Magpie/releases/tag/v0.8.2), which is no longer maintained.

**Comment by BLACKCHARGE** [comment]
我感觉多数报错都应该加个弹窗报错给人感知，不然缩放半天失败了还得翻log查错

**Comment by Blinue** [comment]
CPU 渲染也不是一无是处，如果只使用简单的算法，现代 CPU 可以达到 60 FPS。我觉得给用户尝鲜的机会挺好的，最不济也可以用来截图。警告/错误弹窗很有必要，但不容易实现。
