### ISSUE TITLE
Black line at the bottom of the screen when using NNEDI3

### ISSUE THREAD

**Issue by noobworth** [Blinue/Magpie#961]
### Magpie version 程序版本

0.11.1 | Commit a05855c | x64

### Windows version 系统版本

Windows 10 22H2 (OS Build 19045.3693)

### Related screenshot (optional) 相关截图（可选）

Black line:
![1720022931112](https://github.com/Blinue/Magpie/assets/130678801/f4b146dc-6f79-4b8e-8a37-b5a231daa52a)

Original:
![2024-07-03 23-03-48](https://github.com/Blinue/Magpie/assets/130678801/3c24b2fe-7f42-488e-b11e-19d3b1faab0d)

### Reproduction steps 复现步骤

Any NNEDI3 variation causes the black line to appear on screen

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/16087804/magpie.log)

**Comment by hauuau** [comment]
Confirmed. I'll look into it in a couple of days.

**Comment by hauuau** [comment]
Should be fixed by #962 

A test build is available at https://github.com/Blinue/Magpie/actions/runs/9804155986
