### ISSUE TITLE
你好，是否能添加某个 glsl

### ISSUE THREAD

**Issue by NeilTohno** [Blinue/Magpie#97]
https://github.com/igv/FSRCNN-TensorFlow/releases
FSRCNN_x2_r2_16-0-2.glsl
这个开销少一点，mpv使用经验了

FSRCNNX_x2_8-0-4-1.glsl
这个对付 480p 最好

**Comment by Blinue** [comment]
目前Magpie移植的版本是FSRCNNX_x2_8-0-4-1和FSRCNNX_x2_8-0-4-1_LineArt。

我暂时不会再移植新的着色器，因为v0.7会将现有着色器全面重写。

**Comment by NeilTohno** [comment]
> 目前Magpie移植的版本是FSRCNNX_x2_8-0-4-1和FSRCNNX_x2_8-0-4-1_LineArt。
> 
> 我暂时不会再移植新的着色器，因为v0.7会将现有着色器全面重写。


明白了。

**Comment by yeezylife** [comment]
> 目前Magpie移植的版本是FSRCNNX_x2_8-0-4-1和FSRCNNX_x2_8-0-4-1_LineArt。
> 
> 我暂时不会再移植新的着色器，因为v0.7会将现有着色器全面重写。

看到这条issue之后我也不好提新glsl的事了...但是!! ravu-zoom-r2能耗比zoom-r3低近百分之50,而锐利度(SSIM等评分)只下降不到百分之10,在我看来是个很好的trade off,毕竟使用Magpie的人很多是在找那个性能的妥协点.
另外zoom系列的特点是可以任意缩放,但是性能比完美放大两倍的其他系列要差很多.其实ravu-lite系列(R3或者R2) 应该是性能最好的机器学习算法了.
个人觉得ravu-lite-R2/R3 引进的价值很大,消耗显著的小(相对其他机器学习算法,例如ravu-lite-R2消耗只有FSRCNNXx2 8-0-4-1的百分之40),同时适用于动画和现实(不像anime4K只支持动画).引入ravu-lite系列可以为Magpie提供唯一一个(目前还不具备的)低消耗的机器学习算法选项.

**Comment by Blinue** [comment]
已经移植了 ravu-lite-r3，见[自定义缩放](https://github.com/Blinue/Magpie/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E6%94%BE#ravu)。我正在着手改进Magpie的性能，v0.7里基于机器学习的算法会快的多

**Comment by Blinue** [comment]
如果现在依然有性能问题请重新打开此 issue
