### ISSUE TITLE
magpie无法缩放窗口

### ISSUE THREAD

**Issue by goutttt** [Blinue/Magpie#974]
### Magpie version 程序版本

Magpie-v0.11.0-x64

### Windows version 系统版本

Win10 22H2

### Related screenshot (optional) 相关截图（可选）

此程序无法缩放我需要使用的窗口，热键没有反应，我甚至无法通过计时器来激活缩放功能。
实际上，在演示视频中，我打开了程序的“高DPI缩放替代功能”，但关闭该选项后仍不起作用

### Reproduction steps 复现步骤

1.以管理员身份运行Magpie-v0.11.0-x64
2.打开我需要使用的程序
3.调整Magpie设置
4.输入热键

https://github.com/user-attachments/assets/450dcb92-6aaf-4ee6-ba9a-805d5677ee78

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/16479192/magpie.log)

**Comment by Blinue** [comment]
![image](https://github.com/user-attachments/assets/39a42097-ddf2-40c4-8762-419ebc7ce42b)
所有效果都解析失败了，可能效果文件没放在正确的位置。建议你在 https://github.com/Blinue/Magpie/releases 下载最新版本。
