### ISSUE TITLE
Return of the Incredible Machine: Contraptions

### ISSUE THREAD

**Issue by chrism69** [Blinue/Magpie#975]
### Magpie version 程序版本

0.11.1-x64

### Windows version 系统版本

Windows 10 Home 22H2

### Related screenshot (optional) 相关截图（可选）

![Capture](https://github.com/user-attachments/assets/69238eac-3f63-48b2-8a8d-e5da47a84ba1)

### Reproduction steps 复现步骤

None of the 4 capture methods work for this game (GOG version). Not sure if this would be classed as a bug or just how this old game handles the display - using the method here [https://www.pcgamingwiki.com/wiki/Return_of_the_Incredible_Machine:_Contraptions#Windowed](https://www.pcgamingwiki.com/wiki/Return_of_the_Incredible_Machine:_Contraptions#Windowed) you can get a window but it can't be resized.

I've uploaded the log but I don't think it shows anything other than me trying the 4 modes.

### Log files 日志文件

[magpie - Copy.log](https://github.com/user-attachments/files/16503634/magpie.-.Copy.log)

**Comment by hauuau** [comment]
Might it be possible by any chance that the game is launched as an elevated process while Magpie isn't launched with Administrator privileges?

That seems like the most likely explanation for the observed behavior.

**Comment by chrism69** [comment]
Oh that works, so simple I didn't consider it. Thanks!
