### ISSUE TITLE
Which capture mode offer the best grafic quality. 

### ISSUE THREAD

**Issue by YingDoge** [Blinue/Magpie#978]
### Question 问题

What which of the caputre mode offer the best grafic. 
1. Graphics Capture
2. Desktop Duplication
3. GDI
4. DwmSharedSurface

4090 and 7950x3d dont have to worry about performance. 

Thanks for answering 

Hope you have a great day

**Comment by Blinue** [comment]
There is no loss of quality in the captured images with any capture method; the only differences are in performance and compatibility.
