### ISSUE TITLE
Magpie does not scale the game...

### ISSUE THREAD

**Issue by MuJIbtuGamer** [Blinue/Magpie#979]
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

Windows 10

### Related screenshot (optional) 相关截图（可选）

When scaling, nothing happens! I've already checked on 3 games, but without success... I checked on CS:GO (pirated), Geometry Dash and osu!

https://github.com/user-attachments/assets/20758259-1938-4132-80af-76fb6eefa122

### Reproduction steps 复现步骤

1. Run Magpie
2. Start scaling
3. Wait 3 seconds...

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/16605594/magpie.log)

**Comment by Devahntei** [comment]
I'm using an Intel i7 3770 and HD 4000 Integrated graphics, it does not launch for me either.

**Comment by MuJIbtuGamer** [comment]
> В журналах указано, что ваша видеокарта не поддерживает [ID3D11Device5::CreateFence](https://learn.microsoft.com/en-us/windows/win32/api/d3d11_4/nf-d3d11_4-id3d11device5-createfence) . Возможно, вам стоит попробовать обновить драйверы. По той же причине Magpie также не поддерживает работу в виртуальной машине VMware #921 .
> 
> ссылка: [microsoft/terminal#15601 (комментарий)](https://github.com/microsoft/terminal/issues/15601#issuecomment-1931021701)

It's sad... I have the latest drivers (2012) and I don't even know how to use a virtual machine... Does that mean it won't work for me?

**Comment by MuJIbtuGamer** [comment]
I haven't tried it, but it updated automatically for me... Can you explain it to me?

**Comment by Blinue** [comment]
Download v0.10 from [here](https://github.com/Blinue/Magpie/releases/download/v0.10.6/Magpie-v0.10.6-x64.zip), and then disable automatic updates.

**Comment by MuJIbtuGamer** [comment]
Thanks a lot
