### ISSUE TITLE
win7下无法放大

### ISSUE THREAD

**Issue by JohnChuang33** [Blinue/Magpie#98]
Windows 7 x64 p3000 E3-1535m v6 48g内存
在枯花，金恋，星空的记忆，富婆妹等游戏都试过均报错退出
启动时注入/运行时注入/不注入都试过了不太ok

问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	Magpie.exe
  问题签名 02:	0.6.0.0
  问题签名 03:	8d6a8dfc
  问题签名 04:	Magpie
  问题签名 05:	0.6.0.0
  问题签名 06:	8d6a8dfc
  问题签名 07:	de
  问题签名 08:	5d
  问题签名 09:	System.DllNotFoundException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	467e
  其他信息 2:	467ea9d39023a3ee39ec9d30ae4e1dd4
  其他信息 3:	c34a
  其他信息 4:	c34ab171147a4a93236ad8090f326f68

**Comment by Blinue** [comment]
Magpie不支持Win7。#69
