### ISSUE TITLE
Switch to passes

### ISSUE THREAD

**Issue by 2mg** [Blinue/Magpie#981]
### Question 问题

What does "Switch to passes" do and how can I click on it?

### Logs files (optional) 日志文件（可选）

What does "Switch to passes" do and how can I click on it?

**Comment by Blinue** [comment]
Some effects are composed of multiple passes. This button toggles the in-game overlay between displaying the total render time of a effect and the render time of each individual pass. This feature is intended for effect creators and is generally not something regular users need to worry about.
