### ISSUE TITLE
11版本游戏无法放大，但是10版本可以放大

### ISSUE THREAD

**Issue by BrokenMyth** [Blinue/Magpie#989]
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

win11

### Related screenshot (optional) 相关截图（可选）

![image](https://github.com/user-attachments/assets/770307a0-557e-4f49-a188-d38b04462fb8)

### Reproduction steps 复现步骤

11版本无法放大游戏 《童真兄妹无法忍耐处男哥哥和不直率叛逆妹妹》的中文版，但是却可以放大日文版的(ガマンができない童貞アニキとスナオになれない反抗妹) 各种捕获模式试过了也没用
10版本两个版本都可以放大。放大配置都一样，第一次见到这么奇怪的情况
10版本中文版虽然可以放大，但是无法用快捷键退出，回桌面才可以退出放大，感觉这游戏中文版挺奇怪的
### Log files 日志文件

11版本的日志：(看了下日志，中文版的放大貌似没看到有放大记录)
[magpie.1.log](https://github.com/user-attachments/files/16781955/magpie.1.log)
[magpie.2.log](https://github.com/user-attachments/files/16781957/magpie.2.log)
[magpie.log](https://github.com/user-attachments/files/16781960/magpie.log)
10版本的日志：
[magpie.1.log](https://github.com/user-attachments/files/16781965/magpie.1.log)
[magpie.2.log](https://github.com/user-attachments/files/16781966/magpie.2.log)
[magpie.log](https://github.com/user-attachments/files/16781967/magpie.log)

**Comment by Blinue** [comment]
试试以管理员身份启动
