### ISSUE TITLE
热键更改问题

### ISSUE THREAD

**Issue by hhyacg** [Blinue/Magpie#99]
默认是两个键，更改以后只能用一个键，设置时按ALT或Ctrl+(   )都没反应，已确定没有热键冲突。而且单设一个键可以正常使用热键功能，就是不知道怎么设置组合键。
![783DE69E3B4CF7357C0D10AA179A89B9](https://user-images.githubusercontent.com/40420771/131355855-651e3f4b-83a8-4174-a9e8-6b2eae32a94f.jpg)
![2B969D67DD8B7E0E5E27D061D313229B](https://user-images.githubusercontent.com/40420771/131355866-facefe89-80bb-4dfb-a13d-b3fcacc60827.jpg)

**Comment by hooke007** [comment]
你得手打按键，这个不含有自动映射按键的功能

**Comment by hhyacg** [comment]
> 你得手打按键，这个不含有自动映射按键的功能

手打出来ALT+  是红的，不可用，它只判定打的第一个字符键有用

**Comment by hooke007** [comment]
可以先用f区

**Comment by hooke007** [comment]
你可以看一下热键的文档
https://github.com/gmamaladze/globalmousekeyhook/blob/vNext/keycomb.md

**Comment by hhyacg** [comment]
> 可以先用f区
> 而且应该是`Alt`

解决了，谢谢。

**Comment by Blinue** [comment]
现在更改热键居然需要一定门槛 →_→

我会考虑增加按键映射的功能
