### ISSUE TITLE
修改分辨率后，magpie右上角三个按钮与光标位置不对应

### ISSUE THREAD

**Issue by plainround** [Blinue/Magpie#991]
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

19045.4780

### Related screenshot (optional) 相关截图（可选）

![屏幕截图(204)](https://github.com/user-attachments/assets/d63c6ab1-c38b-43b2-bd7b-f23e0b42320e)

### Reproduction steps 复现步骤

1.打开magpie，最小化到任务栏
2.打开windows设置修改分辨率3840×2160 =>2560×1600
3.点击magpie右上角红色x按钮，正常最小化到托盘
4.双击托盘中magpie图标，这时按钮不符合预期
点击x按钮：预期行为，最小化到托盘。实际行为，没反应。
光标停在三个按钮稍微左边一点的位置：预期行为，没反应。实际行为，按钮亮了。
在稍微左边一点的位置点击：预期行为，没反应。实际行为，生效。

### Log files 日志文件

none

**Comment by Blinue** [comment]
看起来和 DPI 缩放有关，但我复现不了。你是不是有多个屏幕？

**Comment by plainround** [comment]
> 看起来和 DPI 缩放有关，但我复现不了。你是不是有多个屏幕？
抱歉回复晚了，只有一个显示器。

**Comment by plainround** [comment]
[output001.webm](https://github.com/user-attachments/assets/1ef5ff0a-136a-493f-a077-24feffdf83c2)

**Comment by Blinue** [comment]
这个版本我添加了日志，能否重新操作一遍，然后把日志发我？

[Magpie.zip](https://github.com/user-attachments/files/16926517/Magpie.zip)

**Comment by plainround** [comment]
> 这个版本我添加了日志，能否重新操作一遍，然后把日志发我？

[magpie.log](https://github.com/user-attachments/files/16927757/magpie.log)

我发现程序没有问题，问题出在我的文件路径上，只要magpie在那个路径打开，就会有这个问题。

因为用软件很久了，文件路径一直没变，我原来那个路径的magpie是有管理员权限的，把管理员取消勾选，程序右下角依然有小盾牌。不知道和这个有没有关系。

总之只要修改文件夹名称，或者把程序复制到别的路径，小盾就没了，然后好像就没有问题了。。。你发给我的程序，还有0.11.1的版本，我都在别的路径下试过没问题。

我把你发给我的版本放到那个文件路径下，是有问题的，也是有小盾的。log传给你，不过可能意义不是很大了，毕竟程序本身没有问题。
magpie真的很好用，谢谢你。

**Comment by Blinue** [comment]
谢谢，你提供的日志和信息都很有帮助！我排查到 XAML Islands 的 bug 导致的，在你的环境里，XAML Islands 检测不到 DPI 更改。我这里依然复现不了这个错误，我很好奇你的文件夹的配置，为什么里面的程序都需要管理员权限？

**Comment by Blinue** [comment]
我成功复现了，如果更改了程序的“高 DPI 缩放替代”会遇到相同的问题。你最好检查一下这个选项

**Comment by plainround** [comment]
> 我成功复现了，如果更改了程序的“高 DPI 缩放替代”会遇到相同的问题。你最好检查一下这个选项

这个选项是选中并置灰无法更改的状态，靠gpt找到HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers删掉了，现在这个问题没有了！管理员权限就不知道什么时候弄来的了。

**Comment by Blinue** [comment]
高 DPI 缩放替代选项是给没有适配高 DPI 的软件用的，对 Magpie 只会起到反效果。看来这不是 bug，谢谢你的反馈 ;)
