### ISSUE TITLE
Magpie-v0.11.1-x64 在掌机启用触摸支持后，用触摸屏点击放大前窗口以外的区域时，会自动还原为窗口，使用鼠标则一切正常。

### ISSUE THREAD

**Issue by LucyEternal** [Blinue/Magpie#992]
### Magpie version 程序版本

Magpie-v0.11.1-x64

### Windows version 系统版本

win11 23h2专业版 22631.44112

### Related screenshot (optional) 相关截图（可选）

![20240909104835](https://github.com/user-attachments/assets/c4fd5e0a-9bba-42b8-b75f-ed25355087c9)

### Reproduction steps 复现步骤

在管理员模式下启动该软件，设置下勾选始终以管理员身份运行，在主界面勾选上启用触摸支持后，使用该工具放大画面，放大画面的游戏UI触控区域和正常情况下游戏UI的位置对不上，游戏UI的相关交互元素均在放大前窗口的对应位置，在已经使用工具放大的前提下，使用触摸屏点击放大前窗口以外的区域时，会自动还原为窗口，使用鼠标则一切正常。（在日志里提示安装证书成功、复制可执行文件成功；System32\Magpie文件夹下有TouchHelper.exe）

### Log files 日志文件

[Uploading register_touch_helper.log…]()
[Uploading magpie.log…]()

**Comment by LucyEternal** [comment]
[magpie.log](https://github.com/user-attachments/files/16924877/magpie.log)
[register_touch_helper.log](https://github.com/user-attachments/files/16924878/register_touch_helper.log)

**Comment by LucyEternal** [comment]
[magpie.log](https://github.com/user-attachments/files/16924886/magpie.log)
[register_touch_helper.log](https://github.com/user-attachments/files/16924887/register_touch_helper.log)

**Comment by Blinue** [comment]
从日志看，证书安装正确，但 TouchHelper.exe 权限不足。TouchHelper.exe 应该放在**只有管理员有权限写**的路径下，你的系统里 System32 文件夹居然非管理员也能写，这不是正常情况。

进入 System32 文件夹的属性页面，然后点击“高级”可以查看所有用户对这个文件夹的权限。

![image](https://github.com/user-attachments/assets/36614d70-4691-4c65-b36e-215765704ad9)

**Comment by LucyEternal** [comment]
<img width="704" alt="Snipaste_2024-09-09_15-33-51" src="https://github.com/user-attachments/assets/47ddc1dd-3347-4199-9697-023542ae258c">
能看一下是哪里权限有问题嘛？比较奇怪的是，在把文件全部删除后，重新安装软件，会有一次能成功使用触摸支持，但重新启动软件后，功能就失效了。

**Comment by LucyEternal** [comment]
<img width="704" alt="Snipaste_2024-09-09_15-33-51" src="https://github.com/user-attachments/assets/47ddc1dd-3347-4199-9697-023542ae258c">
能看一下是哪里权限有问题嘛？比较奇怪的是，在把文件全部删除后，重新安装软件，会有一次能成功使用触摸支持，但重新启动软件后，功能就失效了。

**Comment by Blinue** [comment]
看起来没问题，这就奇怪了。综合各种文档，可靠的位置只有 Program Files 和 System32，之前有人报告 Program Files 权限不够https://github.com/Blinue/Magpie/issues/218#issuecomment-980834869 ，没想到 System32 文件夹依然可能有问题，UIAccess 的权限要求成谜

**Comment by LucyEternal** [comment]
我好像问题复现了，我是在软件右键-属性-兼容性界面里勾选了“以管理者身份运行该程序”运行，就会出现这个情况，但是我仅右键“以管理者身份运行”情况下，该问题消失了。（别的可能性：中途我还重装了一次电脑）

**Comment by Blinue** [comment]
确实如此，兼容性页面启用管理员就无法获得 UIAccess 权限，和位置没关系。我会调查一下。

**Comment by Blinue** [comment]
这个版本开启兼容性选项也没问题，请试一下

[Magpie.zip](https://github.com/user-attachments/files/16929644/Magpie.zip)

**Comment by LucyEternal** [comment]
有个小小的疑问想确认一下，在软件放大后，实际点击的位置和显示的位置会有偏差（功能正常），这样是否正常呢？拿以下GIF举例，不止这个软件，几乎放大后的所有软件都有这个问题。
![screenshots](https://github.com/user-attachments/assets/12e24b6b-7da8-4370-b24b-dcce5f0e2b78)

**Comment by Blinue** [comment]
触控的圆圈是 OS 显示的，没适配 MagSetInputTransform，可以认为是 OS 的 bug。嫌烦可以关掉，Win10 的选项在轻松使用里

**Comment by boonotakota** [comment]
Hey, I'm having this same issue again.
