### ISSUE TITLE
FormatException when trying to set up voltage offset.

### ISSUE THREAD

**Issue by SAliZarar** [Blinue/Magpie#993]
### Magpie version 程序版本

2.3.1.0

### Windows version 系统版本

Windows 11 23H2

### Related screenshot (optional) 相关截图（可选）

![Screenshot 2024-09-11 091153](https://github.com/user-attachments/assets/6838f788-108a-4a1d-9135-18920488278d)

### Reproduction steps 复现步骤

System specs are as follows:

Alienware m15 r4
I7 10870H
RTX 3070 

This is one of the few plundervolt CPUs that didnt get patched, so its definitely not a matter of compatibility, ive been undervolting it to stable -115 core and -68 cache using throttlestop, XTU works but with the older version.

Funny thing is, the CPU doesnt support ratio changes, but that seems to work fine (atleast, according to the software, actual changes dont happen)

### Log files 日志文件

[Runtime.log](https://github.com/user-attachments/files/16957848/Runtime.log)
[uxtu_log20240911.txt](https://github.com/user-attachments/files/16957850/uxtu_log20240911.txt)

**Comment by Blinue** [comment]
Hello, this issue should be opened in [Universal-x86-Tuning-Utility](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility). You've posted it in the wrong place.
