### ISSUE TITLE
英雄联盟lol始终无法进行缩放

### ISSUE THREAD

**Issue by 404-BugNotFound** [Blinue/Magpie#998]
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

win11 23H2

### Related screenshot (optional) 相关截图（可选）

![{F7323647-7C70-4916-9ED0-BDBD01A61E78}](https://github.com/user-attachments/assets/1d543ec5-c6fa-494d-ba8b-586f10fdaeac)
![{FD17DDCD-DF9B-414A-9137-D18F66254545}](https://github.com/user-attachments/assets/63e26825-1958-43a0-a527-036c35c12c83)
![{D783381D-079F-4D54-B737-D53E669EDCD8}](https://github.com/user-attachments/assets/6059f056-4046-4cbc-8d42-6d25d6897208)
![{6E86C153-DD53-4952-A7D6-82FD6BB238AA}](https://github.com/user-attachments/assets/1aa13f41-58b3-4a4d-a7c0-1b3d53c8a0d3)
![{B4CEF67D-CBE8-4920-B951-E5A0016B14B5}](https://github.com/user-attachments/assets/bc26ecd5-a096-46d6-bb91-d474d309e27a)

### Reproduction steps 复现步骤

1.显示器物理分辨率4k，系统缩放300%
2.游戏兼容性设置了高DPI缩放替代为“应用程序”
3.英雄联盟游戏内设置分辨率为1920*1080，无边框模式
4.megpie中设置好所有相关选项
5.游戏中热键无反应，位于前台时自动缩放也未生效

### Log files 日志文件

折腾半天还是不行，求大佬指点一二，感谢

**Comment by Blinue** [comment]
试试以管理员身份运行Magpie，没用的话把日志贴出来

**Comment by 404-BugNotFound** [comment]
使用管理员运行可以正常缩放，感谢感谢
